### ISSUE TITLE
[DOC] wrong documentation related to maven publication of plugins

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#1007]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
the documentation for `opensearch-plugin install` is wrong, it claims that the command would accept maven artefact identifiers which isn't the case (please double-check on this, though. i'm at least not aware of it!):
https://github.com/opensearch-project/documentation-website/blob/c48cf8c600a9a714b718842836ce47c9b9ac33dd/_opensearch/install/plugins.md?plain=1#L28

see the [blog post](https://opensearch.org/blog/technical-post/2022/08/opensearch-plugin-zips-now-in-maven-repo/) on the actual use of the maven publications. 

**What other resources are available?**
* [blog post](https://opensearch.org/blog/technical-post/2022/08/opensearch-plugin-zips-now-in-maven-repo/)
* this comes from #999 which comes from #938. see the various issue links in that issue for further references
* AFAIK @prudhvigodithi was the main contributor for this feature and might accordingly have further input for you

**Comment by JeffH-AWS** [comment]
Update time!  I had my meeting with Prudhvi and he did a great job explaining things.  So, you CAN install with Maven coordinates using <groupId>:<artifactId>:<version> syntax.  For example, I just successfully ran the following on my VM:

```
$ sudo ./opensearch-plugin install org.opensearch.plugin:opensearch-anomaly-detection:2.2.0.0
```

I had to uninstall anomaly detection first (it was failing with an error), and I also had to run it with `sudo` based on the default permissions when installing from the RPM.

Let me make a few changes to the doc and then I'll get a PR up.

**Comment by prudhvigodithi** [comment]
Also the code for plugin-cli that uses maven is here 
https://github.com/opensearch-project/OpenSearch/blob/main/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java#L399-L409
@JeffH-AWS @rursprung @dblock @bbarani

**Comment by rursprung** [comment]
> Also the code for plugin-cli that uses maven is here https://github.com/opensearch-project/OpenSearch/blob/main/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java#L399-L409 @JeffH-AWS @rursprung @dblock @bbarani

oh, wow, this is awesome, i didn't know that you added that and totally missed it! 🥳
