### ISSUE TITLE
[DOC] Add more info about plugins

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/documentation-website#1015]
**What do you want to do?**
 
- [ ] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
I recommend that the "plugin installation" page (https://opensearch.org/docs/latest/opensearch/install/plugins/) cross-reference the API call "cat plugins" (https://opensearch.org/docs/latest/opensearch/rest-api/cat/cat-plugins/)

Is there any way to list the *available* (not installed) plugins that can be installed by name either on the command line or in an API call?

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by ariamarble** [comment]
@ macrakis plugins are hosted on Maven and there is not a way to list those over the CLI. the opensearch-plugin binary is only able to list installed plugins as well. Maven is covered in the plugin install guide. I will update to link to the CAT page.

**Comment by ariamarble** [comment]
Resolved - https://github.com/opensearch-project/documentation-website/pull/1962
