### ISSUE TITLE
Clarify that wildcards in ISM API apply to system indices

### ISSUE THREAD

**Issue by keithhc2** [opensearch-project/documentation-website#102]
We need to clarify that requests using wildcard expressions with the ISM API can affect system indices. This does not apply to ISM templates

**Comment by aetter** [comment]
Hey @keithhc2, @ashwinkumar12345 might already be on this one. I'd coordinate with him to avoid duplicating efforts.

**Comment by keithhc2** [comment]
@aetter Thanks for letting me know. I'll reassign the ticket to him

**Comment by ashwinkumar12345** [comment]
Added fix- https://github.com/opensearch-project/documentation-website/pull/107.
