### ISSUE TITLE
[DOC] ldap2 auth documentation missing

### ISSUE THREAD

**Issue by Martin-Kemp** [opensearch-project/documentation-website#1042]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Opensearch supports features that are not documented anywhere.

There is an auth type called `ldap2` which supports ldap connection pooling. This auth type is not documented anywhere, I only found it after (through desperation) searching through the code base.

Where it probably should be: https://opensearch.org/docs/latest/security-plugin/configuration/ldap/

Where to find it in the code: https://github.com/opensearch-project/security/tree/main/src/main/java/com/amazon/dlic/auth/ldap2

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@scrawfor99 - Can you please see if this is adequately addressed in the documentation? https://opensearch.org/docs/latest/security/authentication-backends/ldap/. Thank you!

**Comment by AntonEliatra** [comment]
@hdhalter I can take this one

**Comment by AntonEliatra** [comment]
After speaking with @nibix it appears that this feature was not fully implemented, as a result the pooling is not actually working. Should we close this issue?

**Comment by hdhalter** [comment]
Yes, thanks, @AntonEliatra! fyi @scrawfor99 and @cwperks
