### ISSUE TITLE
[DOC] Document remote store feature

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/documentation-website#1045]
**What do you want to do?**
 
[X] Add new documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
- With 2.3 release, we are looking to release an experimental version of the remote store feature.
- Feature Proposal - https://github.com/opensearch-project/OpenSearch/issues/1968
- Design Proposal - https://github.com/opensearch-project/OpenSearch/issues/2700

As an experimental feature, it will be behind a feature flag that must be enabled on each node of a cluster in addition to setting the remote store setting during index creation.

To enable the feature flag:
For developers to enable with Gradle run:
Update run.gradle with:

```
testClusters {
  runTask {
    testDistribution = 'archive'
    if (numZones > 1) numberOfZones = numZones
    if (numNodes > 1) numberOfNodes = numNodes
    systemProperty 'opensearch.experimental.feature.remote_store.enabled', 'true'
  }
}
```

To enable on a node using a tarball:
option 1. Update config/jvm.options with:
```
-Dopensearch.experimental.feature.remote_store.enabled=true
```

option 2. include the flag in OPENSEARCH_JAVA_OPTS before ./bin/opensearch

```
OPENSEARCH_JAVA_OPTS="-Dopensearch.experimental.feature.remote_store.enabled=true" ./opensearch-3.0.0/bin/opensearch
```

option 3: Specify OPENSEARCH_JAVA_OPTS env var.

```
export OPENSEARCH_JAVA_OPTS="-Dopensearch.experimental.feature.remote_store.enabled=true"
./bin/opensearch
```

**Comment by Naarcha-AWS** [comment]
@JeffH-AWS This might make the most sense in two places:

1. On the [Configuration](https://opensearch.org/docs/latest/opensearch/configuration/) page. 
2. In a new page somewhere in the OpenSearch install/configure section.

Either way, we'll have to put a note at the top of the section of page noting that it's an experimental feature.

**Comment by JeffH-AWS** [comment]
Sachin reached out to me via Slack. I've requested a final design doc for the feature in its current state as our timezone difference is roughly 12 hours so a live sync might be difficult to coordinate.

**Comment by JeffH-AWS** [comment]
Putting this in progress since we're talking about it, although I'm blocked on writing until a good feature doc is presented.

**Comment by JeffH-AWS** [comment]
Sachin has provided me with a document that contains the necessary commands as well as sample outputs (although some of the data needs to be fixed - e.g., the changes to `run.gradle` to include the necessary dependency which is segment replication).

@ariamarble is working on the segment replication piece and this will be a child page of that.

**Comment by sachinpkale** [comment]
@JeffH-AWS Even though remote store will be enabled only for segment replicated index, remote store is a stand-alone feature which provides different functionality than Segment Replication.  
IMO, both of these features should have a separate page without parent-child hierarchy.

**Comment by JeffH-AWS** [comment]
PR is ready for tech review.
