### ISSUE TITLE
[DOC-META] Replace "indices" with "indexes"

### ISSUE THREAD

**Issue by JeffH-AWS** [opensearch-project/documentation-website#1046]
**What do you want to do?**
 
Existing documentation is inconsistent with references to "indices" and "indexes" often sitting right next to each other within the same page.

We'll need to review each page on an individual basis to determine whether the reference is `hard coded` into the OpenSearch product (e.g., the actual button in the interface says `indices` or a property in a configuration file must say `indices`), or if it's just part of the narrative.

For instances where `indices` is used, but it is not hard coded into the product, we should replace it with `indexes`.

**List of PRs**

- 
- 
-

**Comment by JeffH-AWS** [comment]
This issue can be used for tracking PRs and progress in making the edits. First step will be to identify where `indices` exists in the documentation when it is not referring to a hardcoded property called `indices`.

**Comment by Naarcha-AWS** [comment]
Closing this in favor of #2358
