### ISSUE TITLE
[DOC] Update async search settings name

### ISSUE THREAD

**Issue by bharath-techie** [opensearch-project/documentation-website#1061]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 The settings given in https://opensearch.org/docs/latest/search-plugins/async/settings/ are outdated. Replace the names with the settings in https://github.com/opensearch-project/asynchronous-search ( Tunable settings section )

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
All given above

**Comment by bharath-techie** [comment]
@kolchfa-aws please take a look at this issue

**Comment by kolchfa-aws** [comment]
@bharath-techie Thank you! Is this for versions 2.x only or for 1.x as well?

**Comment by bharath-techie** [comment]
> @bharath-techie Thank you! Is this for versions 2.x only or for 1.x as well?

1.x as well.
