### ISSUE TITLE
[DOC] Update the rest endpoint `_cat/config` to `_cat/plugins`.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/documentation-website#1099]
**What do you want to do?**
 
- [ ] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The sentence `Send requests to the server to verify that OpenSearch is running:` from the document shows https://opensearch.org/docs/latest/opensearch/install/rpm/ `_cat/config`, where is `_cat/config` is unknown api call method.
Replace it with more generic one `_cat/plugins`.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://opensearch.org/docs/latest/opensearch/rest-api/cat/cat-plugins/

**Comment by prudhvigodithi** [comment]
Hey @JeffH-AWS when you get a chance can you please take a look at this?
Thank you 
@bbarani @dblock

**Comment by JeffH-AWS** [comment]
I'm on it!  Thanks Prudhvi!

**Comment by prudhvigodithi** [comment]
> I'm on it! Thanks Prudhvi!

Thanks @JeffH-AWS
