### ISSUE TITLE
[DOC] Support aggregation on geo_point based on H3 library

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/documentation-website#1100]
**What do you want to do?**
 
- [x] Add new documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
geo_point field will support new aggregation based on H3 grid system.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/geospatial/issues/98

**Comment by Naarcha-AWS** [comment]
To help with load balancing of 2.4 feature writing, I'm going to assign this to me.
