### ISSUE TITLE
Add Snapshot restore from Dashboards

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#1106]
**What do you want to do?**

Add new documentation from Snapshot restore from Dashboards.

**Tell us about your request.** 

Today, users have to restore snapshots through the restore API. 2.3 introduces the restore functionality in Dashboards UI. Users looking for a guided experience will be able to restore their indexes from existing snapshots within OpenSearch Dashboards.

 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

- https://github.com/opensearch-project/index-management-dashboards-plugin/issues/243
- POCs: @praveensameneni

**Comment by vagimeli** [comment]
Syncing with @kolchfa-aws
