### ISSUE TITLE
[DOC] define "multi-term query"

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/documentation-website#1114]
**What do you want to do?**
 
- [ ] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
The page https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/ uses the term "multi-term query" but never defines it. I'm guessing this means the query_string and simple_query_string queries, but it's not clear. It's especially unclear because we have a thing called a ``multi_terms`` aggregation (https://opensearch.org/docs/latest/opensearch/bucket-agg/), which is unrelated.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by alicejw-aws** [comment]
Status: in tech review with PM to verify accuracy.
