### ISSUE TITLE
[DOC] analyzers in the full-text page

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/documentation-website#1115]
**What do you want to do?**
 
- [ ] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
The section "convert text with analyzers" in the Full Text page (https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#convert-text-with-analyzers) is very confusing.

Language analyzers need a section of its own discussing the use of analyzers and distinguishing between indexing time and query time. That section belongs in the Mappings section, not the Query section.

In the Full Text page, there should be a cross-reference to the main page on language analyzers, talking about setting the analyzer used to interpret **queries**.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by alicejw-aws** [comment]
quick status: created new page structure. moved previous "language analyzers" section i wrote to new page, and doing research on what sections/topics are required for the general analyzers page.

**Comment by alicejw-aws** [comment]
Status update: I have a PR draft here: https://github.com/opensearch-project/documentation-website/pull/1376
When complete, i will send it for tech review. thanks

**Comment by alicejw-aws** [comment]
reorg is complete: 
created new page Text analyzers - will send for tech writer review next week. 

Note: Text analyzers also needs a Specialized analyzers reference with contain all 8 analyzers 
so far, Language analyzers section is complete. created separate [meta ticket](https://github.com/opensearch-project/documentation-website/issues/1483) for the remaining 7 pages. 
hid "Specialized analyzers reference" link until we create these new pages.

**Comment by alicejw-aws** [comment]
PR draft for TBD section needed: Specialized text analyzers
https://github.com/opensearch-project/documentation-website/pull/1484/files

**Comment by alicejw-aws** [comment]
Hi @macrakis , could you please review the new Text analyzers page? I wrote how analyzers work, given brief 1-line descriptions for all of the available analyzers, and moved my section on Language analyzers to this page. 

Here is the PR:
https://github.com/opensearch-project/documentation-website/pull/1376
Thanks
