### ISSUE TITLE
[DOC]: Fix broken link in script APIs section

### ISSUE THREAD

**Issue by Steve-O-Murphy** [opensearch-project/documentation-website#1119]
**What do you want to do?**
 
- [ ] Request a change to existing documentation

Please fix broken links in [https://opensearch.org/docs/latest/opensearch/rest-api/_script-apis/index/](https://opensearch.org/docs/latest/opensearch/rest-api/_script-apis/index/)

The links in the bulleted list of script capabilities (above the table of contents) each include a path component `script-apis` which is incorrect. Please change to `_script-apis`.

**Comment by ariamarble** [comment]
This has been completed.
