### ISSUE TITLE
[DOC]: Remove Gender on SQL relevance example

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#1124]
**What do you want to do?**
 
Request a change to existing documentation, https://opensearch.org/docs/latest/search-plugins/sql/aggregations/

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
On the aggregation functions page, we use gender as a way of categorizing for SQL relevance. As opposed to gender, we should use something more inclusive. 

Actual changes to the function examples based how we group the aggregate might need to occur. Whatever example we choose, it should follow these two requirements:

- Be easily observable
- Be quantifiable 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by kolchfa-aws** [comment]
Fixed by PR #1333

**Comment by hdhalter** [comment]
Closing. https://opensearch.org/docs/latest/search-plugins/sql/sql/aggregations/.
