### ISSUE TITLE
`vm.max_map_count` is not a container setting  

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/documentation-website#113]
In `_opensearch/install/important-settings.md` it says:

_For production workloads, make sure the Linux setting vm.max_map_count is set to at least 262144. On the OpenSearch Docker image, this setting is the default._

The part about the OpenSearch Docker image is incorrect. This is something that has to be set on the host manually.  See https://github.com/opensearch-project/opensearch-build/tree/c055f04fd11ab2e493ca2b390b1a2af7b451807c/tools/standard-test#requirements

**Comment by aetter** [comment]
Got it, thanks. Maybe this value happened to be the default on whatever machine I tested it on originally. Regardless, verified on a new AL2 VM: https://github.com/opensearch-project/documentation-website/commit/76e3b2710e1d0ea4c4646aefc6b93102aa4d6e9e
