### ISSUE TITLE
[DOC]Copyedit OpenSearch Dashboards in-product PPL documentation

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#1152]
**What do you want to do?**
 
- [ x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 In OS Dashboards, there is existing in-product documentation for PPL. It needs copyediting.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
If you go to https://playground.opensearch.org/app/observability-dashboards#/ and click on the "PPL" button, it brings up the OpenSearch PPL Reference Manual. To edit the text in this, go to the repo:
https://github.com/opensearch-project/sql/tree/main/docs/user/ppl
and edit all .rst files that are shown in OS Dashboards' PPL in-product documentation.

**Comment by hdhalter** [comment]
I think we should make sure the documentation on this feature is up to date in the doc repo, and then export our content into the UI. Some of the content is the same between them, but upon a quick glance, not all of it is.

**Comment by vagimeli** [comment]
@Naarcha-AWS I've reassigned this issue to myself, as I've rewritten the SQL, PPL, and Query Workbench content this past week and can align these copyedits to those changes and the docs I'm working on for the Observability team.

**Comment by vagimeli** [comment]
Notes from SME: 

this is the PPL documentation in SQL repo https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/index.rst

this is the documentation in event analytics UI: https://github.com/opensearch-project/dashboards-observability/blob/main/public/components/common/helpers/ppl_docs/overview.tsx

that would be the dashboards-observability repo, so the second link i sent before. we copied docs from the sql repo and put in observability for displaying on the UI. 
[@mengweieric] and [Shenoy Pratik Gurudatt] possible POCs

**Comment by vagimeli** [comment]
Screenshot of Observability > Dashboards > PPL in-product documentation

![Image](https://github.com/opensearch-project/documentation-website/assets/105296784/92e5387b-acfd-4190-930e-0d3b0239a79c)

**Comment by vagimeli** [comment]
Writing and editing in progress. See PR

**Comment by vagimeli** [comment]
Editorial review starting 11/29
