### ISSUE TITLE
[DOC] Syntax error in create mapping request in join.md

### ISSUE THREAD

**Issue by xluo-aws** [opensearch-project/documentation-website#1174]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

URL: https://opensearch.org/docs/latest/opensearch/supported-field-types/join/ 
There seems to be an error in 
"Create a mapping to establish a parent-child relationship between products and their brands:"
PUT testindex1/_mappings
{
  "mappings": {

_mappings and mappings should not be specified at the same time
If testindex1 doesn't exist, the url should not include _mappings as part of it's path, otherwise it will throw index not exist error
If testindex1 already exists, the mappings object should not be included in the body, other wise it will throw mapping parse error exception

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by kolchfa-aws** [comment]
Fixed by #1176
