### ISSUE TITLE
[DOC] Create new page and content for Using Vega and Vega-Lite

### ISSUE THREAD

**Issue by alicejw1** [opensearch-project/documentation-website#1178]
**What do you want to do?**

- [ X] Add new documentation
This ticket will write the Vega documentation for OpenSearch.  
**About this request:**
This ticket will write the Vega documentation for OpenSearch.  After docs are written, need to add the UI Help menu item back to the Dashboards to link to this document. 
See ticket [658](https://github.com/opensearch-project/documentation-website/issues/658) to remove link in Dashboards Help menu for docs that do not yet exist. 

 **Basic doc outline**
1. Vega overview - Vega is a visualization type that you can create in OS Dashboards. Vega uses a declarative language that you can use to describe your data. 
2. How to create a Vega visualization in OS Dashboards. (steps)
3. References - List of Vega docs: Tutorials and examples

[[Feature Proposal]:Vega Visualizations](https://github.com/opensearch-project/documentation-website/issues/658)

**What other resources are available?** 
Elastic documentation for Vega can be used as a conceptual resource: https://www.elastic.co/guide/en/kibana/7.10/vega-reference.html

Vega's documentation: https://vega.github.io/vega/about/.

Image of Dashboards Vega help menu: https://user-images.githubusercontent.com/32652829/172729444-98aee7f1-c191-4dfb-87c8-01bd067d7dc8.png

**Comment by alicejw-aws** [comment]
Hi @vagimeli - This is for a new dashboards doc. I'm starting an outline with overview and how-to steps after some research.

**Comment by vagimeli** [comment]
Hi @alicejw-aws I'll schedule a brainstorming session. Here's working draft for the visualizations section, which will include documentation for each visualization type. The initial outline I started follows: 

Visualizations (main page)
- L1 Page: Visualizations overview - give user high-level overview of what, when, and why to use visualizations and types https://github.com/opensearch-project/documentation-website/issues/992 
- L2: Pages: Separate page for each visualization type, including details about that specific type - give users how to each the specific type

**Comment by alicejw-aws** [comment]
Hi @vagimeli , sounds good. Let's meet to discuss the 1-pager first draft.

**Comment by vagimeli** [comment]
@kavilla Please let me know if you're the appropriate technical reviewer for the new content. Draft is in progress.

**Comment by vagimeli** [comment]
Addressing @joshuarrrr feedback. UX working on UI steps graphic

**Comment by vagimeli** [comment]
@joshuarrrr and @vagimeli working to wrap this up for 2.5

**Comment by vagimeli** [comment]
@joshuarrrr Can we publish the foundational content we have to date and iterate as needed?

**Comment by joshuarrrr** [comment]
We'll also want to capture usage of built-in event handlers such as adding filters: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3640

**Comment by joshuarrrr** [comment]
@vagimeli Is there a draft of this doc? I don't see anything linked here.
