### ISSUE TITLE
Update docs with more cautions about beats compatability

### ISSUE THREAD

**Issue by ryn9** [opensearch-project/documentation-website#119]
Please update the docs to reflect beyond wire compatibility, using beats beyond 7.10.x risks beats using logic that may not be compatible with the opensearch backend. 

Example - beats often make use of ingest pipelines - and newer ingest pipelines may use features that require the opensearch backend be compatible with > 7.10.x

**Comment by elfisher** [comment]
@ryn9 is the logic you are referring to in the open source beats?

**Comment by ryn9** [comment]
@elfisher - it is applicable to both opensource and non-opensource versions

**Comment by aetter** [comment]
Hi @ryn9, I added a note to this page: https://opensearch.org/docs/clients/agents-and-ingestion-tools/index/#downloads

Is your thinking here that we should just recommend 7.10.2 across the board?

**Comment by ryn9** [comment]
I would recommend at least a caution that use of beats > 7.10 risks potential compatibility issues with use of ingest pipelines.
Elastic has pushed a fair amount of ETL into the ingest pipelines that lives inside of Elasticsearch, instead of ETL being done in beats, logstash, or other part of the data ingest process.  As such - there very well could be ingest pipeline code not compatible with Opensearch. Again - this is applicable to both opensource and non-opensource versions of beats.  Hopefully I am being clear - but do let me know if you need more info.
