### ISSUE TITLE
[DOC] Update Naming Convention for Drag and Drop Wizard

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#1198]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 With release 2.4, the drag and drop visualization wizard naming convention will change to Visualization Builder. Make changes to documentation accordingly. Add gif showing drag and drop functionality.  

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
#992 
[[D&D] Replace wizard naming convention #1706](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1706)
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1157

**Comment by vagimeli** [comment]
Confirmed with @seanneumann @ashwin-pc UI and name changing to Visualization Builder

**Comment by ashwin-pc** [comment]
@vagimeli Are we on track for this?

**Comment by vagimeli** [comment]
Documentation https://github.com/opensearch-project/documentation-website/pull/1808

**Comment by ashwin-pc** [comment]
Thank you!
