### ISSUE TITLE
[DOC] Search box content is rendered under some elements on the page 

### ISSUE THREAD

**Issue by lukas-vlcek** [opensearch-project/documentation-website#1213]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

A picture is worth a thousand words:

<img width="1445" alt="Screenshot 2022-09-14 at 21 03 20" src="https://user-images.githubusercontent.com/205174/190241123-4b6d7ea9-e632-4525-98ec-0fb7d6530929.png">

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

Go to the documentation page, type any query into the `Search...` box and see how the element with results is rendered.

**Comment by Naarcha-AWS** [comment]
@lukas-vlcek: Which browser were you using at the time?

**Comment by lukas-vlcek** [comment]
@Naarcha-AWS Google Chrome, Version 105.0.5195.52 (Official Build) (arm64)

**Comment by hdhalter** [comment]
@AMoo-Miki - can you please take a look at this? I'm also seeing it in Firefox.
