### ISSUE TITLE
[DOC] Update error_trace URL parameter description

### ISSUE THREAD

**Issue by xuezhou25** [opensearch-project/documentation-website#1235]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Coming from this issue[#4255](https://github.com/opensearch-project/OpenSearch/issues/4255)
The description of Stack traces in [OpenSearch documentation](https://opensearch.org/docs/latest/opensearch/common-parameters/) is not comprehensive and may leading to some misunderstanding. 

"To include the error stack trace in the response when an exception is raised, add `error_trace=true` to the request URL." is right.
It is better to add the description of Config setting: If there is a setting of `http.detailed_errors.enabled: false` in config file, the `error_trace` url request will be rejected. 

The detailed logic will be: 
When the config setting `http.detailed_errors.enabled: false`, the request of `error_trace=true` will not contain the detailed error message.
```
$ curl "http://localhost:9200/opensearch/_search?error_trace=false"
{"error":"IndexNotFoundException[no such index [opensearch]]","status":404}

$ curl "http://localhost:9200/opensearch/_search?error_trace=true" 
{"error":"error traces in responses are disabled.","status":400}   
```
This code regarding to this setting is from: https://github.com/opensearch-project/OpenSearch/blob/2.2.1/server/src/main/java/org/opensearch/rest/RestController.java#L368-L375

When there is no config setting for `http.detailed_errors.enabled` or `http.detailed_errors.enabled: true`, the response of URL parameter will contain detailed error message:
```
$ curl "http://localhost:9200/opensearch/_search?error_trace=true&pretty"
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [opensearch]",
        "index" : "opensearch",
        "resource.id" : "opensearch",
        "resource.type" : "index_or_alias",
        "index_uuid" : "_na_",
        "stack_trace" : "[opensearch] IndexNotFoundException[no such index [opensearch]]\n\tat org.opensearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.indexNotFoundException(IndexNameExpressionResolver.java:1067)\n\tat org.opensearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:1004)
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by rursprung** [comment]
please note that there's more to this: if the config option is set then not just the `error_trace` HTTP parameter is disabled but also some error messages are no longer being returned. see https://github.com/opensearch-project/OpenSearch/issues/4545 for further details (this _might_ be a bug, but i guess for now you can document the status quo and it can be updated once the bug ticket has been addressed one way or the other?)
