### ISSUE TITLE
[DOC] [Remote Store] Missing option in Enable the feature section

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/documentation-website#1236]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 - In 2.3.0 release of OpenSearch, remote store is experimental feature and can be enabled by using 1 of the 3 options:
   - By updating jvm.options file
   - By using OPENSEARCH_JAVA_OPTS environment variable
   - By changing run.gradle
 - In the current documentation for [remote store](https://opensearch.org/docs/latest/opensearch/remote), only first 2 options are mentioned and run.gradle option is documented as a pre-requisite.
 - Please refer Segment Replication [configuration doc](https://opensearch.org/docs/latest/opensearch/segment-replication/configuration/) for these changes 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by JeffH-AWS** [comment]
Hi Sachin. Please describe exactly what is missing in this document and where it needs to be added. The information you presented me explicitly calls out run.gradle as a prerequisite.  This information should have been provided to me during your technical review.

Your information stated:

```
To enable the feature flag:
For developers to enable with Gradle run:
Update run.gradle with:

testClusters {
  runTask {
    testDistribution = 'archive'
    if (numZones > 1) numberOfZones = numZones
    if (numNodes > 1) numberOfNodes = numNodes
    systemProperty 'opensearch.experimental.feature.replication_type.enabled', 'true'
    systemProperty 'opensearch.experimental.feature.remote_store.enabled', 'true'
  }
}
```

So "to enable the feature flag" we add this to `run.gradle` which is documented. You then went on to explain how the feature is enabled on individual nodes:

```
To enable on a node using a tarball:
Option 1. Update config/jvm.options with:

-Dopensearch.experimental.feature.replication_type.enabled=true
-Dopensearch.experimental.feature.remote_store.enabled=true


Option 2. include the flag in OPENSEARCH_JAVA_OPTS before ./bin/opensearch

OPENSEARCH_JAVA_OPTS="-Dopensearch.experimental.feature.replication_type.enabled=true -Dopensearch.experimental.feature.remote_store.enabled=true" ./opensearch-2.3.0/bin/opensearch

Option 3: Specify OPENSEARCH_JAVA_OPTS env var.

export OPENSEARCH_JAVA_OPTS="-Dopensearch.experimental.feature.replication_type.enabled=true -Dopensearch.experimental.feature.remote_store.enabled=true"
./bin/opensearch
```

**Comment by hdhalter** [comment]
This has been documented for 2.3: https://opensearch.org/docs/latest/opensearch/remote/
