### ISSUE TITLE
[DOC] Update segment replication feedback link

### ISSUE THREAD

**Issue by ariamarble** [opensearch-project/documentation-website#1238]
**What do you want to do?**
 
- [X ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Updating feedback link for segment replication page

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Documented in 2.3: https://opensearch.org/docs/latest/opensearch/segment-replication/index/
