### ISSUE TITLE
[DOC-META ] Review LDAP configuration documentation and provide overall updates

### ISSUE THREAD

**Issue by cwillum** [opensearch-project/documentation-website#1248]
The Active Directory and LDAP documentation needs review and update of outdated and missing information. See also issue #905 to update Docker example.

Making this a META issue for LDAP so we can pick away at LDAP issues piecemeal. Known issues for LDAP are listed below, and others can be added to the list as we move along in our review of LDAP content.

- [x] #1583
- [x] #1584
- [ ] Active Directory and LDAP Security Plugin zip is out-of-date. #1365 
- [x]  ldap docker example is outdated. #905

**Comment by cwperks** [comment]
A new attribute for `custom_return_attributes` is under review now and will need to be added to the documentation website for a future release: https://github.com/opensearch-project/security/pull/2093

**Comment by hdhalter** [comment]
Hi @cwperks - Looks like this setting was added in 2.4? It doesn't look like it was added to the documentation. Can you please provide some details or submit a PR? Thanks!

**Comment by cwperks** [comment]
@hdhalter Thank you for pinging. I will submit a PR to add `custom_return_attributes` to the LDAP documentation now that the linked PR has been merged.

**Comment by cwperks** [comment]
@hdhalter Opened a PR for the LDAP setting that was added: https://github.com/opensearch-project/documentation-website/pull/5810

**Comment by hdhalter** [comment]
Since this is in progress and is the last item to address, I'll close this issue. See https://github.com/opensearch-project/documentation-website/issues/1365
