### ISSUE TITLE
Incorrect configurations for Dashboards Security Plugin 

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/documentation-website#125]
### Description
Original Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/686

Developer was trying to setup OpenID Connect and following the directions here: https://opensearch.org/docs/security-plugin/configuration/openid-connect/#opensearch-dashboards-single-sign-on

And it failed because it's not the correct config path. The correct config path is called in the plugin as:
[opensearch_security](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/opensearch_dashboards.json#L5)

### Expected Solution
Update the documentation to display the correct configuration

**Comment by keithhc2** [comment]
Closed with f7093ff
