### ISSUE TITLE
[DOC] cluster settings API documentation doesn't specify that only certain (which?) parameters can be updated

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#1259]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
neither the documentation on [updating configuration via the API](https://opensearch.org/docs/latest/opensearch/configuration/#update-cluster-settings-using-the-api) nor the [API documentation itself](https://opensearch.org/docs/latest/opensearch/rest-api/cluster-settings/) document that this isn't possible for all config options but only for specific options.
if used with a config option which isn't supported an error is returned.
it is unclear which config options are supported as this isn't documented either.

**What other resources are available?**
vaguely related issue (I noticed it as part of this, otherwise unrelated): https://github.com/opensearch-project/OpenSearch/issues/4545

**Comment by ariamarble** [comment]
Status - most of the research and testing is complete on this one. Currently working on a rewrite of some pages.

**Comment by ariamarble** [comment]
Now under review.

**Comment by ariamarble** [comment]
PR https://github.com/opensearch-project/documentation-website/pull/2085 has been completed. Closing
