### ISSUE TITLE
[DOC] Reports scheduler

### ISSUE THREAD

**Issue by ariamarble** [opensearch-project/documentation-website#1272]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Add documentation for reports scheduler feature

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by ariamarble** [comment]
Resource - https://github.com/opensearch-project/reporting

**Comment by ariamarble** [comment]
After reading through the code and testing the plugin I found that I could not hit the reporting endpoints without errors. Reaching out to SME (maharup), they clarified that the report scheduler plugin can not be used without the reportsDashboard plugin. It is backend for reportsDashboard.  This feature is already documented at - https://opensearch.org/docs/latest/dashboards/reporting/. This the only use cases for end-users: working through Dashboards and API calls directly to reports-scheduler won’t work.

This being the case, I am closing out this PR as there is not further action for documentation to take.

**Comment by hdhalter** [comment]
Thanks, Aria!
