### ISSUE TITLE
Add documentation for timeout based cancellation of search request

### ISSUE THREAD

**Issue by sohami** [opensearch-project/documentation-website#128]
[This PR](https://github.com/opensearch-project/OpenSearch/pull/986) introduces the support for timeout based cancellation for search request. It adds request level parameter (`cancel_after_time_interval`) for search and msearch requests and cluster setting `search.cancel_after_time_interval` to control the timeout interval for cancelling the request. The feature is targeted for 1.1 release.

**Comment by elfisher** [comment]
@sohami thanks for creating this issue. I had a couple of questions. Is these parameters only transport layer or are they also available for any `_search` REST call? If they are in the REST layer, is it just a query parameter in the JSON request body? Thanks!

**Comment by sohami** [comment]
The new parameter is supported in REST layer as a query parameter only.
