### ISSUE TITLE
[Bug] Search Experience URL display not correct

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/documentation-website#129]
I found this Search Experience url display is not correct in opensearch.org. Right now it is displayed as
`https://opensearch.org/docs/opensearch/ux/` which should be `https://opensearch.org/docs/opensearch/search-experience/`

**Comment by aetter** [comment]
Hey @ananzh, URLs get generated from the Markdown file name, not the header. In this case, the Markdown file is indeed `ux.md`, so I wouldn't call the link wrong. Are you just saying you'd like the file to be renamed so that it's a little easier to find...?
