### ISSUE TITLE
Add links to tested client versions

### ISSUE THREAD

**Issue by elfisher** [opensearch-project/documentation-website#130]
For the [tested clients](https://opensearch.org/docs/clients/index/), it would be helpful to link to compatible downloads. Could we add them?

**Comment by aetter** [comment]
Hey @elfisher, were you thinking the direct links to the versions in the package managers? AKA the following?

- https://search.maven.org/artifact/org.elasticsearch.client/elasticsearch-rest-client/7.13.4/jar
- https://search.maven.org/artifact/org.elasticsearch.client/elasticsearch-rest-high-level-client/7.13.4/jar
- https://pypi.org/project/elasticsearch/7.13.4/
- https://www.npmjs.com/package/@elastic/elasticsearch/v/7.13.0

**Comment by elfisher** [comment]
Exactly!

**Comment by aetter** [comment]
👍  https://github.com/opensearch-project/documentation-website/commit/3f7f6516198694bacd6500a97e89065369368f17
