### ISSUE TITLE
Correct copyright notices to reflect Copyright OpenSearch Contributors

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#131]
Coming from https://github.com/opensearch-project/.github/issues/21.

The correct copyright for open-source projects in opensearch-project is "Copyright OpenSearch Contributors". Please correct any places that say otherwise, especially where it says copyright Amazon. Make sure NOTICE.txt and README match. See https://github.com/opensearch-project/.github/pull/24 for an example.

**Comment by aetter** [comment]
I believe this has been a non-issue since May:

- https://github.com/opensearch-project/documentation-website#copyright
- https://github.com/opensearch-project/documentation-website/blob/main/NOTICE

**Comment by dblock** [comment]
Copyright still has a year in it, please remove?

**Comment by aetter** [comment]
Oh, sure: https://github.com/opensearch-project/documentation-website/commit/45fea0e20eb7314ed29485f250cb2050db052ab5
