### ISSUE TITLE
Guidance describing potential impacts to DLS and FLS control when using other plugins[DOC]

### ISSUE THREAD

**Issue by cwillum** [opensearch-project/documentation-website#1355]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
For plugins that extract data from an index and store it in the plugin to facilitate their functionality, there may be cases where either metadata captured for alerts or search results retrieved with an API provide description of the index to a user that would otherwise be concealed from that user by document-level security (DLS) and field-level security (FLS) fine-grained access controls. 

The issue creates documentation that advises users to keep these design elements in mind when assigning permissions to groups of users and advocates using role based access control to prevent unintended viewing of this data.

The impacted plugins are:
* Alerting
* Anomaly Detection
* Asnychronous Search

**What other resources are available?**

The PR for this issue: [#1854](https://github.com/opensearch-project/documentation-website/pull/1854).

**Comment by Naarcha-AWS** [comment]
@Naarcha-AWS to find SME for asynchronous search.

**Comment by lezzago** [comment]
We need an additional one for Security Analytics.

**Comment by cwillum** [comment]
Changes for Alerting, Anomaly Detection, Asnychronous Search are merged in #2927. Live in documentation.
Changes for Security Analytics have been made in #3184. Unfortunately, the changes created merge conflicts that need to be resolved. Will try to address these next opportunity.
The PR for Security Analytics isn't cross referenced with this issue. So I'm going to close this.
