### ISSUE TITLE
[DOC] List all breaking change of REST API and setting that caused by applying inclusive terminology

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/documentation-website#1360]
**What do you want to do?**

- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
All OpenSearch REST APIs and settings that contain non-inclusive terminology (master and blacklist/whitelist) have been deprecated in OpenSearch version 2.0, and alternative REST APIs and settings with inclusive terminology are added at the same time.
The current plan is to remove all the deprecated usages in version 3.0, and this will a notable breaking change for end-user.

To help user migrate to the new usages, I suggest in the page for "breaking change in version 3.0" (I assume there will be such a page), list all detailed changes and important notes of the affected REST APIs and settings that I mentioned in the 2 issues: https://github.com/opensearch-project/documentation-website/issues/450 (master -> cluster manager) and https://github.com/opensearch-project/documentation-website/issues/449 (blacklist/whitelist -> deny list/allow list).

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Besides the above 2 issues, a related issue: https://github.com/opensearch-project/documentation-website/issues/1008

**Comment by Naarcha-AWS** [comment]
To close this, we should update the [breaking changes page](https://opensearch.org/docs/2.6/breaking-changes/) to call out that we plan on deprecating these terms in 3.0.0.
