### ISSUE TITLE
[DOC] Add the note regarding the possibility of conflicting settings in jvm.options and OPENSEARCH_JAVA_OPTS

### ISSUE THREAD

**Issue by reta** [opensearch-project/documentation-website#1361]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Came out of https://github.com/opensearch-project/opensearch-devops/issues/93, it would be useful to warn users when conflicting JVM arguments are specified usign diferrent means.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by JeffH-AWS** [comment]
I'm assuming that `jvm.options` is overriding anything passed in the command line to the service. Just need to double check that, then I'll get some wording added.

**Comment by reta** [comment]
> I'm assuming that `jvm.options` is overriding anything passed in the command line to the service. Just need to double check that, then I'll get some wording added.

That is correct, but not only override - it could conflict (fe attempting to change GC and set some GC specific settings), the consequences - the service won't even start.

**Comment by JeffH-AWS** [comment]
Oh!!  Yikes that is quite bad.
