### ISSUE TITLE
[DOC]: Explain `-` is DSL search queries

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#1362]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
OpenSearch relies on text analyzers for processing text fields using the Unicode text-standard. Unicode defines `-` as a word boundary within queries. For examples, if I make a query where I search docuemtns for `User-A`, I could expect to see all documents related to `User-A`. However, OpenSearch returns documents for `User` and `A` as separate terms. As tested in OpenSearch 2.0.1:

**Request**

```
GET test-index/_search
{
  "query": { 
    "bool": {
      "must": {
        "match": {
          "user.id": "kobe-A"
        }
      }
    }
  }
}
```

**Response**

```
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : 2.6694658,
    "hits" : [
      {
        "_index" : "test-index",
        "_id" : "M9pCGoMBluzbdDDR6awp",
        "_score" : 2.6694658,
        "_source" : {
          "@timestamp" : "2022-09-07T13:12:00",
          "message" : "GET /search HTTP/1.1 200 1070000",
          "user" : {
            "id" : "kobe-A"
          }
        }
      },
      {
        "_index" : "test-index",
        "_id" : "N9pCGoMBluzbdDDR9azP",
        "_score" : 1.6099696,
        "_source" : {
          "@timestamp" : "2022-09-07T13:12:00",
          "message" : "GET /search HTTP/1.1 200 1070000",
          "user" : {
            "id" : "kobe-B"
          }
        }
      }
    ]
  }
```

While this is an expected behavior, we should make it clear to users how the `-` operates within DSL search queries, both linking to the unicode standard and explaining the expected response.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

Links:

1. https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#convert-text-with-analyzers
2. https://opensearch.org/docs/latest/opensearch/mappings/
3. https://www.elastic.co/guide/en/elasticsearch/reference/7.10/analysis-standard-analyzer.html
4. https://unicode.org/reports/tr29/#Word_Boundaries

**Comment by hdhalter** [comment]
@lizsnyder Hi Liz, can you please add this to your documentation once we get it documented? We can share the text with you. Thanks.

**Comment by Naarcha-AWS** [comment]
Looks like this issue was addressed in https://opensearch.org/docs/latest/opensearch/query-dsl/index/#a-note-on-unicode-special-characters-in-text-fields. 

Closing this issue for now.
