### ISSUE TITLE
[DOC] Active Directory and LDAP Security Plugin zip is out-of-date

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/documentation-website#1365]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] ~Add new documentation~
- [x] Report a technical problem with the documentation
- [ ] ~Other~

 The documentation at https://opensearch.org/docs/latest/security-plugin/configuration/ldap/ needs to be updated. Right now, there is an embedded zip with a demo setup for running LDAP but users who try to run the demo will be shown a HTTP 401: Unauhorized code when they try to use curl to access the index per the doc. 

To fix this issue the zip needs to have the docker-compose.yml image for osixia/openldap pinned to 1.5.0 `osixia/openldap:1.5.0`; likewise the osixia/phpldapadmin image should be pinned to `osixia/phpldapadmin:0.9.0`

This will make the file work on download. Alternatively the configs can be modified to accommodate the newer 2.3.0 release but I know the rollback works.

**Comment by cwillum** [comment]
Correct, this needs attention. Also see [#905](https://github.com/opensearch-project/documentation-website/issues/905).

**Comment by hdhalter** [comment]
@scrawfor99 - I know Chris started on this, but not sure what state he left it in. Do you want to research this? Thanks

**Comment by AntonEliatra** [comment]
@hdhalter I'll take this one
