### ISSUE TITLE
Plugin Installation Guide Question

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/documentation-website#1377]
- [ ] ~Request a change to existing documentation~
- [X] Add new documentation
- [ ] ~Report a technical problem with the documentation~
- [ ] ~Other~

When attempting to follow the existing plugin installation guide (https://opensearch.org/docs/latest/dashboards/install/plugins/#prerequisites) , I am unclear on the installation process. Perhaps it is an error on my end but I cannot seem to find the opensearch-plugin tool anywhere in `usr/local/bin` or any other path associated with Opensearch or Dashboards. 

If it is an error on my end please direct me towards to correct location if you could; otherwise the documentation may need to be updated. 

Thank you!

**Comment by JeffH-AWS** [comment]
I'll take a look at this today.

**Comment by JeffH-AWS** [comment]
Which installation method did you use for the deployment you're testing @scrawfor99?

In Docker:
```
[opensearch-dashboards@d798e384c868 bin]$ pwd
/usr/share/opensearch-dashboards/bin
[opensearch-dashboards@d798e384c868 bin]$ ll
total 12
-rwxr-xr-x 1 opensearch-dashboards opensearch-dashboards 1182 Sep  9 00:11 opensearch-dashboards
-rwxr-xr-x 1 opensearch-dashboards opensearch-dashboards 1065 Sep  9 00:11 opensearch-dashboards-keystore
-rwxr-xr-x 1 opensearch-dashboards opensearch-dashboards 1102 Sep  9 00:11 opensearch-dashboards-plugin
```

RPM:
```
$ pwd
/usr/share/opensearch-dashboards/bin
$ ll
total 12
-rwxr-xr-x 1 opensearch-dashboards opensearch-dashboards 1182 Sep  9 00:12 opensearch-dashboards
-rwxr-xr-x 1 opensearch-dashboards opensearch-dashboards 1065 Sep  9 00:12 opensearch-dashboards-keystore
-rwxr-xr-x 1 opensearch-dashboards opensearch-dashboards 1102 Sep  9 00:12 opensearch-dashboards-plugin
```

**Comment by JeffH-AWS** [comment]
We can get the doc updated to include guidance on where the command line tool is located, but before moving on to that side please let me know if the output of `pwd` above was helpful or not.

If you're installing manual from the tarball then the relative path is literally `opensearch-<version>/bin`

**Comment by JeffH-AWS** [comment]
@scrawfor99 when you have an opportunity could you please provide more info?  See my previous comments.  I'd like to better understand the use case.

**Comment by JeffH-AWS** [comment]
Putting this on the backlog since I haven't gotten any follow-up info. I'll leave it open for awhile before closing it as stale just in case.

**Comment by JeffH-AWS** [comment]
Closing this stale issue. Please feel free to reopen this issue if/when you're able to provide the requested information.
