### ISSUE TITLE
Improve logstash (opensearch output plugin) doc (Migrate from OpenDistro to OpenSearch)

### ISSUE THREAD

**Issue by itsul** [opensearch-project/documentation-website#142]
The documentation should be extended. There is a chance from elasticsearch to opensearch as an output plugin in the logstash-oss version which can be missed while setting up an opensearch environment

Affected documentation https://opensearch.org/docs/clients/logstash/index/#install-logstash

There should be a hint in step 4 like: "For users that migrate from Elastic or Amazon OpenDistro: The output plugin has changed from elasticsearch to opensearch"

Regards

**Comment by ashwinkumar12345** [comment]
Added - https://opensearch.org/docs/latest/clients/logstash/index/.
