### ISSUE TITLE
[DOC] Immutable indices setting is not documented

### ISSUE THREAD

**Issue by zbalkan** [opensearch-project/documentation-website#1436]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**

Immutable indices are needed for security products that require a guarantee of integrity. We provide integrity for plaintext logs with checksums. But in a database, it is not always the case. And we need to ensure logs are not tampered.

I created a forum topic about the issue and a forum user with a nickname [pablo](https://forum.opensearch.org/u/pablo), managed to find that it is already there. It is also possible to see in the full list of all settings provided in [another issue](https://github.com/opensearch-project/documentation-website/issues/214#issuecomment-1262492962).

How it works, default values, relationship with indice management policies -such as "would a DELETE action be applied to an immutable index?"- needs to be clarified.

All versions are affected from the lack of documentation.

**What other resources are available?**
Nothing but the source code itself: 
https://github.com/opensearch-project/security/search?q=SECURITY_COMPLIANCE_IMMUTABLE_INDICES

**Comment by Naarcha-AWS** [comment]
Thanks for the issue submission @zbalkan.

**Comment by hdhalter** [comment]
@cwillum - Does this look like something you can take on?

**Comment by cwillum** [comment]
@here Sure.

**Comment by hdhalter** [comment]
@scrawfor99 - Is this a setting that was missed? https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/security-settings/

 https://github.com/search?q=repo%3Aopensearch-project%2Fsecurity+SECURITY_COMPLIANCE_IMMUTABLE_INDICES&type=code

**Comment by scrawfor99** [comment]
Hi @hdhalter, yeah seems like this was missed when I had gone through the settings before. My bad! Thanks for the catch. We should add this as well. John should be able to I suspect.

**Comment by hdhalter** [comment]
> Hi @hdhalter, yeah seems like this was missed when I had gone through the settings before. My bad! Thanks for the catch. We should add this as well. John should be able to I suspect.

Thanks, can you please add it to his queue?

**Comment by AntonEliatra** [comment]
@hdhalter I can take this one
