### ISSUE TITLE
Modify documentation about Dashboard ssl.certificateAuthorities

### ISSUE THREAD

**Issue by Jakob3xD** [opensearch-project/documentation-website#144]
**Issue** 
When setting up my Opensearch Cluster and the Dashboard, I got stuck with the option `opensearch.ssl.certificateAuthorities` in the Dashboard configuration file.

For the named option I can find two entries:
https://opensearch.org/docs/security-plugin/configuration/generate-certificates/#opensearch-dashboards
> You have two options: disable SSL verification or add the root CA.

https://opensearch.org/docs/dashboards/install/tls/
> [...]specify the full path (e.g. [ "/usr/share/opensearch-dashboards-1.0.0/config/root-ca.pem" ] to the certificate authority for your OpenSearch cluster.

To get the Dashboard working with SSL you need both the "signing CA" and the "root CA" if they are not the same.

**Wish**
I would wish that the docs get updates with a more clear definition of what CA(s) are needed.
Something like that:
> You have two options: disable SSL verification or add the root CA and signing CA. 

> [...] to the root CA and signing CA for your OpenSearch cluster.

**Comment by aetter** [comment]
Hey @Jakob3xD, I've basically removed that section and pointed to the more comprehensive content, since yeah, you need the root CA and a client certificate. Does https://github.com/opensearch-project/documentation-website/pull/146 address your concerns?

**Comment by Jakob3xD** [comment]
Hey @aetter, unfortunately it does not.
I have a company wide self signed root CA from which we generated an Opensearch CA signed by it. I generate all my node certs from the Opensearch CA. Therefore my root CA is different from the issuer CA.
The dashboard requires to set both CA in the config. Otherwise the dashboard is not able to connect to the cluster.
When the issuer CA is missing and only the root CA is given:
```
{"type":"log","@timestamp":"2021-08-19T07:52:14Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: unable to verify the first certificate"}
```
When the issuer CA is given but the root CA is missing:
```
{"type":"log","@timestamp":"2021-08-19T07:53:05Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: unable to get issuer certificate"}
```
Therefore my current SSL setting looks like this:
```opensearch.ssl.certificateAuthorities: [ "/etc/opensearch.crt", "/etc/root.crt" ]```

As neither error messages are documented I searched for `opensearch.ssl.certificateAuthorities` but could not find a hint to my issue.
That is the reason I asked for the documentation update. You changes does not point out that the Dashboard need both CAs the issuer and the root one.

**Comment by aetter** [comment]
Thanks @Jakob3xD, that's helpful. I've modified the PR. Let me know what you think.

Would you recommend that we update https://opensearch.org/docs/security-plugin/configuration/generate-certificates/ to include an intermediate certificate? In other words, do you think your situation is more common than just using the root CA?

**Comment by Jakob3xD** [comment]
Yes the PR looks good. Thank you for that.

I don't think that we need to update the cert generation. For most users the current documentation is fine.
I assume that an intermediate certificate is something more advanced which could confuse people when they are not familiar with SSL Certificates.
