### ISSUE TITLE
Get Started with Data Prepper

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#1457]
Migrate over https://github.com/opensearch-project/data-prepper/blob/main/docs/getting_started.md

**Comment by Naarcha-AWS** [comment]
We'll only backport this OpenSearch 2.0 and greater

**Comment by hdhalter** [comment]
Looks like this is migrated, but only back to 2.2. Is this the intention? @Naarcha-AWS
