### ISSUE TITLE
[DOC] Update Dashboards plugin page to match core plugin format

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#1479]
**What do you want to do?**
 
- [x] Request a change to existing documentation

**Tell us about your request.** 

Update the [Dashboards plugin page](https://opensearch.org/docs/latest/dashboards/install/plugins/] to match how we convey versions in the [OpenSearch Core plugins page](https://opensearch.org/docs/latest/opensearch/install/plugins/#available-plugins). Instead of calling out each plugin version in the table, create a table that lists each plugin than indicates the supported versions as `1.0.0 or greater`. 
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by akarsh-jain-790** [comment]
Hey, I would like to work on this issue.
