### ISSUE TITLE
[DOC] Add `opensearch_security.openid.root_ca` to security plugin documentation

### ISSUE THREAD

**Issue by davidlago** [opensearch-project/documentation-website#1499]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Coming from https://github.com/opensearch-project/security-dashboards-plugin/issues/210, it seems like there is an undocumented `opensearch_security.openid.root_ca` config setting that we should document.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Hi Chris, can you please take a look at this one? It's a security setting that's missing. An external contributor discovered it a while back and Dave confirmed that it still exists in our code. Thanks!

**Comment by hdhalter** [comment]
See https://opensearch.org/docs/latest/security/authentication-backends/openid-connect/

Closed by #5697
