### ISSUE TITLE
Dark mode for documentation

### ISSUE THREAD

**Issue by aetter** [opensearch-project/documentation-website#15]
Dark modes are—and this is beyond dispute—cool. We should have a dark mode toggle in the documentation, similar to [Docusaurus](https://docusaurus.io/docs/) and [Docker](https://docs.docker.com/get-started/).

Original issue here: https://github.com/opendistro/for-elasticsearch-docs/issues/383

**Comment by joshuarrrr** [comment]
The `just-the-docs` theme supports the ability to [customize or switch the color scheme](https://github.com/just-the-docs/just-the-docs/blob/501c007da1dcde37abd13080df264114b5fe966f/docs/customization.md#color-schemes)

**Comment by hdhalter** [comment]
This will be done by the overall changes to the website. Closing this issue since it is in the project-website repo: https://github.com/opensearch-project/project-website/issues/541
