### ISSUE TITLE
[DOC] Fix the Download link on the Documentation site

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#1514]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 The top right menu Download link on the Documentation site acts differently than the other pages of the site. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
1. Go to https://opensearch.org/docs/latest/
2. Click the Download link in the upper right menu. You get this URL: https://opensearch.org/downloads.html#opensearch instead of this URL: https://opensearch.org/downloads.html. 

The link was fixed on the menu in other pages but not on the Documentation site.

**Comment by hdhalter** [comment]
@nateynateynate - is this something you can fix? Thanks.

**Comment by nateynateynate** [comment]
Branch merged. Will keep eyes on the site to verify, then I'll close this out.

**Comment by hdhalter** [comment]
Done.
