### ISSUE TITLE
Kibana read only access not working

### ISSUE THREAD

**Issue by lizsnyder** [opensearch-project/documentation-website#152]
With read_only permission role in kibana, users seem to be able to edit the dashboard which is not expected.

Issue
==========================
We have an Elasticsearch cluster set up with fine-grain access control enabled, and authentication to Kibana is handled by Cognito. We have Cognito set up to assign an IAM role to the user based on a claim passed from our SAML idp. At the moment we have two IAM roles:

* Admin (Full access to Kibana, this is also specified as the elasticsearch Master User ARN)
* Read-Only (Should only have read-only access to kibana dashboards/visualizations/indices)

The admin user/role is working OK, but I cannot get the read-only role configured such that they have read-only access. They are assigned the IAM role fine, and I can map the read-only backend IAM role to kibana roles. I was following this guide: https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/users-roles/#set-up-a-read-only-user-in-kibana. I created the read_only_index role w/ indices, and mapped the read-only IAM role to this and the "kibana_user"/"kibana_read_only" roles per the guide. When a read-only user logs in I can see they get assigned these kibana roles, but they still have write access to dashboards.

What is the correct combination of kibana roles/setup such that I can provide kibana users read-only access?

Observations:
============
I have also tried replicating the issue at my end with the help of the document https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/users-roles/#set-up-a-read-only-user-in-kibana with the internal users instead of backend role.

After making the read-only setup, when I tried logging in with the new user having read only permission, in the kibana page they are getting only the Dashboard options and all other options has been greyed out and not displayed. On the dashboard I was able to load and edit the dashboard by adding visualisation or removing the existing visualisation from the dashboard. 

Goal:
====
Need to understand why in readonly permission, the user is able to edit or remove visualization from dashborad.

**Comment by keithhc2** [comment]
I want to say we can close it? It was an issue that I could never replicate.
