### ISSUE TITLE
[BUG] Make navbar backport agnostic moving forward. 

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/documentation-website#1545]
**What do you want to do?**
 
- [X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Mods to the navbar seem to require backporting even though they have nothing to do with the actual documentation. I'd like to see about fixing this. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

I'm guessing that most of the answer will end up being inside of the liquid templating for docs site.

**Comment by tanishk-23** [comment]
@nateynateynate can I work on this?

**Comment by nateynateynate** [comment]
@tanishk-23 Please! I have a feeling this will require some mods to the liquid.js templates so that the navbar isn't part of the collections logic. If you end up needing another set of eyes I'm happy to eyeball your solutions as well. 

Thanks!

**Comment by nateynateynate** [comment]
Pro-Tip: Make sure to restart the jekyll server after any modifications to `_config.yml`

**Comment by tanishk-23** [comment]
@nateynateynate can you please elaborate this issue as i am not able to understand.

**Comment by nateynateynate** [comment]
@tanishk-23 - normally when documentation is added or changed, it's for a specific version of OpenSearch's documentation. So in this repo, this is what we refer to as a "backport" - if the documentation submitted applies to more than just latest, it has to be merged with the other branches so that when the user selects the version of documentation they want, a different set of docs appears. 

And therein lies the problem: 

There's something about the way our templates are written that makes it include the navbar as part of some the logic. The navbar should stand on its own. The presentation of the navbar should be pulled out of the logic in the templates and placed inside of a section of the layout that doesn't care what version of the docs the visitor is looking at. 

My first suggestion is to check inside of `_layouts` to see where the navbar is being included, and I have a feeling you'll see that its inside of a bunch of template logic. And then perhaps under `_includes`

**Comment by hdhalter** [comment]
@nateynateynate - Hi Nate, can I trasfer this to the project-website repo? I believe we are handling the common issues there.

**Comment by hdhalter** [comment]
Closing, since this is covered in the project-website repo.
