### ISSUE TITLE
[DOC] Move Docker Performance Analyzer instructions to  _monitoring-plugins/pa/index.md

### ISSUE THREAD

**Issue by JeffHuss** [opensearch-project/documentation-website#1555]
**What do you want to do?**
 
Currently the installation process for Docker also specifically calls out instructions for Performance Analyzer. Based on previous discussions with developers and others involved with the OpenSearch project, this is an artifact of long ago when an arbitrary decision was made to include it. It was decided, however, that the process should not live in the installation documentation, but should be LINKED there and actually described in the PA plugin docs.

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
This affects all versions that include the PA plugin. I'm including the section with all of the original information below. Since GitHub is interpreting the markdown, here's a link to the commit where I removed it for your reference: https://github.com/opensearch-project/documentation-website/commit/a5937320ef6a92f064b9df1af11c1bd766169386

```
### (Optional) Set up Performance Analyzer

1. Enable the Performance Analyzer plugin:

   ```bash
   curl -XPOST localhost:9200/_plugins/_performanceanalyzer/cluster/config -H 'Content-Type: application/json' -d '{"enabled": true}'
   ```

   If you receive the `curl: (52) Empty reply from server` error, you are likely protecting your cluster with the security plugin and you need to provide credentials. Modify the following command to use your username and password:

   ```bash
   curl -XPOST https://localhost:9200/_plugins/_performanceanalyzer/cluster/config -H 'Content-Type: application/json' -d '{"enabled": true}' -u 'admin:admin' -k
   ```

1. Enable the Root Cause Analyzer (RCA) framework

   ```bash
   curl -XPOST localhost:9200/_plugins/_performanceanalyzer/rca/cluster/config -H 'Content-Type: application/json' -d '{"enabled": true}'
   ```

   Similar to step 1, if you run into `curl: (52) Empty reply from server`, run the command below to enable RCA

   ```bash
   curl -XPOST https://localhost:9200/_plugins/_performanceanalyzer/rca/cluster/config -H 'Content-Type: application/json' -d '{"enabled": true}' -u 'admin:admin' -k
   ```

1. By default, Performance Analyzer's endpoints are not accessible from outside the Docker container.

   To edit this behavior, open a shell session in the container and modify the configuration:

   ```bash
   docker ps # Look up the container id
   docker exec -it <container-id> /bin/bash
   # Inside container
   cd config/opensearch-performance-analyzer/
   vi performance-analyzer.properties
   ```

   Uncomment the line `#webservice-bind-host` and set it to `0.0.0.0`:

   ```
   # ======================== OpenSearch performance analyzer plugin config =========================

   # NOTE: this is an example for Linux. Please modify the config accordingly if you are using it under other OS.

   # WebService bind host; default to all interfaces
   webservice-bind-host = 0.0.0.0

   # Metrics data location
   metrics-location = /dev/shm/performanceanalyzer/

   # Metrics deletion interval (minutes) for metrics data.
   # Interval should be between 1 to 60.
   metrics-deletion-interval = 1

   # If set to true, the system cleans up the files behind it. So at any point, we should expect only 2
   # metrics-db-file-prefix-path files. If set to false, no files are cleaned up. This can be useful, if you are archiving
   # the files and wouldn't like for them to be cleaned up.
   cleanup-metrics-db-files = true

   # WebService exposed by App's port
   webservice-listener-port = 9600

   # Metric DB File Prefix Path location
   metrics-db-file-prefix-path = /tmp/metricsdb_

   https-enabled = false

   #Setup the correct path for certificates
   certificate-file-path = specify_path

   private-key-file-path = specify_path

   # Plugin Stats Metadata file name, expected to be in the same location
   plugin-stats-metadata = plugin-stats-metadata

   # Agent Stats Metadata file name, expected to be in the same location
   agent-stats-metadata = agent-stats-metadata
   ```

1. Then restart the Performance Analyzer agent:

   ```bash
   kill $(ps aux | grep -i 'PerformanceAnalyzerApp' | grep -v grep | awk '{print $2}')
   ```
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by SohamRatnaparkhi** [comment]
hey @JeffH-AWS, I would love to work on this issue. Can you assign it to me?

**Comment by codingday123** [comment]
hey @JeffH-AWS, I would love to work on this issue. Can you assign it to me?

**Comment by Naarcha-AWS** [comment]
@codingday123: Feel free to take this on if you have the bandwidth.

**Comment by hdhalter** [comment]
This is done: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/
