### ISSUE TITLE
[DOC] Add self host maps server document

### ISSUE THREAD

**Issue by junqiu-lei** [opensearch-project/documentation-website#1582]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Self host OpenSearch Maps Server will to be released on docker hub, which allow user to self host a maps server to be used for maps visualization when they aren't able to access to our default maps service CDN, along with the release, we need to have the related doc on website to tell user how to use it.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Project repo: https://github.com/opensearch-project/maps/tree/main/opensearch-maps-server
Release issue: https://github.com/opensearch-project/opensearch-build/issues/2681

**Comment by Naarcha-AWS** [comment]
@junqiu-lei: Does this pertain to a specific version?

**Comment by junqiu-lei** [comment]
Hi @Naarcha-AWS, it doesn't require a specific version of OpenSearch, thanks!

**Comment by vagimeli** [comment]
Met with engineer 10/18; draft content needed by EOD 10/19. Releasing this feature this week and they want documentation to accompany the release.

**Comment by vagimeli** [comment]
Merged PR #1625
