### ISSUE TITLE
Edit LDAP documentation for custom_attr_allowlist so that it agrees with inclusive language code changes

### ISSUE THREAD

**Issue by cwillum** [opensearch-project/documentation-website#1584]
Add documentation that covers configuration of the LDAP setting `custom_attr_allowlist` in the config.yml file. This references issue [#2032](https://github.com/opensearch-project/security/issues/2032) in the security repo.

**Comment by hdhalter** [comment]
Closed, see https://github.com/opensearch-project/documentation-website/pull/1636
