### ISSUE TITLE
[BUG] Incorrect documentation

### ISSUE THREAD

**Issue by abbashus** [opensearch-project/documentation-website#160]
The documentation at [security-plugin/access-control/api/configuration](https://opensearch.org/docs/security-plugin/access-control/api/#configuration) and [security-plugin/access-control/api/certificates](https://opensearch.org/docs/security-plugin/access-control/api/#certificates) is same. 

The content under **Certificates** should either be removed or replace with correct documenation.

Also the [Patch configuration REST API](security-plugin/access-control/api/#certificates) does not work. See opensearch-project/security#1428

**Comment by aetter** [comment]
I'm getting extreme deju vu here, @keithhc2. Did we not have/fix something similar...?

**Comment by keithhc2** [comment]
@aetter I thought so, too, but turns out #144 was just about CAs. Either way, I'll comb through the security plugin and see if anything else is amiss.

**Comment by keithhc2** [comment]
Certificates section is now fixed, and patch configuration is updated with a mandatory setting before a user can execute that operation: https://opensearch.org/docs/security-plugin/access-control/api/#patch-configuration
