### ISSUE TITLE
[DOC] Links to distribution-specific download artifacts

### ISSUE THREAD

**Issue by kkaempf** [opensearch-project/documentation-website#1609]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [x] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

While the opensearch-project provides generic packages (rpm) for Linux distributions, I wonder if there's interest
in providing distribution-specific links. 

Apparently there is interests in providing such links. See [here](https://github.com/opensearch-project/opensearch-build/issues/28) and [here](https://github.com/opensearch-project/opensearch-build/issues/1824).
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

[openSUSE](https://build.opensuse.org/package/show/security:logging/opensearch) has packages for various of its own distributions :wink:

**Comment by JeffH-AWS** [comment]
@kkaempf could you please describe your request? Are these distributions available already and we just don't publish links?  I'm not quite clear on what you're asking for.

**Comment by JeffH-AWS** [comment]
Closing this stale issue. The Debian distribution will be released for 2.x versions along with the roll out of 2.5. I believe the plan is for Debian distribution availability for 1.x versions along with the roll out of the next 1.x maintenance release.
