### ISSUE TITLE
Include opensearch.yml setting for compatibility mode.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/documentation-website#163]
[This](url) cluster setting is explained in documentation, but this can also be set on a node inside of opensearch.yml.

We should also include the correct setting name on this page to avoid [confusion](https://github.com/opensearch-project/OpenSearch/issues/1022).

```
compatibility.override_main_response_version: true
```

**Comment by dblock** [comment]
We should also document that the setting should be added to the .yml if you are upgrading and taking live traffic. That's the scenario in  https://github.com/opensearch-project/OpenSearch/issues/1022 - without it you get client failures until you set the cluster setting.
