### ISSUE TITLE
.

### ISSUE THREAD

**Issue by JeffH-AWS** [opensearch-project/documentation-website#1654]

**Comment by JeffH-AWS** [comment]
![image](https://user-images.githubusercontent.com/107883031/197261613-f258aa91-81c8-482b-b8b4-eec1ee30f0f3.png)

^ picture of the table for reference

**Comment by ShabanaNaik** [comment]
Hello @JeffH-AWS if no one is working on this. I would like to give it a try. Please assign me this.

**Comment by vagimeli** [comment]
Good first issue for tech writer quality review circle.
