### ISSUE TITLE
[DOC] mget, msearch or bulk Requests Are Not Documented as Cluster permissions.

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/documentation-website#1656]
**What do you want to do?**
 
- [x] Add new documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 >Cluster-level permissions are used to allow/disallow actions that affect either the whole cluster, like querying the cluster health or the nodes stats.
They are also used to allow/disallow actions that affect multiple indices, like `mget`, `msearch` or `bulk` requests.

The above statements are needed to be documented in the [cluster permissions section](https://opensearch.org/docs/latest/security-plugin/access-control/permissions/#cluster-permissions).

**Comment by cliu123** [comment]
@cwillum Please let me know if any information is missing.

**Comment by hdhalter** [comment]
@scrawfor99 - Can you please tell me if this topic adequately addresses the above? https://opensearch.org/docs/latest/security/access-control/permissions/. Thank you!

**Comment by AntonEliatra** [comment]
@hdhalter I can have a look at this one

**Comment by hdhalter** [comment]
@AntonEliatra - Does this also address this issue: https://github.com/opensearch-project/documentation-website/issues/621. Thanks!

**Comment by AntonEliatra** [comment]
@hdhalter yes, I just left a comment there too
