### ISSUE TITLE
References to plugins.security instead of opensearch_security

### ISSUE THREAD

**Issue by jgough** [opensearch-project/documentation-website#166]
https://github.com/opensearch-project/documentation-website/blob/main/_security-plugin/access-control/multi-tenancy.md

This page references `plugins.security` but I believe this should now be `opensearch_security`?

**Comment by aetter** [comment]
It's endless. 😄 Thanks @jgough.

https://github.com/opensearch-project/documentation-website/commit/eaba608cfd2898cbf2554886568c6e2dc0ebc6d3
