### ISSUE TITLE
[DOC] Clarify when Transport vs REST communication is used

### ISSUE THREAD

**Issue by davidlago** [opensearch-project/documentation-website#1661]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 There is some confusion with the [deprecation of TransportClient](https://github.com/opensearch-project/OpenSearch/issues/1669) as to what each method of communication (Transport vs REST) is used for. Perhaps we should clarify in the first paragraph [here](https://opensearch.org/docs/1.3/security-plugin/configuration/tls) that transport is used for node-to-node communication and REST is for calls from clients.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by JeffH-AWS** [comment]
On it.
