### ISSUE TITLE
[BUG] RPM commands missing in documentation

### ISSUE THREAD

**Issue by yilintao-amzn** [opensearch-project/documentation-website#168]
**Describe the bug**

Missing documentation around RPM build. 

**To Reproduce**
1. run command" yarn build --rpm
2. Failed to build the RPM.

**Expected behavior**
The RPM should be built and can be found in the target folder.

**OpenSearch Version**
1.0.0

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.
1.0.0
**Plugins**
N/A
Please list all plugins currently enabled.
None
**Screenshots**

**Additional context**

**Comment by peterzhuamazon** [comment]
Transfer to documentation repo per request of @ahopp

**Comment by kavilla** [comment]
thanks @peterzhuamazon, basically if we some docs to reference this section: https://github.com/opensearch-project/documentation-website/issues/168#issuecomment-878575092 then it should solve this bug.

**Comment by aetter** [comment]
Hey all, the build commands for a particular project are usually best-left in the repository README or developer guide. I'd expect these commands to go in either the Dashboards repo or the build repo. Our general division of content at this time:

Repos:

- What is this thing?
- How do get started with development and build it from source?
- How do I contribute changes or bug fixes?

Documentation:

- What is this thing?
- How do I install it?
- How do I get started with it?
- Reference stuff: supported operations, configuration, tuning, best practices, REST API, etc.

**Comment by peterzhuamazon** [comment]
We are still working on deb/rpm related builds and they are not going to available for 1.1.0.
Will contact the doc team once we have everything ready.

Thanks.

**Comment by Naarcha-AWS** [comment]
Going to close this since the RPM installation instructions were added in 1.3. 

https://opensearch.org/docs/latest/opensearch/install/rpm/
