### ISSUE TITLE
Need for more detailed information about each permissions on opensearch

### ISSUE THREAD

**Issue by liz-snyder-aws** [opensearch-project/documentation-website#170]
Copied from internal issue

## Description:
The customer made a case about permissions of opendistro(opensearch).
The customer's question is "What actions do each permission specifically correspond to?".
Actually, current "permissions" page shows just list of permissions and there's no additional information about each permission.

I think we need to enrich this page, for example, make a table like below.

|permissions                                       |target           |target URL                                       |action
|cluster:admin/opensearch/ad/detector/delete       |Anomaly detection|https://opensearch.org/docs/monitoring-plugins/ad|delete
|cluster:admin/opensearch/ad/detector/jobmanagement|Anomaly detection|https://opensearch.org/docs/monitoring-plugins/ad|jobmanagement
|cluster:admin/opensearch/ad/detector/run          |Anomaly detection|https://opensearch.org/docs/monitoring-plugins/ad|run
|cluster:admin/opensearch/ad/detector/search       |Anomaly detection|https://opensearch.org/docs/monitoring-plugins/ad|search
|cluster:admin/opensearch/ad/detector/stats        |Anomaly detection|https://opensearch.org/docs/monitoring-plugins/ad|stats
|cluster:admin/opensearch/ad/detector/write        |Anomaly detection|https://opensearch.org/docs/monitoring-plugins/ad|write
|cluster:admin/opensearch/ad/detectors/get         |Anomaly detection|https://opensearch.org/docs/monitoring-plugins/ad|get

## URL of the documentatation page
https://opensearch.org/docs/security-plugin/access-control/permissions/

Please tell me anything needed for your investigation.
Best regards, and hope you stay safe.

**Comment by aetter** [comment]
I'm going to close this out based on https://github.com/opensearch-project/documentation-website/pull/187, but let's keep our ears to the ground and see if more issues of this type come up.
