### ISSUE TITLE
[RFC] [DOC] Add feedback mechanism 

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#1708]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Currently, the only way for users to leave feedback on documentation is to enter a Github issue. While this works fairly well, we have no quantitative way to measure if a user is happy or unhappy with the content.

Therefore, we should add the a feedback widget to each doc page, whether its a star rating (https://www.twilio.com/docs/autopilot/guides/how-to-build-a-chatbot), or a thumbs up, thumbs down mechanism. When a user selects the feedback mechanism, a modal would pop up allowing them to explain their rating.

To add this mechanism, it would require:

1. Changing the default template in Jekyll.
2. Creating a liquid include or some other form to add interaction to the rating.
3. Work with design to determine how the mechanism should look [Nice-to-have]

 We can use Google Analytics to capture the data.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Here is a potential solution from a fellow colleague: https://github.com/facebook/react-native-website/pull/1449 and https://github.com/facebook/react-native-website/pull/1458/files

**Comment by krisfreedain** [comment]
This is interesting. The first thing that comes to mind is something that AWS does on each of their documentation pages ([example](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/concepts.html)). They offer a simple 'yes/no' on 'was this helpful' - then a link to provide specific feedback - then a link to make edits via GitHub. 



![Image](https://user-images.githubusercontent.com/4873623/205750287-c5a117b2-1f7c-40fa-8503-c7f6dfe5939c.png)

**Comment by kolchfa-aws** [comment]
@krisfreedain This is very similar to what I'm implementing.

**Comment by hdhalter** [comment]
I'd like to know what they use? I looked into qualtrics recently and was told we cannot use their feedback mechanism. We can only use surveys.

**Comment by krisfreedain** [comment]
@hdhalter - sent an intro email to you and an AWS docs person I know. Hopeful they can provide technical details, or know someone to assist in getting that information.

**Comment by hdhalter** [comment]
Implemented and backported to 2.0 - https://github.com/opensearch-project/documentation-website/pull/2264

**Comment by kolchfa-aws** [comment]
Closing this issue because it has been implemented in #2264
