### ISSUE TITLE
[RFC] Make navigation sticky

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#1709]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Currently, the side navigation of documentation on the left-pane of opensearch.org doesn't scroll down with the user when the body length is longer than the length of the Navigation pane. Let's make the side Navigation sticky while scrolling down, or add a sticky "Back to top" button.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

For an example of this behavior, see [Square's documentation](https://developer.squareup.com/reference/square/inventory-api/retrieve-inventory-count)

**Comment by Naarcha-AWS** [comment]
@nateynateynate: Any ideas on this one? Figure we could add a new element.

**Comment by kolchfa-aws** [comment]
Implemented in #2043
