### ISSUE TITLE
[Improvement] add OpenSearch Dashboards plugin development docs

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/documentation-website#171]
We have removed the docs related to plugin manifest and don't have a replacement for external plugin development (APIs, how to build them, how to install). External plugin development might be painful with the lack of docs so it would be beneficial to add this. This also would assist if we plan on adding new properties for example: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/761. If this is merged there will be no way of knowing this new property unless you are familiar with the code.

Related issue:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/778

The manifest used to look like the following (note the links are no accurate but the property and descriptions are):
```
[Home](./index.md) &gt; [opensearch-dashboards-plugin-core-server](./opensearch-dashboards-plugin-core-server.md) &gt; [PluginManifest](./opensearch-dashboards-plugin-core-server.pluginmanifest.md)

## PluginManifest interface

Describes the set of required and optional properties plugin can define in its mandatory JSON manifest file.

<b>Signature:</b>

```typescript
export interface PluginManifest 
```

## Remarks

Should never be used in code outside of Core but is exported for documentation purposes.

## Properties

|  Property | Type | Description |
|  --- | --- | --- |
|  [configPath](./opensearch-dashboards-plugin-core-server.pluginmanifest.configpath.md) | <code>ConfigPath</code> | Root  used by the plugin, defaults to "id" in snake\_case format. |
|  [description](./opensearch-dashboards-plugin-core-server.pluginmanifest.description.md) | <code>string</code> | TODO: make required once all plugins specify this. A brief description of what this plugin does and any capabilities it provides. |
|  [extraPublicDirs](./opensearch-dashboards-plugin-core-server.pluginmanifest.extrapublicdirs.md) | <code>string[]</code> | Specifies directory names that can be imported by other ui-plugins built using the same instance of the @osd/optimizer. A temporary measure we plan to replace with better mechanisms for sharing static code between plugins |
|  [id](./opensearch-dashboards-plugin-core-server.pluginmanifest.id.md) | <code>PluginName</code> | Identifier of the plugin. Must be a string in camelCase. Part of a plugin public contract. Other plugins leverage it to access plugin API, navigate to the plugin, etc. |
|  [opensearch-dashboardsVersion](./opensearch-dashboards-plugin-core-server.pluginmanifest.opensearch-dashboardsversion.md) | <code>string</code> | The version of opensearch-dashboards the plugin is compatible with, defaults to "version". |
|  [optionalPlugins](./opensearch-dashboards-plugin-core-server.pluginmanifest.optionalplugins.md) | <code>readonly PluginName[]</code> | An optional list of the other plugins that if installed and enabled \*\*may be\*\* leveraged by this plugin for some additional functionality but otherwise are not required for this plugin to work properly. |
|  [owner](./opensearch-dashboards-plugin-core-server.pluginmanifest.owner.md) | <code>{</code><br/><code>        readonly name: string;</code><br/><code>        readonly githubTeam?: string;</code><br/><code>    }</code> | TODO: make required once all internal plugins have this specified. |
|  [requiredBundles](./opensearch-dashboards-plugin-core-server.pluginmanifest.requiredbundles.md) | <code>readonly string[]</code> | List of plugin ids that this plugin's UI code imports modules from that are not in <code>requiredPlugins</code>. |
|  [requiredPlugins](./opensearch-dashboards-plugin-core-server.pluginmanifest.requiredplugins.md) | <code>readonly PluginName[]</code> | An optional list of the other plugins that \*\*must be\*\* installed and enabled for this plugin to function properly. |
|  [server](./opensearch-dashboards-plugin-core-server.pluginmanifest.server.md) | <code>boolean</code> | Specifies whether plugin includes some server-side specific functionality. |
|  [serviceFolders](./opensearch-dashboards-plugin-core-server.pluginmanifest.servicefolders.md) | <code>readonly string[]</code> | Only used for the automatically generated API documentation. Specifying service folders will cause your plugin API reference to be broken up into sub sections. |
|  [ui](./opensearch-dashboards-plugin-core-server.pluginmanifest.ui.md) | <code>boolean</code> | Specifies whether plugin includes some client/browser specific functionality that should be included into client bundle via <code>public/ui_plugin.js</code> file. |
|  [version](./opensearch-dashboards-plugin-core-server.pluginmanifest.version.md) | <code>string</code> | Version of the plugin. |
```

**Comment by kavilla** [comment]
Someone reached out to me and I typed this out I will just copy-pasta what I sent them:
---
To get you started, you can start out with using the scaffolding process of building a plugin:
```
node scripts/generate_plugin
```

This will ask you a series of questions:
```
Plugin name (use camelCase) {yourPluginName}
Will this plugin be part of the OpenSearch Dashboards repository? # if Yes then the plugin will be added to src/plugins if N then the plugin will be added to plugins
Should an UI plugin be generated? # if Yes then the plugin will have a public folder with components you can see in the browser if N then no components in the browser
Should a server plugin be generated? # if Yes then the plugin will have a server folder that will be started with the Node layer that can host routes where you can transform or interact with different services or interact with the OpenSearch Client, if No then no server folder will be started for that specific plugin).
```

Once built you should have your plugin with some basic functionality, you can start OpenSearch Dashboards and you can hit the server for that plugin or see the component in the UI. You are ready for adding more features!

Please note, if you say no to 'Will this plugin be part of the OpenSearch Dashboards repository', this will build your plugin to plugins/. This folder is not tracked in git for OpenSearch Dashboards if you delete your plugin within plugins/ it will be lost forever if you do not specifically go into that folder and git init there. It is common to delete the plugin if it is in the plugins/ folder because running the integration tests clears /plugins. (This is terrible and was inherited from the legacy application and we haven't gotten around to prioritizing the issue). So that said, once you run through the process of using the CLI to scaffold the plugin, I'd recommend creating a new repo and navigating to your plugin and pushing that plugin to your repo. That way you guarantee not to lose anywork.

Another piece of information is that the data plugin is the plugin that does the most interaction with OpenSearch Client which is the npm package that actually sends the requests to OpenSearch so if you are thinking about interacting with OpenSearch with your plugin then consider adding that plugin to your plugins 'opensearch_dashboards.json' plugin under requiredPlugins. 'opensearch_dashboards.json' is the JSON file that OpenSearch Dashboards will read while installing the plugin so you can define the version of the plugin and OpenSearch Dashboards Version. For example, if your plugin version is 1.2.3 but you built it for OpenSearch Dashboards 2.0.0, otherwise if you don't provide the version of OpenSearch Dashboards then it will use your plugin version. You can also provide configPath within opensearch_dashboards.json. This will allow you to to provide configuration settings within the root layer config/opensearch_dashboards.yml file for example, if you set the config path to be myPluginConfig and a setting like "isDev", in the opensearch_dashboards.yml file you can define myPluginConfig.isDev: true and your plugin will get the setting.

**Comment by hdhalter** [comment]
Closing this issue in favor of #492. Please add anything that's missing to that issue. Thanks.
