### ISSUE TITLE
[RFC] "cat" API naming convention

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#1713]
_"To CAT or not cap cat, that is the question?"_
Bill Shakespeare

**What do you want to do?**
 
- [x] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Unlike most APIs, "cat" is an acronym for "Compact and aligned text". Therefore, it doesn't follow our usual convention of making an API operation lowercase to match it's technical usage.

With that in mind, do we honor acronym rules and use CAT API? 

Or, do we stick with our convention and use "cat API"?

After a decision has been made, let's update the CAT APIs to adhere to the decision.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

For further context, see @JeffH-AWS  from PR #1637 and the normal convention from issue #1712.

**Comment by alicejw-aws** [comment]
I agree we should keep the CAT API individual component reference pages titled in lowercase, per their component names and keep the API group name in camel case on the index page, as follows:

API group index page: [Compact and aligned text (CAT) API](https://opensearch.org/docs/latest/api-reference/cat/index/).
Individual component page: [cat aliases](https://opensearch.org/docs/latest/api-reference/cat/cat-aliases/)

Also, we could add "component" to the individual API component pages to be more specific. For example, change [cat aliases](https://opensearch.org/docs/latest/api-reference/cat/cat-aliases/) to "cat aliases operation"

When we refer to components in sentences, "Use the `_cat/aliases` operation in the request.. . "


Some context about this discussion. . .

Most of the REST API groups contain multiple API operations within an API library. We give them group titles, such as the [Snapshot Management API](https://opensearch.org/docs/latest/opensearch/snapshots/sm-api/), or the [Compact and aligned text (CAT) API](https://opensearch.org/docs/latest/api-reference/cat/index/). 
Each library contains individual API reference pages for each API component. 

To follow our API template, these individual pages should be titled <Name of API> API. 

(my previous suggestion - but keeping to show what the discussion and reasoning was previously):
So the global updates for all API reference pages would include two changes:
1. Change title page to camel case followed by "API." For example, change "cat aliases" to "CAT aliases API."
2. Change mentions of an operation to code font and keep hardcoded casing. "The cat aliases operation. .  ." to "The `_cat aliases` operation. . . 

The name of this API is "CAT aliases API" and its operation name is `_cat aliases`

For reference about how we give new API reference titles, see [API Name]9https://github.com/opensearch-project/documentation-website/blob/main/STYLE_API_TEMPLATE.md#api-name) in the OpenSearch API reference page template.

Other examples: 
API groups: 
[ML Commons API](https://opensearch.org/docs/2.2/ml-commons-plugin/api/)
[Notifications API[(https://opensearch.org/docs/2.2/notifications-plugin/api/)
API components: 

More example usage when you are mentioning the API group name and the specific component name:
“to use the “ML Commons API, specify the `_ml` resource in the request. . .”
"You can use the Alerting API's `search` operation to find. . ." 
See [Search for monitor findings](https://opensearch.org/docs/2.2/monitoring-plugins/alerting/api/#search-for-monitor-findings)).

**Comment by Naarcha-AWS** [comment]
@natebower: What are your thoughts on this?

**Comment by natebower** [comment]
> @natebower: What are your thoughts on this?

Because "cat" has another meaning (the animal), and because even in lowercase form, "cat" has a meaning as an acronym in our context, let's always treat it as an acronym and use "CAT API".
