### ISSUE TITLE
[Windows] Security Documentation

### ISSUE THREAD

**Issue by peternied** [opensearch-project/documentation-website#1714]
Add documentation for the security plugin on a Windows machine

**Comment by peternied** [comment]
@cwillum I've added this as a placeholder for the v2.4.0 release that will include windows can you determine what else needs to be done to update documentation before the new platform release?

**Comment by Naarcha-AWS** [comment]
@kolchfa-aws and @cwillum: I tagged you both so you can collaborate on this.
