### ISSUE TITLE
[DOC]: OpenSearch Installation on Windows

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#1721]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Describe how to install OpenSearch on Windows.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by kolchfa-aws** [comment]
Closed. Complete #1825
