### ISSUE TITLE
[DOC] : Incomplete Documentation for starting the cluster using systemctl command

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/documentation-website#1722]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The process of starting the OpenSearch service defined on this URL: https://opensearch.org/docs/latest/opensearch/cluster/#step-5-start-the-cluster is incomplete and misleading. There is no service provided by the tar or another installation method for creating the opensearch.service and user needs to go ahead create it.

So this command:
```
sudo systemctl start opensearch.service
```
gives error with Unit opensearch not found.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://opensearch.org/docs/latest/opensearch/cluster/#step-5-start-the-cluster

**Comment by Naarcha-AWS** [comment]
@navneet1v: From where were you trying to start OpenSearch? Are you starting the Managed Service or Open Source?

**Comment by navneet1v** [comment]
I am trying to run the OpenSearch on a EC2 machine by downloading the .tar.gz file from the official site.

**Comment by JeffH-AWS** [comment]
I'll take a look at this.

**Comment by JeffH-AWS** [comment]
@navneet1v can you tell me if you're looking for something like this? I put this together when I wrote the installation guide for the tarball:

```
    1. Create opensearch user:
        1. sudo adduser --system --shell /bin/bash -U --no-create-home opensearch
    2. Make opensearch user owner of the OpenSearch installation path
        1. sudo chown -R opensearch /data/opensearch-2.1.0/
    3. Create a configuration for the service to be read by systemd. The following sample configuration is sufficient for testing and reflects the previous guidance for where the OpenSearch files are located in the filesystem.
    4. sudo vi /etc/systemd/system/opensearch.service
    5. Enter the following then save and quit:
        1. [Unit]
            Description=OpenSearch
            Wants=network-online.target
            After=network-online.target
            
            [Service]
            Type=forking
            RuntimeDirectory=data
            
            WorkingDirectory=/data/opensearch-2.1.0
            ExecStart=/data/opensearch-2.1.0/bin/opensearch -d
            
            User=opensearch
            Group=opensearch
            StandardOutput=journal
            StandardError=inherit
            LimitNOFILE=65535
            LimitNPROC=4096
            LimitAS=infinity
            LimitFSIZE=infinity
            TimeoutStopSec=0
            KillSignal=SIGTERM
            KillMode=process
            SendSIGKILL=no
            SuccessExitStatus=143
            TimeoutStartSec=75
            
            [Install]
            WantedBy=multi-user.target
    6. Reload systemd
        1. sudo systemctl daemon-reload
    7. Enable OpenSearch as a service
        1. sudo systemctl enable opensearch.service
    8. Start OpenSearch
        1. sudo systemctl start opensearch
    9. Verify that it is running
        1. sudo systemctl status opensearch


```

**Comment by JeffH-AWS** [comment]
If so I can make them a bit more directory and version-agnostic, and then include them as guidance for those who install via tarball.

**Comment by JeffH-AWS** [comment]
Ok after a little testing here are the steps as they work for me:

```
1. Create opensearch user:

sudo adduser --system --shell /bin/bash -U --no-create-home opensearch

2. Make opensearch user owner of the OpenSearch installation path

sudo chown -R opensearch /opt/opensearch/

3. Add your user to the opensearch group:

sudo usermod -aG opensearch $USER

4. Create a configuration for the service to be read by systemd. The following sample configuration is sufficient for testing and reflects the previous guidance for where the OpenSearch files are located in the filesystem.

4a. Open the file:

sudo vi /etc/systemd/system/opensearch.service

4b. Enter the following then save and quit:

[Unit]
Description=OpenSearch
Wants=network-online.target
After=network-online.target

[Service]
Type=forking
RuntimeDirectory=data

WorkingDirectory=/opt/opensearch
ExecStart=/opt/opensearch/bin/opensearch -d

User=opensearch
Group=opensearch
StandardOutput=journal
StandardError=inherit
LimitNOFILE=65535
LimitNPROC=4096
LimitAS=infinity
LimitFSIZE=infinity
TimeoutStopSec=0
KillSignal=SIGTERM
KillMode=process
SendSIGKILL=no
SuccessExitStatus=143
TimeoutStartSec=75

[Install]
WantedBy=multi-user.target

5. Reload systemd
        1. sudo systemctl daemon-reload
6. Enable OpenSearch as a service
        1. sudo systemctl enable opensearch.service
7. Start OpenSearch
        1. sudo systemctl start opensearch
8. Verify that it is running
        1. sudo systemctl status opensearch
```

**Comment by JeffH-AWS** [comment]
This process worked:

```bash
$ sudo systemctl status opensearch
● opensearch.service - OpenSearch
   Loaded: loaded (/etc/systemd/system/opensearch.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-10-31 18:17:49 UTC; 1min 21s ago
  Process: 6191 ExecStart=/opt/opensearch/bin/opensearch -d (code=exited, status=0/SUCCESS)
 Main PID: 6369 (java)
   CGroup: /system.slice/opensearch.service
           └─6369 /opt/opensearch/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m ...

Oct 31 18:17:47 ip-10-0-13-115.us-west-2.compute.internal systemd[1]: Starting OpenSearch...
Oct 31 18:17:49 ip-10-0-13-115.us-west-2.compute.internal systemd[1]: Started OpenSearch.
```

**Comment by JeffH-AWS** [comment]
PR is up and pending tech review. The doc review should be pretty quick since the commentary is minimal.

**Comment by JeffH-AWS** [comment]
I got some great feedback from @peterzhuamazon - the steps are good as-is. However, due to the lack of strict root user access control and ease of manipulating file locations, etc., we should add a very clear disclaimer to the process. This disclaimer will essentially say something like:

"We strongly recommend using the RPM distribution which is already configured as a service with systemd. Tarball installation allows for manual control of things like the install location, and therefore manually creating a service with systemd is not appropriate for any production environment. It should only be used in a dev environment by advanced users."

**Comment by JeffH-AWS** [comment]
Will ping Peter again for final approval once the PR has been updated.

NOTE: I will be OoO with no access to GH or email through 11/14. I will resume work on this issue when I get back online.

**Comment by JeffH-AWS** [comment]
Waiting on tech review from Peter before moving to doc review.

**Comment by JeffH-AWS** [comment]
Tech review done. Requested docs review.
