### ISSUE TITLE
[Improvement] OpenSearch Field types

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/documentation-website#177]
Can we add a page to outline the various field data types that opensearch supports?

**Comment by q2dg** [comment]
And date formats too....like https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-date-format.html

**Comment by drichelson** [comment]
Specifically I am looking for equivalent info from this page: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/mapping-types.html but for OS.

**Comment by dlvenable** [comment]
I was looking for this information today and was unable to find it. Internet searches for "opensearch data types" or "opensearch field types" had results from the SQL and PPL pages. But, this is not the same information.

**Comment by dlvenable** [comment]
Elasticsearch reference regarding the removal of mapping types: https://www.elastic.co/guide/en/elasticsearch/reference/8.2/removal-of-types.html

**Comment by hdhalter** [comment]
Hi Fanit, can you please try to tackle this issue? In addition to this request (that has been in our backlog for a while), there was a recent request in a Slack thread for documenting the data types: https://amzn-aws.slack.com/archives/C01L92M6Y92/p1654250558281419 chat. Let me know if you can't access it. Nate A. will support, as needed. Thanks!
