### ISSUE TITLE
[DOC] A docker-compose example command to correct on OpenSearch docker installation web page  

### ISSUE THREAD

**Issue by jordarlu** [opensearch-project/documentation-website#1793]
**What do you want to do?**

An existing example docker-compose command shown on https://opensearch.org/docs/latest/opensearch/install/docker/ is a bit mistakenly placing the arguments 'up' and '-f /path/to/your-file.yml' in an incoorect order. If user just do copy&paste, the command fails.

Insted of (current) :  docker-compose up -f /path/to/your-file.yml 
Should change to  :  docker-compose -f /path/to/your-file.yml up 

- [X] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Suggesting to correct the order of arguments placement 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by jordarlu** [comment]
@JeffH-AWS , if this is something you can help with ... Thanks!!

**Comment by JeffH-AWS** [comment]
Hello @jordarlu and thanks for raising this typo! Fix pending.

**Comment by jordarlu** [comment]
Thank you, @JeffH-AWS
