### ISSUE TITLE
[DOC] Maximum allowed monitors

### ISSUE THREAD

**Issue by heyrita** [opensearch-project/documentation-website#1798]
**What do you want to do?**
 
Could you please add to the documentation the information about maximum allowed monitors. 

Is there any limit?

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by lezzago** [comment]
The maximum number of monitors is 1000.
code reference: https://github.com/opensearch-project/alerting/blob/817d9ef6c2b439c0b943df2d699380a9a3d54975/alerting/src/main/kotlin/org/opensearch/alerting/settings/LegacyOpenDistroAlertingSettings.kt#L22

**Comment by lezzago** [comment]
It has always been by default 1000 monitor and is configurable

**Comment by Naarcha-AWS** [comment]
To fix this, we need to add this as a visible limitation to the [monitors page](https://opensearch.org/docs/latest/observing-your-data/alerting/monitors/).

**Comment by carolxob** [comment]
Planning to add this information under the **Create a monitor** section. ([Create a monitor](https://opensearch.org/docs/latest/observing-your-data/alerting/monitors/#create-a-monitor))
