### ISSUE TITLE
Add network and firewall requirements

### ISSUE THREAD

**Issue by aetter** [opensearch-project/documentation-website#18]
please add network and firewall requirements to the documentation?

In case OpenSearch is used in production on-premise, it would be great to get an overview of all the network requirements eg. firewall ports that needs to be opened.

Below a list of some ports (might not be complete) :

Firewall Ports
port: comment
443: OpenSearch Dashboards
5601: OpenSearch Dashboards
9000: Cerebro
9200: REST
9250: cross cluster search
9300: nodes communication / transport
9600: required for Performance Analyzer

Original issue here: https://github.com/opendistro/for-elasticsearch-docs/issues/433

**Comment by Naarcha-AWS** [comment]
@Naarcha-AWS will validate the Port Numbers
