### ISSUE TITLE
Change opensearch-js client name

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/documentation-website#180]
According to infra, the opensearch-js client name should be `@opensearch-project/opensearch` . So in the example[ here](https://github.com/opensearch-project/documentation-website/pull/159/files), we need to do the same modification. 

For example, `const { Client } = require('@opensearch/opensearch')`
should be `const { Client } = require('@opensearch-project/opensearch')`.

**Comment by liz-snyder-aws** [comment]
Thanks @ananzh, updated the PR.
