### ISSUE TITLE
[DOC] ISM Error prevention / Action validation feature

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/documentation-website#1809]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
We are releasing the first stage of ISM Action validation feature in 2.4. The main goal is to improve the user experience on the operational side for ISM. 
ISM helps user to execute action automatically, but action execution could fail because of a variety of reasons. Action validation validates the possible failing reason before execution and surfaces the validation result to user. The first stage mainly refactors the existing validation logic in several actions out to a separate module just for validation. More validation logic will be added and better use flow will be provided in the future stages.

PR: https://github.com/opensearch-project/index-management/pull/579

Our vision for documentation include:
- A troubleshooting page document the validation logic for each ISM action, and the solution for resolving the validation error
- Update existing ISM docs to introduce this feature

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
@Angie-Zhang

**Comment by Naarcha-AWS** [comment]
@bowenlan-amzn: Is this specific to 2.4 or being backport to 2.0?

**Comment by bowenlan-amzn** [comment]
Specific to 2.4. Won't be backported for now.

**Comment by Naarcha-AWS** [comment]
@ariamarble: Since you've written about cluster and index management before, I'm going to assign this to you for now, let me know if that works.

**Comment by ariamarble** [comment]
Currently in progress

**Comment by ariamarble** [comment]
Update of existing ISM docs complete. Waiting on troubleshooting guide from @Angie-Zhang
