### ISSUE TITLE
[DOC] Awareness Attribute Decommission

### ISSUE THREAD

**Issue by imRishN** [opensearch-project/documentation-website#1812]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We have introduced a feature to decommission an awareness attribute from the cluster in the event of zonal failures. With decommissioning an awareness attribute, nodes having those attributes will be kicked out of the cluster and will stay out until the attribute is recommissioned back. Hence, these decommission/recommission APIs serves as an andon cord to cut-off inter-zone replication traffic.

We need to document a brief summary of the feature and all the new apis.
Details on api can be found in the https://github.com/opensearch-project/OpenSearch/issues/3639.

Which versions are affected?
2.4.0

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

1. High Level Proposal - https://github.com/opensearch-project/OpenSearch/issues/3402
2. Design Proposal - https://github.com/opensearch-project/OpenSearch/issues/3917
3. APIs RFC - https://github.com/opensearch-project/OpenSearch/issues/3639
4. Meta Issues - https://github.com/opensearch-project/OpenSearch/issues/3957

Major PRs -

1. https://github.com/opensearch-project/OpenSearch/pull/4084
2. https://github.com/opensearch-project/OpenSearch/pull/4261
3. https://github.com/opensearch-project/OpenSearch/pull/4590
4. https://github.com/opensearch-project/OpenSearch/pull/4586
5. https://github.com/opensearch-project/OpenSearch/pull/4320
6. https://github.com/opensearch-project/OpenSearch/pull/4604

**Comment by imRishN** [comment]
@Naarcha-AWS any updates on this? Let me know if more details are required

**Comment by imRishN** [comment]
@Naarcha-AWS any updates?

**Comment by Naarcha-AWS** [comment]
I'll account for these as well with the 2.5 updates for #1811.
