### ISSUE TITLE
[DOC]Add geo-bounding box query documentation

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#1815]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Add geo-bounding box query documentation
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
@kolchfa-aws: Do you have any additional info on this?

**Comment by kolchfa-aws** [comment]
@Naarcha-AWS It's an issue that I put in for myself because I already did a similar query for xy point, so it would be easy for me to do. That's why there's no information.
