### ISSUE TITLE
[DOC] ISM Alias action

### ISSUE THREAD

**Issue by goyamegh** [opensearch-project/documentation-website#1835]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Gives complete support for all update alias API options by reusing the alias actions parser internally and explicitly not defining the mappings in our config index. 
This feature is intended for both 2.4 and backport to 2.0.

Coming from the GitHub feature request, the use cases people asked for:

My use case is, If we have an alias for an index with rollover ILM policy, can we remove it from alias after some predefined days, let's say 30 days? I know there is a way to delete an index once its old, but in our case we do not want to delete but want the index to be removed from alias and have the alias switch and point to indices whose age is less than 30 days.
This should be easily doable with the Alias action, just have a state that gets transitioned into after the index is 30 days old (or 30 days rollover age) and then remove the alias.

My use case is: we provide search_alias to search our dataset. We publish new version of dataset every week as a new index (e.g. dataset-yyyy-MM-dd. We want the search_alias always pointing to the latest published dataset. The process is: ingest new data to a new index, once ingestion finish, re-pointing search_alias to the new index, remove old index from the search_alias
Should be possible, the newly created index can remove the alias from all search-index-* indices and then add the alias it itself in a single call. The main thing would be knowing when ingestion finished for the new index.. which you could just use some absolute time using the transition condition if you know it only takes x amount of time.

PR: https://github.com/opensearch-project/index-management/pull/575

The idea is to add this as an available action in the list of possible actions while creating the ISM policies. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
@goyamegh, @bowenlan-amzn 

Steps for testing: https://github.com/opensearch-project/index-management/blob/main/worksheets/ism/alias_action.http

**Comment by ariamarble** [comment]
Ramping up and researching this issue.

**Comment by ariamarble** [comment]
Now in review
