### ISSUE TITLE
[DOC]Documentation for new Opensearch-py-ml plugin

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/documentation-website#1848]
**What do you want to do?**
 
- [ ] Add new documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Opensearch-py-ml is a Python Opensearch client for exploring and analyzing data in Opensearch with a familiar Pandas-compatible API.

Where possible the package uses existing Python APIs and data structures to make it easy to switch between numpy, pandas, scikit-learn to their Opensearch powered equivalents. In general, the data resides in Opensearch and not in memory, which allows Opensearch-py-ml to access large datasets stored in Opensearch.

In addition, this client plugin connects with MLCommons plugin to upload custom models to opensearch.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://opensearch-project.github.io/opensearch-py-ml/

Example are here: https://opensearch-project.github.io/opensearch-py-ml/examples/index.html

**Comment by Naarcha-AWS** [comment]
Since the client can be installed and has officially [been published](https://pypi.org/project/opensearch-py-ml/), I'll add the client page today.
