### ISSUE TITLE
[DOC] Orphaned doc links in OpenSearch Dashboards

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/documentation-website#1853]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [x] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

In OpenSearch Dashboards, we have a centralized location where we define all documentation links. Within that file, there's an entire section that lists links in the application that don't actually lead anywhere specific (they all point to the documentation site root):

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/4fd67de27eb1d942450ee8272d2de2bb8ef2f96c/src/core/public/doc_links/doc_links_service.ts#L396-L428

```
          logstash: `${OPENSEARCH_WEBSITE_DOCS}`,
          winlogbeat: `${OPENSEARCH_WEBSITE_DOCS}`,
          siem: `${OPENSEARCH_WEBSITE_DOCS}`,
          indexPatterns: {
            loadingData: `${OPENSEARCH_WEBSITE_DOCS}`,
            introduction: `${OPENSEARCH_WEBSITE_DOCS}`,
          },
          management: {
            opensearchDashboardsGeneralSettings: `${OPENSEARCH_WEBSITE_DOCS}`,
            opensearchDashboardsSearchSettings: `${OPENSEARCH_WEBSITE_DOCS}`,
            dashboardSettings: `${OPENSEARCH_WEBSITE_DOCS}`,
          },
          scriptedFields: {
            scriptFields: `${OPENSEARCH_WEBSITE_DOCS}`,
            scriptAggs: `${OPENSEARCH_WEBSITE_DOCS}`,
            painless: `${OPENSEARCH_WEBSITE_DOCS}`,
            painlessApi: `${OPENSEARCH_WEBSITE_DOCS}`,
            painlessSyntax: `${OPENSEARCH_WEBSITE_DOCS}`,
            luceneExpressions: `${OPENSEARCH_WEBSITE_DOCS}`,
          },
          visualize: {
            guide: `${OPENSEARCH_WEBSITE_DOCS}`,
            timelineDeprecation: `${OPENSEARCH_WEBSITE_DOCS}`,
          },
          addData: `${OPENSEARCH_WEBSITE_DOCS}`,
          vega: `${OPENSEARCH_DASHBOARDS_VERSIONED_DOCS}`,
          dateMath: `${OPENSEARCH_WEBSITE_DOCS}`,
```
 
Some of these need to be created (such as `vega`, which is tracked in https://github.com/opensearch-project/documentation-website/issues/1178). Others may already exist or could be linked to existing OpenSource docs. For example, a user suggested that `dateMath` could likely be linked to https://opensearch.org/docs/latest/opensearch/supported-field-types/date/#full-date-formats. We may also decide to remove some of these links altogether if they are no longer relevant.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

Related to https://github.com/opensearch-project/documentation-website/issues/751

**Comment by vagimeli** [comment]
@joshuarrrr I'm working on this issue

**Comment by vagimeli** [comment]
@joshuarrrr I've updated links related to this issue. Below are the updates. Will you review these to make sure the links are to the appropriate topic? For example, painless. Also, I don't have permission to edit file in the Dashboards repo. How do I update the file? Note that some of these items need documentation. For instance, Dashboards management and timeline deprecation. 
          logstash: `https://opensearch.org/docs/latest/tools/logstash/index/`,
          winlogbeat: `https://opensearch.org/docs/latest/tools/index/`,
          siem: `https://opensearch.org/docs/latest/security-analytics/index/`,
          indexPatterns: {
            loadingData: `https://opensearch.org/docs/latest/im-plugin/index/`,
            introduction: `https://opensearch.org/docs/latest/im-plugin/index/)`
         management: {
            opensearchDashboardsGeneralSettings: `${OPENSEARCH_WEBSITE_DOCS}`,
            opensearchDashboardsSearchSettings: `${OPENSEARCH_WEBSITE_DOCS}`,
            dashboardSettings: `${OPENSEARCH_WEBSITE_DOCS}`,
          },
          scriptedFields: {
            scriptFields: `https://opensearch.org/docs/latest/api-reference/script-apis/index/`,
            scriptAggs: `https://opensearch.org/docs/latest/aggregations/pipeline-agg/`,
            painless: `https://opensearch.org/docs/latest/api-reference/script-apis/exec-stored-script/`,
            painlessApi: `https://opensearch.org/docs/latest/api-reference/script-apis/exec-script/`,
            painlessSyntax: `https://opensearch.org/docs/latest/data-prepper/pipelines/expression-syntax/`,
            luceneExpressions: `https://opensearch.org/docs/latest/search-plugins/knn/filter-search-knn/`,
          },
          visualize: {
            guide: `https://opensearch.org/docs/latest/dashboards/visualize/viz-index/`,
            timelineDeprecation: `${OPENSEARCH_WEBSITE_DOCS}`,
                      },
          addData: `https://opensearch.org/docs/latest/dashboards/discover/index-discover/`,
          vega: `https://opensearch.org/docs/latest/dashboards/visualize/vega/`,
          dateMath: `https://opensearch.org/docs/latest/field-types/date/`,
