### ISSUE TITLE
Incorrect documentation of impersonation header

### ISSUE THREAD

**Issue by astephon88** [opensearch-project/documentation-website#188]
The current documentation for user impersonation https://github.com/opensearch-project/documentation-website/blob/v1.0.0/_security-plugin/access-control/impersonation.md gives the name of the header to add to requests as `opensearch_security_impersonate_as`; however, as of the version of Opensearch running in the docker image tag 1.0.1, Opensearch still only properly does impersonation with the old `opendistro_security_impersonate_as` header.

**Comment by aetter** [comment]
Thanks a bunch for reporting, @astephon88. This won't be the last setting, unfortunately---the rename bit us hard. Updated here: https://github.com/opensearch-project/documentation-website/commit/973d967514c325f6a27a5da6599433ebea86057a
