### ISSUE TITLE
[DOC] Create an easy to navigate and visually appealing landing page

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#1920]
**What do you want to do?**

Create an easy to navigate and visually appealing landing page with calls to action, groupings of similar concepts, what’s new, popular topics, and getting started. Example: https://learn.microsoft.com/en-us/azure/?product=popular

- [ x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other

**Comment by hdhalter** [comment]
We've made several improvements to the home page, but we're getting new templates for the website, so this will be covered then.
