### ISSUE TITLE
[DOC] Doc site: Let body text be scrollable while the left pane and right panes remain static.

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#1921]
**What do you want to do?**
 
Let body text be scrollable while the left pane and right panes remain static. Allow users to hide left pane and right pane elements so that only the body remains. Example: https://www.twilio.com/docs/flex/developer/plugins/debugging-with-vscode#downloading-the-debugger-for-chrome-plugin

- [ x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other

**Comment by Naarcha-AWS** [comment]
This is a duplicate of #1709
