### ISSUE TITLE
[DOC] Doc site: Add the ability to span rows/columns for tables

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#1923]
**What do you want to do?**
 
Add the ability to span rows/columns for tables

- [x ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other

**Comment by Naarcha-AWS** [comment]
This should work with the new UI components, therefore, we should close it.
