### ISSUE TITLE
[DOC] Doc site: Add the ability to copy code samples.

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#1924]
**What do you want to do?**
 
Add the ability to copy code samples with one click. This includes REST APIs, with the ability to copy or modify curl commands based on user input.

- [x ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other

**Comment by Naarcha-AWS** [comment]
Per our meeting with @kolchfa-aws and @nateynateynate, adding a "Add to clipboard" icon should be easy enough to add. However, adding a mechanism to switch between a generic and curl example might be more difficult to achieve. For now, it might be best to keep this low-hanging-fruit and just add an icon for copying code, while keeping to code SDK agnostic.

**Comment by kolchfa-aws** [comment]
Closing this issue because it has been implemented in #2043
