### ISSUE TITLE
[DOC] Doc site: Add ability for code examples or table contents to be resized.

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#1927]
**What do you want to do?**
 
Add ability for code examples or table contents to be resized without scrolling.

- [ x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other

**Comment by hdhalter** [comment]
Closing this issue as this will be taken care of with the new web components.
