### ISSUE TITLE
Update Helm README link - 404 Not Found 

### ISSUE THREAD

**Issue by sebas-intellegens** [opensearch-project/documentation-website#194]
Affected page: https://opensearch.org/docs/opensearch/install/helm/

The README link on the 'Install with Helm' points to a non-existing page
I.e. the following link gives me a 404: https://github.com/opensearch-project/opensearch-devops/blob/main/Helm/README.md

It should instead probably link to: https://github.com/opensearch-project/helm-charts/tree/main/charts

Same goes for the README link on the OpenSearch Dashboards page: https://opensearch.org/docs/dashboards/install/helm/

**Comment by aetter** [comment]
Thanks a bunch @sebas-intellegens . Updated here: https://github.com/opensearch-project/documentation-website/commit/1f90f3ca523f57893ed30dac31db21cf5319ef4c
