### ISSUE TITLE
[DOC] Should Neural Search Plugin be a search plugin?

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/documentation-website#1972]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Currently, in https://opensearch.org/docs/latest/, the neural search plugin has its own top level folder. I think it should be a part of the search plugins folder.
![Screen Shot 2022-11-17 at 12 00 16 PM](https://user-images.githubusercontent.com/19438237/202547051-e08ffec5-ede1-4002-b456-44a4cf5c4146.png)

**Comment by hdhalter** [comment]
Thanks for your input! This has been fixed: 
<img width="232" alt="image" src="https://github.com/opensearch-project/documentation-website/assets/104463754/74452080-82dd-49b8-bdfa-7ccc2526a682">
