### ISSUE TITLE
[DOC] : Incorrect documentation for Neural Search Plugin

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/documentation-website#1973]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The example provided here: https://opensearch.org/docs/latest/neural-search-plugin/index/#example-request are incorrect. It should be changed to :

```
PUT _ingest/pipeline/nlp-pipeline
{
  "description": "An example neural search pipeline",
  "processors" : [
    {
      "text_embedding": {
        "model_id": "bxoDJ7IHGM14UqatWc_2j",
        "field_map": {
           "passage_text": "passage_embedding"
        }
      }
    }
  ]
}
```

so that it matches the fields which are provided in the index.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
One of the customer was trying to use the documentation and got the error. 
https://forum.opensearch.org/t/feedback-neural-search-plugin-experimental-release/11501/4?u=navneet

**Comment by dhrubo-os** [comment]
In addition, `Request fields` aren't quite matching with the `Example request`. We should add more detailed explanation for the `Request fields`

**Comment by navneet1v** [comment]
@Naarcha-AWS when we are planning to take up this task?
