### ISSUE TITLE
[Improvement] Document How to Connect Beats to OpenSearch w/ Details on Roles / Permissions

### ISSUE THREAD

**Issue by hfuss** [opensearch-project/documentation-website#199]
As a novice user of ElasticSearch, OpenSearch, and Filebeat I'm having trouble defining a secure, least privilege role for Filebeat when it connects to OpenSearch.

Following this [doc](https://www.elastic.co/guide/en/beats/filebeat/current/privileges-to-publish-events.html) it sounds pretty straightforward however when looking at what [permissions are available w/in OpenSearch](https://opensearch.org/docs/security-plugin/access-control/permissions/#cluster-permissions) its very unclear how to set this up. For example, what does the cluster permission `monitor` or `read_ilm` map to in OpenSearch permissions? What about `create_doc` for indices? A sort of permission mapping doc would be a great compliment to the existing permissions documentation. I could be missing something obvious with this kind of administration, but I haven't been able to find anything helpful w/in the OpenSearch docs.

An example that details the necessary security config for `opensearch.yml`, `internal_users.yml`, `roles.yaml`, and `config.yml` in order to have a least privilege `filebeat` user would be extremely helpful in this regard.

**Comment by drewmarshburn** [comment]
Any updates on this?

**Comment by Naarcha-AWS** [comment]
Hi @hfuss: Since this issue was submitted, we've increased the amount of documentation around security roles and yml configuration https://opensearch.org/docs/latest/security/configuration/yaml/#internal_usersyml. As such, we'll close the issue for now, but feel free to reopen if needed.
