### ISSUE TITLE
[DOC] Update index settings API's document contains some useless url parameters

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/documentation-website#1991]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Update index settings API's document contains the following useless url parameters:

- flat_settings
- ignore_unavailable

I think they are copied from the Get index settings API's document so they don't work.

https://opensearch.org/docs/2.0/opensearch/rest-api/index-apis/update-settings/
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@bowenlan-amzn - Can you please confirm these parameters are not in the code? Thanks.

**Comment by bowenlan-amzn** [comment]
These parameters do exist, but seems not useful here

flat_settings is not useful because update setting API seems return acknowledge response, so no index setting in it.

ignore_unavailable is not useful because whether it's set to true or false, you will always get a index not found exception

**Comment by hdhalter** [comment]
@bowenlan-amzn - Do you recommend we remove them from the documentation?

**Comment by bowenlan-amzn** [comment]
Yes, recommend to remove them since they are not useful.
