### ISSUE TITLE
[DOC] Prometheus SQL and Metrics Analytics Observability Plugin

### ISSUE THREAD

**Issue by ps48** [opensearch-project/documentation-website#1993]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 With OpenSearch 2.4, we released features for connected metrics in Observability plugin. This included two new components:
 1. Prometheus connection to OpenSearch via the SQL plugin.
 2. Metrics Analytics UI component in Observability 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
1. https://github.com/opensearch-project/sql/issues/561
2. https://github.com/opensearch-project/observability/issues/1091

**Comment by Naarcha-AWS** [comment]
@ps48: Do you have additional resources besides the two PRs you linked?

**Comment by ps48** [comment]
Sorry, missed out the comment here. @Naarcha-AWS are you looking for something please let me know. If would be helpful to get this our in 2.5 now.

**Comment by CEHENKLE** [comment]
Hey @Naarcha-AWS This is still marked for 2.4 (two release ago now).   Can you update it to the right planned release?  Thanks!  If you don't know what release it's going to go in, you can just remove the label. 

/C

**Comment by Naarcha-AWS** [comment]
@CEHENKLE: Done. I'll assign it to myself for now.

**Comment by ariamarble** [comment]
Spinning up on this one

**Comment by anirudha** [comment]
https://github.com/opensearch-project/documentation-website/pull/2769/files

**Comment by ariamarble** [comment]
Tech review complete, working on updates then sending for doc review.
