### ISSUE TITLE
Add Documentation for Dashboards de-couple build

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/documentation-website#200]
When running yarn build --skip-os-packages it will build 4 tarballs
for Dashboards (2x linux, 1x macOS, 1x windows) and takes 10+min to
do so.

From the PR [here](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/795), dashboards now support to build one specific platform. Details are:
```
yarn build-platform --darwin // build only darwin x64 platform
yarn build-platform --linux //build only linux x64 platform
yarn build-platform --linux-arm // build only linux arm64 platrform
```
Customer can also build multiple supported platforms. For example:
```
yarn build-platform --linux-arm --darwin // build both darwin x64 and linux arm64 platforms
```

Below is the updated DEVELOPER_GUIDE.md. Just provide more reference.
```
### Building the artifacts

To build the artifacts for all supported platforms,  run the following:

yarn build --skip-os-packages

If you want to build a specific platform, pass the platform flag after `yarn build-platform`. For example, to build darwin x64, run the following:

yarn build-platform --darwin

You could pass one or multiple flags. If you don't pass any flag, `yarn build-platform` will use your local environment. Currenly we only support `darwin` (darwin x64), `linux` (linux x64) and `linux-arm` (linux arm64).  
```

Just want to check whether we need to update any document in opensearch.org.

**Comment by aetter** [comment]
Build information is typically in the repositories themselves -- we don't have any mention of it in the documentation. We cover installation, concepts, usage, public API, settings, etc. We might eventually include plugin development, too, but I doubt we'll ever want to decouple build instructions from the repos themselves.
