### ISSUE TITLE
Remove documentation for High Level Rest Client [DOC]

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/documentation-website#2010]
**What do you want to do?**
 
- [ X ] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
We have a section on the High Level Rest Client: https://opensearch.org/docs/latest/clients/java-rest-high-level/

In fact this client is not recommended. It will likely be deprecated. There are several challenges to people relying on that client. It is not receiving updates or features at the same rate as the supported client, opensearch-java. It may malfunction if a user does not want to upgrade their jvm for their clients when they need to update their server version (see https://github.com/opensearch-project/documentation-website/issues/1975).

This request is to simply remove the reference to the High Level Rest Client on the docs website.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
The opensearch-java client is the correct resource, and we already document that.

**Comment by hdhalter** [comment]
Hi @Naarcha-AWS , Fanit said she'll take care of this.

**Comment by wbeckler** [comment]
Seeking feedback on this issue from @reta and @dblock

**Comment by reta** [comment]
> Seeking feedback on this issue from @reta and @dblock

I believe for 3.0.0 we have to update documentation with deprecation notice. People do use RHCL right now and without this intermediate step (of deprecation) we leave them no time to migrate.

**Comment by wbeckler** [comment]
How about marking the documentation with advance warning to prevent further
investment

**Comment by dbwiddis** [comment]
> How about marking the documentation with advance warning to prevent further investment

Please leave the documentation as reference with clear documentation not to use it for new development!

**Comment by andrross** [comment]
Agree on updating the documentation to mark the high level REST client as deprecated. Currently both clients show up in the left-hand navigation and it is not at all obvious which one to prefer or even why two of them exist.

![image](https://user-images.githubusercontent.com/9160839/212198984-f2a4220b-1356-455f-aeca-093fc5713110.png)

@reta Is there any reason why we can't start nudging users to opensearch-java now (as opposed to starting in 3.0) with a deprecation notice in the documentation on the high-level REST client?

**Comment by reta** [comment]
> Agree on updating the documentation to mark the high level REST client as deprecated. Currently both clients show up in the left-hand navigation and it is not at all obvious which one to prefer or even why two of them exist.
> 
> ![image](https://user-images.githubusercontent.com/9160839/212198984-f2a4220b-1356-455f-aeca-093fc5713110.png)
> 
> @reta Is there any reason why we can't start nudging users to opensearch-java now (as opposed to starting in 3.0) with a deprecation notice in the documentation on the high-level REST client?

@andrross I think we could start with deprecation now, non-issue, but we are half way through 2.x release (2.5 is coming out), I think we may not give people enough time to jump off the `RestHighLevelClient` (fe timing the deprecation with 2.0 would give much more time). The thing to keep in mind also is that we do have many projects (under OpenSearch umbrella and outside) where `RestHighLevelClient` is used, we may not even have time to phase out  `RestHighLevelClient`  in those before 3.0.0.

**Comment by andrross** [comment]
@reta Agreed that removing `RestHighLevelClient` will likely be difficult because it is widely used so we may end up keeping it around for awhile, but that shouldn't stop us from getting the desired guidance and deprecations in the documentation now.

**Comment by kolchfa-aws** [comment]
Now that 2.5 is out, how about adding the following warning to the high-level REST client: 
`The OpenSearch Java high-level REST client will be deprecated starting with OpenSearch version 3.0.0 and will be removed in a future release. We recommend switching to the [Java client](https://opensearch.org/docs/latest/clients/java/) instead.`
