### ISSUE TITLE
Remove "beta" designation of opensearch-java

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/documentation-website#2011]
**What do you want to do?**
 
- [ X ] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
The documentation here (https://opensearch.org/docs/1.2/clients/java/) suggests that opensearch-java is "beta."  In fact it is not in beta and it is the recommended client. the verbiage is misleading. This verbiage is written on a prior version page, but that doesn't change the fact that it is incorrect.

This is a request to remove that warning wherever it exists.

**Comment by Naarcha-AWS** [comment]
Hi @wbeckler: The `beta` designation is removed from OpenSearch 1.3 up: https://opensearch.org/docs/1.3/clients/java/.

Do you still need us to update the OpenSearch 1.2 documentation?

**Comment by wbeckler** [comment]
Yes, for all versions. The status of the client isn't dependent on the
server version , so every "beta" reference linked from old versions is
confusing and incorrect.

**Comment by hdhalter** [comment]
@Naarcha-AWS - Can we resolve this by backporting the 1.3 version of this to 1.2-1.0? Thanks!
