### ISSUE TITLE
Opensearch Integration With Grafana

### ISSUE THREAD

**Issue by santiagz** [opensearch-project/documentation-website#204]
### Is your feature request related to a problem? Please describe

this integration would open up many possibilities for visualization

### Describe the solution you'd like

I will visualize data from Opensearch and would like to be able to use grafana 

### Describe alternatives you've considered

Elastic has integration with Grafana via Lucene query

**Comment by aetter** [comment]
Hi all, added a tiny stub page so that this link shows up if you search for Grafana. It's not something I've tested, but there's apparently an OpenSearch data source plugin now: https://opensearch.org/docs/clients/grafana/
