### ISSUE TITLE
[Doc] Document examples for filtering Alerts

### ISSUE THREAD

**Issue by devin-2** [opensearch-project/documentation-website#2045]
**Is your feature request related to a problem?**
I encountered some issues attempting to filter alert results using the URI in the developer tools and, when looking at the Alerting dashboard API, it appears to take parameters for: from, size, search, start_time, sortDirection, severityLevel, alertState

**What solution would you like?**
Examples showing how to filter alerts discovered with the endpoint `GET _plugins/_alerting/monitors/alerts` in the documentation
https://opensearch.org/docs/latest/monitoring-plugins/alerting/api/

What options are available, and how can these parameters be applied to filter the endpoint:
`GET _plugins/_alerting/monitors/alerts`

**Comment by dblock** [comment]
I just moved this issue into documentation-website.

**Comment by ryn9** [comment]
@vagimeli - can we please see this updated soon?

**Comment by vagimeli** [comment]
@ryn9 Updated documentation for this issue is part of the 2.8 documentation release cycle.
