### ISSUE TITLE
[DOC] Some suggestions for the Dashboards page

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/documentation-website#2046]
**What do you want to do?**
 
- [X ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
I am new to OpenSearch Dashboards, so I went to the https://opensearch.org/docs/latest/dashboards/index/ page. There were a few points that were unclear.

In section Explore the OpenSearch Dashboards playground:

Step 2: "Choose OpenSearch Dashboards > Dashboard." This should mention that it's in the hamburger menu in the upper left. I clicked on the text "OpenSearch Dashboards" instead, and then the Dashboard button. This gets me to the same place, but ....

Step 3: What does "Explore the available datasets and select one" mean? Am I supposed to click through on the different links? What am I looking for? What does "select one" mean? Does it mean that I click through to one of the examples using the text link? using the pencil link? Or does it mean that I select the checkbox? If it means "select the checkbox", then what's the next step?

Step 4: "Interact with the data on a dashboard". What sorts of interactions are possible? I tried brushing the "Flight Count and Average Ticket Price" and that did nothing. I tried clicking on one of the airlines in Airline Carrier, and it seems to have filtered to just that carrier, but I don't see any way of undoing that selection; even reloading the page doesn't undo it. How do I drill down on the data? I see in Delays & Cancellations that the exclamation point symbol reports on events, but how do I click through to details on the event? That is, the documentation needs to guide the user more on "interacting with the data" -- a priori, there are lots of possible interactions, some of which we provide, but not others. And it's not clear how to undo actions.

Step 4: "Add filter". I tried selecting the first option, Avg Ticket Price, but it is completely unclear what that is an average over, and there doesn't seem to be any hoverover documentation. Then I tried adjusting the Average Ticket Price slider, and that seems to have no effect on the dashboard. AHA! I need to scroll down to see "Apply changes" !!!!!! Very bad UI design, but can be mitigated with documentation. Somewhere it needs to say "scroll down in the Controls box and enter Apply Changes".

Step 5: "Select one of the options from the Field menu". This seems to be part of Step 4, after you've chosen Add filter, and presumably happens before the second half of step 5 ("specify the data").

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by vagimeli** [comment]
@macrakis In progress. I'll set up an info gathering meeting with you and other SMEs.

**Comment by vagimeli** [comment]
@macrakis We are restructuring the Dashboards site. These issues will be addressed during the content development or revisions.

**Comment by vagimeli** [comment]
@macrakis We've replaced the page with a the Quickstart guide. You're welcome to provide feedback on the guide. https://opensearch.org/docs/latest/dashboards/get-started/quickstart-dashboards/

**Comment by vagimeli** [comment]
See https://opensearch.org/docs/latest/dashboards/get-started/quickstart-dashboards/
