### ISSUE TITLE
[DOC] How shards will work if zones are not specified

### ISSUE THREAD

**Issue by tv1n94** [opensearch-project/documentation-website#2068]
**What do you want to do?**
 
- [v] Request a change to existing documentation
- [v] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

Good afternoon!

I'm just getting started with OpenSearch. I have an OpenSearch cluster, but its configuration does not include Configure shard allocation awareness (https://opensearch.org/docs/2.0/opensearch/cluster/#advanced-step-6-configure-shard-allocation-awareness-or- forced-awareness)

Please tell me how the cluster works without shards. Does it have fault tolerance (data replication)?

**Comment by JeffH-AWS** [comment]
Hi Alex,

I'm not sure I understand your request. Can you please explain what this means?

"I have an OpenSearch cluster, but its configuration does not include Configure shard allocation awareness"

As for the second question, a cluster without shards would have no data so I'm not sure I understand.

**Comment by tv1n94** [comment]
Good afternoon!

Jeff, thanks for your answer. I think we can close this thread.

My questions were focused on data resiliency within an OpenSearch cluster. More specifically, at the time of writing these questions, I didn't understand how shard replication works. We didn't understand why I don't see the shard replication option in the OpenSearch.yml configuration file.

Later I found information that all shards are replicated by default - https://opensearch.org/docs/latest/about/

Regarding the old link (https://opensearch.org/docs/2.0/opensearch/cluster/#advanced-step-6-configure-shard-allocation-awareness-or-). I thought that data replication will only occur if shard allocation awareness is configured. But it was not so.
