### ISSUE TITLE
[Docker security configuration] Unknown options in `opensearch.yml`

### ISSUE THREAD

**Issue by placaze** [opensearch-project/documentation-website#207]
I think there are unknown options in this page:
- https://opensearch.org/docs/latest/opensearch/install/docker-security/
- https://github.com/opensearch-project/documentation-website/blob/main/_opensearch/install/docker-security.md?plain=1#L132-L133

Opensearch doesn't boot with these two options:
```yaml
plugins.security.audit.config.disabled_rest_categories: NONE
plugins.security.audit.config.disabled_transport_categories: NONE
```

I'm not sure about this one too:
```yaml
cluster.routing.allocation.disk.threshold_enabled: false
```

Sorry I didn't make more tests. :frowning_face:

**Comment by elfisher** [comment]
> I expected Opensearch to boot following the docs, but it didn't. 🙂


That does sound like a problem. Do you have some additional information about your setup that you could share? Did you update the docker memory settings to 4GB as outlined here: https://opensearch.org/docs/latest/opensearch/install/docker/

**Comment by aetter** [comment]
Hey @placaze, thanks for the heads-up. I'll check it out. The security plugin in particular changed a bunch of settings, but also kept a bunch of them at the old `opendistro` path, so it's been a challenge to get everything into a good state. ☹️

**Comment by aetter** [comment]
Hi @placaze, resolved here, but it's a very unhappy fix: https://github.com/opensearch-project/documentation-website/commit/49acaf051b08556641fd6b1f4209c00000037579

If you look here, you can see that the naming conventions for our settings follow no discernible pattern, so the real fix is to use the same prefix for everything in code: https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/support/ConfigConstants.java

Until that day, though, we'll keep trying to stamp these out. Thanks again for reporting!
