### ISSUE TITLE
[DOC] Issues found in CAT API documentation

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/documentation-website#2077]
## **What do you want to do?**
 
- [x] Request a change to existing documentation

### Inclusive Naming - Version 2.0 to 2.4:
- [x] [CAT nodes](https://opensearch.org/docs/latest/api-reference/cat/cat-nodes/#response): `master` should be changed to `cluster_manager`.
- [x] [CAT allocation](https://opensearch.org/docs/latest/api-reference/cat/cat-allocation/#url-parameters): In the description for *local* parameter, `master node` should be changed to `cluster_manager node`.
- [x] [CAT nodeattrs](https://opensearch.org/docs/latest/api-reference/cat/cat-nodeattrs/#url-parameters): In the description for *local* parameter, `master node` should be changed to `cluster_manager node`.
- [x] [CAT repositories](https://opensearch.org/docs/latest/api-reference/cat/cat-repositories/#url-parameters): In the description for *local* parameter, `master node` should be changed to `cluster_manager node`.
- [x] [CAT shards](https://opensearch.org/docs/latest/api-reference/cat/cat-shards/#url-parameters): `master_timeout` parameter should be changed to `cluster_manager_timeout`, and in the description `master node` should be changed to `cluster_manager node`.
- [x] [CAT thread pool](https://opensearch.org/docs/latest/api-reference/cat/cat-thread-pool/#url-parameters): `master_timeout` parameter should be changed to `cluster_manager_timeout`, and in the description `master node` should be changed to `cluster_manager node`.
 
### Incorrect/Inconsistent Examples - Version 1.0 to 2.4:
- [x] [CAT allocation](https://opensearch.org/docs/latest/api-reference/cat/cat-allocation/#example): The 3rd example should be `GET _cat/allocation/node_name_1,node_name_2,node_name_3`.
- [x] [CAT count](https://opensearch.org/docs/latest/api-reference/cat/cat-allocation/#example): The 3rd example should be `GET _cat/count/index_or_alias_1,index_or_alias_2,index_or_alias_3`.
- [x] [CAT fielddata](https://opensearch.org/docs/latest/api-reference/cat/cat-field-data/#example): The 3rd example should be `GET _cat/fielddata/field_name_1,field_name_2,field_name_3`.
- [x] [CAT indices](https://opensearch.org/docs/latest/api-reference/cat/cat-indices/#example): The 3rd example should be `GET _cat/indices/index1,index2,index3`.
- [x] [CAT recovery](https://opensearch.org/docs/latest/api-reference/cat/cat-recovery/#example): The 3rd example should be `GET _cat/recovery/index1,index2,index3`.
- [x] [CAT templates](https://opensearch.org/docs/latest/api-reference/cat/cat-templates/#example): The 2nd example should be `GET _cat/templates/<template_name_or_pattern>` to be consistent with other pages where `<>` is used instead of `{}`, and `template_name_or_pattern` is more descriptive just like we see in [CAT count examples](https://opensearch.org/docs/latest/api-reference/cat/cat-count/#example)
- [x] [CAT thread pool](https://opensearch.org/docs/latest/api-reference/cat/cat-thread-pool/#example): The 2nd example should be `GET _cat/thread_pool/thread_pool_name_1,thread_pool_name_2,thread_pool_name_3`.
- [x] [CAT thread pool](https://opensearch.org/docs/latest/api-reference/cat/cat-thread-pool/#example): Missing an example for single `thread pool` (like in other API docs with similar features):
```
To limit the information to a specific thread pool, add the thread pool name after your query:
`GET _cat/thread_pool/<thread_pool_name>?v`
```

 ### Malformed Parameters table - Version 2.3 and 2.4:
- [x] [CAT allocation](https://opensearch.org/docs/2.3/api-reference/cat/cat-allocation/#url-parameters)
- [x] [CAT cluster manager](https://opensearch.org/docs/latest/api-reference/cat/cat-cluster_manager/#url-parameters)

**Comment by ariamarble** [comment]
Malformed tables issue is completed

**Comment by ariamarble** [comment]
PR for Incorrect/Inconsistent Examples complete. Waiting on backport fixes.

**Comment by ariamarble** [comment]
Inclusive language backports merged

**Comment by ariamarble** [comment]
Incorrect/Inconsistent Examples backports completed. Closing issue.
