### ISSUE TITLE
404 no longer redirects to docs home

### ISSUE THREAD

**Issue by aetter** [opensearch-project/documentation-website#209]
Previously, 404s redirected users to the docs home `/` (see 404.md and index.md), but it looks like the site now uses the 404 for the project website. If people 404 under the `docs` path, we'd want them to go back home.

For example, if you view the replication plugin docs and then try to swap back to version 1.0 of the docs, you'll 404 and just be stuck.

**Comment by AMoo-Miki** [comment]
@aetter, if a visitor goes to `/docs/1.0/unavailable-page`, would you rather they get redirected to `/docs/latest` or `/docs/1.0`?

**Comment by aetter** [comment]
`/docs/1.0` seems better, but if it's significantly harder to implement and/or maintain over time, `/docs/latest` is fine.
