### ISSUE TITLE
[DOC] Create documentation for _index APIs

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#2093]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
```
 PUT /<index>/_create/
POST /<index>/_create/
HEAD /<index>/_doc/<id>
HEAD /<index>/_source/<id>
GET /<index>/_source/<id> // deprecated (per Nate)
PUT /<index>/_block/<block>
HEAD /<index>
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
- `PUT /<index>/_create/`, `POST /<index>/_create/`,`HEAD /<index>/_doc/<id>` are documented here :https://opensearch.org/docs/latest/api-reference/document-apis/index-document/
- `HEAD /<index>/_source/<id>`, `GET /<index>/_source/<id>` is documented but missing important description information: https://opensearch.org/docs/latest/api-reference/document-apis/get-documents/
- `PUT /<index>/_block/<block>` is missing
- `HEAD /<index>`: Exists https://opensearch.org/docs/latest/api-reference/index-apis/exists/
