### ISSUE TITLE
[DOC]Create documentation for _flush APIs

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#2096]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

```
 POST /<target>/_flush
GET /<target>/_flush
POST /_flush
GET /_flush
POST /<index>/_flush
GET /<index>/_flush
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by JeffH-AWS** [comment]
+1 for this because I'm referencing it as part of the upgrade process.

**Comment by hdhalter** [comment]
Add indices.flush_synced
