### ISSUE TITLE
[DOC]Create documentation for _forcemerge API

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#2097]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

```
 POST /_forcemerge
POST /<index>/_forcemerge
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by kolchfa-aws** [comment]
Closing in favor of #5057

**Comment by hdhalter** [comment]
Closing, see https://opensearch.org/docs/latest/api-reference/index-apis/force-merge/.
