### ISSUE TITLE
[DOC]Create documentation for _refresh API

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#2099]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
```
POST /_refresh
GET /_refresh
POST /<index>/_refresh
GET /<index>/_refresh
```
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
@hdhalter: Can you assign this to me? Its a gap we need filled for Benchmark documentation.

**Comment by Naarcha-AWS** [comment]
Going to prioritize this to assist with #5809
