### ISSUE TITLE
[DOC]Create documentation for _mget API

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#2106]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 
```
 GET /_mget
POST /_mget
GET /<index>/_mget
POST /<index>/_mget
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
We have documentation for mget here: https://opensearch.org/docs/latest/api-reference/document-apis/multi-get/. @kolchfa-aws , does this suffice, or is something missing? Thanks.

**Comment by kolchfa-aws** [comment]
POST is missing

**Comment by Naarcha-AWS** [comment]
As shown in the following screenshot, POST mget does exist in the current API reference.

<img width="715" alt="Screenshot 2024-04-19 at 10 42 38 AM" src="https://github.com/opensearch-project/documentation-website/assets/97990722/c9b81d1e-0923-4be6-86c1-3b32004a9740">
