### ISSUE TITLE
[DOC]Create documentation for _rank_eval API

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#2109]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
```
 GET /_rank_eval
POST /_rank_eval
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
We have documentation for these APIs: https://opensearch.org/docs/latest/api-reference/rank-eval/. @kolchfa-aws - closing this issue.
