### ISSUE TITLE
[DOC] Consolidated Dev Tools

### ISSUE THREAD

**Issue by brijos** [opensearch-project/documentation-website#2156]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Provide support for a consolidated development tooling experience. The work will require adding stubs where existing functionality is migrating from as well as improvements made to the tooling once inside. The scope is still under discussion as to what will fit into what milestone.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3033

**Comment by vagimeli** [comment]
@brijos Do we need to update the existing Query Workbench documentation? PR #5378

- https://opensearch.org/docs/latest/search-plugins/sql/sql/index/ 
- https://opensearch.org/docs/latest/search-plugins/sql/workbench/
