### ISSUE TITLE
[DOC] OpenSearch debian distribution

### ISSUE THREAD

**Issue by setiah** [opensearch-project/documentation-website#2164]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Describe how to install and run OpenSearch Debian distribution.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://github.com/opensearch-project/opensearch-build/issues/28

**Comment by Naarcha-AWS** [comment]
@setiah: Could you provide further context on how the Debian installation differs from Tarball? Also, which versions of OpenSearch will Debian support?

**Comment by JeffH-AWS** [comment]
I imagine the debian distribution will be most similar to RPM, but using the apt-get package manager.

**Comment by Naarcha-AWS** [comment]
@setiah: Could you provide more information on the Debian artifact?

**Comment by bbarani** [comment]
@peterzhuamazon Can you please provide the requested information?

**Comment by peterzhuamazon** [comment]
Hi All,

We can use the old ODFE deb installation as references:
https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/

The difference is, we will change to the new url, remove jdk installation, remove ES installation, and more.
The installation should be extremely similar to the RPM case with a few tweaks.

I am open to have a call or discussion with a tech writer on this.
Just like the one in Windows Release Documentation.

Thanks.

**Comment by setiah** [comment]
hey @JeffH-AWS @Naarcha-AWS - apologies for late reply, I was out of office. 

@JeffH-AWS 
>I imagine the debian distribution will be most similar to RPM, but using the apt-get package manager. Can you confirm, Himanshu? If you can take the most relevant install guide and let me know which steps would be different that'll be enough.

Right. The above odfe documentation that Peter shared should help. If you face any issues w/ installation, feel free to reach out to @peterzhuamazon or me for assistance.

@Naarcha-AWS 
> Could you provide further context on how the Debian installation differs from Tarball? Also, which versions of OpenSearch will Debian support?

Like RPM, Debian can be installed/updated via dedicated package managers on Ubuntu systems. It will be available for 2.5 version and 1.x support will be coming in the subsequent 1.x minor release (@peterzhuamazon @bbarani to confirm on the latter)

**Comment by bertvandepoel** [comment]
Will the documentation describe whether there is a migration path (and how it works) from the last ElasticSearch OSS Debian packages release to the first official OpenSearch Debian packages? 

PS: definitely not asking for a friend, this is exactly our situation right now, and we are really hoping migrations won't be too messy 😅

**Comment by JeffH-AWS** [comment]
Hey @bertvandepoel  - thanks for chiming in. That's definitely a situation we want to cover.

The migration path is something that's being defined and fleshed out, but there are lots of origin configurations/versions and a few different methods. So it will take some time.

There are blogs, like https://opensearch.org/blog/how-to-upgrade-from-opendistro-to-opensearch/, which describe the process. Of course better docs are forthcoming, but it touches on the important aspects of upgrading in case that helps you with planning.

**Comment by bertvandepoel** [comment]
This is great news @JeffH-AWS ! We're quite patient, as you can imagine, so it's not a problem this might take a while. It would make sense for official releases of the Debian packages to come along with either sufficient internal migration scripts or sufficient migration documentation, as I expect quite a lot of people on Ubuntu and Debian have just pinned their package versions and are waiting with great excitement for official packages from OpenSearch :D

**Comment by JeffH-AWS** [comment]
This is completed and merged to the `main` branch for the docs repo. When 2.5 is released a 2.5 version of the docs site will be cut from `main` and the page will be live.
