### ISSUE TITLE
[RFC] Add warning to 1.3 and before 

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#2166]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Add a warning for OpenSearch versions 1.3 and before that says the following:

"This version of the OpenSearch documentation is no longer maintained. For the most up to date version of the documentation, see the [latest version](link to latest version). For more information on OpenSearch version maintenance, see [Release Schedule and Maintenance Policy](https://opensearch.org/releases.html)."
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by alicejw-aws** [comment]
warning note looks good!

**Comment by hdhalter** [comment]
Hi Nate, we have a request for adding a link to the latest version on all the older versions, in case the user gets directed to an older page. See https://github.com/opensearch-project/documentation-website/issues/2234#issuecomment-1355893986

**Comment by ashwin-pc** [comment]
Yes please! you can separate the warning between the versions that we still maintain and the versions we dont, but in all scenarios we should ideally have a banner that directs the user to the latest version of the docs. Depending on what i search in google, I can be taken to any one of our doc versions and its almost impossible to tell unless i click on the version dropdown.

**Comment by hdhalter** [comment]
The warning above is not entirely accurate because we do support updates through 1.3. How about a banner (similar to [this](https://opendistro.github.io/for-elasticsearch-docs/)) in 2.3 and earlier that says, "This is an older version of OpenSearch documentation and may not be fully maintained. For the latest version, see ____" For information on OpenSearch version maintenance, see [Release Schedule and Maintenance Policy](https://opensearch.org/releases.html)." Can we direct them to the same page they're on but in the /latest version?

**Comment by kolchfa-aws** [comment]
Could we have 2 different wordings:
1. For versions that we definitely don't maintain
2. For versions that are older but we are maintaining?
Thanks!

**Comment by hdhalter** [comment]
Ok, so for everything before 1.3, This is an older version of OpenSearch documentation and is no longer maintained. For the latest version, see ____. For information on OpenSearch version maintenance, see [Release Schedule and Maintenance Policy](https://opensearch.org/releases.html)."

**Comment by hdhalter** [comment]
For 1.3 and later, how about, "This is an older (earlier?) version of OpenSearch documentation. For the latest version, see ____. For information on OpenSearch version maintenance, see [Release Schedule and Maintenance Policy](https://opensearch.org/releases.html)."

(I'm not married to providing the link to the release schedule. Open to suggestions!)

**Comment by kolchfa-aws** [comment]
Resolved by #2624, #2626, #2631, and #2641
