### ISSUE TITLE
[DOC] Add OpenSearch Catalog documentation

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#2176]
**What do you want to do?**
 
- [x] Add new documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
OpenSearch Catalog is a searchable interface where you can browse, rate, and download community-developed plugins, artifacts, and visualizations for use in OpenSearch and Dashboards.

While it's likely we won't document every community-developed object inside the catalog, we will need to show OpenSearch users and developers how to interact with and install artifacts from the Catalog.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

- Git issue: https://github.com/opensearch-project/opensearch-catalog/issues/3
- POCs: @khushbar and @xinlamzn

**Comment by Naarcha-AWS** [comment]
Assigning to myself until we receive more information about how Catalog will be implemented for 2.5. @xinlamzn, could you provide more context?

**Comment by Naarcha-AWS** [comment]
Delayed till 2.6

**Comment by hdhalter** [comment]
There is no version attributed to this in the scorecard. Let's confirm the version.

**Comment by seanneumann** [comment]
Heya. We've postponed the catalog due to prioritization and resources. Let's put this on the backlog, but it won't be soon.

**Comment by YANG-DB** [comment]
@Naarcha-AWS can we close this issue ? its not active for almost a year
