### ISSUE TITLE
[DOC] Dashboards list extensibility

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#2203]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

POCs: PM- Andrew Hopp, SDE - Peter Fitzgibbons

**Comment by Naarcha-AWS** [comment]
Need to investigate if this is still making 2.5.

**Comment by Naarcha-AWS** [comment]
As of January 9, this is set for 2.5.

**Comment by vagimeli** [comment]
Info gathering meeting with [pjfitzgibbons](https://github.com/pjfitzgibbons) re: user documentation. Additional resources https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1866 and https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3090

**Comment by vagimeli** [comment]
working draft in progress; @@pjfitzgibbons updating on status of feature release

**Comment by vagimeli** [comment]
Moved to 2.6 release; draft in progress

**Comment by hdhalter** [comment]
Related to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1866

**Comment by vagimeli** [comment]
This feature is being released in 2.7. @PeterFitzgibbons and @vagimeli have meeting 2/21 to sync on doc's audience, learning objectives, and level of detail

**Comment by vagimeli** [comment]
Closing duplicate issue; see https://github.com/opensearch-project/documentation-website/issues/3442 and PR #3443
