### ISSUE TITLE
[DOC] Missing default credentials in docker setup page

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/documentation-website#2235]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
After following the installation steps for the docker compose section and starting up the service, the page should also include the default credentials needed to access the newly started service and instructions on how to reach it.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
@ashwin-pc: Can you provide a link to the version of the docs you were using? Was it above OpenSearch 1.3?

**Comment by ashwin-pc** [comment]
Yeah i think these are all linked to the same issue where the default link in google search takes me to an older version of the doc site: https://github.com/opensearch-project/documentation-website/issues/2234#issuecomment-1353692681

Feel free to consolidate the 3 issues into one about redirecting or prompting the user to the latests version of docs since its not obvious otherwise
