### ISSUE TITLE
[DOC] Docker hint for OpenSearch Dashboards variables incorrect

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/documentation-website#2236]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
There is a hint on the page that is a little misleading

> If you override opensearch_dashboards.yml settings using environment variables, as seen above, use all uppercase letters and periods in place of underscores (e.g. for opensearch.hosts, use OPENSEARCH_HOSTS).

The example does not match the instructions. In this case i believe the examples are correct.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
@ashwin-pc: Can you provide a link to the version of the docs you were using? Was it above OpenSearch 1.3?

**Comment by ashwin-pc** [comment]
Yeah i think these are all linked to the same issue where the default link in google search takes me to an older version of the doc site: https://github.com/opensearch-project/documentation-website/issues/2234#issuecomment-1353692681

**Comment by Naarcha-AWS** [comment]
We added a banner prompting the user to use newer versions of the docs when possible. Closing this issue for now.
