### ISSUE TITLE
[DOC] Forecasting

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#2238]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
Moving this to 2.8

**Comment by hdhalter** [comment]
moving to 2.9

**Comment by hdhalter** [comment]
@Naarcha-AWS - according to Sean Zheng, this has been moved to 2.10. I'll adjust the labels appropriately.

**Comment by hdhalter** [comment]
@Naarcha-AWS  - moving this out of 2.10 to 2.11, as per project meeting 8/10

**Comment by hdhalter** [comment]
In project meeting, Xin pushed to TBD since it needs more work.

**Comment by hdhalter** [comment]
Closing until we get more info.
