### ISSUE TITLE
[DOC] Model registry UI

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#2239]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@Naarcha-AWS - according to Sean Zheng, this feature has been pushed out to 2.10. I'll adjust the labels.

**Comment by hdhalter** [comment]
@Naarcha-AWS  - moving this out of 2.10 to a future release, as per project meeting 8/10

**Comment by hdhalter** [comment]
Closing until we get further information about this feature.
