### ISSUE TITLE
[DOC]Admin UI for ML Commons [Experimental]

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#2240]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
https://github.com/opensearch-project/ml-commons/issues/427
