### ISSUE TITLE
[DOC] GPU-support on ML node

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#2241]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by ylwu-amzn** [comment]
https://github.com/opensearch-project/documentation-website/pull/2384
