### ISSUE TITLE
[DOC] Segment Replication - GA release

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#2255]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Currently an experimental feature, Segment Replication will be generally available in the 2.7 release. 

For the GA release: Propose a new shard replication strategy (segment replication) and outline its tradeoffs with the existing approach (document replication). In segment replication, we copy Lucene segment files from the primary shard to its replicas instead of having replicas re-execute the operation.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
The SDM is Anas Alkous (@anasalkouz) and the SDE is Marc Handalian (@mch2). 
Design proposal: https://github.com/opensearch-project/OpenSearch/issues/2229

**Comment by dreamer-89** [comment]
As mentioned [here](https://github.com/opensearch-project/OpenSearch/issues/6027#issuecomment-1451095332), the segment replication uses recovery settings, thus available `max_bytes_per_sec` defaults (40 MB/s) is not reserved for recovery alone. This should be called out in documentation.

**Comment by Rishikesh1159** [comment]
@ariamarble @kolchfa-aws Sorry I forgot to mention this before. We need to let users using segment replication know that Segment Replication currently doesn't support wait_for requests in refresh API. Can we please include this limitation with segment replication in appropriate place.

**Comment by ariamarble** [comment]
@Rishikesh1159 can do, I'll add a note to the page.
