### ISSUE TITLE
[DOC] Snapshot pages are inconsistent between versions 2.0 and 2.1+

### ISSUE THREAD

**Issue by JeffHuss** [opensearch-project/documentation-website#2257]
**What do you want to do?**
 
It looks like a backport PR might have been missed somewhere along the line but right now the structure and content of snapshots is very very inconsistent between 2.0 and newer 2.x versions.

2.0 - you can see that there is no snapshots section, only a single "Take and restore snapshots" link:
![image](https://user-images.githubusercontent.com/107883031/208500466-ea4b4954-cb83-48bc-8997-01062898fe49.png)

2.1 - you can see the full content of snapshots present:
![image](https://user-images.githubusercontent.com/107883031/208500559-9d573450-a1c8-4372-a2a6-2ff0cd3b33d1.png)

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
Going to assign this to myself for now, since it looks like a backport issue.

**Comment by Naarcha-AWS** [comment]
This will be addressed with the TOC changes here: https://github.com/opensearch-project/documentation-website/pull/2353

**Comment by kolchfa-aws** [comment]
Snapshot management was added in 2.1, so the Snapshots section was added to hold both snapshot and snapshot management documentation. Prior to 2.1, there was only the "Take and restore snapshots" page.

**Comment by hdhalter** [comment]
So, can we close this issue?

**Comment by kolchfa-aws** [comment]
@hdhalter IMHO we can close this issue.
