### ISSUE TITLE
[DOC] More detail for slices parameter of reindex API

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/documentation-website#2280]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [x] Other 

**Tell us about your request.** 
Add more detail about slices parameter of reindex API 

Setting slices to auto will let OpenSearch choose the number of slices to use. This setting will use one slice per shard, up to a certain limit(which is 20). If there are multiple sources, it will choose the number of slices based on the index or backing index with the smallest number of shards.

https://opensearch.org/docs/latest/api-reference/document-apis/reindex/#request-body

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Reassigning to Aria, since she has taken over a lot of the index management doc.
