### ISSUE TITLE
[DOC] Model Health Dashboard

### ISSUE THREAD

**Issue by dylan-tong-aws** [opensearch-project/documentation-website#2283]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

This is a request to provide documentation for the ML model health dashboard. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

(github issue pending) https://github.com/opensearch-project/.github/commit/b426500f4a07bbebb79c4037329c21b6a23904c9

**Comment by hdhalter** [comment]
Is this a duplicate of https://github.com/opensearch-project/documentation-website/issues/2240?

**Comment by Naarcha-AWS** [comment]
Yes. Closing with comment
