### ISSUE TITLE
[DOC] Support College Student Contributor Initiative - Developer Documentation

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#2294]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Develop new documentation for the college student contributor initiative. Topics include:
* Installing Dashboards plugins
* Setting up a simple dashboard
* Configuring Dashboards
* Glossary of commonly used Dashboards terms

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
POCs: @ashwin-pc, @joshuarrrr, @rednaksi91 
Links: 
https://opensearch.org/docs/latest/install-and-configure/install-opensearch/plugins/
https://opensearch.org/docs/latest/install-and-configure/configuration/
https://opensearch.org/blog/dashboards-plugins-intro/
https://github.com/opensearch-project/documentation-website/blob/main/TERMS.md

**Comment by Naarcha-AWS** [comment]
Removing the 2.5 milestone since this isn't tied to a release.

**Comment by vagimeli** [comment]
@ashwin-pc We have existing user documentation for [installing and configuring Dashboards](https://opensearch.org/docs/latest/install-and-configure/install-dashboards/index/), [installing OpenSearch and Dashboards plugins](https://opensearch.org/docs/latest/install-and-configure/install-dashboards/plugins/), and [OpenSearch terms](https://github.com/opensearch-project/documentation-website/blob/main/TERMS.md). User documentation for creating your first dashboard is in progress. I'm tracking to send out the PR for review by 1/9.
