### ISSUE TITLE
[DOC] Add Jaeger Usage Docs

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/documentation-website#2313]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
As a part of 2.5 release, Trace Analytics will support raw Jaeger format data. Thus, docs need to be added to help assist with discovery and usage of this new feature. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
 [FEATURE - add support for jaeger schema ](https://github.com/opensearch-project/dashboards-observability/issues/83)
https://www.jaegertracing.io/

Similar to this: https://medium.com/jaegertracing/jaeger-elasticsearch-and-kibana-7ecb846137b6

Doc page to add new content: [Trace Analytics](https://opensearch.org/docs/latest/observability-plugin/trace/index/)

**Comment by derek-ho** [comment]
Blog will be similar to: https://logz.io/blog/jaeger-and-the-elk-stack/

**Comment by Naarcha-AWS** [comment]
@derek-ho: Do you have any additional resources for this one? Also, could you be more specific about what changes your hoping to see to the documentation, for example, an additional section on the Trace Analytics page or a unique page about the usage of Jaegar?

Furthermore, can you link a development PR from OpenSearch that adds Jaegar support?

**Comment by derek-ho** [comment]
@Naarcha-AWS here is the PR: https://github.com/opensearch-project/dashboards-observability/pull/150. It is basically letting users use trace analytics with the raw jaeger data, instead of having to ingest through data prepper. I think ideally it would be an additional section on the trace analytics page announcing that this integration now exists where they can use OpenSearch purely as their storage backend and use trace analytics, without having to ingest and store twice in data prepper format. I will try to get the feature brief to you ASAP so you have a better idea - let me know if you have any other questions or if this made it more clear, thanks!

**Comment by alicejw-aws** [comment]
Updates: Feature review mtg scheduled 1-10 11:30am PT.
Obtained the feature briefs (2) with more information.

**Comment by alicejw-aws** [comment]
Hi @anirudha, I need to take clean screen shots from a Dashboards instance that is populated with data. 

Could you please share the URL to your dashboard instance that you showed in the demo meeting? Thanks
For now, I'm creating screen shots as placeholders for the documentation, but they are blurry.

data source drop-down menu
other examples shown in the demo presentation

**Comment by alicejw-aws** [comment]
Hi @derek-ho , @anirudha, we are ready for you to review this draft for technical accuracy. Thanks 
also, if you can please share a Dashboards URL that was presented in the demo meeting, we need to use that to get quality screen images to replace the placeholders.

**Comment by alicejw-aws** [comment]
Update: Derek provided the Dashboards URL, and new screen images are now added to the doc PR. 

We are ready for tech review and require approval by EOD today so that we can get it through the doc review and editorial review by the 2.5 release date. Thanks
