### ISSUE TITLE
[DOC] Update remote store feature documentation

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/documentation-website#2319]
**What do you want to do?**
 
- [x] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 As part of OpenSearch 2.5 release, we are adding `Request level durability for remote-backed indices`.
 - Feature proposal - https://github.com/opensearch-project/OpenSearch/issues/1968
 - Design proposal - https://github.com/opensearch-project/OpenSearch/issues/2700

Since this is incremental development over existing experimental feature, we will shortly raise PR for the documentation update required. This is for tracking the same.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
Assigning this to @JeffH-AWS since he completed issue #1045.

**Comment by JeffH-AWS** [comment]
Please provide a concise summary of the feature as well as what you would like documented. Unfortunately I do not have cycles to complete this for the target GA of OpenSearch 2.5.0 unless things are distilled down.

**Comment by Naarcha-AWS** [comment]
@ashking94: With Jeff's availability in mind, @kolchfa-aws will take over the review. Thank you for taking this on @ashking94, makes our lives so much easier.

**Comment by ashking94** [comment]
@JeffH-AWS @Naarcha-AWS I have created PR for the changes we want to have done in the documentation part with respect to 2.5 release. PR link - #2320.

@kolchfa-aws  Please review and lets make appropriate rewording changes if required.
