### ISSUE TITLE
[DOC] Correct Set Compatibility mode code snippet

### ISSUE THREAD

**Issue by tobias-varden** [opensearch-project/documentation-website#2321]
**What do you want to do?**
 
- [x] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The documentation is wrong for how to enable / disable the compatibility mode.
 https://opensearch.org/docs/2.0/clients/agents-and-ingestion-tools/index/

It says you should set it using
```cli
PUT _cluster/settings
{
  "persistent": {
    "compatibility": {
      "override_main_response_version": true
    }
  }
}
```

But that gives a 401 error. The correct version is:
```cli
PUT /_cluster/settings
{
  "persistent" : {
    "compatibility.override_main_response_version" : false
  }
}
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by tobias-varden** [comment]
I only tried this on OS 1.2x version, not 2.0.

**Comment by BigSamu** [comment]
@Naarcha-AWS,

May I take this issue?

**Comment by BigSamu** [comment]
Hi @tobias-varden,

I am reviewing your issue now. Question, regarding this

> But that gives a 401 error. The correct version is:
> 
> ```
> PUT /_cluster/settings
> {
>   "persistent" : {
>     "compatibility.override_main_response_version" : false
>   }
> }
> ```

Did you meant `"compatibility.override_main_response_version" : true` or not?

**Comment by tobias-varden** [comment]
Hi @BigSamu, not sure exactly which version we were on as we are no longer running OpenSearch.
But yes, I meant `true`

**Comment by BigSamu** [comment]
Hi @tobias-varden, Just checked using both versions of OpenSearch and I can confirm that there is no issue. Not sure what were could be the problem.

@Naarcha-AWS, you can close this issue. Documentation is OK.
