### ISSUE TITLE
[DOC] [ml-commons] Add GPU support and prebuilt model to doc

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/documentation-website#2340]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
1. We plan to support running NLP model on GPU ML node. In 2.5, we plan to support NVIDIA GPU and AWS Inferentia. We need to explain how to prepare GPU ML node in our doc.

2. We have built some popular text embedding models and user can use these models easily by specifying model name and version only. No effort needed to trace model and prepare model parameters. We should list these models in a table and add to ml-commons doc.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
@ylwu-amzn: I'm already tracking against #2241. I'll close that one since this encompasses the new pre-built models as well.

**Comment by ylwu-amzn** [comment]
GPU support PR https://github.com/opensearch-project/documentation-website/pull/2384

We are going to push prebuilt-model support to 2.6. Feel free to close this one. We can create a new issue for prebuilt model support in 2.6 release.
