### ISSUE TITLE
[DOC] Query String Query support in Rollups

### ISSUE THREAD

**Issue by deshsidd** [opensearch-project/documentation-website#2341]
**What do you want to do?**
 
- [ ] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 ISM currently supports multiple types of search queries in Rollups such as Term, Terms, Range, etc. We want to now add support for [Query String](https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#query-string) (https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#query-string) search queries in Rollups.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
@deshsidd: Do you have a link to a development PR for this issue? Furthermore, has this been added to the [public roadmap](https://github.com/orgs/opensearch-project/projects/1) for 2.5?

**Comment by deshsidd** [comment]
@Naarcha-AWS Not added to the public roadmap yet, will add it now for 2.5. Here is the link to the PR:
https://github.com/opensearch-project/index-management/pull/616

**Comment by Naarcha-AWS** [comment]
Will merge this in for 2.5. But @kolchfa-aws plans on creating a Query String Query doc since we don't currently have one. I'll spin that off into a different issue.
