### ISSUE TITLE
[DOC] Visualization types - Using Bar charts

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#2357]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Creates new site page and new foundational content on using bar charts in Dashboards
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Hi @vagimeli Melissa, we only need the backport labels on the PR. For the issue, please add the version labels, for example, v2.x, 1.x.

**Comment by vagimeli** [comment]
@carolxob  I'll sync with you about this content development. It's backlog documentation that will be part of the Building data visualizations topic https://opensearch.org/docs/latest/dashboards/visualize/viz-index/
