### ISSUE TITLE
[PROPOSAL] Custom branding (custom logo) docs

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/documentation-website#241]
Custom branding was merged and will be released for `1.2`. Here is some proposed docs that could be added:

---
## Introduction

OpenSearch Dashboards, the default visualization tool for OpenSearch, is a forked project based on old versions of Kibana. Currently, OpenSearch Dashboards UI displays the default OpenSearch branding, and is not designed for ease of making branding configurations. 

In order to make user experience better by making the branding on the OpenSearch Dashboards configurable, we offer a solution for users to customize opensearch dashboard using opensearch_dashboards.yml file. 

As a first step, we will target a predefined list of logos and titles, and our initial user will be cluster administrators who have access to the opensearch_dashboards.yml file and who can configure those before they start the application. The project only targets OpenSearch Dashboard open source, not the managed AES service.

## Branding configurations:

We added a list of branding related configurations in opensearch_dashboards.yml file.

```
# opensearchDashboards.branding:
  # logo:
    # defaultUrl: ""
    # darkModeUrl: ""
  # mark:
    # defaultUrl: ""
    # darkModeUrl: ""
  # loadingLogo: 
    # defaultUrl: ""
    # darkModeUrl: ""
  # faviconUrl: ""
  # applicationTitle: ""
```

## Targeted occurrences of logos and titles: 

Below shows a list of predefined places of logos and titles that we are targeting for the initial launch. There are 7 logos and 4 titles in total. They are distributed from the welcome page, loading page, home page, overview page, as well as the browser tab. The red circle mark refers to the logos and the green underline refers the titles we are targeting. 
![Screen Shot 2021-09-22 at 1 41 51 PM](https://user-images.githubusercontent.com/12060704/139925346-2e42123f-5cc8-41f8-8ff1-400d81850fe0.png)

## User Steps:

Cluster administrators need to follow three steps in order to achieve branding configurations: 

1. Input branding configs in the opensearch_dashboards.yml file
2. Restart the server
3. Refresh the browser

### [Basic] Mark Configuration

Mark is short for brand mark or logo symbol, and it is usually a small icon. In the application, mark will be the logo that is mainly rendered.  If users want a simple one step branding configuration, they can input a valid URL for mark defaultUrl config to achieve that. 

```
# opensearchDashboards.branding:
  # mark:
    # defaultUrl: ""
    # darkModeUrl: ""
```

**Target Logos**

L1 — Welcome Logo
L2 — Loading Logo(mark will be used if no advanced loading logo configuration is provided)
L3 — Side Menu Logo
L4 — Home Dashboard Logo
L5 — Nav Bar Logo(mark will be used if no advanced logo configuration is provided)
L6 — Overview Logo

**Requirements** 

* Allowed URL file types: svg/SVG, png/PNG, gif/GIF
* Dark mode configuration: input URL for darkModeUrl config; a valid URL must be provided for defaultUrl config first

**Example**

1. **No Mark Configuration:**

    Original OpenSearch mark will be rendered.
    ```
    # opensearchDashboards.branding:
    # mark:
        # defaultUrl: "https://validURL.svg"
        # darkModeUrl: ""
    ```

2. **Default Mode Mark Configuration:**

    Custom default mode mark will be rendered in both light mode and dark mode.
    ```
    # opensearchDashboards.branding:
    # mark:
        # defaultUrl: "https://validURL.svg"
        # darkModeUrl: ""
    ```

3. **Default Mode and Dark Mode Configuration:**

    Custom default mode mark will be rendered in default mode and custom dark mode mark will be rendered in dark mode.
    ```
    # opensearchDashboards.branding:
    # mark:
        # defaultUrl: "https://validURL.svg"
        # darkModeUrl: "https://validURL.svg"
    ```

**Error Section**

1. **Invalid URL:**

    Custom default mark will not be rendered. Original OpenSearch mark will be rendered.
    ```
    # opensearchDashboards.branding:
    # mark:
        # defaultUrl: "https://notFound"
        # darkModeUrl: ""
    ```

    Log Message: 

    `[info][branding] logo default config is not found or invalid.`

2. **Dark mode Configuration without default mode configuration:**

    Both default mark and dark mode mark will not be rendered.

    ```
    # opensearchDashboards.branding:
    # mark:
        # defaultUrl: "https://notFound"
        # darkModeUrl: "https://validURL.svg"
    ```

    Log Message: 

    ```
    `[info][branding] logo default config is not found or invalid.`
    `[error][branding] Must provide a valid logo default mode URL before providing a logo dark mode URL`
    ```

### [Basic] Application Title Configuration

The applicationTitle config can be used to configure the title and replace the default “OpenSearch Dashboards” title in the application. The four titles that we are going to target are welcome title, loading title, home dashboard title and browser tab title.

```
# opensearchDashboards.branding:
  # applicationTitle: ""
```

**Target Titles:** 

T1 — Welcome Title
T2 — Loading Title
T3 — Home Dashboard Title
T4 — Browser Tab Title

**Requirements:** 

* Allowed type: string that has length between 1 and 36 letters.

**Example:** 

1. No Application Title Configuration:

    Default application title “OpenSearch Dashboards” will be rendered.

    ```
    # opensearchDashboards.branding:
    # applicationTitle: ""
    ```

2. **Application Title Configuration:**

    Application title will be replaced with the custom application title.

    ```
    # opensearchDashboards.branding:
    # applicationTitle: "Custom Search Dashboard"
    ```

**Error Section:**

1. **Invalid string length:**

    Custom application title will not be rendered. Original OpenSearch Dashboard will be rendered.

    ```
    # opensearchDashboards.branding:
    # applicationTitle: "Custom Search Dashboarddddddddddddddddddddddddddddddd"
    ```

    Log Message: 

    ```
    [info][branding] applicationTitle config is not found or invalid. Title length should be between 1 to 36 characters.
    ```

### [Advanced] Logo Configuration

Different than mark, logo is usually a fuller and more complete representation of the brand, typically including the application title in it. We added the logo.defaultUrl config to provide user an option to display a fuller logo on the navigation bar that will be show on every page of the application. If logo configs is not provided, it will fall back to mark configs.

```
# opensearchDashboards.branding:
  # logo:
    # defaultUrl: ""
    # darkModeUrl: ""
```

**Target Logo:** L5 — Nav Bar Logo

**Requirements:** 

* Allowed URL file types: svg/SVG, png/PNG, gif/GIF
* Dark mode configuration: input URL for darkModeUrl config; a valid URL must be provided for defaultUrl config first

**Example:**

1. **No logo configuration & No mark configuration:** 

    Nav bar logo will render the original OpenSearch logo in both light and dark modes.

    ```
    # opensearchDashboards.branding:
    # mark:
        # defaultUrl: ""
        # darkModeUrl: ""
    # logo:
        # defaultUrl: ""
        # darkModeUrl: ""
    ```

2. **No logo configuration & Default mode mark configuration:** 

    Nav bar logo will render custom default mode mark in both light and dark modes.

    ```
    # opensearchDashboards.branding:
    # mark:
        # defaultUrl: "https://validURL.svg"
        # darkModeUrl: ""
    # logo:
        # defaultUrl: ""
        # darkModeUrl: ""
    ```

3. **No logo configuration & Default mode and dark mode mark configuration:** 

    Nav bar logo will render custom default mode mark in light mode and custom dark mode mark in dark mode.

    ```
    # opensearchDashboards.branding:
    # mark:
        # defaultUrl: "https://validURL.svg"
        # darkModeUrl: "https://validURL.svg"
    # logo:
        # defaultUrl: ""
        # darkModeUrl: ""
    ```

4. **Default mode logo configuration:** 

    Nav bar logo will render custom default mode logo in both light mode and dark mode.

    ```
    # opensearchDashboards.branding:
    # logo:
        # defaultUrl: "https://validURL.svg"
        # darkModeUrl: ""
    ```

5. **Default mode and dark mode logo configurations:**

    Nav bar logo will render custom default mode logo in light mode and custom dark mode logo in dark mode.

    ```
    # opensearchDashboards.branding:
    # logo:
        # defaultUrl: "https://validURL.svg"
        # darkModeUrl: "https://validURL.svg"
    ```

**Error Section:**

1. **Invalid URL:**

    Custom default mode logo will not be rendered. If a valid custom default mode mark exists, custom default mode mark will be rendered. Otherwise, original OpenSearch mark will be rendered.

    ```
    # opensearchDashboards.branding:
    # logo:
        # defaultUrl: "https://notFound"
        # darkModeUrl: ""
    ```

    Log Message: 

    `[info][branding] logo default config is not found or invalid.`

2. **Dark mode Configuration without default mode configuration:**

    Config logo.darkModeUrl will not be considered without a valid logo.defaultUrl. Original OpenSearch logo will be rendered. 

    ```
    # opensearchDashboards.branding:
    # logo:
        # defaultUrl: "https://notFound"
        # darkModeUrl: "https://validURL.svg"
    ```

    Log Message: 

    ```
    `[info][branding] logo default config is not found or invalid.`
    `[error][branding] Must provide a valid logo default mode URL before providing a logo dark m`
    ```

**Fallback mechanism for Nav Bar Logo:**

1. Default Mode: logo.defaultUrl > mark.defaultUrl > original opensearch logo
2. Dark Mode: logo.darkModeUrl > logo.defaultUrl > mark.darkModeUrl > mark.defaultUrl >  original opensearch logo

### [Advanced] Loading Logo Configuration

Loading logo configs provide users an option to display an animated logo for the loading page.

```
# opensearchDashboards.branding:
  # loadingLogo:
    # defaultUrl: ""
    # darkModeUrl: ""
```

**Target Logo:** L2 — Loading Logo

**Requirements:** 

* Allowed URL file types: 
    * Animated loading logo: svg/SVG, gif/GIF
    * Static loading logo: svg/SVG, gif/GIF, png/PNG
* Dark mode configuration: input URL for darkModeUrl config; a valid URL must be provided for defaultUrl config first

**Example:** 

1. **No loading logo configuration & No mark configuration:** 

    Loading logo will render the original OpenSearch spinner in both light and dark modes.

    ```
    # opensearchDashboards.branding:
    # mark:
        # defaultUrl: ""
        # darkModeUrl: ""
    # loadingLogo:
        # defaultUrl: ""
        # darkModeUrl: ""
    ```

2. **No loading logo configuration & Default mode mark configuration:** 

    Loading logo will render custom default mode mark with a horizontal loading bar in both light and dark modes.

    ```
    # opensearchDashboards.branding:
    # mark:
        # defaultUrl: "https://validURL.svg"
        # darkModeUrl: ""
    # loadingLogo:
        # defaultUrl: ""
        # darkModeUrl: ""
    ```

3. **No loading logo configuration & Default mode and dark mode mark configuration:** 

    Loading logo will render custom default mode mark with a horizontal bar in light mode and custom dark mode mark with a horizontal loading bar in dark mode.

    ```
    # opensearchDashboards.branding:
    # mark:
        # defaultUrl: "https://validURL.svg"
        # darkModeUrl: "https://validURL.svg"
    # loadingLogo:
        # defaultUrl: ""
        # darkModeUrl: ""
    ```

4. **Default mode loading logo configuration:** 

    Loading logo will render custom default mode loading logo in both light mode and dark mode.

    ```
    # opensearchDashboards.branding:
    # loadingLogo:
        # defaultUrl: "https://validURL.gif"
        # darkModeUrl: ""
    ```

5. **Default mode and dark mode logo configurations:**

    Loading logo will render custom default mode loading logo in light mode and custom dark mode loading logo in dark mode.

    ```
    # opensearchDashboards.branding:
    # loadingLogo:
        # defaultUrl: "https://validURL.gif"
        # darkModeUrl: "https://validURL.gif"
    ```

**Error Section:**

1. **Invalid URL:**

    Custom default mode loading logo will not be rendered. If a valid custom default mode mark exists, custom default mode mark with a horizontal loading bar will be rendered. Otherwise, original OpenSearch spinner will be rendered.

    ```
    # opensearchDashboards.branding:
    # loadingLogo:
        # defaultUrl: "https://notFound"
        # darkModeUrl: ""
    ```

    Log Message: 

    `[info][branding] loadingLogo default config is not found or invalid.`

2. **Dark mode Configuration without default mode configuration:**

    Config loadingLogo.darkModeUrl will not be considered without a valid loadingLogo.defaultUrl. Original OpenSearch spinner will be rendered. 

    ```
    # opensearchDashboards.branding:
    # loadingLogo:
        # defaultUrl: "https://notFound"
        # darkModeUrl: "https://validURL.svg"
    ```

    Log Message: 

    ```
    `[info][branding] loadingLogo default config is not found or invalid.`
    `[error][branding] Must provide a valid loadingLogo default mode URL before providing a loadingLogo dark mode`
    ```

**Fallback mechanism for Loading Logo:**

1. Default Mode: loadingLogo.defaultUrl > mark.defaultUrl+loading bar > opensearchLogoSpinner
2. Dark Mode: loadingLogo.darkModeUrl > loadingLogo.defaultUrl > mark.darkModeUrl + loading bar> mark.defaultUrl + loading bar > opensearchLogoSpinner

### [Advanced] Favicon Configuration

User can input an image URL for faviconUrl config for favicon configuration.

```
# opensearchDashboards.branding:
  # faviconUrl: ""
```

**Target Logo:** L7 — Favicon

**Requirements**

* Allowed URL file types: svg/SVG, png/PNG, gif/GIF

**Example**

1. **No Favicon Configuration:**

    Original OpenSearch favicon will be rendered on the browser tab.

    ```
    # opensearchDashboards.branding:
    # faviconUrl: ""
    ```

2. **Favicon Configuration:** 

    Custom favicon will be rendered on the browser tab.

    ```
    # opensearchDashboards.branding:
    # faviconUrl: "https://validURL.svg"
    ```

**Error Section**

1. **Invalid URL:**

    Original OpenSearch favicon will be rendered on the browser tab.

    ```
    # opensearchDashboards.branding:
    # faviconUrl: "https://notFound"
    ```

    Log Message: 

    ```
    [info][branding] favicon config is not found or invalid.
    ```

**Details**

1. Custom favicon will be rendered the same in both light mode and dark mode. No current dark mode favicon configuration is supported.
2. Supported browser favicon configurations:
    1. Chrome
    2. FireFox
    3. Edge
    4. Safari
3. Not-supported favicon configurations: 
    1. Windows Title Icon
    2. Android Device Icon
    3. Other advanced device favicon icons

## 6. Other Requirements

* For URLs, only svg, png, and gif are allowed; other file types are not allowed and will not be used. Log will show an info message
* No size and resolution requirements on the input image files. User can upload image with any sizes and we will format it to certain sizes for best appearance. 
* Cluster administrator should be responsible for the security impact of the URLs they provide. Thus, we recommend cluster administrator to use a private domain to host their images. 
    * Possible security issue with custom URL: 
        * URL that can redirect to other websites
        * SVG file that have embedded malicious JavaScript code

**Comment by melokk97** [comment]
Can I add artifacts to the server Opensearch Dashboards and call them by relative path.
For example: `faviconUrl: "/usr/share/opensearch-dashboards/favicon.svg"`

**Comment by kavilla** [comment]
@melokk97 

Unfortunately not at this time. It requires the logo to be served up. Please see https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1022#issuecomment-993019635 for more details.

Thank you!

**Comment by keithhc2** [comment]
Closed with #332

**Comment by pietrogu** [comment]
Is there a configuration sample?

**Comment by keithhc2** [comment]
Sorry about that, @pietrogu. I just submitted #337 that has a sample configuration you can use.

**Comment by amanthakur** [comment]
Can anyone tell me how I can change open search login page text . I want to change login page text

**Comment by nickwalchliversent** [comment]
can these options be added to the dashboards configuration menu? for those running on AWS its not possible to achieve this branding functionality still.
