### ISSUE TITLE
[DOC] Remove superfluous index page in install and config section

### ISSUE THREAD

**Issue by JeffH-AWS** [opensearch-project/documentation-website#2448]
**What do you want to do?**
 
Remove the redundant index/landing page for installation in the ToC. It only repeats information that's already in the ToC, it adds no value or information, and also makes for another place where we need to worry about updating links.

![image](https://user-images.githubusercontent.com/107883031/213775130-0d0ad922-a55e-42d8-b320-17c5203d2e11.png)

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Delete `/install-and-configure/index/`

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
@JeffH-AWS: We can remove the page for now, however, when we move away from collections, we'll need high-level index pages for each section for the side-navigation.

**Comment by Naarcha-AWS** [comment]
What do you think of this structure for now? 

<img width="271" alt="Screen Shot 2023-01-20 at 1 24 44 PM" src="https://user-images.githubusercontent.com/97990722/213788401-0e4e2020-21d6-444b-8b1b-2c7fcd637050.png">
