### ISSUE TITLE
Fix client side documentation for OpenSearch security   

### ISSUE THREAD

**Issue by setiah** [opensearch-project/documentation-website#245]
The client side setup required to work with security enabled OpenSearch cluster is missing some important steps.

See https://github.com/opensearch-project/OpenSearch/issues/1393 and https://github.com/opensearch-project/OpenSearch/issues/1501
 
When using SSL, users need to point client `ca_certs_path`  to the right root ca path, their setup, to ensure the client trusts the server certificate. The root-ca.pem is provided with demo certificates for a quick getting started experience but the setup required by client side is not discussed

**Comment by setiah** [comment]
The OpenSearch java client recommended [here](https://opensearch.org/docs/latest/clients/java-rest-high-level/)  is still in beta and not production ready. Lets remove this recommendation until we have a production release available

**Comment by setiah** [comment]
As part of this [code change](https://github.com/opensearch-project/OpenSearch/pull/1602), we are pointing users to the documentation page. We should add a Troubleshooting section on the page for common misses during the setup. Example, if you see this error signature - `SunCertPathBuilderException`, the  client truststore is missing certificates to validate the server. Action - Look at step... to configure the client truststore correctly. If it still doesn't work, please create an issue @...

cc: @elfisher

**Comment by elfisher** [comment]
@keithhc2 I like the idea of the troubleshooting section. What are your thoughts?

**Comment by keithhc2** [comment]
Sure, I can look into adding some troubleshooting information.

**Comment by keithhc2** [comment]
Fixed with #323
