### ISSUE TITLE
[DOC] Update the Data Prepper table of contents

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/documentation-website#2453]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

With recent changes to Data Prepper's documentation, this may be a good time to update the table of contents.

For some background, Data Prepper has two main users (they are often the same, but need not be):
* Pipeline authors - these users write pipelines which control the flow of data through Data Prepper
* Administrators - these users make sure that Data Prepper is running and handle operations.

Also, Data Prepper supports several common use-cases or scenarios. Some examples are trace analytics, log analytics, metrics ingestion.

With this background laid, I'd like to propose the following table-of-contents structure.

```
Data Prepper
Getting started
Using for common scenarios
  - Trace analytics
  - Log analytics
  - S3 log analytics
  - Metrics ingestion
Authoring Pipelines
  - Pipeline options
  - Expression syntax
  - Sources
  - Buffers
  - Processors
  - Sinks
Administrating Data Prepper
  - Data Prepper Configuration
  - Peer forwarder
  - Core APIs
  - Log4j configuration
  - Monitoring Data Prepper
Migrating from Logstash
Migrating from Open Distro Data Prepper
``` 

The "Authoring Pipelines" section would target pipeline authors. The "Administrating Data Prepper" section is useful for Data Prepper administrators.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

This work is quite related to a few other issues:

* #1542 - That issue calls for re-organizing the plugin references. In this issue, I'm suggesting that we re-word this section to "Authoring Pipelines" from "Reference". Also, we can add other pipeline configurations useful for pipeline authors.
* #1846 - That issue suggests use-case specific pages. The difference in this proposal is to change the title of the section to "Using for common scenarios" instead of "Use-cases."
*  #1267 - Some of the pages from this issue would go into this new ToC structure.

**Comment by carolxob** [comment]
PR has been merged in #2514
