### ISSUE TITLE
[DOC] Update Debian Install Instructions using the Repository

### ISSUE THREAD

**Issue by OlafTei** [opensearch-project/documentation-website#2516]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 
The description on how to install OS with apt is outdated: Debian will warn that apt-key is deprecated.

Steps to install Opensearch from the repository:
1. Update the apt database and ensure all packages are up to date:
`sudo apt update && sudo upgrade -y`

2. Install required tools (that are used in the rest of the documentation)
`sudo apt install pgp curl `

3. Configure the repository for apt
3.1 Get the PGP key of the repository, convert it to binary and save it in /etc/apt/trusted.gpg.d/opensearch.pgp
`wget -qO - https://artifacts.opensearch.org/publickeys/opensearch.pgp | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/opensearch.pgp`

3.2 Add the OpenSearch repository including the key location
`echo "deb [signed-by=/etc/apt/trusted.gpg.d/opensearch.pgp] https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/opensearch-2.x.list`

4.  Update the apt database with the new repository
`sudo apt update`

5. Install Opensearch
5.1 List available versions
`sudo apt list -a opensearch`

5.2 Install the latest version
`sudo apt install opensearch -y`

5.3 Install a specific version (from the list in 5.1)
`sudo apt install opensearch=2.5.0`

6. Delete - it will not ask
7. Do *NOT* suggest to enable and run OpenSearch to test the installation before explaining the configuration: the documentation explains later the option to either run the demo configuration (Step 2) or use own configuration (Step 3) - once the installation was started, the data files are generated for the "opensearch" cluster. It requires extra steps (and time) to clean it up - not needed if the user wants to generate his own configuration.

Similar adjustments are required for OpenSearch-Dashboards using Debian repositories.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
[Debian 11 apt-key man(8) page](https://manpages.debian.org/bullseye/apt/apt-key.8.en.html)

**Comment by hdhalter** [comment]
Hi @JeffH-AWS , can you please take a look at this and update, as necessary? Thanks!

**Comment by JeffH-AWS** [comment]
The decision to use `apt-key` we deliberate by the build/infra team. Tagging @peterzhuamazon and @bbarani. No documentation changes will be made at this time.

**Comment by JeffH-AWS** [comment]
Closing due to the absence of comments. Please open an issue with https://github.com/opensearch-project/opensearch-build
