### ISSUE TITLE
Document building/distributing for openSUSE

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#2517]
### Is your feature request related to a problem? Please describe

It looks like there's a community effort around openSUSE!
https://build.opensuse.org/package/users/security:logging/opensearch

### Describe the solution you'd like

Add a section to https://github.com/opensearch-project/opensearch-build#making-a-release
Add to documentation and https://opensearch.org/artifacts/

### Additional context

Coming from https://github.com/opensearch-project/opensearch-build/issues/27#issuecomment-1077989625

**Comment by hdhalter** [comment]
We have documentation on RPM: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/rpm/. Closing this issue.
