### ISSUE TITLE
[DOC] Security Analytics - integration with Data Lake

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#2540]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 There is a new feature on security analytics coming out in 2.6: Support cohesive integrated experience between observability and security event log data; Support integration with Amazon Security Data Lake

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
samenp (Praveen) [Praveen Sameneni] is the SDM.

**Comment by cwillum** [comment]
Based on a message from the SDM, this update will not go into 2.6 but will be tied to another enhancement in a future release.

**Comment by cwillum** [comment]
@praveensameneni Is this issue possibly covered by updates in issue #4500 : "Update Mappings to support Open Cybersecurity Schema Framework (OCSF)"? If yes, I'll close this one. Thanks.

**Comment by Naarcha-AWS** [comment]
Data Lake is still on the roadmap, but the date for the integration is TBD. Closing this for now.
