### ISSUE TITLE
[BUG] Documentation update

### ISSUE THREAD

**Issue by RajivTaori** [opensearch-project/documentation-website#256]
**What is the bug?**
No opensearch documentation exists that outlines that is the node.ingest setting on the OpenSearch Service domain. 

Examples of what is available on on elastic.co site is pasted below
To disable ingest for a node, configure the following setting in the elasticsearch.yml file:
node.ingest: false
2:54
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/ingest.html

**Do you have any additional context?**
Note that default setting on OpenSearch service is *probably* FALSE, and this needs to be confirmed.

**Comment by ashwinkumar12345** [comment]
We mention this in the Cluster formation section:
 
Specify that this node will not be used for ingesting data:
node.ingest: false
