### ISSUE TITLE
[DOC] Document new multi-tenancy UI for management and configuration

### ISSUE THREAD

**Issue by cwillum** [opensearch-project/documentation-website#2562]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
Configuration for multi-tenancy is currently handled in the config.yml and opensearch_dashboards.yml files. The UX team is replacing the Tenants page in Dashboards with a new Multi-tenancy page that will begin to provide functionality for administrators in both managing and configuring tenants. Documentation needs to provide configuration and management information for both environments: config files and API; Dashboards user interface.

New documentation will provide information about new behavior in the UI and tasks administrators can perform, including:

- Enabling / disabling Multi-tenancy as a feature.
- Disabling the Private tenant.
- Setting a default tenant for all users (choosing between Global or Private).
- Notifications sent to non-admin and admin users about changes to tenant configuration that have an impact on them.

OpenSearch Dashboards multi-tenancy documentation already includes a "Multi-tenancy configuration" topic. We can add relevant documentation here. However, there may be additional changes to the API to align functionality between the two environments, which could require updates in other areas of Security documentation.
 

**What other resources are available?**
RFC for this feature: Issue #[5853](https://github.com/opensearch-project/OpenSearch/issues/5853). 
Some UX-related items:[ #1319](https://github.com/opensearch-project/security-dashboards-plugin/issues/1319).
Multi-tenancy configuration
https://opensearch.org/docs/latest/security/multi-tenancy/multi-tenancy-config/

**Comment by hdhalter** [comment]
Github issue: https://github.com/opensearch-project/security-dashboards-plugin/issues/1302

**Comment by cwillum** [comment]
This has been pushed to 2.7.

**Comment by cwillum** [comment]
Tracking this issue since it looks like it will impact dynamic Tenancy configurations: Issue [#2559](https://github.com/opensearch-project/security/issues/2559).
