### ISSUE TITLE
Update reporting trouble shooting page

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/documentation-website#257]
w.r.t to this issue and fix, which needs to add a section under Reporting -> [Troubleshooting](https://opensearch.org/docs/latest/dashboards/reporting/#troubleshooting)
https://github.com/opensearch-project/dashboards-reports/issues/154
https://github.com/opensearch-project/dashboards-reports/pull/189

**Comment by keithhc2** [comment]
Closed with #311
