### ISSUE TITLE
[DOC] Fix backporting issue(s) from PR 2212

### ISSUE THREAD

**Issue by JeffH-AWS** [opensearch-project/documentation-website#2578]
**What do you want to do?**
 
Fix missed cherrypicks in docs backports. E.g. https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker#related-links

![image](https://user-images.githubusercontent.com/107883031/216428810-91edc92a-451b-44d6-b504-3adb17f086f5.png)

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Please review the pages touched by https://github.com/opensearch-project/documentation-website/pull/2212 for all version backports and clean up the cherrypicks. It might have just been with the Docker install page but all of the backports should still be checked (probably good enough to go to each backport PR, do CTRL+F and look for each of the following strings:

This one shows the current change from your branch HEAD:
```
<<<<<< HEAD
```

This is the delimiter between your HEAD and MAIN:
```
=======
```

This one indicates the state of the doc at the origin:
```
>>>>>>> main
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

n/a

**Comment by Naarcha-AWS** [comment]
Fixed by #2580
