### ISSUE TITLE
[BUG] Typos in PPL Documentation

### ISSUE THREAD

**Issue by eugenesk24** [opensearch-project/documentation-website#259]
**What is the bug?**
1. Command should be fields not field (https://opensearch.org/docs/latest/search-plugins/ppl/commands/#fields)
2. Third row of table has required and default in the wrong columns (https://opensearch.org/docs/latest/search-plugins/ppl/commands/#syntax-1)

**How can one reproduce the bug?**
1. Go to https://opensearch.org/docs/latest/search-plugins/ppl/commands/

**What is the expected behavior?**
1. Under fields
Use the field command to keep or remove fields from a search result.
  -> Use the fields command to keep or remove fields from a search result.
field [+|-] <field-list>
  -> fields [+|-] <field-list>

2. Under dedup
No should be under Required and False should be under Default

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

![Screen Shot 2021-11-10 at 3 43 17 PM](https://user-images.githubusercontent.com/92330893/141211411-68ea40f8-35bf-47bc-b5a6-60eb69374fc3.png)
![Screen Shot 2021-11-10 at 3 42 43 PM](https://user-images.githubusercontent.com/92330893/141211420-6e0eea5e-2537-4817-9186-e59252b042a6.png)

**Do you have any additional context?**
Add any other context about the problem.

**Comment by keithhc2** [comment]
Fixed with c128c29
