### ISSUE TITLE
[DOC] Dashboards TOC

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#2621]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Arrange Dashboards documentation navigation into logical order 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by vagimeli** [comment]
Rearrange pages; below current structure is illogical. 

![TOC-current-structure](https://user-images.githubusercontent.com/105296784/216660992-3653fbce-4d03-4b6c-8108-484bcf030c80.png)

**Comment by vagimeli** [comment]
**Proposed structure** 
Quickstart guide
Exploring data with Discover
Creating dashboards with Dashboard
Building data visualizations with Visualize
Using Reporting plugins
Using Maps plugins
Using Dev Tools
Using Stack Management 
    Index and snap management

**Comment by hdhalter** [comment]
Hi Melissa, I'm going to close this issue.
