### ISSUE TITLE
[DOC] Add new _cat/segment_replication API documentation

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/documentation-website#2627]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

OpenSearch is currently working on new segment replication feature. Segment Replication has been released as an experimental feature in opensearch 2.3. As part of Segment Replication feature we are also introducing new `_cat/segment_replication` API.

 This API development is currently still in progress and will update the issue here as we make progress in API development. More Information about this issue can be found in [issue](https://github.com/opensearch-project/OpenSearch/issues/4554). We are planning to complete development and release this API for opensearch 2.6.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Rishikesh1159** [comment]
Detailed description of API : 

Overview:
The purpose of the this API is to return metric information about ongoing and completed segment replication events on replica shards. This API returns metric per shard level and this API should only be called on Indices with segment replication enabled.

Paths:

`GET/_cat/segment_replication`

`GET/_cat/segment_replication/<index>`

If you want to get information for more than one index, separate the indices with commas:

`GET/_cat/segment_replication/index1,index2,index3`

Description:
→ cat segment_replication API returns metric information about ongoing and completed segment replication events.
→ Segment Replication is a process of copying segment files from primary shard to replica shards. When primary sends checkpoint to replica shards on a refresh, a new segment replication event is triggered on replica shards.
→ Segment Replication event occurs on following processes:

When a new replica shard is added to cluster.
When there are segment file changes on a primary shard refresh.
When recovering replica shards from primary shard using peer recovery.
Query Parameters:

active_only
(Optional, Boolean) If true, the response only includes ongoing segment replications. Defaults to false.hfdhfffgfj
detailed
(Optional, string) If true, the response only includes ongoing segment replications. Defaults to false.
shards
(Optional, string) Comma-separated list of shards to display.
format
(Optional, string) Short version of the HTTP accept header. Valid values include JSON, YAML, etc.
h
(Optional, string) Comma-separated list of column names to display.
help
(Optional, Boolean) If true, the response includes help information. Defaults to false.
index
(Optional, string) Comma-separated list or wildcard expression of index names used to limit the request.
time
(Optional) Unit used to display time values. milliseconds by default.
v
(Optional, Boolean) If true, the response includes column headings. Defaults to false.
Metric Fields:

index | i,idx | index name : Name of the Index
shardId | shard Id : Id of a specific shard
start_time | start : segment replication start time. Show up only when default=true
start_time_millis | start_millis : segment replication start time in epoch milliseconds. Show up only when default=true
stop_time | stop : ssegment replication stop time. Show up only when default=true
stop_time_millis | stop_millis : segment replication stop time in epoch milliseconds. Show up only when default=true
time | t | ti : time taken to complete segment replication event in milliseconds
stage | st : current stage of segment replication event.
source_host | shost : source host
source_node | snode : source node name
target_host | thost : target host
target_node | tnode : target node name
files_fetched | ff : count to files fetched until now in segment replication event
files_percent | fp : percent of files fetched until now in segment replication event
bytes_fetched | bf : amount of bytes fetched until now in segment replication event
bytes_percent| bp : percent of bytes fetched until now in segment replication event
All metrics mentioned below will present in response only when query parameter detailed=true

files | f : count of files that needs to be fetched in a segment replication event
files_total | tf : total number of files that are part of this recovery, both re-used and recovered
bytes | b : amount of bytes that needs to be fetched in a segment replication event
files_total | ft : total number of bytes in the shard
replication_id : Id of the ongoing/completed segment replication event
replicating_stage_time_taken | rstt : Time taken to complete “replicating” stage of segment replication event
get_checkpoint_info_stage_time_taken | gcistt : Time taken to complete “get checkpoint info” stage of segment replication event
file_diff_stage_time_taken | fdstt : Time taken to complete “file diff” stage of segment replication event
get_files_stage_time_taken | gfstt : Time taken to complete “get files” stage of segment replication event
finalize_replication_stage_time_taken | frstt : Time taken to complete “finalize replication” stage of segment replication event
Example Response of API:
→ Sample response with no ongoing segment replication events:

```
curl -X GET "localhost:9200/_cat/segment_replication/test4?v=true"

index shardId time stage source_host source_node target_host target_node files_fetched files_percent bytes_fetched bytes_percent
test4 0 13ms done 127.0.0.1 runTask-0 127.0.0.1 runTask-2 0 0.0% 0 0.0%
test4 1 20ms done 127.0.0.1 runTask-2 127.0.0.1 runTask-1 3 100.0% 3661 100.0%
```
→ Sample response with query parameter shards=0, which limits response to only specific shards with ID as 0:

```
curl -X GET "localhost:9200/_cat/segment_replication?v=true&shards=0"

index shardId time stage source_host source_node target_host target_node files_fetched files_percent bytes_fetched bytes_percent
test4 0 13ms done 127.0.0.1 runTask-0 127.0.0.1 runTask-2 0 0.0% 0 0.0%
test6 0 9ms done 127.0.0.1 runTask-1 127.0.0.1 runTask-2 3 100.0% 3661 100.0%
```
→ Sample response with query parameter detailed=true, which gives more detailed information each stage of segment replication event:

```
curl -X GET "localhost:9200/_cat/segment_replication?v=true&detailed=true"

index shardId time stage source_host source_node target_host target_node files_fetched files_percent bytes_fetched bytes_percent files files_total bytes bytes_total replication_id replicating_stage_time_taken get_checkpoint_info_stage_time_taken file_diff_stage_time_taken get_files_stage_time_taken finalize_replication_stage_time_taken

test4 0 20ms done 127.0.0.1 runTask-0 127.0.0.1 runTask-1 0 0.0% 0 0.0% 0 0 0 0 2 0s 7ms 0s 4ms 7ms
test4 1 18ms done 127.0.0.1 runTask-1 127.0.0.1 runTask-2 0 0.0% 0 0.0% 0 0 0 0 2 0s 8ms 0s 2ms 6ms
```
→ Sample Response when API call made on a Index with segment replication not enabled:

```
curl -X GET "localhost:9200/_cat/segment_replication/test9?v=true"
Reason
error:{Segment Replication is not enabled on index: test9 }
```

**Comment by hdhalter** [comment]
@kolchfa-aws - Fanit, would you be able to take this on since your 2.6 issues were moved to 2.7. Let me know, thanks.

**Comment by kolchfa-aws** [comment]
@hdhalter Sure. Assigned to myself.

**Comment by Rishikesh1159** [comment]
Thanks @kolchfa-aws for picking this up. I have updated the above [comment](https://github.com/opensearch-project/documentation-website/issues/2627#issuecomment-1416202283) with few additional changes/corrections. [PR](https://github.com/opensearch-project/OpenSearch/pull/5718) related to this API has been merged to opensearch main and 2.x branches. We are targeting opensearch 2.6 release.

Few more additional metrics will be added to the API in future, we are targeting opensearch 2.7 release for that. But the initial version of the API is ready to be released in opensearch 2.6.

**Comment by kolchfa-aws** [comment]
Per SMEs, this is not going into 2.6. Removing the label.

**Comment by Rishikesh1159** [comment]
@kolchfa-aws can you please update the draft PR: https://github.com/opensearch-project/documentation-website/pull/2937 with the latest changes I made in comment [above](https://github.com/opensearch-project/documentation-website/issues/2627#issuecomment-1416202283)

**Comment by kolchfa-aws** [comment]
@Rishikesh1159 Thanks, will update!
