### ISSUE TITLE
[DOC] [ml-commons] Support model auto-reload (fault tolerance)

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/documentation-website#2654]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
In current ml-commons (2.5), we don't support model auto reload. That means if some node crashed, then restart, all models deployed on it will be gone. User needs to manually deploy the model to these nodes. We are going to support model auto reload in 2.6 release. When node restarted, we will check which model deployed to this node, and then auto reload the model.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
Issue moved to 2.7
