### ISSUE TITLE
[DOC] Simple Schema for Observability 

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/documentation-website#2655]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 With OpenSearch 2.6, we intend to release a standardization for conforming to a common & unified Observability schema which will be named Simple Schema for Observability (SSO).

This schema is compatible with OTEL schema & includes traces, logs & metrics. We also intend for supporting Alerts entity.
Simple Schema for Observability will also accept ECS logs when such structured log are present.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
 - https://github.com/opensearch-project/observability/issues/1399
 - https://github.com/opensearch-project/observability/issues/1398
 - https://github.com/opensearch-project/observability/issues/1388
 - https://github.com/opensearch-project/observability/issues/1389
 - [OTEL](https://opentelemetry.io/docs/)
 - [ECS](https://github.com/elastic/ecs)

**Comment by hdhalter** [comment]
Hi Aria, can you please take a look at this and let me know the scope? Thanks.

**Comment by ariamarble** [comment]
Hey @YANG-DB , I was wondering if we can get some clarification on this one. For documentation are we looking to explain our integration of SSO and OTel, like how it works under the hood, or are we looking to explain that basically "We support these things, here's how to configure it in Observability" ?

**Comment by YANG-DB** [comment]
Hi
I think that for sso scheme we need to describe the high level purpose and use case without drilling into the actual implementation details...

**Comment by ariamarble** [comment]
Hey @YANG-DB, thanks for clarifying. One further question. Can you tell me if SSO is still scheduled for release with 2.6?

**Comment by YANG-DB** [comment]
Yes we are planning on releasing that on 2.6

**Comment by ariamarble** [comment]
In progress and on track.

**Comment by ariamarble** [comment]
@YANG-DB can you review this PR for technical accuracy? - https://github.com/opensearch-project/documentation-website/pull/2940

**Comment by YANG-DB** [comment]
on it ...
