### ISSUE TITLE
[DOC] Flat Object

### ISSUE THREAD

**Issue by macohen** [opensearch-project/documentation-website#2657]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ x ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
We are targeting a 2.6.0 release for a feature to store full JSON objects without analyzing them. Today, by default, a JSON is stored and analyzed. In many cases, users do not need or want to index all fields in the object. This new feature will allow them to specify a document in mapping so they can use "dot" notation to access data in an object, but it will not be indexed.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/issues/1018

@mingshl

**Comment by hdhalter** [comment]
According to the scorecard, this is targeted for 2.7. Changing the label to 2.7.
