### ISSUE TITLE
[DOC] New doc for index data stream.

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/documentation-website#2659]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We are going to launch index data stream management on v2.6 in index management plugin. It will provide GUI to view / create / delete data streams in current cluster.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/464

**Comment by hdhalter** [comment]
Hi Aria, can you please take a look at this and let me know the scope? Thanks!

**Comment by ariamarble** [comment]
In progress and on track.
