### ISSUE TITLE
[DOC]New doc for index operation: rollover and force merge.

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/documentation-website#2660]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We are going to launch new index operations of rollover and force merge on v2.6 in index management plugin.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/465
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/497
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/484

**Comment by hdhalter** [comment]
Hi Aria, can you please take a look at this one and let me know the scope? Thanks!

**Comment by ariamarble** [comment]
In progress and on track.
