### ISSUE TITLE
[DOC] Add documentation for primary shard based balancing

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/documentation-website#2663]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Coming from https://github.com/opensearch-project/OpenSearch/issues/5240 and https://github.com/opensearch-project/OpenSearch/issues/6210, a new dynamic boolean type setting `cluster.routing.allocation.balance.prefer_primary` was introduced that defines if primary shards based balancing is desired i.e. whether primary shards should be distributed equally among your cluster nodes. Enabling this setting does not always guarantee equal number of primary shards on each node. This balance can't be hold specially post failover (node left/removed) which results in one node having more number of primary while other node contains the replica copy. In this situation, [SameShardAllocationDecider](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/decider/SameShardAllocationDecider.java) prevents the shard relocations. This limitation can be addressed in future work as part of https://github.com/opensearch-project/OpenSearch/issues/6642 and https://github.com/opensearch-project/OpenSearch/issues/6481

Note: Please note this setting is intended only for segment replication feature which is still experimental. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/issues/5240
https://github.com/opensearch-project/OpenSearch/issues/6210

**Comment by Naarcha-AWS** [comment]
@dreamer-89: Is this issue on the roadmap for 2.6?

**Comment by dreamer-89** [comment]
> @dreamer-89: Is this issue on the roadmap for 2.6?

Hi @Naarcha-AWS, thanks for the comment. I am working with @anasalkouz to get https://github.com/opensearch-project/OpenSearch/issues/5240  added to 2.6.0 [roadmap](https://github.com/orgs/opensearch-project/projects/1)

**Comment by kolchfa-aws** [comment]
No PR yet but on track

**Comment by kolchfa-aws** [comment]
@dreamer-89 Could you confirm that this is still going into 2.6?

**Comment by dreamer-89** [comment]
Hi @kolchfa-aws,

Thanks for checking on this. This change is already in `2.6` but as part of https://github.com/opensearch-project/OpenSearch/issues/6210 we are considering removing this setting in `2.7`. There are couple of options here:
1. Document this setting as under development (and mark non-ready for production)
2. Revert this change and thus remove the setting from `2.6`. Checking with current core-oncall @kartg on this.  

CC @anasalkouz @mch2

**Comment by anasalkouz** [comment]
@dreamer-89 does keep the code will break any functionality for either users who is using SegRep or for users who don't use SegRep?
If it's not impacting them, I don't see any need to revert the changes, and I prefer to postpone the documentation till 2.7.

**Comment by dreamer-89** [comment]
> @dreamer-89 does keep the code will break any functionality for either users who is using SegRep or for users who don't use SegRep? If it's not impacting them, I don't see any need to revert the changes, and I prefer to postpone the documentation till 2.7.

@anasalkouz : No the change is isolated. It doesn't break any functionality for both SegRep and DocRep. Thus, it wouldn't impact. 
The reason for revert is that once setting is exposed, it becomes difficult to remove them. Having documentation that it's experimental is fine but not exposing it altogether is better when it is identified that it can be removed later.

**Comment by dreamer-89** [comment]
@kolchfa-aws:
The change is reverted from `2.6` branch as part of https://github.com/opensearch-project/OpenSearch/pull/6444. Keeping this issue open for documentation for new setting introduced with https://github.com/opensearch-project/OpenSearch/issues/6210.

**Comment by kolchfa-aws** [comment]
Thank you, @dreamer-89
