### ISSUE TITLE
[DOC] Add documentation for missing Data Prepper plugins

### ISSUE THREAD

**Issue by lizsnyder** [opensearch-project/documentation-website#2722]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

The DP processor docs are missing documentation for the following plugins:

* Mutate events
* Mutate strings
* OTel metrics string
* OTel trace group processor
* Parse JSON
* Trace peer forwarder

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

For the full plugin reference and documentation, see https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins

**Comment by hdhalter** [comment]
Thanks for entering this, Liz. What is the delivery date for your content?

**Comment by asifsmohammed** [comment]
Hey, please take a look at the readme files of above plugins for reference
- Mutate event processor https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/mutate-event-processors#readme
- Mutate string processor https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/mutate-string-processors/README.md
- OTel trace group processor https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/otel-trace-group-processor#readme
- Parse JSON processor https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/parse-json-processor/README.md
- OTel metrics string processor -https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/otel-metrics-raw-processor/README.md
- Trace peer forwarder processor https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/trace-peer-forwarder-processor/README.md

**Comment by hdhalter** [comment]
Hi Caroline @carolxob - Will you be able to take this over? The deadline is Feb 22.

**Comment by carolxob** [comment]
> Hi Caroline @carolxob - Will you be able to take this over? They've moved the release date to March 14, so the new deadline is March 8.

Sure, I'm on it.

**Comment by hdhalter** [comment]
This is complete. https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/processors/
