### ISSUE TITLE
[DOC] Correct naming of predefined `opensearch_dashboards_readonly` role and `opensearch_dashboards_user` user

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/documentation-website#2723]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3391.
From our documentation,[predefined roles](https://opensearch.org/docs/2.4/security/access-control/users-roles/#predefined-roles) and the example below is using `opensearch_dashboards_read_only` and `openesarch_dashboards_user` as the name of user and role. But actually from the security plugin [codebase](https://github.com/opensearch-project/security/blob/75b6c3055f99ed8df0fdbeb10756a865cf3e6c76/config/roles.yml#L6), you can see it's named `kibana_read_only`. Similar with `opensearch_dashboards_user` --> `kibana_user`

Please correct the naming on our documentation to avoid misleading users.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by zhongnansu** [comment]
tagging @vagimeli for visibility

**Comment by vagimeli** [comment]
Status: TWs synced. @cwillum is working on this issue.
