### ISSUE TITLE
[DOC] Remove duplicate words from ml-commons

### ISSUE THREAD

**Issue by xluo-aws** [opensearch-project/documentation-website#2724]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Duplicate wording "and models"  
Example: Return all tasks and models and models on a specific node

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
@xluo-aws: Do you have a link to the page in question?
