### ISSUE TITLE
[DOC] Include Data Prepper plugin metrics to documentation

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/documentation-website#2751]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

The different plugin in Data Prepper report pipeline metrics. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

The [data-prepper-plugins](https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins) directory contains sub-directories for each plugin. Each has a README.md with metrics.

For example, here is the aggregate-processor metrics. https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/aggregate-processor#metrics

**Comment by dlvenable** [comment]
Also, each of the plugins have common metrics listed here: https://github.com/opensearch-project/data-prepper/blob/main/docs/monitoring.md#plugin-metrics

Each Processor plugin will have the metrics which are listed under "AbstractProcessor".

The bounded_buffer plugin has the metrics listed under "AbstractBuffer."

And the sinks that we have will all have the metrics in "AbstractSink."

**Comment by carolxob** [comment]
@dlvenable Can you confirm that the following need to be added?

- Anomoly detector processor
- Blocking buffer

#2950 covers adding six plugins. 

Is anything missing?

**Comment by dlvenable** [comment]
@carolxob , We do need to have those two plugins documented as well.

**Comment by Naarcha-AWS** [comment]
Let's carry over this issue to the new repo. To start, not all processors have metrics listed at this time. Furthermore, it'll give us the opportunity to discuss how to document common metrics that apply to all processors.
