### ISSUE TITLE
[BUG] "Configure node certificates" needs details

### ISSUE THREAD

**Issue by trombik** [opensearch-project/documentation-website#276]
**What is the bug?**

when `DN` of a certificate does not match any in `plugins.security.authcz.admin_dn`, you will see the following log:

```
[2021-11-16T06:35:07,521][ERROR][o.o.s.t.SecurityRequestHandler] [172.16.1.100] OpenSearchException[Illegal parameter in http or transport request found.
This means that one node is trying to connect to another with 
a non-node certificate (no OID or security.nodes_dn incorrect configured) or that someone 
is spoofing requests. Check your TLS certificate setup as described here: See https://opendistro.github.io/for-elasticsearch-docs/docs/troubleshoot/tls/]
```

"Check for special characters and whitespace in DNs" states:
https://opendistro.github.io/for-elasticsearch-docs/docs/troubleshoot/tls/#check-for-special-characters-and-whitespace-in-dns

> The security plugin uses the string representation of Distinguished Names (RFC1779) when validating node certificates.
>
> If parts of your DN contain special characters (e.g. a comma), make sure you escape it in your configuration:

actually, what users should know is not the RFC nor "special characters" in the RFC, but the following command:

```console
openssl x509 -noout -in /usr/local/etc/opensearch/localhost.pem -subject -nameopt RFC2253
````

"Configure node certificates" states:
https://opensearch.org/docs/latest/security-plugin/configuration/tls/#configure-node-certificates

> The simplest way of configuring node certificates is to list the Distinguished Names (DNs) of these certificates in opensearch.yml. All DNs must be included in opensearch.yml on all nodes. 

it is not that simple in reality. when playing with a new application, the best way is to try the example provided and to change one thing at a time. the example in the documentation is:

```yaml
plugins.security.nodes_dn:
  - 'CN=node.other.com,OU=SSL,O=Test,L=Test,C=DE'
  - 'CN=*.example.com,OU=SSL,O=Test,L=Test,C=DE'
  - 'CN=elk-devcluster*'
  - '/CN=.*regex/'
```

the example is correct, definitely. however, in reality, your DN might be:

```
CN=node.other.com,C=DE,OU=SSL,O=Test,L=Test
```

i guess it is semantically wrong, but anyhow, that is the DN in this case. it is hard to see the difference. it is user's error, but the log is not very helpful. instead of explaining the format, there should be a definite command that produces the correct DN, which is what users want to know.

elastic is far better in this regard. they have detailed troubleshooting guides, error messages and descriptions, common pitfalls, etc. 

**How can one reproduce the bug?**

1. Try to configure TLS
2. Figure it why it does not work

**What is the expected behavior?**

the `openssl` command should be documented in the page.

"Configure TLS certificates" page needs more details. what is requirements for certification and key? does it support EC key? SAN is required? which one is used to verify hostname? CN, or SAN?

A page, "Troubleshooting TLS", should be there, too.

**Do you have any screenshots?**

no

**Do you have any additional context?**

no

**Comment by keithhc2** [comment]
Hey @trombik, thanks a bunch for reporting. Are you referring to the `openssl` command that returns a certificate's DN? If so, that's documented here: https://opensearch.org/docs/latest/security-plugin/configuration/generate-certificates/#add-distinguished-names-to-opensearchyml

Also, we have a troubleshooting TLS page in the troubleshooting section of the site: https://opensearch.org/docs/latest/troubleshoot/tls/

I agree that the section  is by no means extensive, so we try to add in content as issues come in or if we run into them ourselves during testing. 

Hope this helps!

**Comment by trombik** [comment]
the bug is not specific to `opensearch`; there are many other applications that document TLS setup poorly. as opensearch now requires TLS by default, it is quite important to explain details in the doc. I know it is hard to maintain good documentation, but TLS section needs a lot of improvements. as manually maintaining a CA is not feasible in practice, many users use third-party tools, such as Active Directory or `cfssl`. detailed trouble-shooting section will certainly help. I will appreciate:

* requirements in TLS (especially certificates)
* clear explanations in logs (for example, "authentication failed" is hardly helpful)
* better trouble-shooting section

anyway, please consider the Issue as an expression of my frustration. I believe many feel the same thing. this might be a major hurdle for potential users.
