### ISSUE TITLE
[DOC] Fix the links on SQL documentation page 

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/documentation-website#2782]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 The links on SQL documentation [page](https://opensearch.org/docs/latest/search-plugins/sql/sql/jdbc/) is throwing 404 error and it needs to be replaced with the appropriate link.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
NA

**Comment by hdhalter** [comment]
Hi @anirudha , can you please let me know which page on the SQL repo I should link to from the documentation?
