### ISSUE TITLE
[DOC] Security "Features at a glance: Encryption" is confusing/mis-leading 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/documentation-website#2810]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 If you look at the Security -> About Security -> Features at a glance -> Encryption section [here](https://opensearch.org/docs/latest/security/index/#encryption), you will see that it reads "At rest, encryption secures sensitive data stored in a cluster. Some examples of stored data include indexes, logs, swap files, automated snapshots, and all data in the application directory." 
 
This is a bit misleading. While OpenSearch does have encryption at rest, it is handled by the operating system of each node and not the Security plugin [shown here](https://opensearch.org/docs/latest/troubleshoot/index/#encryption-at-rest). 
 
I am hoping that we can get a change to either remove the "at rest" section or reword it so that it is clear it is not a feature of the Security plugin. We have had user(s) asking how we encrypt the data at rest, only to have to explain that we don't actually directly do that. Perhaps, this will be implemented in the future but it is not an option right now. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

There should not be any testing required, just a text swap.

**Comment by cwillum** [comment]
PR is in #2824 and ready for review.

**Comment by cwillum** [comment]
Merged in #2824. Closing this issue.
