### ISSUE TITLE
[DOC] Remove Experimental flag From Search Comparison Tool 

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#2827]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 When the search comparison tool goes GA, remove the experimental flag from the documentation.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

[#144 ](https://github.com/opensearch-project/dashboards-search-relevance/issues/144)
Link to the doc is here: https://opensearch.org/docs/latest/search-plugins/search-relevance/index/

**Comment by hdhalter** [comment]
@macohen - Let us know when we should remove the flag. Thanks!

**Comment by hdhalter** [comment]
Assigning to you, Fanit. Note that there is no date for this change.

**Comment by kolchfa-aws** [comment]
@hdhalter This should be part of 2.6. Added a label.

**Comment by hdhalter** [comment]
@kolchfa-aws We discussed it in the project scorecard meeting yesterday. They decided to not remove the flag until there was a clear path to bring it out of experimental. Do you have new information?

**Comment by macohen** [comment]
I haven't updated @kolchfa-aws on this. The latest info is that we are going to leave the experimental label on until we have a clearer plan ahead for the comparison tool. Removing the label.

**Comment by hdhalter** [comment]
According to the project call today, this is going GA in 2.11.
