### ISSUE TITLE
Java client documentation is missing required dependency in maven section

### ISSUE THREAD

**Issue by bw999** [opensearch-project/documentation-website#283]
Docs at https://opensearch.org/docs/latest/clients/java/ say:

To start using the OpenSearch Java client, ensure that you have the following dependency in your project’s pom.xml file:

		<dependency>
			<groupId>org.opensearch.client</groupId>
			<artifactId>opensearch-java</artifactId>
			<version>0.1.0</version>
		</dependency>

Need to also say (as they correctly do for gradle)

		<dependency>
			<groupId>org.opensearch.client</groupId>
			<artifactId>opensearch-rest-client</artifactId>
			<version>1.1.0</version>
		</dependency>

**Comment by keithhc2** [comment]
Hey @bw999, thanks for letting us know We just merged in #306, and the [Java client page](https://opensearch.org/docs/latest/clients/java/) now has the dependency as well. Feel free to re-open the issue if you notice any other issues!
