### ISSUE TITLE
[DOCS-META] Version upgrade and migration documentation

### ISSUE THREAD

**Issue by JeffH-AWS** [opensearch-project/documentation-website#2830]

**Comment by JeffH-AWS** [comment]
Starting a fresh issue since we'll be linking to this one in the docs and it gives us a clean slate. The old meta issue was very old and didn't have a strong direction early on. Let's move the needle!

**Comment by JeffH-AWS** [comment]
Began work on upgrades while preserving the security settings. I don't this will be a heavy lift - I'm generally familiar with the process from previous reviews. Notes will be added to the Jira issue.

**Comment by dblock** [comment]
Let's capture the answer from https://forum.opensearch.org/t/upgrade-from-opensearch-1-x-to-2-x/12438/2 into this doc.

**Comment by JeffH-AWS** [comment]
I'm trying to determine whether or not relying on the security demo config is creating blind spots in the upgrade process for me by masking issues a user would run into if they use their own certs.

I'm going to manually build a secure cluster with my own certs and test.

**Comment by JeffH-AWS** [comment]
I'd like to get the breaking changes page enhanced to make the changes to nomenclature more clear.

In the meantime, mentioning a couple issues here to create breadcrumbs I can follow later.

https://github.com/opensearch-project/documentation-website/issues/450
https://github.com/opensearch-project/documentation-website/issues/449
https://github.com/opensearch-project/OpenSearch/issues/2589

**Comment by JeffH-AWS** [comment]
Added appropriate labels to better capture the scope of the work I'm doing to generate the data and test results needed for authoring the content.
