### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#2878]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by Naarcha-AWS** [comment]
I know where Codeowners should be, I'll add it.

**Comment by dblock** [comment]
![Screenshot 2023-04-13 at 11 04 45 AM](https://user-images.githubusercontent.com/542335/231802531-54ae08cf-c7ef-4e33-842d-f9e953ec0c44.png)

Repo permissions are incorrect. 

- only admin team should have admin
- individuals in MAINTAINERS should have maintain access directly
- remove the docs team

Please work with @bbarani's team on adjusting these.

**Comment by gaiksaya** [comment]
Permissions are updated now:

![image](https://user-images.githubusercontent.com/61760125/233491224-8778da73-620a-4549-bbe1-14a03fd75be4.png)


Just wanted to bring this up that codeowners file even though valid will only add the last person as reviewer always. Not sure what the bug is you might want to add it this one https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/.github/CODEOWNERS
cc: @ananzh @Naarcha-AWS

**Comment by dblock** [comment]
Verified, thx.

**Comment by rishabh6788** [comment]
Updated Permissions. 
![Screen Shot 2023-04-24 at 12 52 17 PM](https://user-images.githubusercontent.com/19776689/234101566-d9869b59-0a55-438b-8fa0-e7da353b15d1.png)
![Screen Shot 2023-04-24 at 12 52 27 PM](https://user-images.githubusercontent.com/19776689/234101578-ad21eea6-e3f1-4e62-b27e-c8e4a8ee0377.png)

**Comment by rishabh6788** [comment]
![Screen Shot 2023-04-24 at 12 52 27 PM](https://user-images.githubusercontent.com/19776689/234101708-f928e7e9-9603-41d3-9057-86fafaca76a3.png)
