### ISSUE TITLE
[BUG] incomplete java version list on compatibility page

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#288]
**What is the bug?**
the [compatibility](https://opensearch.org/docs/latest/opensearch/install/compatibility/) page states that OpenSearch 1.0.0 ships with Java 15 but at the same time only lists java 8 & java 11 as being supported in the table below. this is obviously inconsistent and the list should be updated with all supported java versions

**How can one reproduce the bug?**
check the compatibility list on the linked page

**What is the expected behavior?**
the list is complete

**Comment by elfisher** [comment]
@keithhc2 should we just add 15 to the list? @rursprung has a good point here. The paragraph and list don't match.

**Comment by keithhc2** [comment]
I think the original intention was to say that OpenSearch also works with these other Java versions, but yeah, I can add it in after confirming a couple things.

**Comment by elfisher** [comment]
Thx @keithhc2!

**Comment by keithhc2** [comment]
Added with #300. Thanks, @rursprung
