### ISSUE TITLE
[DOC] Fixes graphics links and level 3 headings

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#2884]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Fixes graphics links and level 3 headings across all versions

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Closing this issue as complete.
