### ISSUE TITLE
[BUG]Docker compose example yaml can not run

### ISSUE THREAD

**Issue by qixiangyang** [opensearch-project/documentation-website#2905]
when use the docker compose file as a example to start a opensearch service, it occured an error.
docker compose file name is : Sample Docker Compose file for development

error detail:

[ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [opensearch-node1] uncaught exception in thread [main]
opensearch-node1         | org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [cluster.initial_cluster_manager_nodes] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | Caused by: java.lang.IllegalArgumentException: unknown setting [cluster.initial_cluster_manager_nodes] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
opensearch-node1         | 	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:589) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:530) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:500) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:470) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:161) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.node.Node.<init>(Node.java:463) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.2.3.jar:1.2.3]
opensearch-node1         | 	... 6 more
opensearch-node1         | uncaught exception in thread [main]
opensearch-node1         | java.lang.IllegalArgumentException: unknown setting [cluster.initial_cluster_manager_nodes] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
opensearch-node1         | 	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:589)
opensearch-node1         | 	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:530)
opensearch-node1         | 	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:500)
opensearch-node1         | 	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:470)
opensearch-node1         | 	at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:161)
opensearch-node1         | 	at org.opensearch.node.Node.<init>(Node.java:463)
opensearch-node1         | 	at org.opensearch.node.Node.<init>(Node.java:319)
opensearch-node1         | 	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
opensearch-node1         | 	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
opensearch-node1         | 	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412)
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
opensearch-node1         | 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
opensearch-node1         | 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
opensearch-node1         | 	at org.opensearch.cli.Command.main(Command.java:101)
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
opensearch-node1         | For complete error details, refer to the log at /usr/share/opensearch/logs/opensearch-cluster.log

**Comment by peterzhuamazon** [comment]
Hi @qixiangyang please refer to the docker compose files here at the moment.
The documentation website and project website can only display one version of the docker compose files now.
https://github.com/opensearch-project/opensearch-build/tree/main/docker/release/dockercomposefiles

Thanks.

**Comment by peterzhuamazon** [comment]
See here:
* https://github.com/opensearch-project/project-website/issues/1245

**Comment by qixiangyang** [comment]
@peterzhuamazon Got it
