### ISSUE TITLE
[DOC] Codec type config detail is missing

### ISSUE THREAD

**Issue by mann2108** [opensearch-project/documentation-website#2906]
Data Prepper (S3 Source) Documentation needs to be updated with more clarity. 
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

Currently no reference provided for S3 source configuration, I think dummy json with configuration is a good choice to show, alternatively many problems that I am facing if I just try to refer documentation and implement that by my own.

- codec type reference is not clearly mention as in the Type Codec is mention, but in the example direct string like Json, Newline is given.
- aws type reference is not clearly mention as well, in the example it ask to add region and sts-role-arn? so do I don't need ot configure secret and access keys?

**Comment by Naarcha-AWS** [comment]
@mann2108: Since you've submitted the issue, we've added additional information about the S3 source, including [codecs](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/s3/#codec). Let us know if this meets if needs. If not, please reopen the issue.
