### ISSUE TITLE
[DOC] User found documented docker-compose.yml in official guides doesn't work

### ISSUE THREAD

**Issue by jordarlu** [opensearch-project/documentation-website#2945]
**What do you want to do?**
 
- [ ] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 User found documented docker-compose.yml in official guides (https://opensearch.org/samples/docker-compose.yml ) doesn't work at the time she/he use Docker OpenSearch 1.3.2 and 1.3.0'
( ticket/issue reported by user https://github.com/opensearch-project/opensearch-devops/issues/109 )

With further analysis,  the docker-compose.yml provided at https://opensearch.org/samples/docker-compose.yml works well for Docker OpenSearch 2.x and above.

However, for Docker OpenSearch 1.x to work, there is an `enviroment` key required to be updated in docker-compose.yml - 

for build 1.x : - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
for build 2.x and above : - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/opensearch-devops/issues/109 
I think we may want to let user know if you are using docker OpenSearch 1.x, the `enviroment` key is required to be updated from the provided/sample docker-compose.yml as above..

**Comment by jordarlu** [comment]
There is an ongoing session talking about this .. I am going to cancel this issue I opened .. thanks

**Comment by peterzhuamazon** [comment]
Duplicated with:
* https://github.com/opensearch-project/project-website/issues/1245

**Comment by peterzhuamazon** [comment]
Duplicate with:
* #2905
