### ISSUE TITLE
[DOC] Upgrade documentation NAV positioning 

### ISSUE THREAD

**Issue by setiah** [opensearch-project/documentation-website#2949]
**What do you want to do?**
 
- [x] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

I had a comment on the NAV positioning for this. Right now Upgrades seem to be under the “Install and Configure” tab on the website ([Upgrading OpenSearch](https://opensearch.org/docs/latest/install-and-configure/upgrade-opensearch/index/) ), while there is another tab called “Upgrades to OpenSearch”. This causes confusion as there are two separate places that talk about the upgrades. I propose we create a new tab called “Upgrade” or “Upgrade Procedures” and move all aspects of upgrades under that parent tab. With this, the existing Upgrades to OpenSearch tab which is focussed on Elasticsearch to OpenSearch upgrade will also move under this parent tab as shown below. See - 

Upgrade Procedures
* Upgrading OpenSearch Minor version
* Upgrading OpenSearch Major version
* Upgrading from Elasticsearch to OpenSearch

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
We need to reconfigure that section asap! I want to make sure people are finding the most current information.

The original high-level proposal was this:

**Install and Configure**
  Installing OpenSearch
  Installing OpenSearch plugins
  Configuring OpenSearch
  Installing OpenSearch Dashboards
  Installing Dashboards plugins
  Upgrading OpenSearch
  Migrating OpenSearch
  
...with everything under the Install and Configure heading. 

We can certainly rethink that, but in the meantime, we need to understand what from the original content we can keep. At one point we discussed changing the title of the current one to "Migrating to OpenSearch" as that was more applicable. That would be a quick fix. Thoughts??

**Comment by setiah** [comment]
I was thinking something like below structuring. This way we could keep "install and configure" section as it was prior to adding upgrade section in there and add a dedicated section for Upgrade for easy discovery. In the example below i also have renamed current "Upgrade to OpenSearch" to "Migrate to OpenSearch" that talks about moving from other techs to OpenSearch. Let me know how you think about this structuring.

- Install and Configure
    - Installing OpenSearch
    - Installing Dashboards
    - Installing Plugins , etc.
- Upgrade 
    - Upgrade Procedures
        - Platform specific upgrades
    - Breaking changes
- Migrate to OpenSearch 
    - Migrate from OSS Elasticsearch to OpenSearch
    - Migrate from ODFE to OpenSearch
    - Migrate from OSS Kibana to OpenSearch Dashboards
    - Migrate from Elastic Cloud to OpenSearch.

**Comment by hdhalter** [comment]
Here is the proposed structure: 

Install **and Upgrade OpenSearch** (Change from Install and Configure)

-    Installing OpenSearch
-    Installing Dashboards
-    **Upgrading OpenSearch**
-    Configuring OpenSearch
-    Installing Plugins

   
**Migrating to OpenSearch** (Change from Upgrading to...)
- About the process
- Using snapshots to migrate data
- **Migrating from** Elasticsearch OSS to OpenSearch / (add to previous topic - **Migrating** Docker clusters to OpenSearch
- **Migrating from** Kibana OSS to OpenSearch Dashboards

@sumobrian - Are you ok with this? Himanshu approves.

**Comment by JeffH-AWS** [comment]
I like the proposal posted by @hdhalter above. My only concern, though, is with moving the Breaking Changes section to live under a ToC heading - so people wouldn't see it by default, they would need to go looking.

Currently the docs page displays Breaking Changes at the top of the ToC when you navigate to it.

**Comment by sumobrian** [comment]
> Here is the proposed structure:
> 
> Install **and Upgrade OpenSearch** (Change from Install and Configure)
> 
> * Installing OpenSearch
> * Installing Dashboards
> * **Upgrading OpenSearch**
>   --  Rolling Upgrade
>   -- Breaking Changes
> * Configuring OpenSearch
> * Installing Plugins
> 
> **Migrating to OpenSearch** (Change from Upgrading to...)
> 
> * About the process
> * Using snapshots to migrate data
> * **Migrating from** Elasticsearch OSS to OpenSearch / (add to previous topic - **Migrating** Docker clusters to OpenSearch
> * **Migrating from** Kibana OSS to OpenSearch Dashboards
> 
> @sumobrian - Are you ok with this? Himanshu approves.

This change looks good to me but I think "Breaking Changes" needs to be viewable from the ToC. The reason is that this is often the primary section people are interested in when making the decision to upgrade. Perhaps it should be called "Breaking Changes when Upgrading"?

**Comment by hdhalter** [comment]
Sounds good. We will leave Breaking Changes where it is, and change the name. Thanks so much.

**Comment by hdhalter** [comment]
The TOC changes are merged. The only thing remaining is to combine the two files: Migrating from Elasticsearch OSS to OpenSearch and Migrating Docker clusters to OpenSearch. I'll create a new issue for that.
