### ISSUE TITLE
[PROPOSAL] Host unreleased versions of the docs site

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/documentation-website#296]
## What kind of business use case are you trying to solve? What are your requirements?

We have: https://opensearch.org/docs/1.2/dashboards/index/ which only came out for the 1.2 release. But when we bump our version for OpenSearch Dashboards, we would have to point to an older version of docs even thought the branches are accessible to the public.

**What is the problem? What is preventing you from meeting the requirements?**

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/package.json#L15 is used by the docs service to point the links internally to the correct version of docs. For branches if we don't want potential 404s then we need to point older version of the docs or latest.

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**

Host the next upcoming release docs with some indication that it's unreleased so that we can point branches to that version for it's intended release.

**What are your assumptions or prerequisites?**

none

**What are remaining open questions?**

How to ensure not to make people confused for latest being "latest released".

**Comment by seanneumann** [comment]
Can we get this bumped up in priority?

**Comment by kavilla** [comment]
Another issue: https://github.com/opensearch-project/documentation-website/blob/main/_clients/javascript.md

The NPM client is currently on `1.0.2` but main points https://opensearch.org/docs/latest/clients/javascript/ which points to https://opensearch.org/docs/1.2/clients/javascript/. This would confuse me because I would assume that I am reading the docs for JS client version `1.2.x`.

**Comment by hdhalter** [comment]
@kavilla - can you please clarify? Is this still an issue? Thanks!

**Comment by kavilla** [comment]
> @kavilla - can you please clarify? Is this still an issue? Thanks!

@hdhalter yes I would assume so.

To clarify any documentation links added inline to components that don't exist in a previous release will basically be dead links. Take vis builder for example. Developers can't really include code that referenced: https://opensearch.org/docs/latest/dashboards/visualize/visbuilder/ until the version was released because the doc site only gets updated upon version release.

So if there was any code reference to the this link, developers would have to be okay with the 404 and re-route to so default route and verify on the day of release.

If the doc site followed the branching strategy that allowed for documentation to be hosted prior to release then in-application links to new docs can be verified prior to the day of release.

**Comment by hdhalter** [comment]
Hi @kavilla - I'm marking this as 'wontfix' due to having no bandwidth for fixing anything related to our branching strategy. If we move to a different architecture for our docs, we may be able to do something to solve this, but until then, I'm going to close this issue. In the meantime, if you come up with an easy solution and resources to apply it, please let me know. Thanks!
