### ISSUE TITLE
[DOC] Client Side Encryption in OpenSearch

### ISSUE THREAD

**Issue by vikasvb90** [opensearch-project/documentation-website#2995]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 
We need to add a description for a new plugin which will provide support for client side encryption in OpenSearch. This is a placeholder issue and doc content will be updated later.

**What other resources are available?**
Link to the feature proposal : https://github.com/opensearch-project/OpenSearch/issues/6353

**Comment by Naarcha-AWS** [comment]
Adding both Chris and Fanit since this could fit either security or client documentation.

**Comment by kolchfa-aws** [comment]
@Naarcha-AWS I don't think this is specific to clients. I think this relates to encryption of data on the client side for OpenSearch in general.

**Comment by cwillum** [comment]
Development team is currently refining the plugin for OpenSearch applications. No documentation needed for 2.10.

**Comment by hdhalter** [comment]
Hi @vikasvb90 , is this doc issue still relevant or should I close it? Is it related to https://github.com/opensearch-project/OpenSearch/issues/5800?

**Comment by vikasvb90** [comment]
We can close this. Thanks @hdhalter !
