### ISSUE TITLE
Documentation Update for Security Plugin

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/documentation-website#30]
We need to update Security plugin API path and settings.

- APIs are stilling using "opensearch", for [example](https://docs-beta.opensearch.org/docs/security/access-control/api/). We should use "plugins". The changes are in [this PR](https://github.com/opensearch-project/security/pull/1172).
- Settings need to be renamed to reflect the new names, for [example](https://docs-beta.opensearch.org/docs/security/configuration/client-auth/#enabling-client-certificate-authentication). The changes are in [this PR](https://github.com/opensearch-project/security/pull/1184/files).

**Comment by aetter** [comment]
I'm hopeful that I caught everything here: https://github.com/opensearch-project/documentation-website/commit/c4cf6838bf8bfd6264a914d07fa71cb8a6c0a855
