### ISSUE TITLE
[DOC] Wrong property in example opensearch_dashboards.yml

### ISSUE THREAD

**Issue by JeffH-AWS** [opensearch-project/documentation-website#3015]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
On page: https://opensearch.org/docs/1.3/install-and-configure/install-dashboards/tls/

The sample code includes:
```
opensearch.requestHeadersAllowlist: [ authorization,securitytenant ]
```

However this property didn't exist in 1.x - it should be:

```
opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by vagimeli** [comment]
Resolved with PR https://github.com/opensearch-project/documentation-website/pull/3019/
