### ISSUE TITLE
[DOC] Security analytics - New log types, detector dashboards, support multiple indexes as detector data source

### ISSUE THREAD

**Issue by kamingleung** [opensearch-project/documentation-website#3018]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 In 2.6, Security analytics will introduce the following enhancements:
- Support 5 new log types for detectors: ~Google Workspace event logs, Github event logs, Okta authentication logs, Microsoft 365 event logs.~  Google Workspace logs, Github actions, Microsoft 365 logs, Okta events, Azure logs
- Detectors support multiple indexes or index patterns as log sources
- ~When users create a VPC flow logs detector, S3 access logs detector, or CloudTrail log source detector, an Overview dashboard will be created for that detector.~  (A focus for next release)
- Renaming of *Default field mapping* table to *Automatically mapped fields*.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Support multiple indexes on create detector:
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/419
Overview dashboard on detector create:
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/14

**Comment by hdhalter** [comment]
@cwillum - do you have enough information to document this for 2.6 or do we need to push out the release?

**Comment by cwillum** [comment]
@hdhalter Requirements have changed following the demo yesterday. I'm checking in with Security Analytics now to see exactly what features are being included for 2.6.
@opensearch-project/security-analytics

**Comment by cwillum** [comment]
First PR for these changes is #3066.
There are additional features that need to be documented for 2.6. A second PR is in process.

**Comment by cwillum** [comment]
Closing after merging both PRs attached to this issue.
