### ISSUE TITLE
[DOC] Images broken in Visualization page

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#3060]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 On this page: https://opensearch.org/docs/1.3/dashboards/visualize/viz-index/ there are several broken images. The images are fine in 2.0 and later.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
This came in as direct feedback on the documentation website.

/docs/1.3/dashboards/visualize/viz-index/ 
broken images 
no
Australia

**Comment by kolchfa-aws** [comment]
@hdhalter It's just an image that's missing in the 1.3 version

**Comment by hdhalter** [comment]
More feedback on 3/3/23 about broken images.

**Comment by vagimeli** [comment]
PR https://github.com/opensearch-project/documentation-website/pull/2902
