### ISSUE TITLE
[DOC] ML Extensibility Phase1:  ML Inference Endpoint Connectors

### ISSUE THREAD

**Issue by sean-zheng-amazon** [opensearch-project/documentation-website#3063]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
see feature details in: https://github.com/opensearch-project/ml-commons/issues/746, targeting 2.8

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by ylwu-amzn** [comment]
@Naarcha-AWS From PenTest team , we should highlight that all variables in "parameters" block can be overridden in predict request. If user want to keep the variable value immutable, they should hard code the value in body template, rather than put into parameter block.

**Comment by ylwu-amzn** [comment]
From PenTest, we should enforce customer to provide a masterKey for encrypt their credentials. ml-commons provides a new system setting which user can update that to change their encryption key: `plugins.ml_commons.encryption.master_key`
