### ISSUE TITLE
[DOC] incorrect REST API example in _cat/indices 

### ISSUE THREAD

**Issue by vikansal** [opensearch-project/documentation-website#3067]
**What do you want to do?**
 
- [ x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
https://opensearch.org/docs/1.2/opensearch/rest-api/cat/cat-indices/ page refers to _cat/aliases instead of _cat/indices for the example to use multiple indices 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

NA

**Comment by hdhalter** [comment]
Thanks for reporting this issue, @vikansal! We are no longer supporting the 1.2 version of the OpenSearch documentation, but it has been fixed in 1.3 and later versions.
