### ISSUE TITLE
[BUG] OpenSearch version switcher does not work in Safari

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/documentation-website#307]
**What is the bug?**

The OpenSearch version switcher in the documentation does not work in Safari. The drop-down appears, but it will not change versions.

**How can one reproduce the bug?**
1. Load Safari
2. Go to [https://opensearch.org/docs/latest/](https://opensearch.org/docs/latest/)
2. Click on the version switcher. Currently labeled 'OpenSearch 1.2.x'
3. Select another version
4. Nothing happens

**What is the expected behavior?**

The version should change.

**What is your host/environment?**
 - OS: macOS 11.6.1
 - Safari Version 15.1

**Comment by elfisher** [comment]
I can verify the same issue using the following environment: 

OS: macOS 10.15.7
Safari: 15.1

**Comment by dlvenable** [comment]
This fix works for me. Thanks @AMoo-Miki!
