### ISSUE TITLE
[BUG] It is not clear, where the config.yml of "OpenID Connect" plugin should be located

### ISSUE THREAD

**Issue by zemiak** [opensearch-project/documentation-website#309]
**What is the bug?**
The documentation of OpenID configuration specifies a content for `config.yml`. However, I cannot find anywhere, where to put this file so it's picked up by the plugin.

**How can one reproduce the bug?**
1. Go to 'https://opensearch.org/docs/latest/security-plugin/configuration/openid-connect/'
2. Go to the bottom of the page, chapter "OpenSearch security configuration"
3. You can see a reference to `config.yml` but not the file path

**What is the expected behavior?**
Specify something like `/usr/share/kibana/plugins/openid/config.yml` for Dashboards or `/usr/share/elasticsearch/plugins/openid/config.yml` for OpenSearch

Thank you!

**Comment by keithhc2** [comment]
Hey @zemiak, thanks a bunch for writing in. In regards to `config.yml`'s file path, the security plugin's configuration files are all within the `securityconfig` folder, and the file path `/usr/share/opensearch/plugins/opensearch-security/securityconfig`.  https://opensearch.org/docs/latest/security-plugin/configuration/configuration/ has a more introductory look at customizing your own backend configurations, so we recommend taking a look at that first.

If you have any other questions, feel free to reach back out!

**Comment by zemiak** [comment]
Thank you very much for your help :-)
