### ISSUE TITLE
[DOC] Address issues with page - dashboards/dql

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#3094]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The dashboards/dql page is highly unliked - 78% visitors across version 1.3 and latest (2.5) dislike it. We don't have any comments to help understand the issue, so we need to try to figure out what is wrong. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://opensearch.org/docs/latest/dashboards/discover/dql/

**Comment by hdhalter** [comment]
Hi Melissa, we received more feedback on this page: /docs/1.3/dashboards/dql
"what about double quotes? I wanted to search for *"ERROR"*"

**Comment by vagimeli** [comment]
> @hdhalter 
This content was originally written by an SME before I joined the team. The Dashboards team worked with me to refresh it in v 2.4, and it went through a technical review with a developer. We tested the steps and they worked for both the developer and me. I'll reach out to the developer about double quotes. Do we have specific feedback from the users that I can share with the developer?

**Comment by vagimeli** [comment]
In looking at 1.3 content, it isn't the refreshed content. I'll confirm with the developer that we can backport the refreshed content to 1.3. See latest documentation https://opensearch.org/docs/2.6/dashboards/discover/dql/

**Comment by vagimeli** [comment]
Per devs, we can backport the refreshed content to 1.3. The refreshed content should address the external feedback.

**Comment by hdhalter** [comment]
Thanks, @vagimeli ! I'll keep an eye on the feedback numbers and watch for new trends.
