### ISSUE TITLE
[DOC] Proxy-based auth in dashboard

### ISSUE THREAD

**Issue by tciops** [opensearch-project/documentation-website#3102]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 If i provide a config like you suggest:
`opensearch.requestHeadersAllowlist: ["securitytenant","Authorization","x-forwarded-for","x-proxy-user","x-proxy-roles"]` 
I get an error: `FATAL  Error: [config validation of [opensearch].requestHeadersAllowlist]: definition for this key is missing`

I think the right name for this parameter is: `opensearch.requestHeadersWhitelist`
All the docs describing proxy-based auth that I checked so far are giving this
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
@tciops: Which version of OpenSearch are you using?

**Comment by tciops** [comment]
Let see several version of [this documentation page](https://opensearch.org/docs/latest/security/authentication-backends/proxy/)
I wen back to any of v1.x  to find `...WhileList`
v2.0 and newer say `....AllowList`
But my opensearch installed from RPM is v2.5 (as you can see below) still uses `WhiteList`
```
$ rpm -qa | grep opensearch
opensearch-2.5.0-1.x86_64
opensearch-dashboards-2.5.0-1.x86_64
```
Can you verify this?

**Comment by hdhalter** [comment]
I believe both will be accepted in 2.x. @scrawfor99  - Can you please confirm that this is correct for 2.5? Is there something else wrong with the sample config?

**Comment by scrawfor99** [comment]
@hdhalter that is correct. For 2.x both terms are usable. We obviously advise the use of the inclusive terminology but usage of the previous terminology will still work for the 2.x line. It _will not_ work once we reach 3.0

**Comment by hdhalter** [comment]
I'm going to close this issue since the parameter should not have caused the problem. @tciops, if you experience other issues, please don't hesitate to reach out. Thanks!
