### ISSUE TITLE
[DOC] Update TOC for Observability

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#3129]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 As we are working on the TOC, in general, for OpenSearch, we should make any appropriate changes to the Observability section. It looks like this today: 
<img width="199" alt="image" src="https://user-images.githubusercontent.com/104463754/222010620-ea3af5a2-f125-477f-8be7-c47ca0813efd.png">

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
Closing in favor 4167
