### ISSUE TITLE
[DOC] SSO is an overloaded term and we should rename Simple Schema for Observability

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/documentation-website#3130]
**What do you want to do?**
 
- [X] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We have abbreviated [Simple Schema for Observability](https://opensearch.org/docs/latest/observing-your-data/sso/
) to SSO. The issue is SSO is already a very well established abbreviation for single sign on even within the OpenSearch space [[source](https://www.google.com/search?q=sso+opensearch)]. We should update the acronym to be something not so overloaded. 
 
To make it more straightforward I have several suggestions here. Please vote by reacting with the appropriate emoji. If you have another idea please leave it in a comment below and we will vote on it by leaving 👍 emojis. 😊

React for:
🚀 - SiSO
🎉 - SS4O
❤️ - SSFO

**Comment by lukas-vlcek** [comment]
Even our band is called SSO (Sunny Summer Orchestra) 🎹 🎸 🎻 🎺 🎷 🥁 🎙️

**Comment by dtaivpp** [comment]
@lukas-vlcek at least that is in a different domain though. Hopefully no one comes to your shows looking for a lecture on authentication and authorization 🤣

**Comment by AmiStrn** [comment]
I vote for no acronym. It's confusing when reading code, and saying it out loud could be shortened to "simple schema". 

Elasticsearch has ECS which is confusing already if you are using amazon ecs...

**Comment by hdhalter** [comment]
I agree with Amitai - I don't think we should introduce an acronym here when simple schema is an appropriate term.
