### ISSUE TITLE
[DOC] Ability to view Maps from Saved Objects

### ISSUE THREAD

**Issue by naveentatikonda** [opensearch-project/documentation-website#3142]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Dashboards-Maps users should be able to open map which is in the list of saved objects and explore it from the saved objects panel(Stack Management -> Saved Objects)
 Related Github Issue - https://github.com/opensearch-project/dashboards-maps/issues/212

**Comment by naveentatikonda** [comment]
Please add a v2.8 tag

**Comment by vamshin** [comment]
Moving this feature to 3.x
