### ISSUE TITLE
[BUG] Use IndicesCreateRequest in example doc

### ISSUE THREAD

**Issue by forstmeier** [opensearch-project/documentation-website#316]
**What is the bug?**
I'm pretty sure that `IndicesCreateRequest` should be used in the "create index" example where `CreateRequest` is currently used.

**How can one reproduce the bug?**
Following the example and using `CreateRequest` results in an error if you're trying to create an _index_.

**Comment by keithhc2** [comment]
Hey @forstmeier, I'm assuming this is about one of the client pages? Can you clarify which specific client you're referring to?

**Comment by forstmeier** [comment]
Hi @keithhc2, yes, it is. It's in the [Go client example code](https://opensearch.org/docs/latest/clients/go/#sample-code) where it says `// Create an index with non-default settings.`.

**Comment by ashwinkumar12345** [comment]
Thanks, done - https://github.com/opensearch-project/documentation-website/pull/320
