### ISSUE TITLE
[DOC] Building data visualizations page on 1.3 is broken

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/documentation-website#3168]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
The Building data visualizations page on the 1.3 version is missing many of the images. i.e. broken images. 

![Screenshot 2023-03-01 at 5 46 53 PM](https://user-images.githubusercontent.com/20453492/222309605-a2567451-d319-4f9f-b249-d3eac91853a0.png)

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by vagimeli** [comment]
@ashwin-pc Resolved issue. See PR https://github.com/opensearch-project/documentation-website/pull/3231/files
