### ISSUE TITLE
[DOC] Admin UI panel for composite index templates

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/documentation-website#3195]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Index management dashboard version >= 2.7 will be affected. The dashboard will provide pages to manage all the composite templates in users' cluster and a new section to help to simulate index templates composed of composite index templates.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
[#548](https://github.com/opensearch-project/index-management-dashboards-plugin/issues/548)
[#496](https://github.com/opensearch-project/index-management-dashboards-plugin/issues/496)

**Comment by ariamarble** [comment]
@SuZhou-Joe is there a dev environment for index templates so that we can test the feature? Are there any demo presentations? Is there a feature brief we can review etc?

**Comment by vagimeli** [comment]
@SuZhou-Joe Do you have a feature brief, demo, and dev environment for this feature? Who is the target end user for the documentation? What are the benefits of this feature to the users?

**Comment by SuZhou-Joe** [comment]
> @SuZhou-Joe is there a dev environment for index templates so that we can test the feature? Are there any demo presentations? Is there a feature brief we can review etc?

1. Yes, http://dev-dsk-suzhou-2a-f21025f7.us-west-2.amazon.com/v2.7/app/opensearch_index_management_dashboards#/composable-templates?from=0&search=&size=20&sortDirection=desc&sortField=name
2. Yes, the demo gif is posted.
![test-template](https://user-images.githubusercontent.com/13493605/224888857-ab126e39-5fe4-4c81-8c62-2c110b31af82.gif)
3. Nope, it's a enhancement to existing features and you can find the feature brief for index template: https://quip-amazon.com/I1zAAYDHQQsP/Admin-UI-Index-OperationsOpenSearch-Feature-Brief

**Comment by SuZhou-Joe** [comment]
> @SuZhou-Joe Who is the target end user for the documentation? What are the benefits of this feature to the users?

As we generally create a [new documentation(user guide)](https://opensearch.org/docs/latest/dashboards/im-dashboards/index/) to our new features, so we think it is needed for this feature as well.

1. The admins who are using our admin panel to manage their cluster.
2. Instead of creating index template from scratch, users can create index templates by assembling [component templates](https://opensearch.org/docs/latest/im-plugin/index-templates/#composable-index-templates).

**Comment by vagimeli** [comment]
@ariamarble remains the primary point of contact on this feature; @vagimeli is supporting writing efforts
