### ISSUE TITLE
[DOC] Feedback on Docker compose example in 1.3 

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#3201]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Feedback from community about the docker compose example in 1.3 documentation: 

the docker compose example is for the latests version, not the 1.3 version I'm reading about here

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Here's a link to the page: https://opensearch.org/docs/1.3/install-and-configure/install-opensearch/docker/

**Comment by hdhalter** [comment]
Hi Jeff, can you please confirm the validity of this feedback? thanks!

**Comment by JeffH-AWS** [comment]
The version in the code block isn't parameterized because the reader is directed to customize the contents before using it.

There's a big disclaimer on the page:

```
To download a specific version of OpenSearch or OpenSearch Dashboards other than the latest available version, modify the image tag where it is referenced (either in the command line or in a Docker Compose file). For example, opensearchproject/opensearch:1.3.8 will pull OpenSearch version 1.3.8. Refer to the official image repositories for available versions.
```
