### ISSUE TITLE
[PROPOSAL] Add schema_version definition to ISM API documentation

### ISSUE THREAD

**Issue by David-Elizondo** [opensearch-project/documentation-website#321]
Planning on using schema_version as a way to detect policy changes within CI/CD. I'd like to use this attribute as an indicator to PUT new versions of policies on the ISM API with an updated SEQ NO into Opensearch. 

I could not find a definitive definition to what "schema_version" is used for within Opensearch within the documentation and whether this is an improper use of this attribute. 

Within the testing source code here: [OpenSearch Test Code](https://github.com/opendistro-for-elasticsearch/index-management/blob/aca99cf1718c945669d5b169e22e587b4be6e808/src/test/kotlin/com/amazon/opendistroforelasticsearch/indexmanagement/IndexManagementIndicesIT.kt#L30). The comment eludes to this value being used to rollover the index policy under the hood.  We create a description to this attribute and define it on the documentation.

My assumption is that we use this value to track new version internally to mark changes to policies and update them as necessary

**Comment by ashwinkumar12345** [comment]
Yes, schema_version represents the number of times you update a policy.
