### ISSUE TITLE
[DOC] Feedback on Time Filter page

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#3219]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We received feedback 2/28/23 on this page: https://opensearch.org/docs/latest/dashboards/discover/time-filter/

"Calendar icon does not exist on new "Discover" option."

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by vagimeli** [comment]
@hdhalter Do you know the context of this issue? The calendar icon shows in Discover on both the playground and localhost:5601. Do you know what version of OpenSearch Dashboards the user is using? The following image shows the calendar icon in Discover i
<img width="1914" alt="Screenshot 2023-03-06 at 3 10 18 PM" src="https://user-images.githubusercontent.com/105296784/223251622-ac08f3b7-eeff-4674-9b9c-15e118644d96.png">
n OpenSearch Dashboards v 2.5.

**Comment by hdhalter** [comment]
Hi Melissa, thanks for looking into this. I don't have any additional information. It could be that the user couldn't find it? 

The one thing we can do proactively is update the instructions in the documentation. For example instead of starting with "Select the calendar icon", we provide more context in the steps themselves (From Dashboards, select Stack Management > Advanced Settings...), in case the user is coming straight here and wants to quickly perform this task.

**Comment by hdhalter** [comment]
Thanks, @vagimeli !
