### ISSUE TITLE
[BUG] security plugin multi-tenancy docs incorrect about index

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/documentation-website#322]
**What is the bug?**
https://github.com/opensearch-project/documentation-website/blob/main/_security-plugin/access-control/multi-tenancy.md#manage-opensearch-dashboards-indices

We got the green light to utilize functional (under the hood) stuff from legal. Therefore, the index is actually `.kibana` and all the tenants use some variation `.kibana_<hash>_<tenant_name>`.

**What is the expected behavior?**
Docs should reflect actual index name.

**Do you have any additional context?**
Do we need historical context as well? People might think `.kibana` is random. But it was kept in-place for the security plugin.

**Comment by keithhc2** [comment]
Closed with #328
