### ISSUE TITLE
[DOC]Anomaly Detection Extension - GA

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/documentation-website#3242]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We are working on launching Anomaly Detection backend plugin to extension. Meta issue tracking this is https://github.com/opensearch-project/OpenSearch/issues/5224. Target GA is 2.9. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
The SDM is Minal Shah (@minalsha ) and the SDE is Dan Widdis (@dbwiddis).

**Comment by vagimeli** [comment]
Per SDE, on hold
