### ISSUE TITLE
[DOC]Release Extensions with Version decoupling feature as Experimental feature

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/documentation-website#3243]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Release extensions support as an experimental release in OpenSearch 2.x line. Meta issue tracking this: https://github.com/opensearch-project/opensearch-sdk-java/issues/139. We are targeting 2.8 for experimental release. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
The SDM is Minal Shah (@minalsha ) and the SDE is Sarat Vemulapalli(@saratvemulapalli ).

**Comment by minalsha** [comment]
@ryanbogan  believe you are working on documentation with Docs team. Correct me if i am mistaken?

**Comment by ryanbogan** [comment]
@minalsha Yes, I am following up on action items following meetings with @kolchfa-aws
