### ISSUE TITLE
Improve OpenSearch ISM documentation 

### ISSUE THREAD

**Issue by srakshit** [opensearch-project/documentation-website#329]
The OpenSearch ISM documentation doesn't clearly explain that only one transition is checked and only one action is performed in each cycle.

For transitions, if you defined -> transitions: [A, B, C, D] ISM will go through this list sequentially and find the first transition that evaluates to true and transition to the given state in that transition and then goes to sleep before checking the 2nd transition.

For actions if you defined -> actions : [A, B, C, D], ISM will execute A then go to sleep, come back and execute B then go to sleep, etc.

It goes a bit further, some actions are split into multiple steps and each execution only executes a single step, but a lot of actions are a single step so it's not noticeable.
e.g. force merge action is split into 3 steps -> Set index to read only, call force merge, validate force merge finished. So 3 cycles are required to complete the whole force merge operation.

**Comment by ashwinkumar12345** [comment]
Added to the docs - https://github.com/opensearch-project/documentation-website/pull/383
