### ISSUE TITLE
License statement on the website

### ISSUE THREAD

**Issue by nemobis** [opensearch-project/documentation-website#33]
The sidebar at https://docs-beta.opensearch.org/ states:

> © Amazon Web Services, Inc. or its affiliates. All rights reserved.

That doesn't align with the license statement here. AFAIK no SLA is required, so you'll need something like:

> © OpenSearch contributors, 2021. Released under <a rel="license" href="https://www.apache.org/licenses/LICENSE-2.0">Apache License 2.0</a>.

The README is also less than clear:

> Copyright Amazon.com, Inc. or its affiliates. All rights reserved.

**Comment by aetter** [comment]
Hi nemobis, I'll check with our legal team on this.

**Comment by aetter** [comment]
Thanks a bunch, nemobis, made some changes.
