### ISSUE TITLE
[BUG] delete_by_query documentation - running asynchronously option is not documented

### ISSUE THREAD

**Issue by oridool** [opensearch-project/documentation-website#331]
**What is the bug?**
It's not clear whether OpenSearch supports running the asynchronous option as described by :  
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html#docs-delete-by-query-task-api 

The option is not described, but when I technically tried it on my cluster and set `wait_for_completion=false`, it looks like it was working and a new task was created.

**How can one reproduce the bug?**
1. Go to 'https://opensearch.org/docs/latest/opensearch/rest-api/document-apis/delete-by-query/'
2. See that there is no reference for `wait_for_completion=false` or any reminder that query can be executed asynchronously.

**What is the expected behavior?**
Clear documentation about this subject and how asynchronous execution works.

**What is your host/environment?**
 - Version: AWS OpenSearch (7.10.2)

**Comment by keithhc2** [comment]
Thanks a bunch for reporting, @oridool. We've added `wait_for_completion` back in with #334. Feel free to reach back out if anything's missing!
