### ISSUE TITLE
Windows 11 Docker setup documentation incorrect

### ISSUE THREAD

**Issue by nurbq** [opensearch-project/documentation-website#3348]
Documentation says that for Windows users in docker preferences we should set RAM minimum 4GB, but I changed this manually with wsl changing vm.max_map_count to at least 262144.
1. First I installed wsl with Ubuntu backend
2. With wsl terminal added following line to /etc/sysctl.conf:
vm.max_map_count=262144
3. Then with "sudo sysctl -p" command reloaded.

**Comment by hdhalter** [comment]
Closed by https://github.com/opensearch-project/documentation-website/pull/5077
