### ISSUE TITLE
[UI copy] Request for Navigation tool tips

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/documentation-website#3351]
Related to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3573 

The navigation isn't properly labeled with tool tips and UI copy help would be appreciated. 

- [ ]  The three horizontal bars represents "Menu" - Unsure if "Menu", "Show/Hide menu", "Toggle menu" or something else is best
- [ ] The life-bouy (outdated, UX team is revising it) icon represents "Help". In the Help menu there are also links to connect to the community (Forums, GitHub). Unsure "Help" is sufficient or if we might want to label it something more inclusive of the other links. 

 @JeffH-AWS & @kolchfa-aws - would love your thoughts

**Comment by kolchfa-aws** [comment]
@KrooshalUX My thoughts:
We've been calling the three horizontal lines "top menu" and I think it works well.
Lifebuoy: My vote is for "life ring". We want to call the icons by how they appear to the user. For example, we've been calling the icon that brings up settings "the wrench icon" because that's what it looks like. In this case, "lifebuoy" might not be as understandable for global users, but "life ring" intuitively implies that it would look like a circle.

**Comment by kolchfa-aws** [comment]
For the tooltips, we can use "Help" for the life ring icon. The only other instance where I saw an icon without text is the wrench icon in DevTools, where it brings up a menu to copy as cURL, auto indent and open documentation. I'm not sure it adds value to add a tooltip there, and it's not easy to name them as a group since these are not very related. Maybe "Tools"?

**Comment by KrooshalUX** [comment]
> @KrooshalUX My thoughts: We've been calling the three horizontal lines "top menu" and I think it works well. Lifebuoy: My vote is for "life ring". We want to call the icons by how they appear to the user. For example, we've been calling the icon that brings up settings "the wrench icon" because that's what it looks like. In this case, "lifebuoy" might not be as understandable for global users, but "life ring" intuitively implies that it would look like a circle.

The names of the icons already have been determined here: https://oui.opensearch.org/1.0/#/display/icons - this is from a forked design system. We wont be able to change the name of the actual icons until we do a redesign of the icons and deprecate the old ones. For clarity, the life ring/ life bouy is already called "Help" in the component library. To clarify- I was using the life bouy / ring terminology to relate back to the original issue raised by @JeffH-AWS .

------- 

As for the tool tip request, this is just for the header navigation for the application , you can see that there aren't tool tips on the navigation except for "home". You can try it at playground.opensearch.org 

<img width="1790" alt="Screen Shot 2023-03-09 at 10 07 42 AM" src="https://user-images.githubusercontent.com/105819041/224207486-dbf750b1-290d-450d-9cdf-0e61b7652beb.png">

**Comment by Naarcha-AWS** [comment]
Chiming in here. An unoriginal thought perhaps, but I think that matching the name of the icon with the function of the UI element, for example the "Lifebuoy" icon appears as "Help" in the documentation and tooltips, seems to be the cleanest direction and should suffice for most icons. Of course, the icon names and their functions might not always match. In this case, we should try and sum up the function of the icon within the context of the UI. For example, if the "Beaker" icon appears in the Machine Learning Dashboard (it doesn't, but using it for the sake of illustration), a tool tip saying "Train model" or "Test model" could appear.  

As far as the icons and their names are concerned, like changing the buoy icon to something more inclusive, that should be a Dashboards and OUI decision, with documentation following your lead.

**Comment by Naarcha-AWS** [comment]
@KrooshalUX: Does OUI currently have any tooltip text conventions? If not, we should craft some.

**Comment by KrooshalUX** [comment]
@Naarcha-AWS at this point in time I think things are getting a little confused in this issue. To reiterate, lifebouy isn't being used anywhere except in this conversation, because someone asked what it was representing, the shape was not familiar to them. I am 100% aligned to the use in the UI = the icon name, which in these cases, it already does (home is home, help is help, etc). 

The request here is just for tool tips for the navigation - I figure it could be as simple as "Menu" and "Help" but wanted to verify that we have agreement with that or if we want to use any additional copy like "toggle menu" "show/hide menu" etc.

**Comment by kolchfa-aws** [comment]
I think the shorter the tooltip the better, so I would use "Help" and "Home". I don't think menu requires a tooltip because this symbol is widespread at this point, but if we need one, I vote for "Menu"

**Comment by kolchfa-aws** [comment]
Also tagging @natebower on this

**Comment by KrooshalUX** [comment]
Thanks all. Closing this out and updating the related ticket.
