### ISSUE TITLE
[DOC] Alerting API - GET Alerts endpoint Documentation lacks query parameters that it already supports

### ISSUE THREAD

**Issue by brookatlas** [opensearch-project/documentation-website#3368]
**What do you want to do?**

- [ ] Request a change to existing documentation
- [X ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

** Tell Us about the problem? **

Opensearch version used: 2.3 - (latest amazon currently allows on the managed service)
platform: AWS Managed opensearch

We have recently started using opensearch as a log and obversabillity platform in our startup.

I found the alerting API documentation somewhat lacking.
in the GET alerts endpoint, I had a problem.
while trying to "stitch" the alerting API with pagerduty using an AWS Lambda(managing lifecycle for acknowledging and formatting messages properly) , I needed to find the alert via the API(using mustache to get the alert ID in the SNS event), and then acknowledge it, and passover the responsibllity for pagerduty.

however, the problem was that I could not find the alert that was triggered. breaking my head through the API, after a couple hours I went to the source code, realizing that many query params that are used in the UI and in the actual rest handler itself, are not seen in the documentation.

in the alerting codebase, under the following path:
alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetAlertsAction.kt

from line 51-59, I can clearly see that there are quite many query params that can be used.

![image](https://user-images.githubusercontent.com/54084624/224172015-5044ca6b-a729-454e-a312-86e69ad7746b.png)

for me, alertState and sortOrder solved the problem.

I would love it if it could be my first contribution to open source.

for this issue, I guess adding all of the different parameters and adding a description about them would suffice.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by brookatlas** [comment]
added a proposal draft PR that you may review or look at, if you find it relevant. it is my first time contributing to open source projects. I will be happy to change/fix everything needed for it to go through, if you find it important.

https://github.com/opensearch-project/documentation-website/pull/3380

**Comment by Naarcha-AWS** [comment]
@brookatlas: I'll take a look at your draft PR.

**Comment by hdhalter** [comment]
Thanks for submitting this PR, @brookatlas and so sorry for the delay. I added some comments with the missing parameters and fixed the formatting according to our API template. I'm having the doc team review it to make sure the formatting is correct. We still need some descriptions there. I'll see if I can get a developer to review, or feel free to add more input. Thanks, again!

**Comment by brookatlas** [comment]
seems ok
