### ISSUE TITLE
[DOC] incorrect reference to dynamic_templates?

### ISSUE THREAD

**Issue by willemdj** [opensearch-project/documentation-website#3382]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 In https://opensearch.org/docs/2.6/field-types/mappings/ there is an example that mentions "dynamic_templates". But this feature does not exist in opensearch, I think?

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/issues/3648

**Comment by Naarcha-AWS** [comment]
@kolchfa-aws: Can you confirm or deny this?
