### ISSUE TITLE
[BUG] Use "latest" for docker image versions

### ISSUE THREAD

**Issue by elfisher** [opensearch-project/documentation-website#341]
**What is the bug?**
Consider using the "latest" tag for docker image versions in the documentation to ensure the most up to date version of OpenSearch is used. https://opensearch.org/docs/1.2/opensearch/install/docker/

e.g. 

```
docker pull opensearchproject/opensearch:latest
docker pull opensearchproject/opensearch-dashboards:latest
```

**Comment by keithhc2** [comment]
Fixed with #343
