### ISSUE TITLE
[DOC] Feedback on Approximate k-NN Search page

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#3427]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Feedack on https://opensearch.org/docs/latest/search-plugins/knn/approximate-knn/ page: 

GET /_plugins/_knn/models/my-model?filter_path=state&pretty
{
  "state": "training"
}

gives error.

Please fix the documentation

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by martin-gaievski** [comment]
After checking with the team I suggest we update one of the requests in the documentation. In particular I mean model train request ```POST /_plugins/_knn/models/my-model/_train```. Please use following request:

```
{
    "training_index": "train-index",
    "training_field": "train-field",
    "dimension": 4,
    "description": "My models description",
    "method": {
        "name": "ivf",
        "engine": "faiss",
        "space_type": "l2",
        "parameters": {
            "nlist": 4,
            "nprobes": 2
        }
    }
}
```

this request is based on ivf method that also requires training, and it works with small dataset, so the 4 docs mentioned in the doc for training_index is enough.
