### ISSUE TITLE
[DOC] Update max k-NN vector size to 16,000 for non-Lucene implementations

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/documentation-website#3448]
**What do you want to do?**
 
- [X ] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Please update maximum vector size for native (not Lucene) implementations from 10000 to 16000 starting in 2.4.
Affected pages:
* https://opensearch.org/docs/latest/search-plugins/knn/approximate-knn/
* https://opensearch.org/docs/XXX/search-plugins/knn/approximate-knn/ for XXX=2.4 and up
* https://opensearch.org/blog/Building-k-Nearest-Neighbor-(k-NN)-Similarity-Search-Engine-with-Elasticsearch/

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by kolchfa-aws** [comment]
Assigning this small change to Caroline.
