### ISSUE TITLE
[DOC] Integrations 

### ISSUE THREAD

**Issue by brijos** [opensearch-project/documentation-website#3453]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 A user experience which allows users to install dashboards for data sources they have in their pipeline. Dashboards will auto populate if the ingestion workflow is enriched using the recently launched Simple Schema for Observability.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Example integration launched in 2.6 - https://github.com/YANG-DB/observability/tree/nginx_integration_bundle/integrations
Integrations documentation - https://github.com/opensearch-project/observability/tree/e18cf354fd7720a6d5df6a6de5d53e51a9d43127/integrations

**Comment by Naarcha-AWS** [comment]
@brijos: Is this something we need to document for 2.7?

**Comment by hdhalter** [comment]
@vagimeli  - you are assigned to this in the attached github issue, so I will assign you to this doc issue. Please let me know if you are not covering this. Thanks!

**Comment by brijos** [comment]
@vagimeli Yes, the plan is to release and we have a current demo site you have review.
