### ISSUE TITLE
[DOC] Spark Connector

### ISSUE THREAD

**Issue by brijos** [opensearch-project/documentation-website#3454]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Introduce the ability to reach data at rest in an object store (e.g., S3 or data lake) via Spark (Spark to be supplied by the user). Our first release will focus on data stored in Parquet format. Users will be able to query this data as though it is regular OpenSearch data and visualize it alongside their OpenSearch data in OpenSearch Dashboards.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/opensearch-spark/issues/4
https://github.com/opensearch-project/sql/issues/1746

**Comment by Naarcha-AWS** [comment]
@brijos: do we have a timeline on when this should be complete.
