### ISSUE TITLE
Provide instructions to set max_map_count for WSL2 users on sample docker-compose page

### ISSUE THREAD

**Issue by bradthurber** [opensearch-project/documentation-website#346]
**Is your feature request related to a problem?**

Windows WSL2 user here. I decided to learn OpenSearch this morning and immediately hit a road block using the sample docker compose file from [here](https://opensearch.org/docs/latest/opensearch/install/docker/):

Docker Compose did its thing but opensearch didn't load because it didn't have enough `max_map_count` resources.

**What solution would you like?**

A note in the OpenSearch documentation that users will need to increase the value of `max_map_count` before running docker-compose up.

It looks like this issue has been around for a good while and [this stackoverflow answer](https://stackoverflow.com/a/69294687) gets to the bottom of it for WSL2 users.

I chose to implement the option that survives a reboot from the Answer but was also successful running `sudo sysctl -w vm.max_map_count=262144` before the `docker-compose up` command - knowing it would not survive a reboot. 

**What alternatives have you considered?**

I decided to report this because my guess is that all users will encounter this when starting their OpenSearch journey like I did. It is frustrating to start to learn something and have something fail.

**Do you have any additional context?**

No

**Comment by keithhc2** [comment]
Hey @bradthurber, thanks a bunch for writing in. We actually documented setting `max_map_count` in the [important settings](http://localhost:4000/docs/latest/opensearch/install/important-settings/) page, but I've also now added a note that links to it in the [Docker](http://localhost:4000/docs/latest/opensearch/install/docker/#start-a-cluster) installation page. The setting isn't part of the docker compose file, so I didn't want to add it to that section. If there are any other related issues, feel free to re-open the ticket!

**Comment by opyate** [comment]
@keithhc2 your links point to localhost.

**Comment by keithhc2** [comment]
@opyate Sorry about that. Just fixed.
