### ISSUE TITLE
[BUG] correction for transforms documentation

### ISSUE THREAD

**Issue by thalurur** [opensearch-project/documentation-website#347]
**What is the bug?**
* The current documentation of IM transforms features list `if_seq_no` and `if_primary_term` are non required params - this is not true and needs to be corrected to required and one can get these values by doing a GET call on the transform
* Also we are missing calling out the allowed fields that can be updated once transform is created which are only 
    * all fields in schedule
    * description  
    * page size

Current documentation - https://opensearch.org/docs/latest/im-plugin/index-transforms/transforms-apis/#update-a-transform-job

**Comment by keithhc2** [comment]
Fixed with #354
