### ISSUE TITLE
[BUG] Update footer on docs site

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/documentation-website#349]
**What is the bug?**
We recently changed the footer on the rest of the OpenSearch.org site - /docs needs updated to the new footer as well. 
(link to PR from that change: https://github.com/opensearch-project/project-website/pull/453) 

**How can one reproduce the bug?**
1. Go to https://opensearch.org/
2. Scroll down to light blue footer area
4. See 
- 'Resources' column includes a link to 'Testimonials'
- 'Connect' has been changed to 'Contact Us' 
-- 'Email' replaced with link to new 'Connect' page

**What is the expected behavior?**
Footer on docs page should be the same as the rest of the site.

**Comment by krisfreedain** [comment]
ATT: @AMoo-Miki

**Comment by keithhc2** [comment]
Fixed with #352

**Comment by krisfreedain** [comment]
thank you!
