### ISSUE TITLE
[DOC]GeoIP processor

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/documentation-website#3524]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
We are targeting OpenSearch 2.8 to release GeoIP processor with auto database update. This feature is an enhancement of existing GeoIP processor. With this enhancement, a user can associate GeoIP processor with GeoIP database in an external endpoint. The GeoIP database will get updated periodically in the background while a user keep using GeoIP processor. Current GeoIP processor does not support auto update of GeoIP database. 

FYI, we do not have a document for GeoIP processor which has been available since 1.0.x. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/issues/5856
https://github.com/opensearch-project/OpenSearch/issues/5860

**Comment by hdhalter** [comment]
This got moved to the 2.10 train during the project call today.
<img width="682" alt="image" src="https://github.com/opensearch-project/documentation-website/assets/104463754/7d12cc0e-9415-4fc3-8e2d-8c3a5d2ff8ed">
