### ISSUE TITLE
[DOC] Index/Bulk Response JSON missing information if index was created. How to surface?

### ISSUE THREAD

**Issue by Diego-Hernandez-Moodys** [opensearch-project/documentation-website#3530]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [x] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
If OpenSearch automatically creates an index in an Index or Bulk request if it doesn't exist, where in the JSON response can I see if an index was created? The current response JSON looks exactly the same for an unseen document and an unseen index.
```json
{
    "_index": "unseen",
    "_id": "FAKE_ID",
    "_version": 1,
    "result": "created",
    "_shards": {
        "total": 2,
        "successful": 2,
        "failed": 0
    },
    "_seq_no": 0,
    "_primary_term": 1,
    "status": 201
}
```

**To reproduce, post the following JSON and investigate the JSON response**
```json
PUT /existing

POST _bulk
{ "index": { "_index": "existing", "_id": "FAKE_ID" } }
{ "A JSON": "document" }
```

```json
POST _bulk
{ "index": { "_index": "unseen", "_id": "FAKE_ID" } }
{ "A JSON": "document" }
```

**Comment by Naarcha-AWS** [comment]
@Diego-Hernandez-Moodys: Which version of OpenSearch were you using?

**Comment by Diego-Hernandez-Moodys** [comment]
@Naarcha-AWS 2.5

**Comment by Diego-Hernandez-Moodys** [comment]
Alternatively, is it possible to turn off auto construction of an index?

**Comment by Naarcha-AWS** [comment]
What does the [GET _mget](https://opensearch.org/docs/2.5/api-reference/document-apis/multi-get/) API return? This should return any documents added by the bulk request. Alternatively, before making the request, you can use the [Index exists API](https://opensearch.org/docs/2.5/api-reference/index-apis/exists/) to verify if the index exists.

I don't believe there's a way to turn off the automatic index creation in a bulk request.

**Comment by Diego-Hernandez-Moodys** [comment]
> [GET _mget](https://opensearch.org/docs/2.5/api-reference/document-apis/multi-get/) API return?

That sounds very helpful for another use case I had. Thank you

>Alternatively, before making the request, you can use the [Index exists API](https://opensearch.org/docs/2.5/api-reference/index-apis/exists/) to verify if the index exists.

I am ingesting a million documents a day. That might slow down my use case unfortunately.

> I don't believe there's a way to turn off the automatic index creation in a bulk request.

Bummer. I wouldn't mind the auto construction but the mapping I use is too specific with keywords, analyzers, rank_features, etc to be interpreted. Is there maybe a default mapping that I can set to use?

**Comment by Naarcha-AWS** [comment]
It might help to define some explicit mappings per index as described in [Explicit mapping](https://opensearch.org/docs/latest/field-types/mappings/#explicit-mapping). You can see what field types are supported in the [Supported field types](https://opensearch.org/docs/latest/field-types/index/) reference. 

If you're looking for some additional ideas for your use case, it might be good to post this question in [forums.opensearch.com](https://forum.opensearch.org/) as well.

**Comment by Diego-Hernandez-Moodys** [comment]
@Naarcha-AWS I found something called https://opensearch.org/docs/latest/im-plugin/index-templates/ that solved my issue. Thanks
