### ISSUE TITLE
[DOC] Add docs for otel logs source plugin

### ISSUE THREAD

**Issue by lizsnyder** [opensearch-project/documentation-website#3541]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Requesting full documentation in the opensearch docs that cover the following plugin: https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/otel-logs-source

**Comment by hdhalter** [comment]
Hi Caroline, this plugin is also going out with the OSI release in late April.
