### ISSUE TITLE
[DOC] Document anomaly detectory data prepper processor

### ISSUE THREAD

**Issue by lizsnyder** [opensearch-project/documentation-website#3544]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Requesting documentation of the following processor in the official opensearch docs: https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/anomaly-detector-processor

**Comment by hdhalter** [comment]
Hi Caroline, there is one more plugin that will be supported in the OSI release. Can you please add it to the docs? Thank you.

**Comment by carolxob** [comment]
@lizsnyder Thanks! Here's the current PR open for it: #3569
