### ISSUE TITLE
[DOC] Request to adjust wording for Alerting plugin documentation

### ISSUE THREAD

**Issue by AWSHurneyt** [opensearch-project/documentation-website#3546]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

 The following paragraph on this page for the Alerting plugin describes configuring a `data filter` when creating a monitor through the visual editor.
https://opensearch.org/docs/latest/observing-your-data/alerting/monitors/
> To define a monitor visually, choose Visual editor. Then choose a source index, a timeframe, an aggregation (for example, count() or average()), a data filter if you want to monitor a subset of your source index, and a group-by field if you want to include an aggregation field in your query. At least one group-by field is required if you're defining a bucket-level monitor. Visual definition works well for most monitors.

We've refactored the visual editor to support configuring more than 1 data filter at a time, so we'd like to edit the paragraph a bit. I've drafted some edits to the wording below. Configuring monitors to have more than 1 filter was already supported, but required configuration using the extraction query editor. This is just an enhancement to the visual editor to align with that existing support.
> To define a monitor visually, choose Visual editor. Then choose a source index, a timeframe, an aggregation (for example, count() or average()), **up to 10 data filters if you want to monitor a subset of your source index (please note that only documents which match ALL of the filter conditions will be included in the results of the monitor execution)**, and a group-by field if you want to include an aggregation field in your query. At least one group-by field is required if you're defining a bucket-level monitor. Visual definition works well for most monitors.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

More details about the visual editor change can be found in issue https://github.com/opensearch-project/alerting-dashboards-plugin/issues/432

**Comment by Naarcha-AWS** [comment]
Because this PR is not on the roadmap, I'm moving this to the backlog.

**Comment by Naarcha-AWS** [comment]
I'll circle back to this after 2.7 is released.

**Comment by vagimeli** [comment]
@AWSHurneyt Is this change still accurate? If so, is it for versions 2.9 and later?

**Comment by AWSHurneyt** [comment]
Hi @vagimeli ,
Looks like we were able to get this enhancement in for the v2.7 release. Could the documentation be updated back to that version?
