### ISSUE TITLE
[DOC] Make Event Analytics Visualizations Available in Core Dashboards

### ISSUE THREAD

**Issue by brijos** [opensearch-project/documentation-website#3549]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
As part of driving cohesion, the Observability team is making functionality available from the Observability plugin into Core Dashboards. Dashboard producers who have build out visualizations in Observability will be able to add visualizations to their new or existing Core Dashboards by adding a new visualization.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/dashboards-observability/issues/304

**Comment by vagimeli** [comment]
@brijos @joshuali925 Do we have a demo or test site for this feature?

**Comment by joshuali925** [comment]
@vagimeli i reached to you offline, i can show you how it looks like
