### ISSUE TITLE
[DOC] Observability plugin Integration → Dashboards

### ISSUE THREAD

**Issue by nitincd** [opensearch-project/documentation-website#3571]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 with the change in navigational patterns, we will need to highlight the availability of observability and other plugin features in the main dashboards area documentation.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1866

**Comment by vagimeli** [comment]
Duplicate issue; see #2203
