### ISSUE TITLE
[BUG] Dead link to Apache Lucene

### ISSUE THREAD

**Issue by piotr-jagiello** [opensearch-project/documentation-website#358]
**What is the bug?**
There is a dead link on this page that is supposed to lead to explanation of Lucene segments:
https://opensearch.org/docs/latest/search-plugins/knn/approximate-knn/
It leads here, which returns 404:
https://lucene.apache.org/core/890/core/org/apache/lucene/codecs/lucene87/package-summary.html#package.description

**How can one reproduce the bug?**
Go on the page and click on the link in the sentence "To learn more about Lucene segments, see the Apache Lucene documentation. ".
**What is the expected behavior?**
I expected the link to work, it doesn't.

My guess would be that they removed documentation for "890", and link to "8_11_1" might be the right one:
https://lucene.apache.org/core/8_11_1/core/org/apache/lucene/codecs/lucene87/package-summary.html#package.description
but I don't actually know if information on that page still applies, etc. I'd actually like to know if it does.

**Comment by keithhc2** [comment]
Hey @piotr-jagiello, thanks for letting us know about the dead link. We've corrected the documentation so it links to 8_11_1 instead. https://opensearch.org/docs/latest/search-plugins/knn/approximate-knn/ Let us know if there are any other issues!
