### ISSUE TITLE
[DOC] Feedback on Data Prepper topic

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#3580]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Feedback on this topic: /docs/latest/data-prepper/pipelines/pipelines/

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
doesn't show information about pulling values from env variables

**Comment by hdhalter** [comment]
Hi Caroline, is this something you can look into to see what information we are missing? Thanks!

**Comment by carolxob** [comment]
> Hi Caroline, is this something you can look into to see what information we are missing? Thanks!

Sure! I'll look into this.
