### ISSUE TITLE
Where to check the OpenSearch 1.2.3 Compatibility Matrix for Logstash and Beats?

### ISSUE THREAD

**Issue by balar06** [opensearch-project/documentation-website#360]
https://opensearch.org/docs/latest/clients/agents-and-ingestion-tools/index/#compatibility-matrices 

Couldn't see the Compatibility Matrix for Logstash and Beats for the OpenSearch 1.2.3. 
In OpenSearch documentation compatibility Matrix present for OpenSearch 1.0.0 only.

Where to check the OpenSearch 1.2.3 Compatibility Matrix for Logstash and Beats?

BREAKING CHANGES section is not available in OpenSearch release notes.
Where to check Breaking changes and Deprecation changes for the OpenSearch version 1.0.0 to 1.2.3?

Could you please advise on this?

**Comment by dblock** [comment]
Forgot to answer re:deprecations I think we need to call that out as "none", but if there are none mentioned, then there are none. 

I also opened https://github.com/opensearch-project/OpenSearch/issues/1868 and would love some suggestions about how we can improve release notes.

**Comment by balar06** [comment]
Thanks a lot.

**Comment by keithhc2** [comment]
Thanks a bunch for reporting, @balar06. As mentioned before, new OpenSearch 1.x versions don't introduce breaking changes, so we've updated [the compatibility page](https://opensearch.org/docs/latest/clients/agents-and-ingestion-tools/index/#compatibility-matrices) to say so. Once 2.0 releases, we'll update the page again to account for new compatibility.
