### ISSUE TITLE
[DOC] Feedback on /docs/2.4/opensearch/query-dsl/text-analyzers/ page

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#3628]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Direct user feedback on this page: https://opensearch.org/docs/2.4/opensearch/query-dsl/text-analyzers/
"share examples for pattern analyzer"

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
Sounds we go ahead and make an individual page per text analyzer @kolchfa-aws?

**Comment by kolchfa-aws** [comment]
We have an overarching issue for analyzers #1483. Closing this one because it is a duplicate.
