### ISSUE TITLE
[DOC] Add OpenSearch Dashboards index pattern and scripted field documentation

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/documentation-website#3629]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Index patterns are a fundamental OpenSearch Dashboards concept, because they're the primary method for specifying how to fetch data. Index patterns can be created and managed through the UI: https://playground.opensearch.org/app/management/opensearch-dashboards/indexPatterns

This index pattern management UI contains many links to documentation that doesn't exist and that we should create.

## 1. A documentation page about how to add data to OpenSearch from OpenSearch Dashboards

(`docLinks.links.noDocumentation.addData`)
The link appears in the initial index pattern management prompt when no data has been loaded.

https://user-images.githubusercontent.com/1679762/228623243-56212619-7aa0-46d1-aead-cbb6b52312f1.mov

## 2. A documentation page that introduces the concept of index patterns

(`docLinks.links.noDocumentation.indexPatterns.introduction`)

One link appears in the initial prompt for index pattern management when no index patterns exist, but multiple datasource feature is enabled. 

https://user-images.githubusercontent.com/1679762/228623222-fe27939f-ed37-4bd0-a25e-f6e8f09c84dd.mov

Another link appears on [the form for creating a new index pattern
](https://playground.opensearch.org/app/management/opensearch-dashboards/indexPatterns/patterns/d3d7af60-4c81-11e8-b3d7-01146121b73d/create-field/)

https://user-images.githubusercontent.com/1679762/228623253-a03b19b3-4c76-4bcb-9a10-fef11453348a.mov

## 3. A documentation intro page about scripted fields

(`docLinks.links.noDocumentation.scriptedFields.painless`)

Subtopics or subpages should cover

- 3a. The concept of scripted fields (`docLinks.links.noDocumentation.scriptedFields.scriptFields`)
- 3b. Limitations of scripted fields in aggregations (`docLinks.links.noDocumentation.scriptedFields.scriptAggs`)

Links appear when [editing or creating a scripted field](https://playground.opensearch.org/app/management/opensearch-dashboards/indexPatterns/patterns/d3d7af60-4c81-11e8-b3d7-01146121b73d/field/hour_of_day)

https://user-images.githubusercontent.com/1679762/228623265-8bdf8790-33b2-4b29-a944-525145f154c4.mov

## 4. A documentation intro page about the Painless scripting language

(`docLinks.links.noDocumentation.scriptedFields.painless`)

Subtopics or subpages should cover

- 4a. The Painless Java API (`docLinks.links.noDocumentation.scriptedFields.painlessApi`)
- 4b. The Painless syntax (`docLinks.links.noDocumentation.scriptedFields.painlessSyntax`)
- 4c. Lucene expressions (`docLinks.links.noDocumentation.scriptedFields.luceneExpressions`)

Links appear in flyout when clicking "Get help with the syntax and preview the results of your script." when [editing or creating a scripted field](https://playground.opensearch.org/app/management/opensearch-dashboards/indexPatterns/patterns/d3d7af60-4c81-11e8-b3d7-01146121b73d/field/hour_of_day)

https://user-images.githubusercontent.com/1679762/228623268-3fd5d226-9a33-4437-8f76-4da8d4b0f530.mov

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

Customer request: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3309

Part of https://github.com/opensearch-project/documentation-website/issues/1853

**Comment by joshuarrrr** [comment]
From https://github.com/opensearch-project/documentation-website/issues/1853#issuecomment-1464798590, @vagimeli proposed:

```
scriptedFields: {
scriptFields: https://opensearch.org/docs/latest/api-reference/script-apis/index/,
scriptAggs: https://opensearch.org/docs/latest/aggregations/pipeline-agg/,
painless: https://opensearch.org/docs/latest/api-reference/script-apis/exec-stored-script/,
painlessApi: https://opensearch.org/docs/latest/api-reference/script-apis/exec-script/,
painlessSyntax: https://opensearch.org/docs/latest/data-prepper/pipelines/expression-syntax/,
luceneExpressions: https://opensearch.org/docs/latest/search-plugins/knn/filter-search-knn/,
}
```

But none of these docs are really sufficient or appropriate for providing the info a user would be looking for in these cases.

**Comment by Naarcha-AWS** [comment]
@joshuarrrr: Would index patterns and scripted fields be specific for Dashboards or is it relevant for OpenSearch core as well?

**Comment by joshuarrrr** [comment]
My understanding is that index patterns are a dashboards-specific concept. But I believe scripted fields are more general and can be used from the CLI and directly with OpenSearch. But I'm only familiar with the Dashboards-specific content for them.

**Comment by joshuarrrr** [comment]
Another related forum question: https://forum.opensearch.org/t/how-to-create-index-pattern-through-dashboards-api/13928/2
