### ISSUE TITLE
[DOC] Feedback on /docs/latest/query-dsl/ page

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#3631]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Direct user feedback on https://opensearch.org/docs/2.6/query-dsl/.
03/21: "I just want to do 'contains' query or a substring match" 

Also, 
03/28: "the examples don't work"

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Hi Fanit, does it make sense to add something about this? Thanks.

**Comment by kolchfa-aws** [comment]
@hdhalter This is a specific use case, which can be implemented multiple ways in OpenSearch. We already have issues to add query string query full documentation and analyzer/tokenizer documentation, so we can close this issue.
