### ISSUE TITLE
[DOC] Feedback on /docs/latest/troubleshoot/security-admin/ page

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#3634]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Direct user feedback on https://opensearch.org/docs/latest/troubleshoot/security-admin/.
"where is the location of this script?"

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@cwillum - is this something we can add to this topic? Thanks.

**Comment by cwillum** [comment]
Fix is in PR #3645.
