### ISSUE TITLE
[DOC] The example request for Index Rollup API is incorrect. 

### ISSUE THREAD

**Issue by tanqiuliu** [opensearch-project/documentation-website#3636]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

The current documentation for "Index Rollup API" -> "Create or Update an index rollup job" has an example request, which contains `dimensions` & `metrics` fields like this:
```
{
	"dimensions": {
		"date_histogram": {
			"source_field": "tpep_pickup_datetime",
			"fixed_interval": "1h",
			"timezone": "America/Los_Angeles"
		},
		"terms": {
			"source_field": "PULocationID"
		},
		"metrics": [{
			"source_field": "passenger_count",
			"metrics": [{
					"avg": {}
				},
				{
					"sum": {}
				},
				{
					"max": {}
				},
				{
					"min": {}
				},
				{
					"value_count": {}
				}
			]
		}]
	}
}
```

However, this is incorrect. When I test the above request in OpenSearch, it encountered `parsing_exception`. 

According to the documentation for `rollup` operation in ISM ([link](https://opensearch.org/docs/latest/im-plugin/ism/policies/#rollup)), `dimensions` and `metrics` fields are both top level fields and have type `Array`. I also confirmed this by looking at the source code of index rollup APIs ([link](https://github.com/opensearch-project/index-management/blob/main/src/main/kotlin/org/opensearch/indexmanagement/rollup/model/Rollup.kt#L304-L315)). 

In a correct request, these two fields should look like: 
```
{
	"dimensions": [{
			"date_histogram": {
				"source_field": "tpep_pickup_datetime",
				"fixed_interval": "1h",
				"timezone": "America/Los_Angeles"
			}
		},
		{
			"terms": {
				"source_field": "PULocationID"
			}
		}
	],
	"metrics": [{
		"source_field": "passenger_count",
		"metrics": [{
				"avg": {}
			},
			{
				"sum": {}
			},
			{
				"max": {}
			},
			{
				"min": {}
			},
			{
				"value_count": {}
			}
		]
	}]
}
``` 
All of the versions are affected.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by tanqiuliu** [comment]
Created a PR #3637 to address this.

**Comment by Naarcha-AWS** [comment]
Thanks for addressing this @tanqiuliu
