### ISSUE TITLE
[BUG] `OPENSEARCH_JAVA_HOME` is incorrect

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/documentation-website#364]
**What is the bug?**
OpenSearch doesn't use the environment variable `OPENSEARCH_JAVA_HOME` as mentioned on https://opensearch.org/docs/latest/opensearch/install/compatibility/
**How can one reproduce the bug?**
1. Go to [install/compatibility](https://opensearch.org/docs/latest/opensearch/install/compatibility/)
2. Read the doc

**What is the expected behavior?**
This should likely be just `JAVA_HOME`

**Comment by dblock** [comment]
This was opened as https://github.com/opensearch-project/OpenSearch/issues/1872, let's make sure it's not just a bug.

**Comment by dblock** [comment]
@julesg is saying that we use `JAVA_HOME` - I would verify that and if that's true, document that

**Comment by jcgraybill** [comment]
Hey please no, let's not implement a documentation error into the product. Please fix the documentation error.

**Comment by elfisher** [comment]
This is an error. I'll open a PR to fix.

**Comment by elfisher** [comment]
https://github.com/opensearch-project/documentation-website/pull/368

**Comment by elfisher** [comment]
Fixed in #368

**Comment by asummers1** [comment]
This still seems to be an issue in https://opensearch.org/docs/latest/install-and-configure/install-opensearch/debian/#configure-a-user and https://opensearch.org/docs/latest/install-and-configure/install-opensearch/debian/#configure-a-user.

The documentation is using `OPENSEARCH_JAVA_HOME`, when the correct syntax is `JAVA_HOME`.
