### ISSUE TITLE
[DOC] Data Prepper - Add documentation on Snappy Compression Support

### ISSUE THREAD

**Issue by ashoktelukuntla** [opensearch-project/documentation-website#3644]
**What do you want to do?**
 Data Prepper - Add documentation on Snappy Compression Support

https://github.com/opensearch-project/data-prepper/issues/2420

- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/s3/ <----- Add `snappy` to compression table.
