### ISSUE TITLE
[BUG] Bredcrumb navigator doesn't link to parent page

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#365]
**What is the bug?**

The breadcrumb on https://opensearch.org/docs/latest/dashboards/browser-compatibility/ does not link back to the correct page.

**How can one reproduce the bug?**

1. Go to https://opensearch.org/docs/latest/dashboards/browser-compatibility/
2. Click on 'OpenSearch Dashboards'
3. Doesn't go anywhere

**What is the expected behavior?**

Go to the root of the documentation.

**Do you have any screenshots?**

![click](https://user-images.githubusercontent.com/542335/149421608-f86c364f-b599-41bf-a74e-f5c36fc56d57.gif)

**Comment by keithhc2** [comment]
Other standalone Dashboards pages don't have breadcrumbs, so I'm just going to remove it entirely. Will push with next PR
