### ISSUE TITLE
[BUG] Bulk API Timeout Documentation 

### ISSUE THREAD

**Issue by mgodwan** [opensearch-project/documentation-website#367]
**What is the bug?**
Bulk API documentation mentions `timeout` as  `How long to wait for the request to return. Default 1m.` This is not the case as bulks could take longer and have an overall time greater than this. The timeout is for actions to wait on which happens as part of bulk or are required for bulks to go through e.g. automatic index creation, mapping updates.

**How can one reproduce the bug?**
1. Go to https://opensearch.org/docs/latest/opensearch/rest-api/document-apis/bulk/#url-parameters
2. Go to timeout section
3. Refer to the description

**What is the expected behavior?**
The documentation should reflect that actual response time can be larger than the mentioned values.

**What is your host/environment?**
NA

**Do you have any screenshots?**
NA

**Do you have any additional context?**

From the Opensearch code:
1. https://github.com/opensearch-project/OpenSearch/blob/01e1b94e47aa8cb04ad2a34e505f31cfdf7b0fed/server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java#L1037
2. https://github.com/opensearch-project/OpenSearch/blob/01e1b94e47aa8cb04ad2a34e505f31cfdf7b0fed/server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java#L821

**Comment by keithhc2** [comment]
Hey @mgodwan, thanks a bunch for writing in. Yes, you are correct in that `timeout` can take longer than `1m`, and OpenSearch would report back saying that the operation failed. However, `timeout` is a parameter you can set that specifies how long OpenSearch should wait before it decides the operation failed, _not_ how long the actual response time is. I hope that clears any confusion!
