### ISSUE TITLE
[DOC] Document cookie split configuration parameter

### ISSUE THREAD

**Issue by davidlago** [opensearch-project/documentation-website#3691]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We are shipping an update to our session cookies where we split them and stitch them back together to circumvent cookie size limitations. As part of this effort, we are creating a new configuration parameter to specify the number of "chunks" we allow. See details of the change (and question in particular about this behavior) [here](https://github.com/opensearch-project/security-dashboards-plugin/pull/1352#issuecomment-1497873922). We are targeting 2.7 for this change (hope it is small enough that we can fit the doc changes in, and sorry for the late notice!).

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
This is based on security-dashboards plugin issue [#1352](https://github.com/opensearch-project/security-dashboards-plugin/pull/1352).

**Comment by cwillum** [comment]
Monitoring for 2.7.
