### ISSUE TITLE
Possible error in the segrep documentation?

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/documentation-website#3710]
Hi,

https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/segment-replication/configuration/#enable-on-a-node-using-a-tarball-install

I am not expert here but is it possible to put this config of segrep in config file instead of config/jvm.options?
```
opensearch.experimental.feature.replication_type.enabled
```
See: https://github.com/opensearch-project/OpenSearch/blob/main/distribution/src/config/opensearch.yml#L95

Thanks.

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/documentation-website/blob/main/_tuning-your-cluster/availability-and-recovery/segment-replication/configuration.md#enable-on-a-node-using-a-tarball-install

**Comment by kolchfa-aws** [comment]
@dreamer-89 @andrross Is it possible to turn on segment replication from the opensearch.yml file or do we have to use config/jvm.options?
@ariamarble for visibility.

**Comment by dreamer-89** [comment]
The PR for [feature flag support](https://github.com/opensearch-project/OpenSearch/pull/5941) in opensearch.yml was made in Jan 19, based on release [timeline](https://opensearch.org/releases.html), opensearch.yml can be used for enabling feature flags starting from `2.6` version.

**Comment by andrross** [comment]
@kolchfa-aws @dreamer-89 It's also in the release notes :)

https://github.com/opensearch-project/OpenSearch/blob/main/release-notes/opensearch.release-notes-2.6.0.md?plain=1#L7

**Comment by kolchfa-aws** [comment]
Thank you, @dreamer-89 and @andrross!

**Comment by hdhalter** [comment]
This is no updated in the doc. https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/segment-replication/backpressure/
