### ISSUE TITLE
[DOC] Maps: support adding label to document layer

### ISSUE THREAD

**Issue by junqiu-lei** [opensearch-project/documentation-website#3712]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 For maps 2.7.0 release, the documents layer supports adding label by static text or index pattern field value, we need update this feature to maps doc https://opensearch.org/docs/2.6/dashboards/visualize/maps

* GH issue: https://github.com/opensearch-project/dashboards-maps/issues/321

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by kolchfa-aws** [comment]
Implemented in #3640

**Comment by kolchfa-aws** [comment]
Closed. Implemented in #3640
