### ISSUE TITLE
Lacking documentation for managing index patterns via API[DOC]

### ISSUE THREAD

**Issue by PatrickMulvanny** [opensearch-project/documentation-website#3713]
Hi,

I am trying to work out how to create an index patter programmatically. I thought that the Opensearch dashboard API was meant to map to the Kibana API however the documented method for kibana does not seem to work in Opensearch Dashboard. 

https://www.elastic.co/guide/en/kibana/current/index-patterns-api-create.html

Can you please update the Opensearch-Dashboard Docs on how to replicate this Kibana feature in Opesearch

Thanks,
Patrick

**Comment by joshuarrrr** [comment]
In OpenSearch Dashboards, index patterns are just a particular type of Saved Object, and can be created or edited programmatically via the Saved Object API (which itself needs documentation). See https://github.com/opensearch-project/documentation-website/issues/3799
