### ISSUE TITLE
[BUG] Passing custom YAML file for Docker missing colon

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/documentation-website#373]
**What is the bug?**
[Here](https://github.com/opensearch-project/documentation-website/blob/5c6de68cb0598360280604356ed7800e5cfeb12c/_opensearch/install/docker.md?plain=1#L183)

It is missing colon for `opensearch-dashboards`

**What is the expected behavior?**
It should be `opensearch-dashboards:`

**Comment by keithhc2** [comment]
Missing colon should be in there now: https://opensearch.org/docs/latest/opensearch/install/docker/
