### ISSUE TITLE
[DOC] Update security plugin API `actiongroups` sample response

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/documentation-website#3751]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

Update the documentation for the security plugin default action-groups API example:
[Current example response](https://t.corp.amazon.com/V861844626): 
```json
{
  "read": {
    "reserved": true,
    "hidden": false,
    "allowed_actions": [
      "indices:data/read*",
      "indices:admin/mappings/fields/get*"
    ],
    "type": "index",
    "description": "Allow all read operations",
    "static": true
  },
  ...
}
```
<a name="response"></a>
Updated example response:
```json
{
  "read": {
    "reserved": true,
    "hidden": false,
    "allowed_actions": [
      "indices:data/read*",
      "indices:admin/mappings/fields/get*",
      "indices:admin/resolve/index"
    ],
    "type": "index",
    "description": "Allow all read operations",
    "static": true
  },
  ...
}
```
 
This change updates the allowed actions to reflect the correct response being sent.

To test this:
1. Download [latest](https://opensearch.org/samples/docker-compose.yml) docker-compose.yml
2. Run `docker-compose up` from the download location
3. Goto OpenSearch-Dashboards window in the browser and navigate to Dev Tools
4. Run `GET _plugins/_security/api/actiongroups/read`
5. You should see the updated response there

**Comment by cwillum** [comment]
@DarshitChanpura Do we want to backport this minor change to 2.x and 1.3?

**Comment by DarshitChanpura** [comment]
> @DarshitChanpura Thanks for creating the issue. Do we want to backport this minor change to 2.x and 1.3 documentation?

I think backport to 2.x line should suffice. Not sure if changes in 1.3 is required.
