### ISSUE TITLE
Update the website Documentation for releases

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/documentation-website#378]
Can someone help update the website documentation to list `1.2.4` release? We need to update https://opensearch.org/docs/latest/opensearch/install/plugins/ page for `1.2.4` and other minor releases as well.

### Enhancement
Can we automate this process for future releases? https://github.com/opensearch-project/documentation-website/issues/379

### Acceptance Criteria
- [ ] The [website](https://opensearch.org/docs/latest/opensearch/install/plugins/) is up to date for all releases upto `1.2.4`

**Comment by keithhc2** [comment]
Added back in here https://opensearch.org/docs/latest/opensearch/install/plugins/
