### ISSUE TITLE
[PROPOSAL] Browser support matrix

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/documentation-website#38]
OpenSearch Dashboards contains items that isn't supported in other browsers.

For example, https://github.com/opensearch-project/OpenSearch-Dashboards/pull/387 introduces [animateTransform](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateTransform) which isn't supported in IE11.

Browser support, as of 7.9, Kibana (and EUI) no longer supports IE11. See this matrix: https://www.elastic.co/support/matrix#matrix_browsers. This could be very important for people to know.

**Comment by aetter** [comment]
Hi @kavilla, I think the full matrix is overkill given that as of 1.0, Dashboards will never have supported legacy browsers. I've added a bulleted list here: https://docs-beta.opensearch.org/docs/opensearch-dashboards/browser-compatibility/
