### ISSUE TITLE
[BUG] broken link to Lucene docs

### ISSUE THREAD

**Issue by jhockett** [opensearch-project/documentation-website#381]
**Describe the bug**

**To Reproduce**
1. Go to https://opensearch.org/docs/latest/opensearch/query-dsl/term/#regex
2. Click on 'To learn more, see the Lucene documentation.'
3. See error

**Expected behavior**

Working link

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Version: [e.g. 22]
 - Browsers: [e.g. Chrome, Safari] Firefox ESR
 - Browser Version: [e.g 93.0.4521.12]

**Additional context**

**Comment by keithhc2** [comment]
Thanks a bunch for reporting, @jhockett. The Lucene link on [this page](https://opensearch.org/docs/latest/opensearch/query-dsl/term/#regex) should be fixed now, and I've fixed the Lucene links on a few other pages, too, but if you find any more, feel free to re-open the issue.
