### ISSUE TITLE
[DOC] Document experimental codecs

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#3816]
**What do you want to do?**
 
- [x] Add new documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

In https://github.com/opensearch-project/OpenSearch/issues/3354 we've introduced some new experimental compression codecs  . The documentation is sparse on what this does, in https://opensearch.org/docs/1.0/opensearch/rest-api/create-index/ we only say that `index.codec` is "The compression type to use to compress stored data. Available values are best_compression and default."

I propose we add documentation that 1) describes each codec, their pros, cons and tradeoffs, provide links to benchmarks, 2) explain what can and cannot be done at runtime (e.g. can one change a codec after the index is created? can one restore a snapshot that used a certain codec into an index that uses another?).

**Comment by hdhalter** [comment]
The 2.9 release covers the new index codecs ZSTD and ZSTD_NO_DICT, but there is more detail and use cases to add. We will address post-2.9.

**Comment by hdhalter** [comment]
Hi @dblock  - We have enhanced the section on index codecs quite a bit. Can you please review and let me know if we are missing anything? Thanks! https://opensearch.org/docs/latest/im-plugin/index-codecs/
