### ISSUE TITLE
[SQL-CLI] Documentation needs update

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/documentation-website#382]
We just released SQL-CLI `1.0.0` to Pypi https://pypi.org/project/opensearchsql/

The existing documentation on website is outdated: https://opensearch.org/docs/latest/search-plugins/sql/cli/

Please refer to the latest README in codebase to update accordingly. https://github.com/opensearch-project/sql/tree/sql-cli-1.0/sql-cli

**Comment by keithhc2** [comment]
Should be updated now according to the README: https://opensearch.org/docs/latest/search-plugins/sql/cli/

**Comment by zhongnansu** [comment]
@keithhc2 The gif is still not updated on the website documentation

**Comment by keithhc2** [comment]
Okay, I will add it in my next PR
