### ISSUE TITLE
[Documentation/UX Update] index_pattern/s clarification

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/documentation-website#389]
Hey All,

Putting this here as I am not sure if this should be classified as a bug as the documentation on it is not clear. For OpenSearch-Dashboards the [documentation](https://opensearch.org/docs/latest/opensearch/index-templates/) states, "to any new index whose name matches the regular expression logs-2020-01-*" implying that regular expressions can be used. This seems to be bad wording as the field only seems to support asterisks as wild cards. (also in Open Distro's [documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/index-templates/#index-template))

This is also confirmed on the page for creating index patterns which states `Use an asterisk (*) to match multiple indices. Spaces and the characters \, /, ?, ", <, >, | are not allowed.`

The documentation should reflect the hint above for this. Also, if this pattern is the same for ISM then it should be reflected in their [documentation](https://opensearch.org/docs/latest/im-plugin/ism/index/).

**Comment by kavilla** [comment]
Thanks for opening! Yeah I agree the docs implies regex accepted. Moved to doc repo.

**Comment by keithhc2** [comment]
Updated with #394
