### ISSUE TITLE
[Documentation] ISM Actions

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/documentation-website#393]
Hey All, 

It's come to our attention that the [Index Policy Actions documentation](https://opensearch.org/docs/latest/im-plugin/ism/policies/#actions) needs to be clarified. 

The ISM actions will execute synchronously even if there is a timeout specified. The timeout acts as a circuit breaker rather than a buffer period between actions as implied by the current documentation. 

[https://github.com/opensearch-project/index-management/blob/6141c3c6fec9fe4c0c7bf7[…]arch/indexmanagement/indexstatemanagement/ManagedIndexRunner.kt](https://github.com/opensearch-project/index-management/blob/6141c3c6fec9fe4c0c7bf733877660e78ed2b1b1/src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexRunner.kt#L282)

Documentation should be upgraded to reflect this.

**Comment by keithhc2** [comment]
Fixed with #412
