### ISSUE TITLE
[Asset Request] How can I get this background 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/documentation-website#3945]
I am trying to create some education materials and would like to use these backgrounds for the slides:

![Screenshot 2023-05-02 at 5 56 21 PM](https://user-images.githubusercontent.com/65832608/235794766-00cd049e-b478-4c9c-9297-c5172ceeb920.png)
![Screenshot 2023-05-02 at 5 57 47 PM](https://user-images.githubusercontent.com/65832608/235794872-d156e4d9-54ff-4928-80ba-e1e7a1b07ca1.png)

I cannot find the assets for being able to turn this into a background for slides though. Can you link the blank slide templates?

Thank you.

**Comment by hdhalter** [comment]
Hi @scrawfor99, the marketing team has the images. Reach out to pattijur in Slack.

**Comment by scrawfor99** [comment]
Hi @hdhalter, thank you for your quick reply. I will follow up there!
