### ISSUE TITLE
[BUG] k-NN endpoint is incorrect

### ISSUE THREAD

**Issue by vishalsrao** [opensearch-project/documentation-website#395]
The following command on https://opensearch.org/docs/latest/search-plugins/knn/approximate-knn/ is incorrect:
```
POST /_plugins/_knn/models/_train/my-model
```

I think it should be:
```
POST /_plugins/_knn/models/my-model/_train
```

Additionally, the index train-index should probably contain documents with higher embedding-dimensions to be compatible with pq parameter m=8.

It would be good to have a link to an example which can be used to load more embeddings. PQ requires at least 256 samples to be compatible with code_size 8.

**Comment by Naarcha-AWS** [comment]
I suspect that this might have been fixed due to recent updates in the kNN documentation. Will investigate and close if so.

**Comment by hdhalter** [comment]
@cwillum - Looks like the first issue is fixed (_train). Can you please see if the second request has been addressed? Thanks.

**Comment by hdhalter** [comment]
@martin-gaievski - following up on this inquiry. @kolchfa-aws - for visibility, since I know you've reworked this section. Thanks!

**Comment by martin-gaievski** [comment]
PR author is correct, url must be `/_plugins/_knn/models/my-model/_train`, that is a bug and needs to be corrected

**Comment by hdhalter** [comment]
> PR author is correct, url must be `/_plugins/_knn/models/my-model/_train`, that is a bug and needs to be corrected

This has been updated in the documentation already: POST /_plugins/_knn/models/my-model/_train. 

The question is on the second part of their suggestion:  
"Additionally, the index train-index should probably contain documents with higher embedding-dimensions to be compatible with pq parameter m=8.

It would be good to have a link to an example which can be used to load more embeddings. PQ requires at least 256 samples to be compatible with code_size 8."

Any input you can provide here is appreciated. Thanks!

**Comment by hdhalter** [comment]
The second item is addressed here: https://opensearch.org/docs/latest/search-plugins/knn/knn-index#supported-faiss-encoders
