### ISSUE TITLE
[DOC] Remote Store feature documentation changes for 2.8.0 release

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/documentation-website#3950]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
- We are planning to make Remote Store feature GA in 2.8.0 release.
- This feature is already documented [here](https://opensearch.org/docs/latest/opensearch/remote) but need some changes with 2.8.0 release.

**Comment by kolchfa-aws** [comment]
@sachinpkale @ashking94 Could one of you specify what needs to be documented for this issue please? Thanks!

**Comment by ashking94** [comment]
@kolchfa-aws  acknowledged.
