### ISSUE TITLE
[DOC] [Multiple Datasource] Update documentation for AWS OpenSearch Serverlesss support in 2.8

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/documentation-website#3983]
**What do you want to do?**
 In upcoming 2.8 release, we plan to add support for AWS OpenSearch Serverlesss support, in multiple datasource. We need some updates to the documentation 

- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
https://opensearch.org/docs/latest/dashboards/discover/multi-data-sources/#creating-a-data-source-connection
![image](https://user-images.githubusercontent.com/32652829/236285148-64112893-bdc8-4de7-8cf0-18c6bb3b3e74.png)

Within the existing "aws sigV4" auth type configuration while creating a datasource, we will add an "service" option that user will  choose between "Amazon OpenSearch Service" or "Amazon OpenSearch Serverless"

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
- original feature request issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3623
- draft PR with video attached https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3957

**Comment by ahopp** [comment]
Thanks for adding @hdhalter!
