### ISSUE TITLE
[DOC] Support cross cluster queries via PPL

### ISSUE THREAD

**Issue by anirudha** [opensearch-project/documentation-website#3988]
**What do you want to do?**
 
- [ x ] Request a change to existing documentation
- [ x ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Add documentation to support cross cluster search from PPL
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
 engineering reference docs are here:
https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/admin/cross_cluster_search.rst

**Comment by anirudha** [comment]
dupe : https://github.com/opensearch-project/documentation-website/issues/3512

**Comment by hdhalter** [comment]
@Naarcha-AWS - this is under the security section in our docs. Do you think it makes more sense to assign it to @cwillum ?
