### ISSUE TITLE
[DOC] Documentation desperately needs a keyword index

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/documentation-website#4000]
Suppose I want to find the documentation on the "should" keyword.
In order to look that up, I need to notice that that's an option within the "bool" query.
That shouldn't be necessary.
I should be able to find it either by searching for "should" (which doesn't work) or by looking in the index for "should".
But there is no index. BTW, the search engine would presumably use the tag used to create the index entry to go directly to that page as well.

**Comment by Naarcha-AWS** [comment]
@kolchfa-aws: Can we transfer this to the project website?

**Comment by kolchfa-aws** [comment]
There is already an issue for it in the project website https://github.com/opensearch-project/project-website-search/issues/43.
