### ISSUE TITLE
[FEATURE] Add documentation for geo_shape/geo_point/ region maps/coordinate maps

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/documentation-website#402]
**Is your feature request related to a problem?**
Need detailed explanation on how to use these data field types and supported/unsupported operation list.

**What solution would you like?**
How to use geospatial fields, with example, visualization like create region maps, coordinate maps and heat maps.

**What alternatives have you considered?**
I have to use elasticsearch documentation, update version to 7.10.2

**Do you have any additional context?**
N/A

**Comment by keithhc2** [comment]
#177 is about documenting field data types, which includes information about geo_shape and geo_point, so I'm closing this ticket.
