### ISSUE TITLE
[DOC] Add documentation for configuring notifications on Index Management operations

### ISSUE THREAD

**Issue by kamingleung** [opensearch-project/documentation-website#4037]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Index operations may take tens of minutes or even hours to complete (e.g. reindex, split). However, there is no way for Admins to get informed on status or the completion of long running operations. With this feature, Admins can get notified through notification channels on upcoming operations that have been completed or failed. To configure notifications, Admins can configure these notifications globally, so they will not need to manually configure notifications for every single operation. Users can also configure additional notification settings when submit those long-running index operations. 

In 2.8, users can configure notifications for the following 5 index operations: Shrink, split, clone, reindex, force merge.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
UX RFC: https://github.com/opensearch-project/index-management-dashboards-plugin/issues/687
API: https://github.com/opensearch-project/index-management/issues/700
API Documentation request: https://github.com/opensearch-project/documentation-website/issues/3186

**Comment by zhichao-aws** [comment]
Introduction to new APIS for this feature: #4170
