### ISSUE TITLE
[DOCUMENTATION] the example in documentation has invalid package paths

### ISSUE THREAD

**Issue by SingingBush** [opensearch-project/documentation-website#404]
the documentation on https://opensearch.org/docs/latest/clients/java/ has imports with the package  `org.opensearch.clients` which does not exist. Seems the correct package is  `org.opensearch.client`.

**Comment by dblock** [comment]
cc: @keithhc2

**Comment by dblock** [comment]
The code in the documentation should be published as a working sample on GitHub.

**Comment by keithhc2** [comment]
Closed with #412
