### ISSUE TITLE
[DOC] Alerting - Support Composite Monitors

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/documentation-website#4056]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 A composite monitor is a workflow that requires user to define a sequence of bucket/doc/query level monitors. When a composite monitor is executed it executes a sequence of monitors. User may choose to use the findings of one monitor as a filter input to a following monitor in the same sequence. All the monitors defined in a composite monitor sequence are called delegate monitors. Composite monitors allow users to execute delegate monitors in sequential fashion hence providing more control over the data seen by composite monitors which will enable creation of more granular findings and chained alerts.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/alerting/issues/697
https://github.com/opensearch-project/alerting/issues/524

**Comment by cwillum** [comment]
@eirsep Thanks for creating an issue for this. I've begin looking at the resources for this 2.8 enhancement. Do expect to have a test environment you could share at some point so I can experiment and begin to understand how the monitor creation and alerting chaining works for this new composite monitor type? Thanks.

**Comment by cwillum** [comment]
This will be pushed to 2.9.
