### ISSUE TITLE
[DOC] Add examples with .p12 keystore and truststore

### ISSUE THREAD

**Issue by KevinVerm** [opensearch-project/documentation-website#4060]
**What do you want to do?**
 
- [ x] Request a change to existing documentation
- [ x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Throughout the documentation for OpenSearch and OpenSearch dashboards we see references to .pem files. However we use keystore and truststore .p12 files. Would it be possible to add such information to the help on how to configure opensearch and opensearch dashboards with p12 files for TLS purposes? This in the light of an on-prem OpenSearch cluster.

**Comment by AntonEliatra** [comment]
@hdhalter I can work on this one

**Comment by AntonEliatra** [comment]
PR raised https://github.com/opensearch-project/documentation-website/pull/7015
