### ISSUE TITLE
[DOC] Address feedback on DQL documentation

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#4063]
**What do you want to do?**
 
x Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
- [x] Address user feedback, in particular the following: 

1. Examples involving special characters
2. Show the data record being queryed in the examples

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Another feedback comment on 5/2/23: 
>>>queries like text:*sales-channel* not working, not returning result, escaping - with / not working

**Comment by hdhalter** [comment]
Feedback comment on 5/22/23:
/docs/latest/dashboards/discover/dql/ | DQL: how to handle multi-word search within a field?  Ex. field:"find phrase" gives error.  If no quotes, only matches the last word.

**Comment by hdhalter** [comment]
Feedback comment on 2023-06-06: wildcards, contains examples missing

**Comment by hdhalter** [comment]
- [ ] Feedback on 20230422: /docs/latest/dashboards/discover/dql/ | I was looking for at more advanced query, but there is no reference to that page

**Comment by hdhalter** [comment]
20230828 | /docs/latest/dashboards/discover/dql/ | AND isn't same and
