### ISSUE TITLE
[DOC] Step-by-Step instructions for setting a OpenSearch to be used as a vector database

### ISSUE THREAD

**Issue by dylan-tong-aws** [opensearch-project/documentation-website#4066]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

We need two "getting started" doc pages that provide step-by-step instructions on how to setup our vector database (k-nn) so that it's ready for application development.

There are two experiences. One experience is building on our core vector database capabilities which is just using the k-nn index.

The other experience involves using the ml-commons and neural search plugin.
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by jhmcintyre** [comment]
@Naarcha-AWS do you have what you need to move forward with this? Once documented, this information will be a useful destination to link to from our growing library of vector database & neural search content.

**Comment by hdhalter** [comment]
@jhmcintyre - We don't have the bandwidth to move forward on this but it would be a great addition to the documentation. @dylan-tong-aws - is there anyone on your team that can start a draft?
