### ISSUE TITLE
[DOC] Notifications - Support Microsoft Teams webhooks

### ISSUE THREAD

**Issue by zhichao-aws** [opensearch-project/documentation-website#4071]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Change existing documentation, add content about microsoft teams webhook. User can add microsoft teams webhook as notification channel, and send notifications to this channel.
 It will affect the versions after 2.8(including 2.8).

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
[opensearch-project/notifications#585](https://github.com/opensearch-project/notifications/issues/585)

**Comment by kolchfa-aws** [comment]
@zhichao-aws Is this still going into 2.8?

**Comment by zhichao-aws** [comment]
This will go into 2.9

**Comment by zhichao-aws** [comment]
The feature will be released in 2.10
