### ISSUE TITLE
[DOC] New file option for Clear Index Cache API

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/documentation-website#4092]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 A new option to clear filecache was added to the existing clear indices cache API (https://opensearch.org/docs/latest/api-reference/index-apis/clear-index-cache/)

Parameter: `file`
Type: `Boolean`
Description: If `true`, clears the unused entries from the filecache on `search` capable nodes. Defaults to `false`.

Sample Request: 
`POST http://localhost:9200/*/_cache/clear?file=true`

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
- https://github.com/opensearch-project/OpenSearch/pull/7498

**Comment by Naarcha-AWS** [comment]
Add the new parameter to this section: https://opensearch.org/docs/latest/api-reference/index-apis/clear-index-cache/#path-parameters
