### ISSUE TITLE
Private tenants not available for indexes with FGAC domains[DOC]

### ISSUE THREAD

**Issue by cwillum** [opensearch-project/documentation-website#4094]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 
Add note to the `server_username` setting in config.yml to alert users that when they change from the default `kibanaserver` the system drops the `indices:admin/index_template*` permissions, which leads to missing private tenants.

**What other resources are available?**
Based on Security Dashboards PR [#1418](https://github.com/opensearch-project/security-dashboards-plugin/issues/1418).

**Comment by AntonEliatra** [comment]
@hdhalter I can take this one

**Comment by AntonEliatra** [comment]
PR raised https://github.com/opensearch-project/documentation-website/pull/7066
