### ISSUE TITLE
Docs for nested documents and parent/child relationships

### ISSUE THREAD

**Issue by hansott** [opensearch-project/documentation-website#410]
Hey 👋 

I like how OpenSearch is progressing. I was skimming through the existing docs (I know it's work in progress) but couldn't find anything about nested documents or parent/child relationships. Is OpenSearch planning to keep these supported for the foreseeable future?

**Comment by nateynateynate** [comment]
Hi Hans! I've been trying to figure out whether this is something that still exists or is just undocumented. I did come across this issue in the OpenSearch repo : https://github.com/opensearch-project/OpenSearch/issues/2474 which led me to try out on my own some index mappings that had some of the relational stanzas in them. 

This mapping call seems to have been accepted: 
`PUT /parentchildtest
{
  "mappings": {
    "properties": {
      "join": {
        "type": "join",
        "relations": {
          "parent": "child"
        }
      }
    }
  }
}`

So this leads me to believe that whatever fundamental pieces for having parent/child 'joins' via the mappings are still in the guts somewhere, just not documented. 

Do you have an existing mapping that you're trying that doesn't work? 

Either way, it sounds like this does need to be documented. Thanks for calling this out, and sorry you haven't seen a response in so long. Bad form.

Thanks @hansott

**Comment by hansott** [comment]
@nateynateynate Thanks for your reply! It's just not clear whether the parent/child joins are supported and will be supported in the future. We rely heavily on these relationships and this is what prevents us to move towards OpenSearch.

**Comment by Naarcha-AWS** [comment]
Hi everyone! Parent child relationships are documented in the join field type page (https://opensearch.org/docs/latest/opensearch/supported-field-types/join/). 

Feel free to look over the page and if you notice anything missing, open a new issue.

**Comment by hansott** [comment]
@Naarcha-AWS Thanks! Not super complete compared to Elastic's but at least it's documented now. That means the feature will stay and be supported? Still wondering whether we should stay on Elastic or adopt OpenSearch.
