### ISSUE TITLE
[DOCS] New out of box experience for OpenSearch

### ISSUE THREAD

**Issue by setiah** [opensearch-project/documentation-website#413]

**Comment by JeffH-AWS** [comment]
This is related to https://github.com/opensearch-project/documentation-website/issues/789

**Comment by JeffH-AWS** [comment]
Putting this issue on the backlog again. Still waiting on a lot of the materials and a good amount of dev work. This feels like a 3.0 target since a lot of the recommended behavior are breaking changes.

**Comment by hdhalter** [comment]
A Quickstart was added to the docs earlier this year. See https://opensearch.org/docs/latest/quickstart/. Closing this issue.
