### ISSUE TITLE
[DOC] Feedback on configuration/generate-certificates

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#4130]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [x] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 In this section: 
20230517 | /docs/latest/security/configuration/generate-certificates/ | you say we need to add admin.pem and admin-key.pem to each node, yet you use neither in your opensearch.yml config?

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Here is the location: https://opensearch.org/docs/2.7/security/configuration/generate-certificates/#add-certificate-files-to-opensearchyml

**Comment by hdhalter** [comment]
Thanks for reviewing this one, @scrawfor99!

**Comment by scrawfor99** [comment]
I will update with what I figure out :)

**Comment by scrawfor99** [comment]
Should be clarified by #5628 

Basically, you don't actually need the admin certificate on every node unless you want to ssh into them and execute the securityadmin script or reload your certificates
