### ISSUE TITLE
[DOC] Replace "Destinations" with "Notifications" in Dashboards documentation 

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#4140]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 UI updates made to interface. Destinations is now Notifications.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by vagimeli** [comment]
Update api.md to remove redundant and outdated information about the monitor types. Move information into the specific monitors documentation. Update destinations to notifications, as destination is now notifications.

**Comment by hdhalter** [comment]
@vagimeli - This is marked 'done' in the project, but looks like there are still some instances of 'destinations' in the doc. Is this work still in progress? For instance, here: https://opensearch.org/docs/latest/observing-your-data/alerting/security/. Thanks!
