### ISSUE TITLE
[FEATURE] Document Intervals Query

### ISSUE THREAD

**Issue by mattweber** [opensearch-project/documentation-website#415]
Add documentation for the full-text intervals query.

**Comment by Naarcha-AWS** [comment]
@mattweber: This feature is already documented here, https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/

**Comment by mattweber** [comment]
@Naarcha-AWS no it is not, please reopen.

**Comment by mattweber** [comment]
@Naarcha-AWS  please reopen, cc @dblock @nknize
