### ISSUE TITLE
[DOC] Search pipeline script request processor

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/documentation-website#4155]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

A subtask of [search pipeline](https://github.com/opensearch-project/documentation-website/issues/2560) is to add docs for the script processor, which allows users to manipulate search request via painless script. We would like to explicitly mention all the [supported search request body fields ](https://github.com/opensearch-project/OpenSearch/pull/7607#issue-1714286320) in the public document. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

Meta issue https://github.com/opensearch-project/documentation-website/issues/2560

**Comment by noCharger** [comment]
Simply copy the design specifics from the PR and paste them here for convenience:

### Description
Because the script processor is quite flexible, the design should be cautious about the range of fields that it may read and modify. One approach to managing request/response context is utilizing Java's classloader and field dynamically at runtime. The key advantage of this method is its flexibility, providing a general solution adaptable to various contexts. However, its broad applicability can also be a liability, as it could inadvertently create security vulnerabilities unless explicitly disabled. Alternatively, an explicit field check offers more control and security by only supporting specific fields. While this approach reduces the risk of security breaches, it requires developers to add support on new fields. The recommandation is approach two and iterate with community engagement

Search source fields for request
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java

Table for Search Request script processor supports (Not final decision. Iterating and looking for community feedback)

No. | Field Type & Name | Description | Readable (Y / N / Partially) | Writable (Y / N / Partially) | Notes
-- | -- | -- | -- | -- | --
1 | int from | Starting document offset. Defaults to 0. | Y | Y |  
2 | int size | Defines the number of hits to return. Defaults to 10. | Y | Y |  
3 | Boolean explain | If true, returns detailed information about score computation as part of a hit. Defaults to false. | Y | Y |  
4 | Boolean version | If true, returns document version as part of a hit. Defaults to false. | Y | Y |  
5 | Boolean seqNoAndPrimaryTerm | If true, returns sequence number and primary term of the last modification of each hit. See Optimistic concurrency control. | Y | Y |  
6 | boolean trackScores | If true, calculate and return document scores, even if the scores are not used for sorting. Defaults to false. | Y | Y |  
7 | Integer trackTotalHitsUpTo | Number of hits matching the query to count accurately. Defaults to 10000.If true, the exact number of hits is returned at the cost of some performance. If false, the response does not include the total number of hits matching the query. | Y | Y |  
8 | Float minScore | Minimum _score for matching documents. Documents with a lower _score are not included in the search results. | Y | Y |  
9 | TimeValue timeout | Specifies the period of time to wait for a response. If no response is received before the timeout expires, the request fails and returns an error. Defaults to no timeout. | N | N |  require more complex handling on read and rewrite
10 | int terminateAfter | The maximum number of documents to collect for each shard, upon reaching which the query execution will terminate early.Defaults to 0, which does not terminate query execution early. | Y | Y |  
11 | List<SortBuilder<?>> sorts | A comma-separated list of <field>:<direction> pairs. | N | N |   require more complex handling on read and rewrite
12 | List<FieldAndFormat> docValueFields | A comma-separated list of fields to return as the docvalue representation of a field for each hit. | N | N |  require more complex handling on read and rewrite
13 | List<ScriptField> scriptFields | List of script fields to compute and include in the response. | N | N |  require more complex handling on read and rewrite
14 | List<FieldAndFormat> fetchFields | List of fields to fetch and return as part of the search response. | N | N |   require more complex handling on read and rewrite
15 | StoredFieldsContext storedFieldsContext | This field contains information about which stored fields to include in the response. | N | N |  require more complex handling on read and rewrite
16 | FetchSourceContext fetchSourceContext | This field specifies whether the source of each hit should be returned and how the source should be filtered. | N | N | Valid values for _sourcetrue(Boolean) The entire document source is returned.false(Boolean) The document source is not returned.<string>(string) Comma-separated list of source fields to return. Wildcard (*) patterns are supported.
17 | List<IndexBoost> indexBoosts | Boosts the _score of documents from specified indices. | N | N |   require more complex handling on read and rewrite
18 | List<String> stats | Stats groups to associate with the search. Each group maintains a statistics aggregation for its associated searches. You can retrieve these stats using the indices stats API. | N | N |  require more complex handling on read and rewrite
19 | boolean profile | If true, the response will include detailed profiling information. | Y | Y |  
20 | QueryBuilder queryBuilder | This field is used to build the main search query. | P | P | Only some fields of certain type of queries for 2.8/2.9 release
21 | QueryBuilder postQueryBuilder | This field is used to build post-processing queries. | P | P | Only some fields of certain type of queries for 2.8/2.9 release
22 | SearchAfterBuilder searchAfterBuilder | This field is used to construct searches that fetch the next page of results. | N | N | Not support all scroll releated features as of now. Open to community feedback.
23 | PointInTimeBuilder pointInTimeBuilder | This field is used to build point-in-time specifications for consistent search results. | N | N | Not support PIT for now. Open to community feedback.
24 | SliceBuilder sliceBuilder | This field is used to build slice specifications for parallel scrolling. | N | N | Not support all scroll releated features as of now. Open to community feedback.
25 | CollapseBuilder collapse | This field is used to build field collapsing specifications. | N | N | Open to community feedback.
26 | Map<String, Object> searchPipelineSource | This field contains the source of the ad hoc search pipeline. | N | N | Open to community feedback.
27 | AggregatorFactories.Builder aggregations | This field is used to build aggregation specifications for the search. | N | N | Open to community feedback.
28 | HighlightBuilder highlightBuilder | This field is used to build highlighting specifications. | N | N | Open to community feedback.
29 | SuggestBuilderSuggestBuilder suggestBuilder | This field is used to build suggestions for the search. | N | N | Open to community feedback.
30 | List<RescorerBuilder> rescoreBuilders | This field is used to build rescorers that adjust the relevance score of search hits. | N | N | Open to community feedback.
31 | List<SearchExtBuilder> extBuilders | List of builders for search extensions. | N | N | Open to community feedback.

### Related Issues
https://github.com/opensearch-project/OpenSearch/issues/6712

**Comment by msfroh** [comment]
@kolchfa-aws  See also:

https://github.com/opensearch-project/OpenSearch/blob/main/modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/helpers/SearchRequestMap.java#L92

and

https://github.com/opensearch-project/OpenSearch/blob/main/modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/helpers/SearchRequestMap.java#L133
