### ISSUE TITLE
[DOC] Update Flat Object Documentation for partial flat object

### ISSUE THREAD

**Issue by mingshl** [opensearch-project/documentation-website#4168]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Flat object will be enhanced to accept partial flattened. The current documentation will need to update to reflect the enhanced feature

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/issues/7136

**Comment by hdhalter** [comment]
@kolchfa-aws - this is moving to 2.10 according to Mark in today's project call.
