### ISSUE TITLE
[DOC] Add documentation for segment replication bug impacting plugins

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/documentation-website#4194]
**What do you want to do?**
Coming from bug on core https://github.com/opensearch-project/OpenSearch/issues/7781; segment replication today fails for plugins that uses custom codecs (e.g. kNN, security-analytics). This bug prevents replica copies from allocation.

- [x] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 
Add documentation to share this issue with users and provide alternative solution. 
OpenSearch Version: 2.7.0
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Bug on core: https://github.com/opensearch-project/OpenSearch/issues/7781

**Comment by hdhalter** [comment]
@dreamer-89 , @Naarcha-AWS  - Was there anything we needed to document for this? If so, was the documentation completed? Thanks!

**Comment by dreamer-89** [comment]
@hdhalter : Thanks for checking on this. Yes, as part of this issue we need to document the bug which impacts plugins using custom codecs. I feel documentation will caution users when using custom codecs segment replication enabled indices on OpenSearch version <= 2.7. Please let me know if more details are needed.

**Comment by hdhalter** [comment]
Thanks, @dreamer-89 ! Can you please provide the appropriate warning text and the appropriate location? For example, we have a page on index codecs here: https://opensearch.org/docs/latest/im-plugin/index-codecs/.

**Comment by dreamer-89** [comment]
> Thanks, @dreamer-89 ! Can you please provide the appropriate warning text and the appropriate location? For example, we have a page on index codecs here: https://opensearch.org/docs/latest/im-plugin/index-codecs/.

Thanks @hdhalter for the update. I will open up the PR for the change shortly.

**Comment by hdhalter** [comment]
Thanks, @dreamer-89 and @Naarcha-AWS ! I'll close this issue.
