### ISSUE TITLE
[DOC] Update _tasks API documentation with concurrency related changes

### ISSUE THREAD

**Issue by jed326** [opensearch-project/documentation-website#4206]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 As a part of introducing concurrent segment search we have also updated the `_tasks` API to return thread information and more detailed summary stats in cases with concurrency.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/pull/7673
https://github.com/opensearch-project/OpenSearch/issues/7425

**Comment by hdhalter** [comment]
Are we targeting release 2.9/3.0 for this update?

**Comment by andrross** [comment]
@hdhalter We are targeting 2.9
