### ISSUE TITLE
[DOC] Incorrect upsert documentation

### ISSUE THREAD

**Issue by rkreicbergs-sorsera** [opensearch-project/documentation-website#4219]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
 As per documentation https://opensearch.org/docs/latest/api-reference/document-apis/update-document/#upsert:
 
"In the sample below, the upsert object updates the last name and adds the age field if a document already exists." - in the example, first_name and last_name is updated if document already exists. 
 
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
Does this effect the code examples? If so, can you provide the example where you discovered the bug?
