### ISSUE TITLE
[DOC] add s3ObjectNoRecordsFound metric to S3 source docs

### ISSUE THREAD

**Issue by cmanning09** [opensearch-project/documentation-website#4221]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We added a new metric to S3 source plugin to record the number of S3 objects which resulted in 0 events being written to the buffer. 

This section should include the new metric.

    * `s3ObjectNoRecordsFound` - The number of S3 objects that resulted in 0 records added to the buffer.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
I updated the DataPrepper readme with these details as well: https://github.com/opensearch-project/data-prepper/pull/2812

**Comment by hdhalter** [comment]
@Naarcha-AWS - Looks like this has been addressed: https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/s3/#counters. Can we close this issue? Thanks!
