### ISSUE TITLE
[DOCUMENTATION] Cluster formation fails without cluster.initial_master_nodes configuration

### ISSUE THREAD

**Issue by gabrielcocenza** [opensearch-project/documentation-website#425]
I'm following the documentation about [cluster formation](https://opensearch.org/docs/latest/opensearch/cluster/#step-4-configure-discovery-hosts-for-a-cluster) and I was not able to create a cluster without adding cluster.initial_master_nodes configuration. This information it's not on the documentation and apparently setting node role to `MASTER` it's not enough for cluster formation for the first time.

**How can one reproduce the bug?**
1. Create 4 VMs running Ubuntu 20.04
2. Download and decompress the tarball on all VMs
3. Make the changes for every node on the file `config/opensearch.yml` as said in the documentation
4. Run `./opensearch-tar-install.sh` on every node

**What is the expected behavior?**
A health cluster with 4 nodes (1: Coordinator, 1: Master, 2: Data)

**What is your host/environment?**
 - OS: Ubuntu 20.04
 - Version: 1.2.4

**Do you have any screenshots?**
The configuration in one of the nodes looks like this and the other nodes will just change name, roles and IP's:
```
# ======================== OpenSearch Configuration =========================
#
# NOTE: OpenSearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.opensearch.org
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
node.name: opensearch-master
node.roles: [ master ]
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
#path.data: /path/to/data
#
# Path to log files:
#
#path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# OpenSearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 10.5.1.192
#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when this node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discovery.seed_hosts: ["10.5.1.192", "10.5.0.212", "10.5.0.207", "10.5.3.224"] 
#
# Bootstrap the cluster using an initial set of master-eligible nodes:
#
#cluster.initial_master_nodes: ["opensearch-master"]
#
# For more information, consult the discovery and cluster formation module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
```

After running the install script, the cluster complains that master is not discovered yet and has not  previously joined a bootstrapped (v7+) cluster

```
[2022-02-23T14:52:06,461][WARN ][o.o.c.c.ClusterFormationFailureHelper] [opensearch-master] master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and [cluster.initial_master_nodes] is empty on this node: have discovered [{opensearch-master}{r8GyxEUzTu6yFc-t08nWng}{pyCyFxYAQ8yN6ExwkLJkEQ}{10.5.1.192}{10.5.1.192:9300}{m}{shard_indexing_pressure_enabled=true}]; discovery will continue using [10.5.0.212:9300, 10.5.0.207:9300, 10.5.3.224:9300] from hosts providers and [{opensearch-master}{r8GyxEUzTu6yFc-t08nWng}{pyCyFxYAQ8yN6ExwkLJkEQ}{10.5.1.192}{10.5.1.192:9300}{m}{shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
[2022-02-23T14:52:08,584][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [opensearch-master] Exception while retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, AUDIT] (index=.opendistro_security)
org.opensearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
```

Setting `cluster.initial_master_nodes: ["opensearch-master"]` fixed the problem.

**Comment by hdhalter** [comment]
HI @peterzhuamazon - Can you please look at this and let me know if the solution is valid? (I know we've changed some terminology since this was written, so that would need to be adjusted, as appropriate.)

**Comment by hdhalter** [comment]
HI @soosinha, can you please review this and let me know if the solution is valid? Thanks.

**Comment by soosinha** [comment]
Yes @hdhalter , for initial bootstrap of a cluster, we need to provide the setting `cluster.initial_master_nodes`. With the terminology change, the setting will be `cluster.initial_cluster_manager_nodes` and the value will be the list of cluster manager node names which should be used for the first election.
For the example listed on [documentation page](https://opensearch.org/docs/latest/tuning-your-cluster/index/), the setting will be as below:
```
cluster.initial_cluster_manager_nodes: ["opensearch-cluster_manager"]
```

Please modify the documentation accordingly.

**Comment by hdhalter** [comment]
@vagimeli - Can you please update the documentation with this setting? Thanks!

**Comment by vagimeli** [comment]
@soosinha Is this simply a setting name change? If so, please provide me with the specific information we need to include in the documentation and where exactly we need to include this change in the documentation. The associated PR is #5712. Thank you.

**Comment by soosinha** [comment]
This is not a setting change. This was a miss in the documentation for setting up a cluster.
We need to add the following information in the step 4 of `Creating a Cluster` [here](https://github.com/opensearch-project/documentation-website/blob/a8bd47e07b747ac12677643f9280079603baaa4a/_tuning-your-cluster/index.md?plain=1#L151).

_You need to specify the cluster manager nodes which will be used in the first election for cluster bootstrapping. In the current example, the setting would look like below:_
```
cluster.initial_cluster_manager_nodes: ["opensearch-cluster_manager"]
```

Also change the step 4 title from "Configure discovery hosts for a cluster" to "Configure discovery hosts and initial cluster manager nodes for a cluster"
