### ISSUE TITLE
[DOCUMENTATION] Add documentation on Plugins mechanisms

### ISSUE THREAD

**Issue by asafm** [opensearch-project/documentation-website#426]
Hi,

You recently published a blog post on how [Plugins works in OpenSearch](https://github.com/opensearch-project/project-website/issues/446). 

It makes sense to me to have that content as documentation

**Comment by keithhc2** [comment]
Hey @asafm, thanks for writing in. We're in the process of reorganizing the docs site and what may be relevant topics, and you're welcome to chime in at #419. As the docs site is now, I don't think introductory content about OpenSearch and OpenSearch plugins should not be mixed in with the documentation, which, right now, is mainly about how to use OpenSearch features. The blog post you're referring to talks about how to install and load plugins (which we have in the documentation), and then goes more in-depth into Security Manager, which is more about OpenSearch's code than it is about how to use OpenSearch. It's possible that we revamp the documentation site to include more marketing and introductory content, so we may revisit this topic of adding more content types to the docs site. Right now, though, I'm going to close this ticket, and feel free too re-open it if you have any questions.
