### ISSUE TITLE
[DOCUMENTATION FEATURE] Create a page with user-facing features by version

### ISSUE THREAD

**Issue by Jon-AtAWS** [opensearch-project/documentation-website#427]
**Is your feature request related to a problem?**
I want to know which version of OpenSearch I should use if I want to use feature X

**What solution would you like?**
Create a documentation page with a matrix of features and when they launched.

**What alternatives have you considered?**
This information exists in the release notes, but that's not a very user-friendly way to consume it. As there are more versions, I will need to look at more release notes. 

**Do you have any additional context?**
Have a look at the Amazon OpenSearch Service documentation (https://docs.aws.amazon.com/opensearch-service/latest/developerguide/features-by-version.html) to see what I mean.

**Comment by hdhalter** [comment]
HI @Jon-AtAWS - Does this page do the job? https://opensearch.org/docs/latest/version-history/. 

We've also started to track changes we've made to the documentation per release, starting with 2.4: https://github.com/opensearch-project/documentation-website/tree/main/release-notes.

**Comment by hdhalter** [comment]
Closing this issue since we have Version History and release notes.
