### ISSUE TITLE
[DOC] Update search profile API documentation with concurrency related changes

### ISSUE THREAD

**Issue by ticheng-aws** [opensearch-project/documentation-website#4281]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 As a part of introducing concurrent segment search we have also updated the search profile API to return more detailed summary stats in cases with concurrency.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/issues/7355
https://github.com/opensearch-project/OpenSearch/pull/7898

**Comment by ticheng-aws** [comment]
Hi @hdhalter, we are targeting this for 2.9 as well.

**Comment by kolchfa-aws** [comment]
Thanks for the clarification, @ticheng-aws!

**Comment by sohami** [comment]
https://github.com/opensearch-project/OpenSearch/pull/8801

**Comment by kolchfa-aws** [comment]
2.10 changes tracked in #4989

**Comment by kolchfa-aws** [comment]
@sohami Is there any documentation needed for the 2.11 version for this issue?

**Comment by sohami** [comment]
Confirming we don't need any change in 2.11 for this API doc

**Comment by ticheng-aws** [comment]
We need to update the document for the query profile part in the next release https://opensearch.org/docs/latest/api-reference/profile#the-query-array-1
