### ISSUE TITLE
[FEATURE] documentation for terms lookup queries

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#430]
**Is your feature request related to a problem?**
opensearch supports terms lookup queries, but they're currently undocumented.

**What solution would you like?**
extend the [terms query documentation](https://opensearch.org/docs/latest/opensearch/query-dsl/term/#terms) to include terms lookup queries.

**What alternatives have you considered?**
n/a

**Do you have any additional context?**
see the original [documentation from ES](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-terms-query.html#query-dsl-terms-lookup).

**Comment by alicejw-aws** [comment]
FYI. This issue is similar to a duplicate issue: https://github.com/opensearch-project/documentation-website/issues/474
I will work to blend the content. thanks

**Comment by rursprung** [comment]
> FYI. This issue is similar to a duplicate issue: #474 

i'm aware of the TLQ-in-DLS documentation update (btw, thanks for that!), but that's documentation for a new feature.

>I will work to blend the content. thanks

please note that TLQ-in-DLS (the thing already documented) is a special case which just describes that you can now (starting in 2.0) use TLQ in a DLS (previously it just failed at runtime if you set up a DLS with a TLQ in it). however, what i mentioned with this ticket here is the fact that TLQ is not documented at all (normal `terms` queries are - at least in a very rudimentary way - but there's no mention of TLQ at all) and that it should thus be added. i was actually trying to add it as a preparation for TLQ-in-DLS (see #483).

**Comment by alicejw-aws** [comment]
ok thanks @rursprung for explaining it. let me remove duplicate label, the other one is not directly related to this issue. 
i do have an additional PR that does relate to the TLQ for Query DLS section. Here it is for reference: https://github.com/opensearch-project/documentation-website/pull/561
