### ISSUE TITLE
[DOC] Feedback on Security topics

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#4314]
**What do you want to do?**
 
x Request a change to existing documentation

Community feedback from the documentation website:

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
- [x] 20230505 | /docs/latest/security/audit-logs/index | 
/plugins.security.audit.ignore_requests is plugins.security.audit.config.ignore_requests, and this is  the same for most of the settings - Fixed by https://github.com/opensearch-project/documentation-website/pull/4058
- [x] 20230526 | /docs/latest/security/authentication-backends/authc-index/ | There is no description of the configuration for Basic Auth/internal users.  There is no description of how to use multiple authentication methods together. See https://github.com/opensearch-project/documentation-website/pull/4638/files
- [x] 20230526 | /docs/latest/security/configuration/configuration/config.yml | contains element 'config' not element opensearch_security'
- [x] 20230527 | docs/latest/security/configuration/configuration/ | Example root element is documented as 'opensearch_security:' when it is actually 'config:'
- [x] 20230526 |/docs/latest/security/configuration/multi-auth/ | opensearch_security.openid.scope is not described or even mentioned
- [x] 20230525 |/docs/2.7/security/multi-tenancy/dynamic-config/ | "Disable or enable multi-tenancy...The default is true"  Does that mean the default is true==disable or true==enable? https://github.com/opensearch-project/documentation-website/pull/5722
- [x] 20230524 | /docs/2.5/security/configuration/disable/ | When I remove securityDashboards plugin, the OpenSearch Dashboards don't start until the plugin is installed back. https://github.com/opensearch-project/documentation-website/pull/5830
(Solution from Peter) PZ: 1. OS must also disable security if OSD removed security  2. OSD must change config to remove all the security related settings, and change https to http.  3. Reboot OS/OSD.
- [x] 20230525 | /docs/latest/security/multi-tenancy/multi-tenancy-config/ | Is this for kibana or opensearch dashboards? n seems to override any sort filter. Addressed by https://github.com/opensearch-project/documentation-website/pull/6374 
- [x] 20230914 | /docs/2.6/security/configuration/disable/ | Please try to build and EXECUTE the docker container you propose. You will see that it fails - Fixed with https://github.com/opensearch-project/documentation-website/pull/5830
 - [x] 20231012 | /docs/latest/security/multi-tenancy/tenant-index/ | The global tenant is not a primary tenant -> are you meaning your private tenant? - Addressed by https://github.com/opensearch-project/documentation-website/pull/6373
- [x] 20230726 | /docs/latest/security/access-control/permissions/ | indices:admin/mappings/get 
Index permissions could have a description or something - Addressed by https://github.com/opensearch-project/documentation-website/pull/6404
- [x] 20231026 | /docs/1.3/security/access-control/default-action-groups/ | not enough details -Addressed by https://github.com/opensearch-project/documentation-website/pull/6405
- [x] 20231107 | /docs/latest/security/authentication-backends/proxy/ | Even though everything is set, I am still facing 401 error -x https://github.com/opensearch-project/documentation-website/pull/6952
- [x] 20230825 | /docs/latest/security/access-control/document-level-security/ | This document did not provide information on how edit the document level permissions. In progress - Addressed by https://github.com/opensearch-project/documentation-website/pull/6606
- [x] 20231130  | /docs/latest/security/configuration/system-indices/ | "When Security is installed" is not a helpful condition. If one asks "How to install security" using the built in search at the top "When Security is installed" is not a helpful condition. If one asks "How to install security" using the built in search at the top of the page one gets a long list of "hits". None of the top ones seems to answer the questions and studying all of them would take days. So the list of hits is actually worthless.Please underpin the phrase with a link. (in progress) - Addressed by https://github.com/opensearch-project/documentation-website/pull/6605
- [x] 20231026 | /docs/latest/api-reference/document-apis/index-document/ | please give a full detailed document with method type. what use put method? like this if describe that can easy to use a developer this apies.-x
~~- [ ] 20230811 | /docs/latest/security/access-control/permissions/ | No example code~~
- [x] 20230503 |  /docs/latest/security/access-control/cross-cluster-search/ |What about other details? What if my port is proxied? https://github.com/opensearch-project/documentation-website/pull/6952
- [x] 20230804 | /docs/latest/security/access-control/cross-cluster-search/ | no information on remote clusters that are not docker managed - in progress - https://github.com/opensearch-project/documentation-website/pull/6657
- [x] 20231102 | /docs/latest/security/configuration/index/ | how do I do this in the UI if I am not using the docker image at the moment - in progress - https://github.com/opensearch-project/documentation-website/pull/6657
- [x] 20230811 | /docs/latest/security/access-control/cross-cluster-search/ | why is it docker centric - in progress - https://github.com/opensearch-project/documentation-website/pull/6657

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://opensearch.org/docs/latest/security/index/

**Comment by hdhalter** [comment]
This PR fixes a couple of the items. https://github.com/opensearch-project/documentation-website/issues/4315

**Comment by hdhalter** [comment]
In progress by @john-eliatra

**Comment by john-eliatra** [comment]
I can work on this.

**Comment by leanneeliatra** [comment]
PR submitted for multi-tenancy issues
1.  [20231012 | /docs/latest/security/multi-tenancy/tenant-index/ | The global tenant is not a primary tenant -> are you meaning your private tenant? -x](https://github.com/opensearch-project/documentation-website/pull/6373)
2.  [20230525 | /docs/latest/security/multi-tenancy/multi-tenancy-config/ | Is this for kibana or opensearch dashboards? n seems to override any sort filter.-x](https://github.com/opensearch-project/documentation-website/pull/6374)

**Comment by leanneeliatra** [comment]
PR created for  [20230825 | /docs/latest/security/access-control/document-level-security/ | This document did not provide information on how edit the document level permissions.
](https://github.com/opensearch-project/documentation-website/pull/6606)

**Comment by Anthony7774** [comment]
PR created for [20231130 | /docs/latest/security/configuration/system-indices/ | "When Security is installed" is not a helpful condition. If one asks "How to install security" using the built in search at the top "When Security is installed" is not a helpful condition. If one asks "How to install security" using the built in search at the top of the page one gets a long list of "hits". None of the top ones seems to answer the questions and studying all of them would take days. So the list of hits is actually worthless.Please underpin the phrase with a link. (in progress)](https://github.com/opensearch-project/documentation-website/pull/6605)

**Comment by leanneeliatra** [comment]
@hdhalter please assign me to this issue.

**Comment by hdhalter** [comment]
> I've been looking into _20230811 | /docs/latest/security/access-control/permissions/ | No example code_, from reading through the page, there are examples given. There are lists provided such as, [Alerting Permissions](https://opensearch.org/docs/latest/security/access-control/permissions/#alerting-permissions), [Asynchronous Search permissions](https://opensearch.org/docs/latest/security/access-control/permissions/#asynchronous-search-permissions), [Index State Management permissions](https://opensearch.org/docs/latest/security/access-control/permissions/#index-state-management-permissions), etc. At the top of those lists there are links to the relevant page where the examples are given e.g. [Alerting Permissions](https://opensearch.org/docs/latest/security/access-control/permissions/#alerting-permissions) shows the link See [Alerting API](https://opensearch.org/docs/latest/observing-your-data/alerting/api/) where the examples are given in further depth on the relevant page. cc @hdhalter

Thanks for looking at this, @leanneeliatra ! There were some updates to that topic after the comment was made. Let's close that one.

**Comment by leanneeliatra** [comment]
Brilliant thank you @hdhalter

**Comment by hdhalter** [comment]
All feedback has been addressed. Thanks, @AntonEliatra and @leanneeliatra !
