### ISSUE TITLE
Benchmarking on Graviton nodes

### ISSUE THREAD

**Issue by Cai-Chen** [opensearch-project/documentation-website#434]
I am comparing benchmark results on Graviton VS x86.

- Tool: rally
- Track: pmc
-  Instance: r5.2xlarge(volume IOPS 4500 in gp2) VS r6g.2xlarge(volume IOPS 4500 in gp3)

**Result**

Mean Throughput
Operation | unit | r5.2xlarge | r6g.2xlarge
-- | -- | -- | --
index-append  | docs/s | 1982.46 | 2865.43
default  | ops/s | 19.98 | 19.96
term  | ops/s | 19.99 | 19.96
phrase  | ops/s | 19.99 | 19.97
articles_monthly_agg_uncached  | ops/s | 19.93 | 19.94
articles_monthly_agg_cached  | ops/s | 20 | 19.99
scroll  | pages/s | 12.56 | 12.56

90th percentile latency 
Operation  | unit | r5.2xlarge | r6g.2xlarge
-- | -- | -- | --
default  | ms | 14.16 | 16.71
term  | ms | 13.56 | 15.08
phrase  | ms | 13.39 | 13.89
articles_monthly_agg_uncached  | ms | 16.10 | 16.44
articles_monthly_agg_cached  | ms | 7.54 | 8.25
scroll  | ms | 782.27 | 877.14
index-append  | ms | 3,666.45 | 2,545.25

index-append is better for throughput and latency on Graviton. But x86 performs better for other operations in terms of latency.

Has anyone got any ideas? Thanks

**Comment by jkowall** [comment]
> 



> What is the recommended number of shards on Graviton? And can you give more detail in which size of workload would be better to use EBS?

I would suggest 2 cores per shard, but once again if you are running single node (which is never what you run in production) then the test is likely not really valid. I would run on 3 node clusters minimally, and have 2/3 replicas. 

We do not run on EBS as the performance is too low, we only use local SSD. I would propose using local disk if you can versus EBS it will be a faster and lower latency since you aren't connecting to storage over the network. It will also be cheaper. Since Opensearch replicates data, there is no need to use EBS.

**Comment by Cai-Chen** [comment]
> > 
> 
> > What is the recommended number of shards on Graviton? And can you give more detail in which size of workload would be better to use EBS?
> 
> I would suggest 2 cores per shard, but once again if you are running single node (which is never what you run in production) then the test is likely not really valid. I would run on 3 node clusters minimally, and have 2/3 replicas.
> 
> We do not run on EBS as the performance is too low, we only use local SSD. I would propose using local disk if you can versus EBS it will be a faster and lower latency since you aren't connecting to storage over the network. It will also be cheaper. Since Opensearch replicates data, there is no need to use EBS.

I was using 3 node cluster to test. And I did a test again with more `number_of_shards` from default 5 to 10, but result is same. 

In terms of EBS/Local SSD, i was using EBS for both Graviton and x86 which has same IOPS. I can do another test in Local SSD for both, but it cannot explain why Graviton performs worse than x86 in EBS.

**Comment by Cai-Chen** [comment]
BTW, I did a test on AWS as well.
https://github.com/aws/aws-graviton-getting-started/issues/200#issue-1163217406

**Comment by jkowall** [comment]
Graviton SSD is using Nitro, which should be much faster and lower latency. Every system has a constraint, and I am pretty sure you are hitting a network constraint here. Have you pulled stats from the interfaces or other system level metrics?

**Comment by JeffH-AWS** [comment]
There isn't an ask from the documentation team here. This repo is also for the OpenSearch Project, not for Amazon OpenSearch Service which is where the instance class and EBS discussion would apply.
