### ISSUE TITLE
[DOC] Install instructions omit starting opensearch

### ISSUE THREAD

**Issue by am312** [opensearch-project/documentation-website#4342]
**What do you want to do?**
 
- [ x ] Request a change to existing documentation
- [ x ] Report a technical problem with the documentation

Under Option 2, between steps 3 & 4 there should be a step to start opensearch.
 (https://opensearch.org/docs/latest/install-and-configure/install-opensearch/tar/)

**Comment by hdhalter** [comment]
@peterzhuamazon - can ypu provide some info for this? I'm not sure what to add. Himanshu said the path might be wrong, too: should be  /opensearch in that location. Thanks.

**Comment by peterzhuamazon** [comment]
@hdhalter 

Step2 of this: https://github.com/opensearch-project/documentation-website/blob/main/_install-and-configure/install-opensearch/tar.md#option-1-test-your-opensearch-settings-with-security-enabled

Should change `Run the demo security script.` to `Run OpenSearch Startup script with security demo configuration`.
