### ISSUE TITLE
[DOC] k-NN Clear Cache API

### ISSUE THREAD

**Issue by naveentatikonda** [opensearch-project/documentation-website#4346]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
As of today, we don’t have an API to evict a given K-NN index out of native memory. Currently, the possible ways to clear indices out of the cache is by either deleting the index or by setting a couple of knn cluster settings which will remove the indices out of cache if they are idle for a given amount of time.

Adding this external API will help users to clear the cache of their k-NN indices by themselves. As of now, we are planning to release this feature in v2.12 or later due to AppSec.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/k-NN/issues/333

**Comment by kolchfa-aws** [comment]
Moved to 2.11 per SME

**Comment by naveentatikonda** [comment]
Please change the label to v2.12

**Comment by vamshin** [comment]
Will add new release label once we have clarity on the release for this feature

**Comment by hdhalter** [comment]
From Naveen:  This feature still needs to go through AppSec and it is not getting prioritized by AppSec engineers due to ReInvent. Might go in 2.12 or will be postponed to future releases.

**Comment by hdhalter** [comment]
Tagging as 2.12 just in case.

**Comment by hdhalter** [comment]
Vamshi confirmed that this is not 2.12.

**Comment by hdhalter** [comment]
@vamshin - Confirming that this going out in 2.13? The associated issue has 2.13 as the release train. Thanks!

**Comment by hdhalter** [comment]
Hi @naveentatikonda - Is this feature going in 2.14?

**Comment by naveentatikonda** [comment]
> Hi @naveentatikonda - Is this feature going in 2.14?

yes @hdhalter. I will create the PR for documentation by Friday. Thanks!
