### ISSUE TITLE
[Blog] Search Pipelines

### ISSUE THREAD

**Issue by macohen** [opensearch-project/documentation-website#4347]
This is for a blog post featuring Search Pipelines and will discuss how they work, some use cases for them, and how to create your own search processors.

**Comment by Naarcha-AWS** [comment]
We'll likely need to transfer this to the project-website repo, sense that's where blogs are published.

**Comment by hdhalter** [comment]
Yes, please add to https://github.com/opensearch-project/project-website/issues. Thanks!

**Comment by macohen** [comment]
just going to close and open a new one in the right place.
