### ISSUE TITLE
[DOC] Score Normalization and Combination for Semantic Search

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/documentation-website#4351]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation

**Tell us about your request.** 
We are introducing ability to combine scores from multiple queries in one query, with control on how scores are normalized (as  for each query score can be at different scale) and how score are combined (e.g. sum up or take average of scores for the same doc from different queries). Typically customers are doing this today in external system after running multiple queries independently, we want to provide a one stop point for this in OpenSearch.
As part of this feature we create new Hybrid query type (neural-search plugin), extend core OpenSearch to allow adding new type of injector processor to search pipelines and registering one new processor (part of neural-search plugin)
Feature is planned for 2.10 release.

**What other resources are available?** 
RFC that describes the approach at high level: https://github.com/opensearch-project/neural-search/issues/126
RFC for new phase in search pipelines: https://github.com/opensearch-project/neural-search/issues/152

**Comment by hdhalter** [comment]
Fixes https://github.com/opensearch-project/documentation-website/issues/4406
