### ISSUE TITLE
[DOC] Update documentation on Management navigation changes

### ISSUE THREAD

**Issue by kamingleung** [opensearch-project/documentation-website#4364]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
In 2.9, we will be making updates to the hamburger navigation menu. We will move the following items from OpenSearch Plugins section to the Management section of the nav:
- Index Management
- Snapshot Management
- Security
- Notifications
- We will also rename Stack Management to Dashboards Management.

Any documentation that reference the navigation such as UI instructions and screenshots will need to be updated.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4133

**Comment by kamingleung** [comment]
Tracking pages that need updates:

### OpenSearch Dashboards ###

[**Index management in Dashboards > Notifications**](https://opensearch.org/docs/latest/dashboards/im-dashboards/notifications/)
- [ ] Update to `To get started, select *Management* > *Index Management* from the top menu. Under *Index Management*, select *Notification settings*.`


[**Snapshot management in Dashboards > Any reference**](https://opensearch.org/docs/latest/dashboards/sm-dashboards/)
- [ ] Update to `On the top menu bar, go to *Management > Snapshot Management*.`


[**Dev Tools**](https://opensearch.org/docs/latest/dashboards/dev-tools/index-dev/)
- [ ] Update screenshot with new navigation menu


[**Dev Tools > Running queries in Dev Tools console**](https://opensearch.org/docs/latest/dashboards/dev-tools/run-queries/)
- [ ] Update screenshot with new navigation menu


[**Adding multiple data sources**](https://opensearch.org/docs/latest/dashboards/discover/multi-data-sources/)
[**Using VisBuilder**](https://opensearch.org/docs/latest/dashboards/visualize/visbuilder/)
[**Exploring data > Setting the time filter**](https://opensearch.org/docs/latest/dashboards/discover/time-filter/)
- [ ] Replace any references of “*Stack Management”* to *"Dashboards Management"*


### Security in OpenSearch ###

[**OpenSearch Dashboards multi-tenancy > Multi-tenancy aggregate view for saved objects**](https://opensearch.org/docs/latest/security/multi-tenancy/mt-agg-view/)
- [ ] Replace any references of “*Stack Management”* to *"Dashboards Management"*
- [ ] Update screenshot with new navigation menu

**Comment by vagimeli** [comment]
@cwillum Let's sync about how to handle the security-related changes.

**Comment by vagimeli** [comment]
@kamingleung Will you share the testing environment link with me? Thanks!

**Comment by cwillum** [comment]
@vagimeli I think I should be able to cut a separate PR from this issue (Heather pointed out that I should be careful not to let it close the issue when I merge it). When an environment/endpoint is available that represents the menu changes, I'll capture a screenshot of the changes for multi-tenancy aggregate view and alter text where needed.
@kamingleung Thanks for identifying and listing the areas of documentation that need attention, particularly for me the security related issue. That change makes sense.

**Comment by kamingleung** [comment]
@vagimeli UPDATE ON 2.9. Index management and Snapshots management nav changes did not make it to the 2.9 release due to technical issues. Can we remove any changes regarding to Index Management and Snapshot Management defined in this issue? Thanks.

**Comment by vagimeli** [comment]
Reverted changes in #4550; holding for 2.10.

**Comment by hdhalter** [comment]
@vagimeli - can we close this since the changes went into 2.9? Thanks.

**Comment by hdhalter** [comment]
Removing Chris as assignee since security changes are already implemented.

**Comment by vagimeli** [comment]
@kamingleung Do we have a test environment I can use to take screenshots of the updated UI? Thanks!

**Comment by vagimeli** [comment]
@kamingleung Do we have a test environment I can use to update the UI screenshots for documentation? Thanks!
