### ISSUE TITLE
[DOC] Update API documentation for Correlation Engine in Security Analytics

### ISSUE THREAD

**Issue by getsaurabh02** [opensearch-project/documentation-website#4375]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 
We launched the Correlation Engine in 2.7 as experimental and published the documentation for users to try out this feature from the Security Analytics Dashbpard. 
https://opensearch.org/docs/latest/security-analytics/usage/correlation-graph/

We also need to publish the API documentation for the same as part of the OS 2.9 release. 

**What other resources are available?**

RFC In Security Analytics https://github.com/opensearch-project/security-analytics/issues/369
RFC in Core : https://github.com/opensearch-project/OpenSearch/issues/6779
cc: @sbcd90

**Comment by cwillum** [comment]
Correlation Engine API was documented for 2.9 in PR #4549
