### ISSUE TITLE
[DOC]  Add documentation for OnBehalfOf Authentication

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/documentation-website#4388]
**What do you want to do?**
 
- [ ] ~Request a change to existing documentation~
- [x] Add new documentation
- [ ] ~Report a technical problem with the documentation~
- [ ] ~Other~

### Description of the Feature 
the security team has opted to develop an on-behalf-of Json web token for managing authentication requests between the user's client and the extension just in time. For the initial extensions design, these tokens will allow the extension to interact with the OpenSearch cluster using the same privileges as the initiating user, that’s the reason it is named as “on-behalf-of”. However, since this token doesn’t have any restrictions in place, it also has the capability of letting a service operate as if they are the original user for some window of time. Which means this generic feature is not limited extension related use cases..

For the most of the scenarios, this obo token will be used just-in-time which means that the token is issued just before it is needed for usage. The token will have a configurable short time window of validity after which it is expired and no longer good for use. If the extension REST handler finished quickly, the token may still be valid after the request is done. If the extension REST handler takes a long time then there is a risk that the token will expire before the request has been fully handled. There may need to be a mechanism in place to refresh a token or have certain handlers be able to obtain tokens with a longer window of validity, for example I think 5 minutes is reasonable and most handlers should be able to handle a request in a short period of time.

#### Generic Usage vs. Extension Project ###
Just-in-time UsageFor extensions project, the security team has opted to develop an on-behalf-of Json web token for managing authentication requests between the user's client and the extension just in time. For the initial extensions design, these tokens will allow the extension to interact with the OpenSearch cluster using the same privileges as the initiating user, that’s the reason it is named as “on-behalf-of”. However, since this token doesn’t have any restrictions in place, it also has the capability of letting a service operate as if they are the original user for some window of time. Which means this generic feature is not limited extension related use cases..

For the most of the scenarios, this obo token will be used just-in-time which means that the token is issued just before it is needed for usage. The token will have a configurable short time window of validity after which it is expired and no longer good for use. If the extension REST handler finished quickly, the token may still be valid after the request is done. If the extension REST handler takes a long time then there is a risk that the token will expire before the request has been fully handled. There may need to be a mechanism in place to refresh a token or have certain handlers be able to obtain tokens with a longer window of validity, for example I think 5 minutes is reasonable and most handlers should be able to handle a request in a short period of time.

### Token’s Payload
```
Issuer (iss): OpenSearch Cluster Identifier
Issue-at (iat): Current time of issuing this token
Expiry (exp): Expiration time
Subject (sub): User ID
Audience (aud): Extension’s unique identifier
Roles: Security Privilege Evaluation
```
### Roles in OBO's Payload ###
Plugin Backward Compatibility Mode (BWC Mode)
```
BWC Mode OFF (default):
Encrypted roles (er)
BWC Mode ON:
Decrypted roles in plain-text (dr)
Decrypted backend roles in plain-text (dbr)
```
### Configuration in `Config.yml`
```
on_behalf_of:
    signing_key: xxxxxxxxxx
    encryption_key: xxxxxxxx
```

### References ###
- https://github.com/opensearch-project/security/issues/2573
- https://github.com/opensearch-project/security/issues/2865

**Comment by cwillum** [comment]
@RyanL1997 A big thanks for adding this issue, and especially for the thoroughly detailed information on the feature.

**Comment by cwillum** [comment]
Pausing this for 2.9. If it doesn't get fresh attention between release cycles, it will be an issue for 2.10.

**Comment by hdhalter** [comment]
@RyanL1997 - can you please add this to the roadmap? Thanks.

**Comment by peternied** [comment]
@cwillum This is not going to make it for 2.10, moving to 2.11 - sorry for the shuffle.

CC: @davidlago @hdhalter

**Comment by RyanL1997** [comment]
Hi @cwillum and @hdhalter, thanks for the following up. This issue is a bit outdated and we are preparing a documentation guidance for both service accounts + obo on https://github.com/opensearch-project/security/issues/3290. Me and @scrawfor99 will update everything in the comment section of that issue and we will let you know when everything is ready.

**Comment by RyanL1997** [comment]
Hi @hdhalter, just a friendly reminder that our [documentation guidance](https://github.com/opensearch-project/security/issues/3290) is ready. Please feel free to contact me if you guys have some questions.

**Comment by peternied** [comment]
Note; we need to make sure we are consistent with the casing/naming of the feature it is my understanding it is `OnBehalfOf` @RyanL1997 if you agree can you see about making sure this is consistent?
