### ISSUE TITLE
[DOC] Segment Replication + Remote Storage

### ISSUE THREAD

**Issue by mch2** [opensearch-project/documentation-website#4405]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Segment Replication and Remote storage (experimental) have their own sets of documentation.  We would like to include new documentation covering the integration of these two features (for release in 2.9), where segment replication uses a remote store to copy out segments to replicas. The meta issue & design proposal is here - https://github.com/opensearch-project/OpenSearch/issues/4448

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Test plan - https://github.com/opensearch-project/OpenSearch/issues/8109 where we will include results to include in docs.

There are no new APIs for this feature, however we will need to document the performance implications along with configuration options.

Configuration:
If remote store is enabled, *all* indices will internally use segment replication to copy to replicas.  There will be no index level override option that is provide with node-node segment replication.

**Comment by Naarcha-AWS** [comment]
Status is currently in RED. Will update on July 5 with a better idea of if this will make 2.9.

**Comment by hdhalter** [comment]
This is moving to 2.10 as reported in the project call on 6/6.

**Comment by dreamer-89** [comment]
@Naarcha-AWS @hdhalter : I see some additional documentation changes/addition for 2.10.0 release not mentioned here, captured in #5011. Please also include those changes for the documentation PR. Let know in you need more details to open the doc PR.
