### ISSUE TITLE
[DOC] SearchPhaseResults Processor

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/documentation-website#4406]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation

**Tell us about your request.** 
We are extending core OpenSearch to allow adding new type of injector processor to exiting search pipelines. As part of this feature we're introducing new Processor Interface which will run in between the Phases of Search. This will allow components (like plugins) to provide logic that transforms the results retrieved from one phase before it goes to next phase at the Coordinator Node Level.
Feature is planned for 2.9 release.

**What other resources are available?** 
RFC for new phase in search pipelines: https://github.com/opensearch-project/neural-search/issues/152
RFC for search pipelines at high level: https://github.com/opensearch-project/search-processor/issues/80

**Comment by navneet1v** [comment]
Discussed with @vamshin, for SearchPhaseResultsProcessor we don’t need documentation in 2.9 as we are not enabling any use-cases with the SearchPhaseResultsProcessor. 

We can do this in 2.10 with the launch of https://github.com/opensearch-project/search-processor/issues/80 (Doc Issue: https://github.com/opensearch-project/documentation-website/issues/4351 )

**Comment by hdhalter** [comment]
Closing, as this was addressed in https://github.com/opensearch-project/documentation-website/issues/4351
