### ISSUE TITLE
[DOC] Update documentation of metrics analytics.

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/documentation-website#4408]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The ask is to change the documentation provided here: https://opensearch.org/docs/latest/observing-your-data/prometheusmetrics/
The way we configure datasources has been moved to Rest APIs mentioned here: https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/admin/datasources.rst

 This impacts all the versions >= 2.7

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks so much for updating this, @vamsi-amazon! I will close this issue.
