### ISSUE TITLE
[FEATURE] Update SQL/PPL docs for 1.3

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/documentation-website#441]
@keithhc2 We added a few new features in SQL/PPL and have updated documentation in our repo. The docs in this repo should also be updated. Are we the ones who should do this? And how were the other docs converted to markdown from rst? thanks

Documentation updates:
- add date_nanos data type: https://github.com/opensearch-project/sql/pull/360/files#diff-e4d5153d4f3ee0bebe5c5f00d573beae96e9eb0ee431da89c3cc41762ca3fcb2
- add parse command: https://github.com/opensearch-project/sql/pull/411/files#diff-d1e21c8ad5d6e5e687a31d1c69ec88be957855eed4aef2b89cfe98659a55d635
- add cast function: https://github.com/opensearch-project/sql/pull/433/files#diff-2cd6bff3d6c2cac7daebd7d067ebba2c545feb4c8332201f6bf78cede14b0b52
- https://github.com/opensearch-project/sql/pull/486
- https://github.com/opensearch-project/sql/pull/456

**Comment by Naarcha-AWS** [comment]
Closing in advance of 1.3.
