### ISSUE TITLE
[DOC] Discover 2.0

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/documentation-website#4418]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
As a part of the Data explorer and Deangularization project we are updating the existing Discover application. As a part of this upgrade existing documentation that references discover pages need to be updated. there is also a lack of documentation about how to use the Discover tool that can be added as a part of this update. The new experience is slated to be released in 2.10

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4165

**Comment by hdhalter** [comment]
Duplicate

**Comment by vagimeli** [comment]
@ashwin-pc Is this on schedule for 2.10?

**Comment by ashwin-pc** [comment]
@hdhalter can you point me to the duplicate issue?

**Comment by hdhalter** [comment]
https://github.com/opensearch-project/documentation-website/issues/4686
