### ISSUE TITLE
[DOC] Legacy Clients Section Incorrect

### ISSUE THREAD

**Issue by RLashofRegas** [opensearch-project/documentation-website#4419]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 As per the [Legacy clients table](https://opensearch.org/docs/latest/clients/index/#legacy-clients), ElasticSearch Java High-Level Rest Client version 7.13.4 _should_ work with OpenSearch. I understand that this is a best effort, but even a simple request of indexing a document fails as of OpenSearch 1.3. In OpenSearch 1.3 the response body for the Index Document API changed to no longer include the `_type` field which breaks compatibility with this client.

**Comment by hdhalter** [comment]
Closing this issue since it has been moved to the opensearch-java repo: https://github.com/opensearch-project/opensearch-java/issues/565.
