### ISSUE TITLE
[DOC] 2.9 Enhancement to Alerting plugin documentation

### ISSUE THREAD

**Issue by AWSHurneyt** [opensearch-project/documentation-website#4437]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 For the `2.9` release, we're looking to make an enhancement to the [cluster metrics monitors](https://opensearch.org/docs/latest/observing-your-data/alerting/monitors/#create-cluster-metrics-monitor) feature. We're planning to add support for the [cat/shards](https://opensearch.org/docs/latest/api-reference/cat/cat-shards/) and [cat/indices](https://opensearch.org/docs/latest/api-reference/cat/cat-indices/) API, and would like the [list of supported API](https://opensearch.org/docs/latest/observing-your-data/alerting/monitors/#supported-apis) to be updated to reflect that enhancement.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Issue in the alerting plugin tracking this enhancement - https://github.com/opensearch-project/alerting/issues/611

**Comment by hdhalter** [comment]
@vagimeli - do you mind taking this one? Thanks.
