### ISSUE TITLE
[DOC] Cross Cluster search support for Alerting Plugin

### ISSUE THREAD

**Issue by mnkugler** [opensearch-project/documentation-website#4438]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Alerting documentation would need to be updated with details on cross cluster search support. Our plan is to introduce support for Cross Cluster search in Alerting Plugins. Currently, customers face limitations when performing a cross cluster search call through a monitor, as the plugin user does not possess the necessary permissions to access the remote cluster. Our service team has verified that this is the anticipated behavior in the current state. We will enhance this functionality to enable alerting-monitor searches to be carried out seamlessly across multiple clusters.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc. https://github.com/opensearch-project/alerting-dashboards-plugin/issues/570

**Comment by hdhalter** [comment]
Thanks, Monica. What version are we targeting for this feature?

**Comment by mnkugler** [comment]
@hdhalter 2.10 Thanks Heather!

**Comment by vagimeli** [comment]
Hi @mnkugler, Is this feature on track for 2.11?

**Comment by mnkugler** [comment]
@vagimeli It's likely 2.12 now

**Comment by hdhalter** [comment]
@praveensameneni - Can you please confirm that this is going in 2.12?

**Comment by hdhalter** [comment]
From Praveen 11/10: Hi Heather, yes, planning to get it out in 2.12.

**Comment by hdhalter** [comment]
@AWSHurneyt - Can you please help with creating the PR for this feature? Please let me know if someone else should be responsible. Thanks!

**Comment by vagimeli** [comment]
Hi @AWSHurneyt: I'm following up on the status of this feature. Is it on track for 2.12? If so, has a documentation PR been created? Thank you!

**Comment by AWSHurneyt** [comment]
Hi @vagimeli ,
A documentation PR has not been created yet. Let me check on the status of the security testing for the feature, and reply back afterwards. Whether this feature releases in 2.12 or 2.13 will depend on whether we can get the testing scheduled.

**Comment by hdhalter** [comment]
Hi @AWSHurneyt - Do you have an update on the status of this feature?

**Comment by AWSHurneyt** [comment]
We're currently targeting experimental for 2.12, and GA for 2.13.

**Comment by bbarani** [comment]
@AWSHurneyt Does this require documentation in 2.12.0? I assume you need to add documentation around this features even if its experimental?

**Comment by AWSHurneyt** [comment]
@bbarani Correct, I'll be creating a documentation PR.

**Comment by vagimeli** [comment]
@AWSHurneyt Thanks! Please tag me when it's ready for doc review. I'll move the content through doc and editorial reviews and merge the PR.

**Comment by AWSHurneyt** [comment]
@vagimeli Thank you! Here's the PR https://github.com/opensearch-project/documentation-website/pull/6350
