### ISSUE TITLE
[FEATURE] ISM new parameter for explain API

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/documentation-website#445]
The ISM policy currently applied to the index could be an **outdated** one if the user update the policy using [the update policy API](https://opensearch.org/docs/latest/im-plugin/ism/api/#update-policy). 
We add a parameter to [explain API](https://opensearch.org/docs/latest/im-plugin/ism/api/#explain-index) in this [PR](https://github.com/opensearch-project/index-management/pull/251). So user can use this to see the currently applied policy, and can compare it with the result of [get policy API](https://opensearch.org/docs/latest/im-plugin/ism/api/#get-policy) to know if the currently applied policy is an outdated one.

For the documentation, we need to mention this newly added parameter of explain API releasing in 1.3. 
And the problem of outdated applied policy should be mentioned in update policy API, so that user can know this when they are updating the policy.

**Comment by keithhc2** [comment]
Closed with #447
