### ISSUE TITLE
[DOC] Feedback on snapshot management API

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#4473]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Feedback on 20230628:

 /docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/sm-api/

"Sorry guys, but you have a bad Bug in your Snapshot Management API. To create a snapshot Policy with  the dashboard UI is no Problem, but when you want to create a Policy directly with a API Call and with curl it Fails with: Failed to parse object: expecting token of type [START_OBJECT] but found [VALUE_STRING] The Json that I provide is def.correct"

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Here is the page: https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/sm-api/

**Comment by hdhalter** [comment]
@bowenlan-amzn - Hi Bowen, we received some feedback about the snapshot management API. Can you please test it and let me know if there is anything we should change in our documentation? Thank you!

**Comment by bowenlan-amzn** [comment]
Hi, thanks for getting customer feedback. This looks to be an issue that can be re-created in IM repository https://github.com/opensearch-project/index-management/issues

Please ask customer to provide the API request sample for us to reproduce the issue. Currently we don't have enough info to do any further investigation.

**Comment by hdhalter** [comment]
@bowenlan-amzn - we don't collect customer names that leave feedback, so cannot inquire any further. I can recreate in that repo, though, if someone can test our example code?

**Comment by hdhalter** [comment]
Closing, since we can't reproduce.
