### ISSUE TITLE
[FEATURE] OpenSearch 1.3 release related changes

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/documentation-website#448]
As part of OpenSearch 1.3 release, there are changes which needs corresponding update on documentation. Using this issue to track all those changes (issues/PR). A few of them are self explanatory while other needs more inputs from the author around external wordings. 

1. https://github.com/opensearch-project/OpenSearch/issues/1711
2. https://github.com/opensearch-project/OpenSearch/pull/1981
3. https://github.com/opensearch-project/OpenSearch/pull/1978
4. https://github.com/opensearch-project/OpenSearch/pull/1989
5. https://github.com/opensearch-project/OpenSearch/pull/1916
6. https://github.com/opensearch-project/OpenSearch/pull/1606

**Comment by dblock** [comment]
Looks all done, closing.
