### ISSUE TITLE
[DOC] Project readme incorrect

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/documentation-website#4498]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
The project readme today asks the user to install ruby version 2.6 but this does not work and need to be updated to 2.7. With 2.6 installing the bundles results in this error

```sh
bundle install             
Your RubyGems version (3.0.9) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
Fetching gem metadata from http://rubygems.org/............
Resolving dependencies...
Could not find compatible versions

Because every version of ruby-link-checker depends on Ruby >= 2.7
  and Gemfile depends on ruby-link-checker >= 0,
  Ruby >= 2.7 is required.
So, because current Ruby version is = 2.6.6,
  version solving has failed.
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
We are rewriting the contributing and readme files, so this will be addressed there. Thanks for letting us know, @ashwin-pc !  https://github.com/opensearch-project/documentation-website/pull/4416

**Comment by hdhalter** [comment]
This is updated in the contributing.md file: https://github.com/opensearch-project/documentation-website/blob/main/CONTRIBUTING.md. Thanks @ashwin-pc!
