### ISSUE TITLE
[DOC]: Update Mappings to support Open Cybersecurity Schema Framework (OCSF)

### ISSUE THREAD

**Issue by praveensameneni** [opensearch-project/documentation-website#4500]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We are adding support for OCSF schema to VPC Flow logs, CloudTrail and Route53 (DNS) logs

- [ ] Update field mapping to include OCSF field mappings associated with Amazon Security Lake OCSF
- [ ] Add API documentation for correlation engine.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/security-analytics/issues/459

**Comment by hdhalter** [comment]
Thanks, @praveensameneni . Which version is this targeting?

**Comment by praveensameneni** [comment]
We are targeting 2.9

**Comment by hdhalter** [comment]
@cwillum - Chris, can you please take a look at this and let me know if we will be able to document this for 2.9?

**Comment by cwillum** [comment]
@hdhalter I'm meeting with dev today to discuss these updates. After that I'll have a better idea of the breadth of the updates required.
