### ISSUE TITLE
[DOC] Search Pipelines - GA

### ISSUE THREAD

**Issue by macohen** [opensearch-project/documentation-website#4502]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Search Pipelines are going GA in 2.9 so we want to update all related documentation to remove the experimental tags.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://opensearch.org/docs/latest/search-plugins/search-pipelines/index/

cc:@msfroh, @noCharger, @mingshl, @sejli

**Comment by noCharger** [comment]
Major changes
1. Feature flag - default to true
2. Ad-hoc pipeline
3. Ignore failure flag
