### ISSUE TITLE
[DOC] Search Pipeline Metrics

### ISSUE THREAD

**Issue by macohen** [opensearch-project/documentation-website#4511]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Relating to [Search pipeline metrics (at least on par w/ ingestion pipeline metrics).#6723](https://github.com/opensearch-project/OpenSearch/issues/6723), we want to add a page under Search Pipelines that show what metrics we are exposing. 

This affects 2.9 only as this feature is new to 2.9. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by noCharger** [comment]
Metrics overview https://github.com/opensearch-project/OpenSearch/issues/6723#issuecomment-1509165529
PR https://github.com/opensearch-project/OpenSearch/pull/8053

**Comment by noCharger** [comment]
1. Example request / response
2. Field type
3. Meaning of each field

**Comment by noCharger** [comment]
https://opensearch.org/docs/latest/api-reference/nodes-apis/nodes-stats/

1. The following table lists all available metric groups.

```
search_pipeline |  Statistics about search pipelines.
```
