### ISSUE TITLE
[DOC] New system property: opensearch.xcontent.fast_double_writer

### ISSUE THREAD

**Issue by mgodwan** [opensearch-project/documentation-website#4513]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 
 
Provide the documentation for recently introduced new system property `opensearch.xcontent.fast_double_writer` that allows to configure using fast double serialization features which provides better performance for serialization of floating point numbers.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

Covered in issue: https://github.com/opensearch-project/OpenSearch/issues/7822

**Comment by hdhalter** [comment]
Hi @mgodwan - Is this being introduced in version 2.9?

**Comment by mgodwan** [comment]
Yes, The changes have been merged already: https://github.com/opensearch-project/OpenSearch/pull/8467#event-9746205752

**Comment by vagimeli** [comment]
@mgodwan Where would the new documentation be published on the [doc site](https://opensearch.org/docs/latest/)? Also, will you link me to the feature brief and dev docs?

**Comment by andrross** [comment]
First, the issue description is incorrect: the system setting is `opensearch.xcontent.fast_double_writer` (no `.enabled` suffix). [code link](https://github.com/opensearch-project/OpenSearch/blob/2.x/libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContent.java#L65)

> Also, will you link me to the feature brief and dev docs?

@vagimeli There is no feature brief to my knowledge. This is a pretty low-level performance improvement and a system setting was added to alleviate concerns around potential incompatibilities.

I think it is logical to group it with the existing `opensearch.xcontent` setting documentation. I would document this something like the following:

- `opensearch.xcontent.fast_double_writer=[true|false]`

By default, OpenSearch uses the floating point parsing capability built in to the Java Runtime Environment. Set this value to `true` to configure OpenSearch to use the [FastDoubleParser](https://github.com/wrandelshofer/FastDoubleParser) library to parse floating point numbers, which has shown to be faster in many cases.

---

@mgodwan A couple questions for you:

- This property defaults to `false`. Is that correct? The original issue talked about adding a property to enable users to opt out on 2.x versions, but it was implemented as an opt in. Please confirm that this is correct.
- Can you give some guidance as to when a user should or should not enable this setting? I think the testing has shown it to be faster, so why would a user not want to set this?

**Comment by mgodwan** [comment]
Thanks @andrross for pointing to the correct name of the property.
I've updated the issue title/description.


> Where would the new documentation be published on the [doc site](https://opensearch.org/docs/latest/)? Should it be added to https://opensearch.org/docs/latest/install-and-configure/install-opensearch/index/#important-system-properties?

@vagimeli Yes, this seems to the correct place since we are already adding other system properties related to xcontent in the same place.


> This property defaults to false. Is that correct? The original issue talked about adding a property to enable users to opt out on 2.x versions, but it was implemented as an opt in. Please confirm that this is correct.

@andrross Yes, we decided to make it an opt-in property to reduce the blast radius. This property only deals with floating point serialization (and not parsing which is always enabled as we didn't observe differences in the parsing of floating point numbers compare to java code)


> Can you give some guidance as to when a user should or should not enable this setting? I think the testing has shown it to be faster, so why would a user not want to set this?

Possible description we can add for this can be:

The property can be set  to determine whether to use standard Java code to write floats/doubles (default) or use the Schubfach algorithm which is faster. The latter approach may lead to small differences in the precision of the float/double that is written to the JSON output.
