### ISSUE TITLE
[DOC] Unnecessary `expose` property in Docker Compose file

### ISSUE THREAD

**Issue by glen-84** [opensearch-project/documentation-website#4538]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

What is the purpose of the `expose` property in the Docker Compose file, if `ports` is already set?

https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

- https://stackoverflow.com/questions/40801772/what-is-the-difference-between-ports-and-expose-in-docker-compose
- https://www.baeldung.com/ops/docker-compose-expose-vs-ports

**Comment by unfinishednemesis** [comment]
We need to expose the port so that the application is accessible externally via that port.

**Comment by glen-84** [comment]
@unfinishednemesis The port is already exposed via the `ports` option. Try it without the `expose`.

**Comment by unfinishednemesis** [comment]
thanks @glen-84 , yeah it not required -
"The EXPOSE keyword is primarily a no-op. It's informative ("this image will offer services on these ports"), but it doesn't have any operational impact."

**Comment by hdhalter** [comment]
Thanks for entering this issue, @glen-84! You are correct that the expose property is not typically required, but may be  needed for earlier versions of Docker. We will not take any action to remove it at this time, so I will close this issue. Have a great day!
