### ISSUE TITLE
[DOC] `exchange_key` should be 64 bytes rather than 32 characters

### ISSUE THREAD

**Issue by chibacchie** [opensearch-project/documentation-website#4545]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
In the SAML authentication backend document, requirement for `exchange_key` is described as follows:

https://github.com/opensearch-project/documentation-website/blob/3567e8b90a46c50ea59f9dc4ddbbf529fbc41eb3/_security/authentication-backends/saml.md?plain=1#L227

However, according to the code below, the algorithm seems HS512 (HMAC using SHA-512) and the minimum key length should be 64 bytes (as recommended in RFC 2104). In addition, it would be better to mention that the key should be base64 URL encoded.

https://github.com/opensearch-project/security/blob/0e6608d938af44b8db31440f94cfbb39d9a97d98/src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java#L274

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

none.

**Comment by john-eliatra** [comment]
I can take this. Thanks, John

**Comment by john-eliatra** [comment]
Being reviewed internally by Eliatra team.
