### ISSUE TITLE
[DOC] Update Alerting > Monitors documentation

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#4547]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Content gaps: Updates to Monitors and Notifications documentation for readability, accuracy of information, and elimination of redundancy

Schedule: Throughout August 2023

Next steps: @vagimeli drafting content strategy and outline; meeting TBD with SMEs to define schedule and review process 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
POCs: @ohltyler @AWSHurneyt @lezzago @brijos

**Comment by hdhalter** [comment]
Closing as complete.
