### ISSUE TITLE
[DOC]Link keystore and truststore files documentation with related securityadmin script documentation 

### ISSUE THREAD

**Issue by cwillum** [opensearch-project/documentation-website#4578]
**What do you want to do?**
Before updating the Security plugin with configured [keystore and truststore files](https://opensearch.org/docs/latest/security/configuration/security-admin/#using-securityadmin-with-keystore-and-truststore-files) using the securityadmin script, a user should be made aware of the actual [keystore and truststore file settings](https://opensearch.org/docs/latest/security/configuration/tls/#keystore-and-truststore-files) that configure their location and passwords. These separate pages of documentation should be linked to facilitate the process.

When making these updates, it's probably a good idea to look into whether the upcoming [Authorization in REST layer](https://github.com/opensearch-project/documentation-website/issues/4381) feature will have an impact on the current information and guidance. 
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**

Link these two sources of information and check whether the current information needs to be updated.
 
**What other resources are available?**

[Authorization in the REST layer](https://github.com/opensearch-project/security/issues/2590)

**Comment by seashman** [comment]
It looks like keystore CLI ommands work about the same as the elasticsearch-keystore: https://www.elastic.co/guide/en/elasticsearch/reference/current/elasticsearch-keystore.html. It would be good to include how to use the keystore CLI to add credentials for plugins.

**Comment by AntonEliatra** [comment]
@hdhalter I'll pick this one up

**Comment by AntonEliatra** [comment]
PR raised https://github.com/opensearch-project/documentation-website/pull/7015
