### ISSUE TITLE
[DOC] Update security analytics engine documentation

### ISSUE THREAD

**Issue by amsiglan** [opensearch-project/documentation-website#4631]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 1. Correlation engine under Security Analytics plugin was made GA. Update required in documentation to reflect this.
Other updates made to correlation engine:
  - Correlation rules can be edited/updated now
2. New log type added to security analytics - VPC Flow

**Comment by hdhalter** [comment]
Hi Chris, looks like this is out of experimental and we still have the experimental flag in the doc. Can you please update? Thanks! https://opensearch.org/docs/latest/security-analytics/sec-analytics-config/correlation-config/

**Comment by cwillum** [comment]
I forgot to link this issue with the PR, so it didn't close automatically. Closing this now.
