### ISSUE TITLE
[DOC]Add documentation to clarify differences between admin and super admin roles

### ISSUE THREAD

**Issue by cwillum** [opensearch-project/documentation-website#4646]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
Provide definitions for an "admin" and "super admin" in an appropriate place in security documentation that distinguish between regular users, admins, and super admins and the tasks they can and cannot do within OpenSearch. Also important to spell out how mappings and configurations enable these roles.
 

**What other resources are available?**

Clues (and only clues) for differences between admin roles can be found currently in the following topics:

Predefined roles:
https://opensearch.org/docs/latest/security/access-control/users-roles/#predefined-roles

Applying changes to configuration files:
https://opensearch.org/docs/latest/security/configuration/security-admin/ 

Configuring admin certificates
https://opensearch.org/docs/latest/security/configuration/tls/#configuring-admin-certificates

**Comment by leanneeliatra** [comment]
@hdhalter can you assign this to me please.

**Comment by leanneeliatra** [comment]
Currently I am ensuring full understanding of the docs and locally running instance for correct documentation.
