### ISSUE TITLE
[DOC] Alerting Dashboards Content Gaps

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#4683]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://github.com/opensearch-project/alerting-dashboards-plugin

**Comment by hdhalter** [comment]
@vagimeli - Is this issue still valid? Thanks.
