### ISSUE TITLE
[DOC] Discover 2.0

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/documentation-website#4686]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ X ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We will need to update the documentation about our Discover functionality (https://opensearch.org/docs/2.4/dashboards/discover/index-discover/)

In 2.11 we will be launching a new version of Discover with a different UI:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4165

**Comment by hdhalter** [comment]
From Ashwin: As a part of the Data explorer and Deangularization project we are updating the existing Discover application. As a part of this upgrade existing documentation that references discover pages need to be updated. there is also a lack of documentation about how to use the Discover tool that can be added as a part of this update. The new experience is slated to be released in 2.10

What other resources are available? Provide links to related issues, POCs, steps for testing, etc.

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4165

**Comment by vagimeli** [comment]
@wbeckler Here's the current published documentation about the Discover application. I'm updating it for 2.10. Will you and Ashwin be the points of contact for the technical review? Thanks, Melissa
