### ISSUE TITLE
[DOC] Format all API pages according to the API template

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/documentation-website#4689]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 A lot of pages in the API reference section do not conform to our [API template](uhttps://github.com/opensearch-project/documentation-website/blob/bbd95662c1f1a49ad7eb69519181df347fcb8c9a/templates/API_TEMPLATE.md). They need to be reorganized in order to follow the template. This includes:

- Reordering the sections so that they are in the correct order
- Splitting the URL parameters table into two tables: Path parameters and Query parameters
- Ensuring all field names and variables are in code font (surrounded by tick marks (`)).
- Ensuring the headings are heading level 2 for the section names and level 4 for examples.
- Making any other necessary changes for the pages to conform to the API template.

**Comment by samipak458** [comment]
@Naarcha-AWS I would like to work on this issue, kindly assign me.

**Comment by Naarcha-AWS** [comment]
@samipak458: Scope. I would start with any files that are more have no been modified in the past 4 months in the `api_reference` directory. https://github.com/opensearch-project/documentation-website/tree/main/_api-reference

**Comment by Naarcha-AWS** [comment]
Beyond formatting according to the template, I would also address the following:

- Make heading levels consistent across pages.
- Make sure API names use the same capitalization. 
- Make sure that each page uses terminology that matches the template.

**Comment by samipak458** [comment]
Ok
