### ISSUE TITLE
[FEATURE]: Make a breaking changes list for v2.0.0

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#473]
**Is your feature request related to a problem?**
Make a new breaking changes page for v2.0.0 features. Reference https://github.com/opensearch-project/OpenSearch/issues/2480 for context.

See also breaking changes for 2.0 issue: https://github.com/opensearch-project/opensearch-clients/issues/12

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by kavilla** [comment]
You can't directly migrate from versions less than 7.0 as indicated here: https://opensearch.org/docs/2.0/upgrade-to/upgrade-to/

**Comment by CEHENKLE** [comment]
@kavilla #2936 should be fixed now :)

**Comment by kavilla** [comment]
> @kavilla #2936 should be fixed now :)

Does that mean user can migrate from 6.x to OpenSearch 2.0?
