### ISSUE TITLE
[Documentation] DLS support for Term Lookup Queries

### ISSUE THREAD

**Issue by davidlago** [opensearch-project/documentation-website#474]
We recently [merged a PR](https://github.com/opensearch-project/security/pull/1541) with an enhancement adding support for term lookup queries. The PR has an explanation of the feature in the description. We need to add documentation for this change as this is planned to go out as part of 2.0.

This is a backend-only change adding support for an already existing feature (TLQ) that prior to this PR just errored out when used in conjunction to DLS, but it is worth adding an explanation in our documentation website, especially around the new configuration field that allows to explicitly set the DLS evaluation mode.

**Comment by alicejw-aws** [comment]
Hi David @davidlago ,
just a question about Term Lookup Queries (TLQ), are these the same as Term-level queries? (e.g. https://opensearch.org/docs/latest/opensearch/query-dsl/term/)
I want to keep the nomenclature consistent, and I searched the doc set, and couldn't find any instances of TLQ used anywhere yet. . .
Thanks,
Alice

**Comment by rursprung** [comment]
> Hi David @davidlago , just a question about Term Lookup Queries (TLQ), are these the same as Term-level queries? (e.g. https://opensearch.org/docs/latest/opensearch/query-dsl/term/) I want to keep the nomenclature consistent, and I searched the doc set, and couldn't find any instances of TLQ used anywhere yet. . . Thanks, Alice

i'm not @davidlago, but please see #430: documentation for TLQ is currently missing. it'd be great if this could be added as well (it's not new in 2.0, it's been around in elasticsearch for a long time)

**Comment by davidlago** [comment]
@alicejw-aws  yes, sorry! They are the same thing
