### ISSUE TITLE
[DOC] Custom Log Type support for Security Analytics

### ISSUE THREAD

**Issue by getsaurabh02** [opensearch-project/documentation-website#4741]
**What do you want to do?**
 
User-defined(Custom) log types. Provide CRUD API for user to define its own custom log type. Custom log type will be defined by new LogType structure defined in first task and stored in .opensearch-sap-log-types-config index. Replace DetectorType enum with class which loads detector types(log types) from .opensearch-sap-log-types-config.

**Tell us about your request.** 
2.10
 

**What other resources are available?** 
https://github.com/opensearch-project/security-analytics/issues/459

**Comment by cwillum** [comment]
@getsaurabh02 Are there any resources to describe details about this update? A META issue, or something similar?
