### ISSUE TITLE
[FEATURE] Documentation - Support Notifications and Alerts in 2.0.0 (Breaking Changes)

### ISSUE THREAD

**Issue by brijos** [opensearch-project/documentation-website#476]
**Is your feature request related to a problem?**
Alerts will use notifications in 2.0 and will be adding breaking changes to the Alerts API.  We need to document the feature and make it clear to the community what will be changing.  Details can be found in https://github.com/opensearch-project/alerting/issues/105.

**Comment by Naarcha-AWS** [comment]
Related to #473

**Comment by kavilla** [comment]
+1, there's also a link that points from alerting to the notifications plugin but if the notifications plugin is not installed you get an `Application not found` error.

**Comment by alicejw-aws** [comment]
Hi  Joshua @brijos, 

Could you help me locate more details about how this new feature will work?
I'd like to get a high-level overview and as much usage details as possible so i can explain how to use the new notifications in the OpenSearch Dashboards.
Thanks,
Alice
