### ISSUE TITLE
[DOC]Documentation - Enable merge on refresh and merge on commit in Opensearch 2.1.0+

### ISSUE THREAD

**Issue by reta** [opensearch-project/documentation-website#477]
**Is your feature request related to a problem?**
There are 2 new index settings added to support merge on refresh and merge on commit:

```
index.merge_on_flush.enabled = true | false (default: false)
index.merge_on_flush.max_full_flush_merge_wait_time = <time unit> (default: 10s)
index.merge_on_flush.policy = default | merge-on-flush
```

**What solution would you like?**
These new index settings are worth documenting along with  merge on refresh / commit benefits.

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
See please https://github.com/opensearch-project/OpenSearch/pull/2535, https://github.com/opensearch-project/OpenSearch/pull/3561

**Comment by hdhalter** [comment]
Hi @reta - Do you know if these settings are still relevant and, if so, do you have any suggestions for where we should add them? We've introduced guidance here: https://opensearch.org/docs/latest/tuning-your-cluster/performance/. Thanks!

**Comment by hdhalter** [comment]
> Hi @hdhalter , yes, those are still valid and relevant, the most suitable section for it would be https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/index-settings/, I will be more than happy to add section there, thank you!

Of course, I will take you up on that! Thanks.
