### ISSUE TITLE
[FEATURE] Documentation - Document 'concurrent-search' sandbox plugin in OpenSearch 2.1.0+

### ISSUE THREAD

**Issue by reta** [opensearch-project/documentation-website#482]
**Is your feature request related to a problem?**
The new 'concurrent-search' plugin has been added to OpenSearch as a sandbox plugin. 

**What solution would you like?**
Document the usage of the  'concurrent-search' sandbox plugin and its benefits and limitations. 

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
See please https://github.com/opensearch-project/OpenSearch/issues/2587

**Comment by sohami** [comment]
@reta Can we close this issue as it is not sandbox plugin any more. We are tracking the document task here https://github.com/opensearch-project/documentation-website/issues/3662
