### ISSUE TITLE
[DOC] Data Prepper S3 scan updated configuration

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/documentation-website#4820]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
- `start_time` and `end_time` supported now keyword previously, which is not supported anymore.
- `start_time` or `end_time` cannot be used along with `range`
- We don't mix global `start_time`, `end_time`, `range` with bucket level `start_time`, `end_time`, `range` anymore. Options at bucket level will overwrite global options.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
PR: https://github.com/opensearch-project/data-prepper/pull/3188

**Comment by Naarcha-AWS** [comment]
@asifsmohammed: Since the original source scan PR is still open, should we go ahead and update that before publishing to staging?
