### ISSUE TITLE
[DOC] Add documentation for cluster routing allocation settings

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/documentation-website#4827]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Reference: https://opensearch.org/docs/latest/api-reference/cluster-api/cluster-settings/ - This is the doc that has information about other cluster routing allocation settings.
Currently, the documentation for opensearch does not have any information on these 2 settings: 

 1. cluster.routing.allocation.move.primary_first - This is now deprecated. Boolean setting. 
 2. cluster.routing.allocation.shard_movement_strategy - This is the replacement setting for the above setting being introduced in 2.10. Enum setting can take 3 values - primary_first, replica_first and no_preference. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Reference for (1): 
- https://github.com/opensearch-project/OpenSearch/issues/1349 
- https://github.com/opensearch-project/OpenSearch/pull/1445 

Reference for (2): 
- https://github.com/opensearch-project/OpenSearch/issues/8265 
- https://github.com/opensearch-project/OpenSearch/pull/8875 
- https://github.com/opensearch-project/OpenSearch/pull/9420

**Comment by hdhalter** [comment]
See also https://github.com/opensearch-project/OpenSearch/issues/3881 for more information.

**Comment by hdhalter** [comment]
@Poojita-Raj - we don't have a documentation resource available to work on this. Can you please create a PR with the updates?
