### ISSUE TITLE
[DOC] Reference ZSTD Codecs as optional plugin

### ISSUE THREAD

**Issue by sarthakaggarwal97** [opensearch-project/documentation-website#4832]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Following recent discussions with respect to [this issue](https://github.com/opensearch-project/OpenSearch/issues/9422), it would be required to inform the users that codecs are still in optional plugin, experimental or feature flag based.

Docs to be changed: 
1. https://opensearch.org/docs/latest/im-plugin/index-codecs/
2. https://opensearch.org/docs/latest/tuning-your-cluster/performance/

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Hi @kolchfa-aws , since you are familiar with this content, can you please update the doc? Thanks.

**Comment by sarthakaggarwal97** [comment]
Closing this issue since we are not making this feature experimental for now. Thanks @kolchfa-aws @hdhalter

**Comment by dblock** [comment]
1. In 2.10 the ZSTD plugin is not installed by default like in 2.9.
2. If we do https://github.com/opensearch-project/opensearch-build/issues/3971 it will be installed in the full distribution but not in the min distribution.

Either way this is a breaking change and needs to be documented, reopening.

**Comment by hdhalter** [comment]
@dblock - Is there someone that can create a PR?

**Comment by andrross** [comment]
> Either way this is a breaking change and needs to be documented, reopening.

@dblock There are many examples in the documentation of installed-by-default plugin functionality being described without mention that it is a plugin that can be uninstalled. (e.g. [Aysnc search](https://opensearch.org/docs/latest/search-plugins/async/index/)) What specifically do you think needs to be documented here (assuming the plugin is installed by default)?

**Comment by dblock** [comment]
IMO the change to users for the min distribution. But I am not sure whether we say anything about that anywhere?

**Comment by andrross** [comment]
At a minimum we should add it to the list of bundled plugins: #5000

@hdhalter Can someone take a look here?

**Comment by kolchfa-aws** [comment]
Thanks, @andrross! Is there any more work needed for this issue or is it fixed by #5000?

**Comment by andrross** [comment]
@kolchfa-aws, I don't have any other specific suggestions to change other than what is done by #5000
