### ISSUE TITLE
[DOC] Fix the Documentaion on debian for the APT repository.

### ISSUE THREAD

**Issue by paulkoehlerdev** [opensearch-project/documentation-website#4833]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
The documentation states the following to be the APT repository for OpenSearch Version 1.3.x:
`deb [signed-by=/usr/share/keyrings/opensearch-keyring] https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable main`

But that repository only contains the 2.x Versions of OpenSearch.

The right Repository would be:
`deb [signed-by=/usr/share/keyrings/opensearch-keyring] https://artifacts.opensearch.org/releases/bundle/opensearch/1.x/apt stable main` for these versions.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

The page containing this issue is:
[https://opensearch.org/docs/1.3/install-and-configure/install-opensearch/debian/#install-opensearch-from-an-apt-repository](https://opensearch.org/docs/1.3/install-and-configure/install-opensearch/debian/#install-opensearch-from-an-apt-repository)

**Comment by hdhalter** [comment]
This is fixed. Thanks for your input, @paulkoehlerdev !

**Comment by paulkoehlerdev** [comment]
Thank you for the quick fix and your work on this project. I am migrating a project from Elasticsearch right now and I really appreciate the documentation project.

**Comment by hdhalter** [comment]
Thanks, @paulkoehlerdev! If you have any other feedback, please send it our way. Feel free to create issues, PRs, or add comments in the feedback mechanism on the page itself. I check the feedback regularly. Best of luck with your migration project.
