### ISSUE TITLE
[BUG] Duplicate pages for Index API `Update Mapping`

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/documentation-website#485]
**What is the bug?**
There are 2 pages to describe the same Index API `PUT /<target-index>/_mapping`
https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/put-mapping/
https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/update-mapping/

Since the meaning of the API is to add new fields to an existing index, a possible solution is to delete the page of `Put mapping`.

**How can one reproduce the bug?**
n/a

**What is the expected behavior?**
Only one page of the 2 is supposed to exist.

**What is your host/environment?**
n/a

**Do you have any screenshots?**
none.

**Do you have any additional context?**
Link to the 2 pages in this repo:
https://github.com/opensearch-project/documentation-website/blob/681e166a86480f01a995d4a5601d68c5082f3ecf/_opensearch/rest-api/index-apis/update-mapping.md
https://github.com/opensearch-project/documentation-website/blob/681e166a86480f01a995d4a5601d68c5082f3ecf/_opensearch/rest-api/index-apis/put-mapping.md

**Comment by alicejw-aws** [comment]
is it ok to close this issue now? we can re-open as needed. 
Thanks,
Alice
