### ISSUE TITLE
[BUG] Request parameter 'master_timeout' is missing in the page of 'CAT Segments' API

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/documentation-website#486]
**What is the bug?**
The request parameter (or URL parameter) `master_timeout` is not shown in the page of `CAT Segments` API
https://opensearch.org/docs/latest/opensearch/rest-api/cat/cat-segments/

'master_timeout' is very a common parameter for OpenSearch REST APIs, and the meaning of this parameter is the same as in other APIs, such as https://opensearch.org/docs/latest/opensearch/rest-api/cat/cat-allocation/#url-parameters.

It's actually supported for `CAT Segments` API since OpenSearch version 1.0.0, and the source code is here: https://github.com/opensearch-project/OpenSearch/blob/1.0.0/server/src/main/java/org/opensearch/rest/action/cat/RestSegmentsAction.java#L84

**How can one reproduce the bug?**
n/a

**What is the expected behavior?**
'master_timeout' is added to the `URL Parameter` section of the page.

**What is your host/environment?**
n/a

**Do you have any screenshots?**
none.

**Do you have any additional context?**
none.

**Comment by alicejw-aws** [comment]
hi @Naarcha-AWS should we add label 2.0 for this one, or should it go to 1.3?

**Comment by Naarcha-AWS** [comment]
@alicejw-aws: Let's make this a 1.3 issue. Could we add it before we perform the release tomorrow?
