### ISSUE TITLE
[DOC] Neural Search Plugin Needs a Prerequisites Section and General Architecture

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/documentation-website#4866]
We should add a prerequisites section to the Neural Search page. This section should cover that you need either a deployed model using ML Commons (local) or a ML Connector (remote inference).  

https://opensearch.org/docs/latest/search-plugins/neural-search/
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 There prerequisite steps to using the Neural Search plugin. You need a model_id to create the index and need to know the dimensionality of the model. Additionally it would help to have a general architecture diagram to understand how the components work together. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
N/A

**Comment by kolchfa-aws** [comment]
@Naarcha-AWS I'm currently in the process of rewriting these sections so I'll assign this issue to myself.
