### ISSUE TITLE
[DOC] Proposed hierarchy for Machine Learning catagory

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/documentation-website#4868]
**What do you want to do?**
I'd like to change the Machine Learning category documentation structure. At the moment the flow of the documentation doesn't reflect the experience of users using the documentation. 
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
```bash 
Machine Learning
├── ML Commons Cluster Settings
├── Model Access Control
├── ML Framework
│   ├── Pre-trained Models
│   └── GPU Acceleration
├── ML Extensibility
│   ├── Creating connectors for third-party ml platforms
│   └── Building blueprints
├── ML Commons
│   ├── Commons API
│   └── Supported Algorithms
├── Managing Models in ML Dashboards
└── Troubleshooting ML
 ```
 
 Link to troubleshooting page that is being proposed: #4867 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Jiali03713** [comment]
@Naarcha-AWS Hi, could you assign this to me? I want to give it a try :)
