### ISSUE TITLE
[DOC] Machine Learning page re-write?

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/documentation-website#4869]
**What do you want to do?**
At the moment the top level Machine Learning page it doesn't describe what you can achieve with the machine learning framework, commons, and connectors. There should be a use-cases section that sets out the goals you can achieve with Machine Learning and direct you to the right path for that goal. 

Eg: When would you use k-means and what would the goal of that be? 
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 I think there should be some clear paths for each of the things you would do with Machine Learning and OpenSearch. This may also include a intended use section. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by kolchfa-aws** [comment]
Closing this issue because this was taken care of as part of the latest ML rewrites.
