### ISSUE TITLE
[BUG] Typo in Query-DSL documentation

### ISSUE THREAD

**Issue by JustAMicrobe** [opensearch-project/documentation-website#487]
**What is the bug?**
There is a typo in the documentation for full-text query options

**How can one reproduce the bug?**
1. Go to https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#options and scroll down to types
2. Use the `best_fields` or `most_fields` values for the `type` parameter and get successful responses
3. Use the `cross-fields` as value and you get the following error
```json
{
    "error": {
        "root_cause": [
            {
                "type": "parse_exception",
                "reason": "failed to parse [multi_match] query type [cross-fields]. unknown type."
            }
        ],
        "type": "x_content_parse_exception",
        "reason": "[12:33] [bool] failed to parse field [must]",
        "caused_by": {
            "type": "parse_exception",
            "reason": "failed to parse [multi_match] query type [cross-fields]. unknown type."
        }
    },
    "status": 400
}
```
4. Use `cross_fields` and get a successful response

**What is the expected behavior?**
types in the documentation should say `cross_fields` instead of `cross-fields`

**What is your host/environment?**
AWS opensearch instance.

**Do you have any screenshots?**
![opensearch_type_bug](https://user-images.githubusercontent.com/8113266/161242910-56c41592-9a59-4791-b065-0a0ecdf40350.png)

**Comment by AlexVCS** [comment]
Hi, I'd like to work on this issue. Please assign it to me :)

**Comment by Naarcha-AWS** [comment]
@AlexVCS: Feel free to submit a PR for it!
