### ISSUE TITLE
[DOC] ML Framework page updates

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/documentation-website#4870]
**What do you want to do?**
1. Prerequisites - should back link to ML Cluster Configuration page
2. Model format - should link to some documentation on how to find the dimensional of a model
3. Upload model to OpenSearch - should specify that a model group is created by default when you call this api and back link to the model documentation. 

- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other

**Comment by kolchfa-aws** [comment]
One more thing to change: we should replace the soon-to-be deprecated `upload` and `load` with their new versions---`register` and `deploy`.

**Comment by kolchfa-aws** [comment]
Closing because this was taken care of as part of the latest ML rewrites. @dtaivpp Please take a look at the updated documentation when you get a chance. Thanks!
