### ISSUE TITLE
[DOC] Add documentation for support for SearchResponse extensions via SearchExtBuilder

### ISSUE THREAD

**Issue by austintlee** [opensearch-project/documentation-website#4877]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Feature request - https://github.com/opensearch-project/OpenSearch/issues/9328

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/pull/9379

**Comment by hdhalter** [comment]
@austintlee - this is for release 2.10, right?

**Comment by austintlee** [comment]
Yes!

**Comment by hdhalter** [comment]
Related to https://github.com/opensearch-project/documentation-website/issues/4281

**Comment by austintlee** [comment]
Do you need anything from me?

**Comment by kolchfa-aws** [comment]
@austintlee Just to review the documentation PR #4959. This is what's going into the user documentation on our site. Thanks!
