### ISSUE TITLE
[PROPOSAL][Security plugin] Modify global tenant docs

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/documentation-website#488]
From: https://opensearch.org/docs/latest/security-plugin/access-control/multi-tenancy/ 

> The global tenant is shared between every OpenSearch Dashboards user. The private tenant is exclusive to each user and can’t be shared.

Might be a little confusing and leaves room for interpreting this as the `global` tenant as the `primary` tenant and the `private` tenants are `minions` to the `global` tenant. This then leads to the conclusion that if the user modifies the `global` tenant then anything thing they do or configure gets replicated (shared) to `private` tenants.

For example, user may think going into the `global` tenant and adding a default route or default index pattern to something only available in the `global` tenant. Then they switch to a `private` tenant and these settings are not applied and then they are confused and wonder why they no longer have these settings applied thus creating a new issue wondering why their settings were lost.

### Proposal

Explicitly state that `global` is not a `primary` tenant and that any action done within the `global` tenant will not be replicated to `private` tenants. This includes but not limited to:  
* Advanced settings
* Creation of visualizations
* Creation of ndex patterns

**Comment by ahopp** [comment]
@Naarcha-AWS This comes up all the time - any thoughts on how we can document this in a way that removed as much user confusion as possible?

**Comment by Naarcha-AWS** [comment]
> @Naarcha-AWS This comes up all the time - any thoughts on how we can document this in a way that removed as much user confusion as possible?

@ahopp: For the time being, we could add a note to the Multi-Tenancy page detailing the behavior and that if a user modifies the Global tenant it won't appear in private tenants.

@kavilla: How can private tenants access routes or index patterns made by a global tenant? Why are we naming that tenant setting "Global", when in practice that's a bit of misnomer?

**Comment by kavilla** [comment]
> How can private tenants access routes or index patterns made by a global tenant?

They can only access them by switching to the global tenant.

> Why are we naming that tenant setting "Global", when in practice that's a bit of misnomer?

That's a good question.

**Comment by alicejw-aws** [comment]
Fixed with PR https://github.com/opensearch-project/documentation-website/pull/508
