### ISSUE TITLE
[DOC] Add documentation for Do Not Fail on Forbidden Feature

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/documentation-website#4896]
**What do you want to do?**
 Create documentation surrounding the do not fail on forbidden configuration/feature

- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 May have been introduced in Version 1.0 - @cwperks 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/security/blob/0338cdd4ab701e6dfdbaaf49765300b1d6190aa0/src/test/resources/config_dnfof.yml#L4

**Comment by cwillum** [comment]
@derek-ho Hi, can you elaborate on what this issue is about and possibly provide resources (RFC, Meta-issue, etc.) that describe it? Is this issue intended to be attached to the 2.10 release? Thanks!

**Comment by cwillum** [comment]
@derek-ho Sounds good. Thanks for providing context and putting the issue into perspective.
