### ISSUE TITLE
[PROPOSAL] [Documentation] opensearch.yml reference documentation. 

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/documentation-website#493]
## What kind of business use case are you trying to solve? What are your requirements?

Without knowing the API call to use before hand that displays the configuration defaults available in `opensearch.yml`, we have no current reference for the configuration options. I'd very much like to see a full and complete reference including what options do what.

**What is the problem? What is preventing you from meeting the requirements?**

Threads in the category "OpenSearch and OpenSearch Dashboards" on the forums have the highest rate of threads being tagged with `configuration` - we should be more explicit and direct about what options are available in the configuration files. 

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**

I don't think there's a 100% solution for this, but I'd love to see a basic reference for each config option on the doc site, or maybe even include all of the default options in the `opensearch.xml` commented out with the explanations there. 

**What are your assumptions or prerequisites?**

I'm assuming that newcomers to OpenSearch won't be able to properly configure their cluster without a configuration reference of some kind. 

**What are remaining open questions?**

Is there a full list anywhere? Do we have a list of ones that are only modifiable via changes to the `xml` and which ones can be changed via API?

**Comment by nateynateynate** [comment]
One of the documentation goals I have is to make sure that no one has to visit any site but our own to get what they need. I suspect we're lacking a lot of basic references where someone will come across a configuration variable and wonder, "I wonder what *that* does?" and won't be able to find the answer on *our* site specifically.

**Comment by ahopp** [comment]
Adding to what @nateynateynate has called out, I think we need documentation on all the .yml options for both OpenSearch and OpenSearch Dashboard. We have issues like [this ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1406) that pop up fairly often and we can find the associated reference (i.e., console.enabled: false) in the docs site.

**Comment by Naarcha-AWS** [comment]
@nateynateynate: We're going to close this one in favor of two separate issues, one for opensearch.yml and one for opensearch.yml dashboards. The issues are:

- #214 
- #908
