### ISSUE TITLE
[DOC] Updates to the ML Framework Section: summary section and clarity on local vs. external model options.

### ISSUE THREAD

**Issue by dylan-tong-aws** [opensearch-project/documentation-website#4934]
**What do you want to do?**
 
- [ x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

 Request to update the summary for the ML Framework: https://opensearch.org/docs/latest/ml-commons-plugin/ml-framework/.
 
The machine learning (ML) framework allows users to manage and integrate ML models with their OpenSearch cluster through common OpenSearch [APIs](https://opensearch.org/docs/latest/ml-commons-plugin/api/). Models can be hosted on an OpenSearch cluster or integrated via [connectors](https://opensearch.org/docs/latest/ml-commons-plugin/extensibility/connectors/) to external 3rd-party endpoints and APIs. The ML framework enables AI use cases on OpenSearch like semantic search by integrating and managing ML workloads to power AI-powered features like ones available in the [neural search plugin](https://opensearch.org/docs/latest/search-plugins/neural-search/).

Also, note that the ML extensibility section should fall under the ML Framework. The AI connectors are an alternative to managing models locally. The user has the choice to go through the process of registering and deploying models on an OpenSearch cluster, or integrating with models that are managed externally via the connectors. So this [page](https://opensearch.org/docs/latest/ml-commons-plugin/ml-framework/) needs to clarify that there are these two methods to integrate and manage ML models to power features like neural search.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@Naarcha-AWS - is anything here new to 2.10? If not, let's drop the 2.10 label. Thanks.

**Comment by kolchfa-aws** [comment]
@dylan-tong-aws This should be addressed in the [latest iteration of ML rewrites](https://github.com/opensearch-project/documentation-website/pull/5636). Let me know if there is anything else to be done for this issue.

**Comment by kolchfa-aws** [comment]
@hdhalter I think we can close this issue because this is addressed in the multiple ML commons rewrites.
