### ISSUE TITLE
[DOC] rename processor 'otel_trace' to 'otel_traces'

### ISSUE THREAD

**Issue by toby181** [opensearch-project/documentation-website#4935]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

With the release of Data-Prepper version 2.2.0 the 'otel_trace_raw' processor has been [renamed](https://github.com/opensearch-project/data-prepper/tree/2.4.0/data-prepper-plugins/otel-trace-raw-processor) to 'otel_traces'. The [OpenSearch documentation](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/otel-trace-raw/) states the processor as 'otel_trace'. So simply the "s" is missing, which leads to an exception when using it.

https://github.com/opensearch-project/data-prepper/tree/2.4.0/data-prepper-plugins/otel-trace-raw-processor
https://github.com/opensearch-project/data-prepper/releases/tag/2.2.0
https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/otel-trace-raw/
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

I've also tried to use the processor 'otel_trace' (without s) and data-prepper version 2.3.0 and it throws the exception:
```
org.opensearch.dataprepper.model.plugin.NoPluginFoundException: Unable to find a plugin named 'otel_trace'. Please ensure that plugin is annotated with appropriate values.
```

**Comment by samipak458** [comment]
Kindly assign me this issue @Naarcha-AWS.

**Comment by SergK** [comment]
I believe the issue still exists. Please check the official documentation: https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/otel-trace-raw/
<img width="1074" alt="image" src="https://github.com/opensearch-project/documentation-website/assets/1520525/af3112e1-a91c-491e-8fde-849e1c611455">
