### ISSUE TITLE
[DOC] Error in the 1.3.x Version of the Documentation

### ISSUE THREAD

**Issue by paulkoehlerdev** [opensearch-project/documentation-website#4936]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

The problem seems to be in the configuration reference for [`Creating a cluster`](https://opensearch.org/docs/1.3/tuning-your-cluster/index/#cluster-manager-node) for the Version `1.3.x` in the section about the `cluster_manager` node.

In this version `cluster_manager` is still `master`.

That means:
```yaml
node.roles: [ cluster_manager ]
```
should be:
```yaml
node.roles: [ master ]
```

This issue is probably also reflected in the node types, as the `cluster_manager-elegible` node type seems to be new in OpenSearch 2.x

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

- Related Documentation article: [https://opensearch.org/docs/1.3/tuning-your-cluster/index/#cluster-manager-node](https://opensearch.org/docs/1.3/tuning-your-cluster/index/#cluster-manager-node)

**Comment by Dantochi** [comment]
Hi 👋, I'm new to open source contribution and looking forward to dealing my first issue. Please could you tell me how I may go about the number 2 task "Adding new documentation". I'd like to help...🙏

**Comment by BigSamu** [comment]
@Naarcha-AWS I would like to take this issue if @Dantochi don't want to take it anymore

**Comment by hdhalter** [comment]
Hi @Naarcha-AWS - Looks like this has been fixed: https://opensearch.org/docs/1.3/tuning-your-cluster/index/#cluster-manager-node. OK to close this issue? Thanks!

**Comment by BigSamu** [comment]
> [OSCI][DOC] Fixing documentation in v1.3.x for Cluster Creation.md #5256

Hi @hdhalter, yeah this has been fixed in PR #5256, with a successful merge approved by @Naarcha-AWS.

Regards,

Samuel
