### ISSUE TITLE
[FEATURE] Document new configuration value “data.search.usageTelemetry.enabled” in the opensearch_dashboard.yml

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/documentation-website#494]
**Is your feature request related to a problem?**
Yes. this feature request related with issue [#928](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/928) ,  and [PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1427) address the issue #928. Added configuration value “data.search.usageTelemetry.enabled” to opensearch_dashboard.yml, which customer can opt in/out with search usage telemetry by modifying the data.search.usageTelemetry.enabled value in the opensearch_dashboard.yml. 

| opensearch_dashboard.yml enabled value  | data plugin config enabled value  | Search usage telemetry      |
|---------------------------------------- |---------------------------------- |------------------------     |
|                  TRUE                   |               FALSE               | OPT IN                      |
|                  FALSE                  |               FALSE               | OPT OUT                     |
|                  TRUE                   |               TRUE                | OPT IN                      |
|                  FALSE                  |               TRUE                | OPT OUT                     |
|                  NONE                   |               TRUE                | OPT IN                      |
|                  NONE                   |               FALSE               | OPT OUT                     |

**What solution would you like?**
We add configuration value “data.search.usageTelemetry.enabled” to allow customer to opt in/out search usage telemetry, and changed the default behavior to false, which turn off search usage telemetry as large traffic for the opensearch cluster, it can improve the performance of cluster. 

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
This feature target at release 2.0.0, I don't have permission to change the label, can someone change this feature's labels to 2.0.0. Thanks

**Comment by Naarcha-AWS** [comment]
Label added. Thanks for submitting this issue @Flyingliuhub

**Comment by alicejw-aws** [comment]
hi @Flyingliuhub , could you please share an example opensearch_dashboard.yml  file with the configuration setting? 

I'd like to add it to the documentation as an example. 
Thanks

**Comment by Flyingliuhub** [comment]
Yes. the sample opensearch_dashboard.yml  in the https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/config/opensearch_dashboards.yml#L180. 

#1 enable usageTelemetry
data.search.usageTelemetry.enabled: true

#2 default behavior is disabled, it is meaning that customer didn't need to change opensearch_dashboard.yml

**Comment by alicejw-aws** [comment]
Hi Tao, thanks for the quick reply! @Flyingliuhub

**Comment by alicejw-aws** [comment]
Hi  @Flyingliuhub Tao, could you look at my [PR 594](https://github.com/opensearch-project/documentation-website/pull/594) for this issue, and let me know your feedback? Thanks

**Comment by Flyingliuhub** [comment]
Yes. I just leave some comments on your PR.

**Comment by alicejw-aws** [comment]
Hi @Flyingliuhub could you help us locate the "data plugin"
I see the config file, but just wondering if there is an official plugin name? Thanks

**Comment by Flyingliuhub** [comment]
The configuration file is under https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data
"The data plugin provides common data access services, such as search and query, for solutions and application developers.", which readme called the data plugin. it is not [Trace analytics dashboard plugin](https://opensearch.org/docs/2.0/observability-plugin/trace/ta-dashboards/)

**Comment by alicejw-aws** [comment]
Thanks Tao Liu @Flyingliuhub i really appreciate your help.

**Comment by alicejw-aws** [comment]
Hi @Flyingliuhub, one last question - so i can show customers how to enable telemetry in the data config file. (already showed them how to do in YAML file).
Do they just change this entry to "true?"
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data/config.ts

    usageTelemetry: schema.object({
      enabled: schema.boolean({ defaultValue: **false** }),

**Comment by Flyingliuhub** [comment]
I don't think that we need to show customer how to enable it in the data config file. you already have yaml matrix above, it is configuration combination, if you need to show user how to enable it in the data configuration, the user need to check if opensearch_dashboards.yml have value to override here, the value is passed from top to bottom, and user cannot change here, they just need to change the opensearch_dashboards.yml to enable it if they need.

**Comment by Flyingliuhub** [comment]
the value form data configuration just tell user that the default behavior is disabled, if you don't change anything.
