### ISSUE TITLE
[DOC] Set up a read-only user in OpenSearch Dashboards

### ISSUE THREAD

**Issue by BlaBlaGITTE** [opensearch-project/documentation-website#4947]
**What do you want to do?**
 
- [ x] Request a change to existing documentation

Set up a read-only user in OpenSearch Dashboards: this sample doesn't work as expected.
link: https://opensearch.org/docs/latest/security/access-control/users-roles/#:~:text=Set%20up%20a%20read%2Donly%20user%20in%20OpenSearch%20Dashboards,-Create%20a%20new&text=Open%20OpenSearch%20Dashboards.,add%20the%20cluster_composite_ops_ro%20action%20group.

**Comment by BlaBlaGITTE** [comment]
![image](https://github.com/opensearch-project/documentation-website/assets/120639073/e4b238bb-bea2-4d0e-bb9f-a1f92b5ae88e)

**Comment by Naarcha-AWS** [comment]
@BlaBlaGITTE: Can you give a few more details here? The link you provided only leads to the page and not a specific section.

**Comment by BlaBlaGITTE** [comment]
...
Sample roles
The following examples demonstrate how you might set up a read-only role and a bulk access role.

Set up a read-only user in OpenSearch Dashboards
Create a new read_only_index role:

Open OpenSearch Dashboards.
Choose Security, Roles.
Create a new role named read_only_index.
For Cluster permissions, add the cluster_composite_ops_ro action group.
For Index Permissions, add an index pattern. For example, you might specify **my-index-*.**
For index permissions, add the read action group.
Choose Create.
...

If I try this:
For Index Permissions, add an index pattern. For example, you might specify **my-index-*.**

Opensearch does not show only the indicated index **my-index-*.** but all indexes also with different names. Is that a normal
behaviour?

**Comment by hdhalter** [comment]
@scrawfor99 - Can you please comment on whether this is the expected behavior or if we need to update the documentation? Thanks!

**Comment by scrawfor99** [comment]
Hi @BlaBlaGITTE, can you clarify what index names you are seeing? 

If you provide the ability to read indices with a pattern `my-index-*` I would expect you to be able to see all indices which start with "my-index-" (OpenSearch supports wildcards similar to regex patterns). 

If that is what you are seeing then this is expected.
