### ISSUE TITLE
[PROPOSAL] [Documentation] Index Mapping reference

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/documentation-website#495]
## What kind of business use case are you trying to solve? What are your requirements?

The information needed to create a custom index mapping and make sure that my timestamp fields were recognized properly was nonexistent. There's a few mentions of data types in the PPL sections, but no direct reference for someone hoping to use the Dev Tools or PUT to the api to create/update a mapping. 

**What is the problem? What is preventing you from meeting the requirements?**

There is no existing reference material for all of the options possible when making a call to `/<index-name>/_mapping` including the ones that help OpenSearch understand the format of your timestamps. 

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**

A proper reference document in our documentation as well as some educational examples. 

**What are your assumptions or prerequisites?**

I'm assuming that newcomers will be 'playing' with OpenSearch and will notice these same gaps when they go through the OOB experience. I want to minimize the amount of time from having a cluster that has nothing to a cluster that does something. 

**What are remaining open questions?**
List questions that may need to be answered before proceeding with an implementation.

**Comment by alicejw-aws** [comment]
Just a note. . . I've linked a related PR where we started a mapping guide. ( linked PR#515), but  will also create separate PR to address this issue's requirements: reference for all of the options possible when making a call to /<index-name>/_mapping including the ones that help OpenSearch understand the format of your timestamps.
