### ISSUE TITLE
[DOC] Create Benchmark Quickstart section

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#4950]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Add a simple "Quickstart" page to the OpenSearch Benchmark side-nav, above installing. Also consider moving Concepts to its own page and using the intro page as a hub.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

Talk to Govind about best Quickstart steps to use.

**Comment by Naarcha-AWS** [comment]
To increase the speed of contribution, lets add the following skeleton pages to the staging site:

- Quickstart
- Tips and Tricks (Consult the office questions or forum questions to find a concept).
- Running OSB (https://esrally.readthedocs.io/en/stable/race.html, use Geonames workload)

**Comment by gkamat** [comment]
I would add an item to have a separate section for the command line options.  That would the top priority, since it has been coming up as a request from several users, for instance, re. `--workload-params`, which is very widely-used:
```
Note: does not appear on this page: https://opensearch.org/docs/latest/benchmark/commands/execute-test/
```

**Comment by hdhalter** [comment]
Closing. Feel free to reopen if there are any remaining open items related to this issue. Thanks!
