### ISSUE TITLE
[DOC]Modify stats api documentation to reflect addition of segment replication statistics

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/documentation-website#4954]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Changes requested: 
 
 1. Under list of index properties in this table (holding list of properties for index statistics for each shard), we need to add the following rows: 
 Link: https://opensearch.org/docs/latest/api-reference/nodes-apis/nodes-stats/#indices 
 

Field | Field type | Description
-- | -- | --
segments.segment_replication | Object | Segment replication statistics for all primary shards with segment replication enabled that exist on the node.
segments.segment_replication.maxBytesBehind | long | The max number of bytes behind the primary a replica is.
segments.segment_replication.totalBytesBehind | long | The total number of bytes behind the primary the replicas are. 
segments.segment_replication.maxReplicationLag | long | The max time (in milliseconds) taken by a replica to catch up to primary. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
PR: https://github.com/opensearch-project/OpenSearch/pull/9709 
Issue: https://github.com/opensearch-project/OpenSearch/issues/9417

**Comment by Naarcha-AWS** [comment]
Moved this to Pr #4995
