### ISSUE TITLE
[DOC] ml-framework page example request doesn't work

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/documentation-website#4966]
**What do you want to do?**
 
- [X] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

https://opensearch.org/docs/latest/ml-commons-plugin/ml-framework/ - 
The example request here doesn't seem to work. It's missing the `model_content_hash_value` key.

![image](https://github.com/opensearch-project/documentation-website/assets/96254688/1f2d8d7b-ac68-49f6-9b10-0d8acbfd47cf)

Regarding that, it's not mentioned anywhere. When registering a model via URL, you'll have to pass that value and it's the sha256 checksum of the model zipfile. You'll want to provide instructions on how to calculate that and make it part of the call. 

For comparison, the example call to register a model from the API reference page for machine learning works proper-like. 

https://opensearch.org/docs/latest/ml-commons-plugin/api/

![image](https://github.com/opensearch-project/documentation-website/assets/96254688/169e6556-9fd0-4d5e-9b17-ccb250a4432a)

**Comment by hdhalter** [comment]
Looks like you're working on the same problem under the other issue (5591), @kolchfa-aws , so assigning to you so you can close them both. Thanks.

**Comment by kolchfa-aws** [comment]
@nateynateynate Did you have to calculate the hash code and if so, do you have instructions on how to do it?

**Comment by kolchfa-aws** [comment]
Actually, never mind. Found the command.
