### ISSUE TITLE
[DOC] Full-Text / (Simple) Query String should specify the syntax

### ISSUE THREAD

**Issue by smacrakis** [opensearch-project/documentation-website#4979]
**What do you want to do?**
 
- [X ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
.../query-dsl/full-text/index/#query-string and .../query-dsl/full-text/index/#simple-query-string
do not specify the syntax of the query string. Ideally, we would have a full specification of the query string mini-language, but until we have that, it should summarize it in some way. If I'm not mistaken, this is exactly the syntax supported by the Lucene query parser (https://lucene.apache.org/core/2_9_4/queryparsersyntax.html), but that needs to be checked.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by ShatilKhan** [comment]
Hey, can I take this on?

**Comment by kolchfa-aws** [comment]
Hi @ShatilKhan! We'd love your help on the documentation, but this particular issue is already being addressed as part of the meta issue where we're tracking full-text queries (see https://github.com/opensearch-project/documentation-website/issues/2173#issuecomment-1447424894). We'll comment on here once the PR is up. Also, please feel free to browse other documentation issues and taking on one that you're interested in. We'd appreciate your contribution. Thank you!

**Comment by ShatilKhan** [comment]
Sure thing!
