### ISSUE TITLE
[DOC] [Concurrent Segment Search] Experimental Release in 2.10

### ISSUE THREAD

**Issue by sohami** [opensearch-project/documentation-website#4989]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
In 2.10, we want to announce concurrent segment search as an experimental feature. For that we will need to add documentation for the users. This issue is to track the documentation related changes for experimental release.

**Comment by kolchfa-aws** [comment]
This new issue is part of #4281. #4281 will track all profile-related changes for experimental and GA release. This issue is for the 2.10 experimental release.
