### ISSUE TITLE
[DOC] Update documentation for the index setting `index.remote_store.translog.buffer_interval`

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/documentation-website#4992]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
This is coming out from https://github.com/opensearch-project/documentation-website/pull/4973 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@Naarcha-AWS - is this a duplicate issue to #4973?

**Comment by ashking94** [comment]
> @Naarcha-AWS - is this a duplicate issue to #4973?

The #4973 issue is for adding cluster level settings. I have created this issue for updating the documentation for the index level setting `index.remote_store.translog.buffer_interval`.
