### ISSUE TITLE
[DOC] ZStd Documentation update to exclude knn and correlation indices for v2.10

### ISSUE THREAD

**Issue by sarthakaggarwal97** [opensearch-project/documentation-website#5002]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 With the moving of ZStd to a plugin in OS v2.10, the users won't be able to use ZStd compression codecs for KNN and Correlation Indices (Security Analytics), since all three plugins implement EnginePlugin and for an index, we can override only one [custom codec service factory method](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java#L106)

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/pull/9658

**Comment by hdhalter** [comment]
@sarthakaggarwal97 - can you please provide a PR for this update, and then we can review it? We are trying to get all changes merged by 9/18. Thanks!
