### ISSUE TITLE
[BUG] wrong xsrf.whitelist ACS URL in the SAML configuration doc

### ISSUE THREAD

**Issue by l-ra** [opensearch-project/documentation-website#502]
**What is the bug?**
In the doc https://github.com/opensearch-project/documentation-website/blob/main/_security-plugin/configuration/saml.md#opensearch-dashboards-configuration there is ACS URL `"/_plugins/_security/saml/acs"`

The ACS URL is not working. When testing in the latest docker release (image 1.3.1), opensearch-dashboards uses URLs starting with  `/_opendistro/` prefix instead of `/_plugins/` prefix.

It is confusing not only for `xsrf.whitelist` but the right SAML redirect URL needs to be known when configuring IdP.

I was not testing the other URLs - logout and idpinitiated variant.

**How can one reproduce the bug?**
The URL can be found  in the plugin source code: https://github.com/opensearch-project/security-dashboards-plugin/blob/558a7e1728b7edfa9c59309d77e8cea5a77818d7/server/auth/types/saml/routes.ts#L87
To reproduce - configure SAML according the docs. When trying login, redirect does not work.
After changing my config to the `_opendistro` prefix it started to work.

**What is the expected behavior?**
Documentation should contain the right URL.

**What is your host/environment?**
 - OS: Linux/Docker distributionimage opensearchproject/opensearch-dashboards:1.3.1
 - Version 1.3.1
 - Plugins - opensearch-dashboards-security

**Do you have any screenshots?**
No

**Do you have any additional context?**
No

**Comment by hdhalter** [comment]
@cwillum - can you please check to see if this was implemented in security: whitelist vs. allow list?

**Comment by hdhalter** [comment]
This has been addressed. See https://github.com/opensearch-project/documentation-website/commit/206e97a2b76e960e0a84d4fc8dc101a92e420073.
