### ISSUE TITLE
[DOC] Add benchmarks section for search pipeline

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/documentation-website#5024]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Search Pipelines is GA-ed in 2.9 and we would like to add benchmarks section which evaluates the performance of search pipeline and various processors using OpenSearch benchmark.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Code changes:** 
1. OSB Support create search pipeline: https://github.com/opensearch-project/opensearch-benchmark/pull/364
2. search pipeline test procedures: https://github.com/opensearch-project/opensearch-benchmark-workloads/pull/101

Section format ref: https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/segment-replication/index/#benchmarks

**Comment by hdhalter** [comment]
@noCharger - Is this an enhancement in 2.10? If so, can you please create a PR?

**Comment by msfroh** [comment]
Discussed this last week. Decided not to document (relatively uninteresting) benchmark results in documentation, since they don't really contribute anything.

**Comment by hdhalter** [comment]
This is targeting 2.12 according to the roadmap, so updated the version and milestone.
