### ISSUE TITLE
[DOC] Create documentation about index patterns

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#5041]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 No documentation exists about index patterns; create documentation

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by lmako-aws** [comment]
@vagimeli I was about to create a ticket for this but you beat me to it. Do we have an approximate ETA as to when this can be done or how far is it in the backlog? Thanks
