### ISSUE TITLE
Report a technical problem with the documentation

### ISSUE THREAD

**Issue by manishkumar-cpi** [opensearch-project/documentation-website#5045]
Report a technical problem with the documentation
 
**https://opensearch.org/docs/2.7/query-dsl/term/#wildcard** document says **case_insensitive** is true by default but I have to give explicitly true to get the results.

Please verify.

**Comment by BigSamu** [comment]
@Naarcha-AWS, can I take this issue?

**Comment by BigSamu** [comment]
@Naarcha-AWS I can confirm that what is saying @manishkumar-cpi is correct, but for versions 2.10 and 3.0 from OpenSearch. Thinking is a mistake from past versions (@manishkumar-cpi refers to version 2.7) that continues in new versions. I will start doing an update for the last version of the `documentation-website`, but I am not sure if we should do an update backwards.

Regards,

Samuel

**Comment by Naarcha-AWS** [comment]
@BigSamu: We can backport to other versions if necessary. Let's fix on the main branch first, then we can decide which versions we need to backport to.

**Comment by BigSamu** [comment]
Roger that. Fixing Documentation right now and creating PR @Naarcha-AWS!

**Comment by BigSamu** [comment]
@Naarcha-AWS PR #5197 created to fix this issue.
