### ISSUE TITLE
[DOC] Terms (sub-)aggregation missing some low level parameters and accuracy details

### ISSUE THREAD

**Issue by lukas-vlcek** [opensearch-project/documentation-website#5046]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
 
The latest (as of writing `2.9.x`) documentation on [Terms Aggregation](https://opensearch.org/docs/2.9/aggregations/bucket/terms/) does not include some low level parameters and explanation of accuracy of the results and effect ordering and use of sub-aggregations. For example there are missing `shard_size`, `show_term_doc_count_error`, `shard_min_doc_count` and `collect_mode` to name some of them.

This can lead to user confusion like [this one](https://opensearch.slack.com/archives/C01QHR7481Y/p1695126586206179) (on Slack channel).

**What other resources are available?**

I am listing some of the tickets that might have been relevant to some degree:

- https://github.com/opensearch-project/documentation-website/issues/4293
- https://github.com/opensearch-project/documentation-website/issues/2173
- https://github.com/opensearch-project/OpenSearch/pull/9085

**Comment by kolchfa-aws** [comment]
@hdhalter This is part of the missing aggregation pages and should be taken care of by whoever is doing that back documentation.

**Comment by hdhalter** [comment]
Ok, thanks. I'll leave unassigned for now until we determine who is taking this over.
