### ISSUE TITLE
[DOC]Need to add another model information in the pre-trained model listing

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/documentation-website#5051]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
We recently published torchscript version of `distiluse-base-multilingual-cased-v1` model. So we need to update [this table](https://opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/#sentence-transformers)

Expected row should be:

Model name: sentence-transformers/distiluse-base-multilingual-cased-v1
vector dimension: 512-dimensional dense vector space.
auto truncation: yes
torch script artifact: 

model url: 
https://artifacts.opensearch.org/models/ml-models/huggingface/sentence-transformers/distiluse-base-multilingual-cased-v1/1.0.1/torch_script/sentence-transformers_distiluse-base-multilingual-cased-v1-1.0.1-torch_script.zip
config url: 
https://artifacts.opensearch.org/models/ml-models/huggingface/sentence-transformers/distiluse-base-multilingual-cased-v1/1.0.1/torch_script/config.json

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
This looks like it's already addressed: 
<img width="787" alt="image" src="https://github.com/opensearch-project/documentation-website/assets/104463754/34df2a25-e138-4852-8175-2976a24db4d2">
I will close this issue. Please reopen if there are any issues. Thanks!
https://opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/#supported-pretrained-models
