### ISSUE TITLE
[DOC] Add a new request field to segment replication backpressure

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/documentation-website#5075]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 There's a list of fields for segment replication backpressure listed in this doc: 
 https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/segment-replication/backpressure/#request-fields 
 
 We need to add a new field here: 
 

Field | Data type | Description
-- | -- | --
SEGMENT_REPLICATION_INDEXING_PRESSURE_ENABLED | Boolean | Enables the segment replication backpressure mechanism. Default is false.
MAX_REPLICATION_TIME_BACKPRESSURE_SETTING | Time unit | The maximum amount of time that a replica shard can take to copy from the primary shard. Once MAX_REPLICATION_TIME_BACKPRESSURE_SETTING is breached along with MAX_INDEXING_CHECKPOINTS, the segment replication backpressure mechanism is initiated on primary. Default is 5 minutes.
MAX_REPLICATION_LIMIT_STALE_REPLICA_SETTING | Time Unit | The maximum amount of time that a replica shard can take to copy from the primary shard. Once MAX_REPLICATION_LIMIT_STALE_REPLICA_SETTING is breached, we start failing the replica shard. Default is 0 minutes(disabled).
MAX_INDEXING_CHECKPOINTS | Integer | The maximum number of indexing checkpoints that a replica shard can fall behind when copying from primary. Once MAX_INDEXING_CHECKPOINTS is breached along with MAX_REPLICATION_TIME_BACKPRESSURE_SETTING, the segment replication backpressure mechanism is initiated. Default is 4 checkpoints.
MAX_ALLOWED_STALE_SHARDS | Floating point | The maximum number of stale replica shards that can exist in a replication group. Once MAX_ALLOWED_STALE_SHARDS is breached, the segment replication backpressure mechanism is initiated. Default is .5, which is 50% of a replication group.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/pull/9507 
https://github.com/opensearch-project/OpenSearch/issues/8453

**Comment by hdhalter** [comment]
@Naarcha-AWS - Is this complete? Can we close?

**Comment by hdhalter** [comment]
@Naarcha-AWS - It doesn't look like this was done in 2.10. Can we get these added? Thanks.
