### ISSUE TITLE
[DOC] Add default text_docs input pre/post processor docs in ml-commons

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/documentation-website#5081]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Per this [issue](https://github.com/opensearch-project/ml-commons/issues/1304) and this [PR](https://github.com/opensearch-project/ml-commons/pull/1274) in ml-commons, we need to add the documentation to ml-commons plugin to let user know the default processors and how to use them in remote inference case correctly.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Links are already attached above.

**Comment by hdhalter** [comment]
@zane-neo - Is this feature going in 2.11? It's on the project roadmap, but wanted to confirm. Thanks.

**Comment by kolchfa-aws** [comment]
It will be going into 2.11 https://github.com/opensearch-project/ml-commons/pull/1397
