### ISSUE TITLE
[DOC] Documentation for Neural Sparse Feature

### ISSUE THREAD

**Issue by model-collapse** [opensearch-project/documentation-website#5105]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Requesting documentation for the newly developed feature Neural Sparse in the plugin of NeuralSearch. The feature will be released along with OpenSearch 2.11.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
RFC for requirement validation: https://github.com/opensearch-project/neural-search/issues/230
RFC for design: https://github.com/opensearch-project/neural-search/issues/284

**Comment by kolchfa-aws** [comment]
@model-collapse Could you provide an end-to-end example of how to use this query (including setting up the index, etc.)? Thank you!
