### ISSUE TITLE
[FEATURE] Documentation for upcoming RPM distribution release

### ISSUE THREAD

**Issue by setiah** [opensearch-project/documentation-website#511]
**Is your feature request related to a problem?**
https://github.com/opensearch-project/opensearch-build/issues/27

**What solution would you like?**
Provide documentation for 
1. RPM installation process via manual download
2. RPM installation process via yum download
3. OpenSearch version update process via yum

**What alternatives have you considered?**
None

**Do you have any additional context?**
None

**Comment by stockholmux** [comment]
I'll need to reference this on the downloads page - see opensearch-project/project-website#772

**Comment by elfisher** [comment]
@Naarcha-AWS we should get this added to the project board for tracking.
