### ISSUE TITLE
[DOC] Add Codec/Input Type support table

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#5136]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Add the following table to the S3 Source codec section.

 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@Naarcha-AWS - Is this complete?

**Comment by hdhalter** [comment]
@Naarcha-AWS - I believe this is complete, right?

**Comment by Naarcha-AWS** [comment]
https://opensearch.org/docs/latest/data-prepper/common-use-cases/codec-processor-combinations/ Yes
