### ISSUE TITLE
[PROPOSAL][Documentation] DateTimeFormatter time formatting characters reference for mapping a date field. 

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/documentation-website#514]
**What kind of business use case are you trying to solve? What are your requirements?**

A clear and concise reference of the formatting characters used when declaring a time format in an index mapping. 

**What is the problem? What is preventing you from meeting the requirements?**

After much clicking around I realized that the formatting characters are those as-implemented in "DateTimeFormatter", but people just wanting to aggregate their data shouldn't need to browse through the inheritance hierarchies to find "https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html" - let's try to spoon feed it.

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**

Either link right to it, or recreate the section describing the formatting characters under `Patterns for Formatting and Parsing` on 
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

**What are your assumptions or prerequisites?**

I'm assuming that the person making use of the product is not a programmer and wouldn't quite know how to find the appropriate information. 

**What are remaining open questions?**

If this base class is ever implemented differently or changed, how will we keep our doc up to date?

**Comment by hdhalter** [comment]
This has been documented: https://opensearch.org/docs/latest/opensearch/supported-field-types/date/
