### ISSUE TITLE
[DOC]: Security Analytics - Update Log Types in Log Type descriptions to include various log sources

### ISSUE THREAD

**Issue by praveensameneni** [opensearch-project/documentation-website#5145]
**What do you want to do?**
 
- [ x] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Please update the description for the following Log Types to include additional log sources

https://opensearch.org/docs/latest/security-analytics/sec-analytics-config/log-types/

Network events: Supports Zeek, Cisco / AAA, and firewall
System logs: Supports [auditd](https://github.com/opensearch-project/security-analytics/tree/main/src/main/resources/rules/linux/auditd), [builtin](https://github.com/opensearch-project/security-analytics/tree/main/src/main/resources/rules/linux/builtin), [file_create](https://github.com/opensearch-project/security-analytics/tree/main/src/main/resources/rules/linux/file_create), [modsecurity](https://github.com/opensearch-project/security-analytics/tree/main/src/main/resources/rules/linux/modsecurity), [network_connection](https://github.com/opensearch-project/security-analytics/tree/main/src/main/resources/rules/linux/network_connection), [other](https://github.com/opensearch-project/security-analytics/tree/main/src/main/resources/rules/linux/other), [process_creation](https://github.com/opensearch-project/security-analytics/tree/main/src/main/resources/rules/linux/process_creation)

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
N/A

**Comment by hdhalter** [comment]
@Naarcha-AWS - this is a request to update the descriptions in the documentation. It is not tied to 2.11, but they'd like to get it updated for the 2.11 docs. Thanks.

**Comment by hdhalter** [comment]
Hi @praveensameneni , we've updated the documentation to describe log types, but have not updated the information about network events or system logs. Is there someone on your team who can create a PR to update the doc? Thanks.

**Comment by Naarcha-AWS** [comment]
https://github.com/opensearch-project/security-analytics/tree/main/src/main/resources/OSMapping
