### ISSUE TITLE
[DOC] Add a note on default remote upload backpressure enabled by default

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/documentation-website#5150]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Changes corresponding to https://github.com/opensearch-project/OpenSearch/pull/10356. Please add a note on the https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/remote-store/remote-segment-backpressure/ that remote store upload backpressure is enabled by default.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@Naarcha-AWS - it looks like this is a change from 2.11. Can you please take a look and update, as needed? Thanks.

**Comment by hdhalter** [comment]
Reassigning to @vagimeli . Can you please get this updated appropriately? Thanks!
