### ISSUE TITLE
[DOC] CAT repositories documentation has incorrect description 

### ISSUE THREAD

**Issue by slippman** [opensearch-project/documentation-website#5160]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 I believe the description for the `_cat/repositories` API is incorrectly copied from the `_cat/recoveries` documentation. I believe the description should be: "Returns the snapshot repositories for a cluster."

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://opensearch.org/docs/2.3/api-reference/cat/cat-repositories/

**Comment by slippman** [comment]
I also checked this in the latest version documentation.

**Comment by BigSamu** [comment]
@Naarcha-AWS, I would like to work on this issue

**Comment by BigSamu** [comment]
Thanks @slippman. Pull Request #5296 was created. 

@Naarcha-AWS would appreciate your review on this one.

**Comment by slippman** [comment]
It looks like this issue was merged. Should I close this issue? Does this fix not get back-ported to earlier documentation? I only see the fix in the latest documentation.

**Comment by hdhalter** [comment]
@Naarcha-AWS - I'm going to close this issue, but please backport to earlier versions, as appropriate. Thanks!
