### ISSUE TITLE
[DOC] Openserach.org Users and roles docs are out of date

### ISSUE THREAD

**Issue by lmako-aws** [opensearch-project/documentation-website#5166]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Hi,

Just wanted to let you know that the list of built-in roles on the "[Users and roles](https://opensearch.org/docs/latest/security/access-control/users-roles/)" page of opensearch.org is severely out of date. 

Built-in roles that are available in Opensearch v2.7 but aren't listed in the documentation:
- index_management_read_access
- ml_full_access
- ml_read_access
- notifications_full_access
- notifications_read_access
- opensearch_dashboards_read_only
- opensearch_dashboards_user
- security_manager

Built-in roles that are listed in the documentation but aren't present in Opensearch v2.7:
- observability_full_access
- observability_read_access
- kibana_read_only (this is the Kibana equivalent of opensearch_dashboards_read_only)
- kibana_user (this is the Kibana equivalent of opensearch_dashboards_user)
- logstash
- manage_snapshots
- readall_and_monitor
- security_rest_api_access
- reports_read_access
- reports_full_access

Can we please get them in sync.

Thanks,
Laz

**Comment by lmako-aws** [comment]
There may be some roles in the list that were only added to Opensearch Managed Cluster through [roles.yml](https://github.com/opensearch-project/security/blob/main/config/roles.yml) and they don't apply to the open source version of Opensearch. Perhaps we could add those too but mark them as "AWS managed services only".

**Comment by BigSamu** [comment]
@Naarcha-AWS may I take this issue?

**Comment by john-eliatra** [comment]
@hdhalter Hi Heather, I'm just putting the comment in here to take this one.

**Comment by hdhalter** [comment]
> There may be some roles in the list that were only added to Opensearch Managed Cluster through [roles.yml](https://github.com/opensearch-project/security/blob/main/config/roles.yml) and they don't apply to the open source version of Opensearch. Perhaps we could add those too but mark them as "AWS managed services only".

Thanks for your contribution, @lmako-aws! However, in the OpenSearch documentation, we can only document the roles that are specific to open source and not mention AWS roles. @john-eliatra - if there are any roles that are specific to AWS, let's see if they need to be in there at all. Thanks.

**Comment by leanneeliatra** [comment]
@hdhalter can this be assigned to me please :) Thank you.

**Comment by hdhalter** [comment]
@lmako-aws - the documentation has been updated. Feel free to give it a review, and let us know what you think. Thanks!
https://github.com/opensearch-project/documentation-website/pull/6826; https://opensearch.org/docs/latest/security/access-control/users-roles/#predefined-roles

**Comment by lmako-aws** [comment]
It's tip-top. Thanks guys!
