### ISSUE TITLE
[BUG][UX] Make top sections accept focus (i.e. make them "click-able")

### ISSUE THREAD

**Issue by lukas-vlcek** [opensearch-project/documentation-website#518]
**What is the bug?**

To expand top level section, such as "Upgrade to OpenSearch", "OpenSearch", "OpenSearch Dashboards", "Security Plugin", ... etc, user has to click the small arrow "🔽" symbol next to section name. The section name element itself does not accept the focus.

This is in contrast to sub-sections which all accept focus (and thus their name can be clicked directly, no need to click the arrow).

**How can one reproduce the bug?**

See screenshots...
Interacting with the website without a pointer device can help understand the issue (see [accessibility instructions](https://www.accessibility-developer-guide.com/knowledge/keyboard-only/browsing-websites/#interacting-with-a-website)).

**What is the expected behaviour?**

When a top level section name is clicked then the browser is redirected to the "/index" URL of that section, similarly to how sub-sections already work now. 

**Do you have any screenshots?**

Sub-section | Top level section
--- | ---
Sub-section accept focus. | Top section does not accept focus **except for the arrow** element.
<img width="279" alt="Screenshot 2022-04-22 at 8 22 51" src="https://user-images.githubusercontent.com/205174/164615650-be2f9093-9c80-4035-9c50-9152c09ceb03.png"> | <img width="280" alt="Screenshot 2022-04-22 at 8 23 04" src="https://user-images.githubusercontent.com/205174/164615661-b6704e10-2ac4-44c6-bbb4-6fb5da7ef358.png">

**Comment by hdhalter** [comment]
Hi @lukas-vlcek, thanks for pointing this out and linking to that accessibility reference! I agree that our top-level section names should be clickable and link directly to topics. I'm not sure we can do this easily with our current template, but it is a requirement for the next iteration of our documentation.

**Comment by Naarcha-AWS** [comment]
Going to prioritize this before switching around the order of the TOC as described in #1036.

**Comment by Naarcha-AWS** [comment]
@nateynateynate: Would you have any perspective on the best way to approach this? I'm experimenting with removing collections, but wondering if there's an alternative to that strategy.

**Comment by hdhalter** [comment]
Adding @kolchfa-aws for visibility. Let's discuss next steps for how we can get this accomplished.

**Comment by hdhalter** [comment]
Hi @lukas-vlcek - we've implemented the ability for controls on the documentation site  to accept focus. Please check it out! I'm going to close this issue, but if you see anything else, please open a new issue. (Note that there are a couple things that are accepting focus out of order which we intend to fix.)
