### ISSUE TITLE
[DOC] Fix Snapshot Management Feature documentation 

### ISSUE THREAD

**Issue by setiah** [opensearch-project/documentation-website#5188]
**What do you want to do?** 
Remove Snapshot Management feature documentation from OpenSearch version 1.3 docs, since the feature is supported from OpenSearch v2.1 onwards. This is causing confusion.

See https://opensearch.org/docs/1.3/tuning-your-cluster/availability-and-recovery/snapshots/sm-api/ 

- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by JohnathonBowers** [comment]
Hi, @setiah and @Naarcha-AWS , could either of you take a look at PR #5376 and the discussion there? I removed the snapshot directory and the snapshot API material from the 1.3 documentation, but I'm not sure if more needs to be done.

**Comment by hdhalter** [comment]
This is fixed by https://github.com/opensearch-project/documentation-website/pull/5376. Thanks, @JohnathonBowers !
