### ISSUE TITLE
[BUG] Common REST parameters is missing "filter_path"

### ISSUE THREAD

**Issue by lukas-vlcek** [opensearch-project/documentation-website#519]
**What is the bug?**

The documentation for common REST parameters is missing `filter_path` parameter.
See the `org.opensearch.rest.AbstractRestChannel` for details.

I would also suggest to not use the table for content formatting. The Description column is too narrow.
I think it would be better to format the page as a standard page with paragraphs. One of the benefits would be that individual common parameters can be URL linked from forum posts.

**Comment by smsalamon** [comment]
Hi @lukas-vlcek, I'd like to work on this if you want to assign it to me?
