### ISSUE TITLE
[PROPOSAL] Adjust design to fit wide screen resolutions

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/documentation-website#527]
### What are you proposing?
I'm kindly asking to update website design to occupy more space on the screen. Unfortunately, the crucial part of the page is fixed on 740px width, which leaves too much blank space on any monitor of the 21st century. See pic below:
![image](https://user-images.githubusercontent.com/88679692/165403017-6eb03701-1c28-4a5e-9924-cd98045fa7ac.png)
My screen has 2560*1440 resolution, so I have 3/4 of screen blank.
Furthermore, such restriction makes some parts of documentation unreadable, as you can see on the screenshot. It is table `Options` on [this page](https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#options).

### What is the user experience going to be?
1. The text block dimensions should be adjusted and extended to the window size automatically;
2. A user should be able to hide navigation blocks on the left and on the right, which would allocate more space for the central block.
or 
3. A user should be able to adjust size of side blocks manually. See [Jira](https://jira.atlassian.com/issues/?filter=12844) as a good example.

**Comment by hdhalter** [comment]
This was reported for v2.0.0, and fixed: https://github.com/opensearch-project/documentation-website/issues/554. Let me see if we can push the fix also in 1.3.x.

**Comment by hdhalter** [comment]
This has been implemented.

**Comment by Yury-Fridlyand** [comment]
I confirm, great job!
