### ISSUE TITLE
[BUG] Some parameters of Full-text Queries are not explained or lack of information.

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/documentation-website#528]
### What is the bug?
1. Examples given on [this page](https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/) have some options (function arguments actually) that are not explained nor described.
I found these options lack of documentation:
- `default_field`
- `fuzzy_max_expansions`
- `fuzzy_prefix_length`
- `default_operator`
- `quote_analyzer`
2. Some options have ambiguous (or missing) description:
- What is `language` for `analyzer`?
- What is `Boolean` options' valid values? What of the following could be used: `true/false`, `TRUE/FALSE`, `"true"/"false",` `0/1`, `"0"/"1"`, `"yes"/"no"`, `"Y"/"N"`, `YES/NO`?
- Which restrictions apply for `cutoff_frequency` and `fuzziness`? Could it be `>100` or `.5` or `50%`? (also relevant for `max_determinized_states`, `max_expansions`, `minimum_should_match`, `phrase_slop`, `prefix_length`, `slop`).
- Which formats are valid for `time_zone`? `-08:00`, `"-08:00"`, `PDT`, `"PST"`, `UTC`, `UTC-1`, `"UTC+2"`, `America/Vancouver`, `"America/Vancouver"`?

### What is the expected behavior?
* There is table `Option` in [the bottom](https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#options), which should contain all existing arguments and options. `cutoff_frequency` is deprecated, for example.
Options' allowed values, rules and restrictions should be verbosely described as well.
* Regarding `language` for `analyzer` - I know that it is described in [Elastic documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/analysis-lang-analyzer.html), but OpenSearch is not Elasticsearch. So, corresponding parts of Elasticsearch documentation should be copied there or, at least, referenced. This is relevant for all parameters, not only for those I listed. Elastic gives another definition for acceptable values for `minimum_should_match` and `fuzziness` as well (links: [one](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-minimum-should-match.html), [two](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/common-options.html#fuzziness)).

**Comment by Yury-Fridlyand** [comment]
Some parameter values are case-sensitive - this should be mentioned as well.

**Comment by alicejw-aws** [comment]
quick note: tested out there is no "fuzzy_prefix_length" you use the prefix_length for a fuzzy query.
tested it:   "reason" : "[match] query does not support [fuzzy_prefix_length]",

**Comment by Yury-Fridlyand** [comment]
Hi @alicejw-aws,
Thank you for your reply.
`cutoff_frequency` is deprecated, please see OpenSearch sources:
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/query/MatchQueryBuilder.java#L61-L72

**Comment by alicejw-aws** [comment]
ok thanks @Yury-Fridlyand for providing the confirmation that they are deprecated. 
I'll update the document accordingly.
I had tested cutoff_frequency in a Dashboard query, and it worked/no errors so i thought it was still active.
