### ISSUE TITLE
[BUG] Missing documentation for security plugin `reloadcerts` endpoints

### ISSUE THREAD

**Issue by peternied** [opensearch-project/documentation-website#530]
### What is the bug?
The `_opendistro/_security/api/ssl/{certType}/reloadcerts/` API is not documented on https://opensearch.org/docs/latest/security-plugin/index/

### How can one reproduce the bug?
Look through the security APIs or search opensearch.org for `reloadcerts`, it cannot be found

### What is the expected behavior?
All APIs for the security plugin should be documented, see some javadocs on that API already https://github.com/opensearch-project/security/blob/565f47e804ec03aeeba02ca8def563b91307fcc7/src/main/java/org/opensearch/security/ssl/rest/SecuritySSLReloadCertsAction.java#L50

### Do you have any additional context?
I think this is a tip-of-the-iceberg kind of issue, there are likely many other APIs that are not documented. Quickly checking a subset of the APIs in security with [query for BaseRestHandler](https://github.com/opensearch-project/security/search?q=BaseRestHandler) shows the following gaps:

| Documented | API Path | Http Verbs |  Code Reference | Notes |
| - | - | - | - | - |
| 🚫  | `/_plugins/_security/dashboardsinfo` | GET & PUT | [DashboardsInfoAction](https://github.com/opensearch-project/security/blob/54a920b20bd520f25aef328c1bb4997b325f46ce/src/main/java/org/opensearch/security/rest/DashboardsInfoAction.java#L59) | 
| 🚫  |`/_plugins/_security/kibanainfo` | GET & PUT | [DashboardsInfoAction](https://github.com/opensearch-project/security/blob/54a920b20bd520f25aef328c1bb4997b325f46ce/src/main/java/org/opensearch/security/rest/DashboardsInfoAction.java#L59) | should be deprecated?
| 🚫 | `/_plugins/_security/whoami` | GET & POST | [SecurityWhoAmIAction](https://github.com/opensearch-project/security/blob/81a43c22d5d3dd952d442e2739159c8dc75d582f/src/main/java/org/opensearch/security/rest/SecurityWhoAmIAction.java#L38) | No java docs
| 🚫 | `/_opendistro/_security/sslinfo` | GET |  [SecuritySSLInfoAction](https://github.com/opensearch-project/security/blob/54a920b20bd520f25aef328c1bb4997b325f46ce/src/main/java/org/opensearch/security/ssl/rest/SecuritySSLInfoAction.java) |
| ✔️ | `_opendistro/_security/api/ssl/{certType}/reloadcerts/` | PUT | [SecuritySSLReloadCertsAction](https://github.com/opensearch-project/security/blob/565f47e804ec03aeeba02ca8def563b91307fcc7/src/main/java/org/opensearch/security/ssl/rest/SecuritySSLReloadCertsAction.java#L41) | Has java documentation
| 🚫 | `/permissionsinfo` | GET | [PermissionsInfoAction](https://github.com/opensearch-project/security/blob/565f47e804ec03aeeba02ca8def563b91307fcc7/src/main/java/org/opensearch/security/dlic/rest/api/PermissionsInfoAction.java) | Internal only API?
| 🚫 | `/_plugins/_security/authinfo` | GET & POST | [SecurityInfoAction](https://github.com/opensearch-project/security/blob/54a920b20bd520f25aef328c1bb4997b325f46ce/src/main/java/org/opensearch/security/rest/SecurityInfoAction.java) |
| 🚫 | `/_plugins/_security/tenantinfo` | GET & POST | [TenantInfoAction](https://github.com/opensearch-project/security/blob/54a920b20bd520f25aef328c1bb4997b325f46ce/src/main/java/org/opensearch/security/rest/TenantInfoAction.java) | 
| 🚫  | `/_plugins/_security/configupdate` | PUT | [SecurityConfigUpdateAction](https://github.com/opensearch-project/security/blob/81a43c22d5d3dd952d442e2739159c8dc75d582f/src/main/java/org/opensearch/security/rest/SecurityConfigUpdateAction.java) |

**Comment by cliu123** [comment]
Duplicate of the issue #535. Please close this one.

**Comment by peternied** [comment]
While the request is very similar to issue #535, this contains more context on other missing areas.  I'd like the maintainers of this repo to weigh to handle the path forward.

**Comment by Naarcha-AWS** [comment]
I decided to close the older issue #535, in favor of this one.

**Comment by Naarcha-AWS** [comment]
Remember to assign to Chris.

**Comment by peternied** [comment]
@cwillum This issue also documents several other APIs that are missing documentation.  Would it make sense to keep this issue open or migrate those other APIs in another issue?

**Comment by cwillum** [comment]
@peternied Good question. I ran this by the team earlier and the consensus was that it would be better to break the APIs into separate issues. There should be advantages to tracking them separately.

**Comment by peternied** [comment]
Gotcha - until we have those issues file could we keep this open, and went we have them all we close this issue?

**Comment by cwillum** [comment]
Will close this issue again once there are separate issues for the other APIs mentioned above. Those can be referenced back to this issue.

**Comment by peternied** [comment]
@hdhalter Could you reference the pull request or other issue are associated with this?

**Comment by hdhalter** [comment]
Sorry, Peter! It's unclear what is left to do on this issue. @cwillum - can you please make notes to indicate what is done and what is left to do?

**Comment by kolchfa-aws** [comment]
@hdhalter @Naarcha-AWS @cwillum should these be added to #424?

**Comment by cwillum** [comment]
I count eight more issues in need of attention in the list above. The `reloadcerts` API (central to this issue) is in our documentation. 
@hdhalter @peternied I can add these new issues. After that we can close this one.
@kolchfa-aws @Naarcha-AWS Once I have issues for the remaining eight APIs, I'll add those to [#424](https://github.com/opensearch-project/documentation-website/issues/424).

**Comment by Naarcha-AWS** [comment]
@cwillum and @peternied: Moved the table with the other eight APIs to a new issue. Since these are specific to the security plugin and not OpenSearch core, let's avoid adding these to #424.

**Comment by peternied** [comment]
@Naarcha-AWS Thanks for creating #887 I'm good to close out this issue

**Comment by cwillum** [comment]
Closing this issue. 
Remaining eight security APIs that need documentation are covered by [#887](https://github.com/opensearch-project/documentation-website/issues/887).
The `reloadcerts` API is covered by [#753](https://github.com/opensearch-project/documentation-website/pull/753).
