### ISSUE TITLE
[PROPOSAL] Document Review Process in Readme

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#531]
### What are you proposing?
As we add more full time writers to the OpenSearch project, we need to take the time to codify and clarify the PR review process. This documentation is even more important with the addition of our new editor, who gives the final sign off before a OpenSearch docs contribution is merged.

After we've finalized the review process, let's publish the entire process in the documentation-website readme.

### What will it take to execute?

- [x] Create any labels needed to help aid in the review process
- [ ] Document the review process in the documentation website readme

**Comment by hdhalter** [comment]
Here is an internal document that outlines the review process for PRs. https://quip-amazon.com/lSyeAj55sfSt/Add-review-comments-to-a-PR-in-GitHub. 

But, @Naarcha-AWS, I think you are more concerned with how we review external contributors' input?

**Comment by Naarcha-AWS** [comment]
https://quip-amazon.com/24daAPTLn6xt/Readmemd-DRAFT

**Comment by hdhalter** [comment]
Merged the second part of this issue: Removed Partners from the footer.
