### ISSUE TITLE
[DOC] Add model version column; clarify model redeploy

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/documentation-website#5314]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
1. On https://opensearch.org/docs/latest/ml-commons-plugin/ml-framework/ and https://opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/ We should clarify that if user run a model inside OpenSearch cluster. When cluster restarted, or some node restarted, the model needs to be redeployed. If they want to avoid that effort , they should use https://github.com/opensearch-project/ml-commons/blob/2.x/docs/tutorials/model_auto_redeploy.md

2. on https://opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/, the table doesn't have latest version column, we should add it, because not all models are using same latest version

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Hi @kolchfa-aws, were these issues addressed with the latest revision of the documentation? Thanks!

**Comment by kolchfa-aws** [comment]
@hdhalter The second part is. The first one is not.

**Comment by hdhalter** [comment]
@ylwu-amzn - Is there someone who can update the documentation for the first issue?
