### ISSUE TITLE
[DOC] Connecting multiple data sources

### ISSUE THREAD

**Issue by setgian** [opensearch-project/documentation-website#5316]
Connecting multiple data sources
https://opensearch.org/docs/2.11/dashboards/management/multi-data-sources/
 
- [ X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

in documentation:

"To enable multiple data sources:

Navigate to your Dashboards home directory, for example, in Docker, /usr/share/opensearch-dashboards.
[...]
"
the .yml config file is under "/usr/share/opensearch-dashboards/config" folder instead

**Comment by BigSamu** [comment]
@Naarcha-AWS, the issue resolved. PR #5391 raised. I checked against the base code of OpenSearch-Dasboards, and @setgian is correct!

**Comment by hdhalter** [comment]
Thanks, @BigSamu ! Closing this issue.
