### ISSUE TITLE
[FEATURE] Update clients and tools compatibility matrix

### ISSUE THREAD

**Issue by elfisher** [opensearch-project/documentation-website#533]
### Is your feature request related to a problem?

[`compatibility.override_main_response_version: true`](https://opensearch.org/docs/latest/opensearch/configuration/) was deprecated in OpenSearch 1.x and is being removed in 2.0. This will impact what legacy clients and other tools are compatible with OpenSearch 2.0 since it will not be able to use this setting. 

At a minimum, it will impact the following pages:
* https://opensearch.org/docs/latest/clients/index/
* https://opensearch.org/docs/latest/clients/agents-and-ingestion-tools/index/

### What solution would you like?
We should update these pages to reflect what will and will not be compatible with OpenSearch 2.0.

**Comment by Naarcha-AWS** [comment]
@elfisher: Would this also be considered a breaking change?

**Comment by alicejw-aws** [comment]
Hi @elfisher 
Is there an alternative setting that they will use instead of the deprecated (in 1.x/removed in 2.0) setting? 
Or is it ok to just remove all mentions of it? 
Thanks

**Comment by alicejw-aws** [comment]
i found a related ticket with related information : [Remove Override #517](https://github.com/opensearch-project/documentation-website/issues/517)

**Comment by alicejw-aws** [comment]
Need info: what specifically is not compatible with OpenSearch 2.0 on this list?
https://opensearch.org/docs/latest/clients/index/

**Comment by alicejw-aws** [comment]
another question: do we need to update all 1.x doc sets to note this is deprecated? Or is it sufficient to just remove it from the 2.0 doc version?

**Comment by alicejw-aws** [comment]
Hi @VachaShah, could you help me identify any of the items on this [index page](https://opensearch.org/docs/latest/clients/index/)

There is a list of legacy clients and tools - could you help me identify granularly which ones on this list will work with 2.0 (now that the setting is removed)?

Or, if it's all of them, is it ok in your opinion to give a generic note that none of them will work with 2.0?
Thanks
