### ISSUE TITLE
[BUG] Missing geotile_grid aggregation documentation

### ISSUE THREAD

**Issue by nknize** [opensearch-project/documentation-website#538]
### What is the bug?
The documentation website does not cover the [`geotile_grid` aggregation](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/bucket/geogrid/GeoTileGridAggregationBuilder.java) 

### How can one reproduce the bug?
Navigate to: https://opensearch.org/docs/latest/opensearch/bucket-agg/#geo_distance-geohash_grid

### What is the expected behavior?
Documentation to include `geotile_grid` aggregation.

### What is your host/environment?
Internet / Chrome

### Do you have any screenshots?
I can provide if needed

**Comment by Naarcha-AWS** [comment]
@nknize: If you do have screenshots, they would be useful here.

**Comment by hdhalter** [comment]
Hi @nknize - the documentation for geotile_grid is here: https://opensearch.org/docs/latest/aggregations/bucket/geotile-grid/. Thanks so much! I am closing this issue.
