### ISSUE TITLE
[DOC] Update link in OpenSearch docs to newer Lucene docs

### ISSUE THREAD

**Issue by evankielley** [opensearch-project/documentation-website#5389]
**What do you want to do?**
 
- [ x ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Update the link on the OpenSearch docs for HyphenationCompoundWordTokenFilter (https://opensearch.org/docs/latest/analyzers/token-filters/index/#:~:text=HyphenationCompoundWordTokenFilter) to point at new v9.8.0 Lucene docs.

What the OpenSearch docs have now: https://lucene.apache.org/core/8_7_0/analyzers-common/org/apache/lucene/analysis/compound/HyphenationCompoundWordTokenFilter.html

What the OpenSearch docs should have after this change: https://lucene.apache.org/core/9_8_0/analysis/common/org/apache/lucene/analysis/compound/HyphenationCompoundWordTokenFilter.html

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
 
OpenSearch PR [#10765](https://github.com/opensearch-project/OpenSearch/pull/10765) introduced two new arguments to the HyphenationCompoundWordTokenFilter constructor in order to catch up with the arguments being added to Lucene in this PR: https://github.com/apache/lucene/pull/12437

**Comment by BigSamu** [comment]
@Naarcha-AWS I want to work on this one!
