### ISSUE TITLE
[DOC] The "Dangling indexes API" page doesn't show up in the left nav

### ISSUE THREAD

**Issue by alex-at-cascade** [opensearch-project/documentation-website#5393]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 The  "Dangling indexes API" page https://opensearch.org/docs/2.11/api-reference/index-apis/dangling-index/ doesn't show up in the left nav

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by sushanthvutukuri** [comment]
I can pick up this issue. My git username is sushanthvutukuri.

**Comment by hdhalter** [comment]
Hi @sushanthvutukuri , are you still planning to fix this or do you need some help? Looks like a capitalization issue with the parent: 
<img width="247" alt="image" src="https://github.com/opensearch-project/documentation-website/assets/104463754/430f4fb9-4cf3-435a-a7b8-7503268e8edf">

**Comment by hdhalter** [comment]
Hi @sushanthvutukuri - are you still planning to work on this? Thanks!
