### ISSUE TITLE
[DOC] The `_index_template' API docs are missing

### ISSUE THREAD

**Issue by alex-at-cascade** [opensearch-project/documentation-website#5394]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
The `_index_template` API docs are missing.  It would be helpful if the full description of the API was covered.  (As well as the deprecated `_template` APIs, for helping to understand code that are calling those.)

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Hi @alex-at-cascade - does this page cover the information you are looking for? https://opensearch.org/docs/2.11/im-plugin/index-templates/

**Comment by alex-at-cascade** [comment]
That seems to have *some* stuff, but it seemed like it might be incomplete.  I was looking for the *full* API definition in the "API Reference" section.  (As an example, see how https://opensearch.org/docs/2.11/api-reference/index-apis/alias/ has a lot more detail than https://opensearch.org/docs/2.11/im-plugin/index-alias/ )

**Comment by hdhalter** [comment]
@kolchfa-aws  - Assigning to you so you can look into it when you start work on the API coverage. Thanks.
