### ISSUE TITLE
[DOC] Create documentation corresponding to changes in _nodes/stats api in OpenSearch

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/documentation-website#5400]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected. Fixed by:
 https://github.com/opensearch-project/documentation-website/pull/5184 - Thanks @BhumikaSaini-Amazon!
https://github.com/opensearch-project/OpenSearch/pull/10656 - @Rishikesh1159 Need your help to provide more details here.
https://github.com/opensearch-project/OpenSearch/pull/10670 - @amkhar Need your help to provide more details here
https://github.com/opensearch-project/OpenSearch/pull/10567- @gbbafna  Need your help to provide more details here.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@Naarcha-AWS  - is this a duplicate issue to https://github.com/opensearch-project/documentation-website/issues/5409?

**Comment by hdhalter** [comment]
Hi @amkhar , @ashking94 - does #5662 cover everything in this issue or are further PRs needed?

**Comment by hdhalter** [comment]
@Naarcha-AWS - What is the status of this?
