### ISSUE TITLE
[DOC] Combined Fields (BM25F) Documentation

### ISSUE THREAD

**Issue by macohen** [opensearch-project/documentation-website#5425]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We are adding BM25F support which is a new query type we are integrating from Lucene. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/issues/3996

cc: @mingshl

**Comment by kolchfa-aws** [comment]
Removing the 2.12 label because this is not going to make it into 2.12 cc: @ylwu-amzn @mingshl

**Comment by hdhalter** [comment]
@ylwu-amzn , @mingshl , is this going out in 2.13? Thanks.

**Comment by mingshl** [comment]
@hdhalter  thanks for following up. No, we have other priorities for 2.13 now. Will update again once we have new timeline.

**Comment by hdhalter** [comment]
Hi @mingshl , do you know if this is targeting 2.14? Thanks!

**Comment by mingshl** [comment]
@hdhalter we are not prioritizing this task, I will close it for now, and reopen this task when we need it. thanks!
