### ISSUE TITLE
[DOC] match_only_text handler 

### ISSUE THREAD

**Issue by macohen** [opensearch-project/documentation-website#5427]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
match_only_text handler was originally requested by someone using Elastic Common Schema which has a dependency on this feature. Subsequently, we realized this could be a useful performance  enhancement and are targeting a 2.12 release.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/issues/6836

cc: @rishabhmaurya (the developer working on this)

**Comment by hdhalter** [comment]
Thanks for entering the issue, @macohen ! @rishabhmaurya , will you be creating the PR for this doc update?

**Comment by hdhalter** [comment]
Assigning @kolchfa-aws for visibility.
