### ISSUE TITLE
[DOC] Search latency stats for coordinator node

### ISSUE THREAD

**Issue by sgup432** [opensearch-project/documentation-website#5446]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We added a feature as part of https://github.com/opensearch-project/OpenSearch/pull/8386 where we now have the ability to track coordinator level search latency stats. We need to document this feature. 
**Note**: This feature already went as part of 2.11 release.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/pull/8386 - PR
https://github.com/opensearch-project/OpenSearch/issues/8381 -  Related issue

**Comment by hdhalter** [comment]
@sgup432 - Can you please take a stab at documenting this? If you put up a PR with the required information, we will review and merge. Thanks!
