### ISSUE TITLE
[DOC] Text Embedding" search result leads nowhere

### ISSUE THREAD

**Issue by lmako-aws** [opensearch-project/documentation-website#5449]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

When you search for "text embedding", the search results will have a corresponding find. called "Text Embedding". When you click on this item, it doesn't take you to the appropriate page and you land on the homepage instead. 
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
- Visit https://opensearch.org/docs/latest/
- On the top right, type "text embedding" in the search text box
- In the results window click on "Text Embedding"
- Notice that you land on the home page instead as the resource either doesn't exist or the search results points to the wrong location.

**Comment by hdhalter** [comment]
@lmako-aws - Thanks so much for creating an issue! I'm not personally able to reproduce this. It's a relatively new page, so maybe a caching issue? If someone else can reproduce it, let me know and I'll look into it further.

**Comment by lmako-aws** [comment]
Hmm interesting. I've just checked in Chrome and Safari and they both worked. Maybe it's a Firehose-only issue or caching related, as you've mentioned rightly so.

**Comment by hdhalter** [comment]
OK, I'm going to close this issue. If you find anything else that you think needs to be addressed, don't hesitate to reach out.

**Comment by lmako-aws** [comment]
Sure, thanks for the quick turnaround @hdhalter
