### ISSUE TITLE
Using a temporary search pipeline for a request - pipeline vs search_pipeline

### ISSUE THREAD

**Issue by kirubasankars** [opensearch-project/documentation-website#5473]
https://opensearch.org/docs/latest/search-plugins/search-pipelines/using-search-pipeline/#using-a-temporary-search-pipeline-for-a-request 

- [ ] Report a technical problem with the documentation

Detailed attached : https://github.com/opensearch-project/OpenSearch/issues/11030

**Comment by kirubasankars** [comment]
[Documentation i](https://github.com/opensearch-project/OpenSearch/blob/main/modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/30_filter_query.yml#L90C12-L90C27)

Based on integration test. its search_pipeline, not pipeline.

**Comment by msfroh** [comment]
D'oh! This was probably my fault. 

If I recall correctly, the parameter was just `pipeline` originally, but we changed it to `search_pipeline` just before the feature shipped. The examples that I sent for documentation were likely from before the change.
