### ISSUE TITLE
[DOC] Field masking roles.yml example is out of date

### ISSUE THREAD

**Issue by terryquigleysas** [opensearch-project/documentation-website#5476]
**What do you want to do?**
 
- [ ] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

The example at https://opensearch.org/docs/latest/security/access-control/field-masking/#rolesyml does not work.
![image](https://github.com/opensearch-project/documentation-website/assets/77437788/a7002a8b-b445-4301-8ace-f3ca13b7a270)

It appears to be out of date. It should at least reference _index_permissions_ and _index_patterns_ as output by the securityadmin backup and https://opensearch.org/docs/latest/security/access-control/api/#create-role

![image](https://github.com/opensearch-project/documentation-website/assets/77437788/bc62ce88-ac26-4e8b-8ff6-8531e2d8e3b6)

**Comment by ShatilKhan** [comment]
Can I take this one? @Naarcha-AWS

**Comment by Naarcha-AWS** [comment]
@ShatilKhan: Assigned.

**Comment by hdhalter** [comment]
> Can I take this one? @Naarcha-AWS

Hi @ShatilKhan , are you still interested in working on this?

**Comment by ShatilKhan** [comment]
@hdhalter 
Yeah I'll finish it up within a few days

**Comment by hdhalter** [comment]
Just checking in, @ShatilKhan. Are you working on this, or should I reassign? Thanks!

**Comment by hdhalter** [comment]
> @hdhalter If you would like to reassign I am willing to volunteer our efforts towards this.

Thanks, @terryquigleysas ! I'll assign to you.

**Comment by terryquigleysas** [comment]
@hdhalter Is there anything else I need to be added to the PR (e.g. labels) to ensure it gets picked up?

**Comment by hdhalter** [comment]
Thanks, @terryquigleysas! I will kick off the required review process.
