### ISSUE TITLE
[DOC] Threat Intelligence based detection in Security Analytics plugin

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/documentation-website#5489]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
@eirsep: Can you provide additional information on what's needed to complete the issue?

**Comment by Naarcha-AWS** [comment]
@jowg-amazon provided some intel. This currently exists in the managed service but does not exist in Open Source. The team plans on moving to Open Source during 2.12.

**Comment by Naarcha-AWS** [comment]
@eirsep: Will assist directly with the threat intelligence details.
