### ISSUE TITLE
Security-admin docs contain references to `.opensearch_security`

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/documentation-website#55]
It looks like the docs are incorrect on the [security admin](https://docs-beta.opensearch.org/security-plugin/configuration/security-admin/) page - it references `.opensearch_security` as an index. Using RC1, the index is still `.opendistro_security`. To my knowledge this isn't changing prior to GA.

Looking back in history, this seems to be unchanged from the repo creation. Perhaps a copy/paste error?

**Comment by aetter** [comment]
https://github.com/opensearch-project/documentation-website/commit/4e469c25796131352ff4522ea1d957dadd702d39
