### ISSUE TITLE
[DOC] Diversified Sampler Agg doc does not include max_docs_per_value parameter

### ISSUE THREAD

**Issue by jed326** [opensearch-project/documentation-website#5509]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The doc https://opensearch.org/docs/latest/aggregations/bucket/diversified-sampler/ is missing the `max_docs_per_value` parameter. Additionally, it would be good to have a short description of what these parameters do. 

For more details see: https://github.com/opensearch-project/OpenSearch/issues/11075

**Comment by BigSamu** [comment]
@Naarcha-AWS I want to take this one

**Comment by hdhalter** [comment]
@jed326 - Would you like to take a stab at updating the documentation?

**Comment by jed326** [comment]
@hdhalter sure, I think I have a few docs PRs I'm planning to open in the next week or two so I can just take them all together
