### ISSUE TITLE
[DOC] dead links

### ISSUE THREAD

**Issue by grinapo** [opensearch-project/documentation-website#5527]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

There are multiple 404s in the documentation, wouldn't it be useful to run a robot through it collecting them and give a list to fix? 

_Anyway_, my specific one is
 `https://opensearch.org/docs/latest/search-plugins/sql/ppl/index`
which links to
 `https://opensearch.org/search-plugins/sql/ppl/functions/`
which does not exist. I guess `/docs/` is missing.

**Comment by grinapo** [comment]
(I can run a link verifier if you'd like me to, but I am very new around so shouldn't just offer to actually fix them.)

**Comment by BigSamu** [comment]
@Naarcha-AWS may I take this one?

**Comment by hdhalter** [comment]
Which version are you running? We know that in earlier versions of the documentation we have several link issues. See https://github.com/opensearch-project/documentation-website/issues/5472. 
We do run a link checker with each build, so the latest documentation should be dead link-free.

**Comment by BigSamu** [comment]
@hdhalter,

Just created PR #5528. They problem was very minor. prefix `{{site.url}}{{site.baseurl}}` was not included in the link `Commands` under the `PPL commands` section.

**Comment by grinapo** [comment]
(_Yes but_ I think I have seen some other dead links in the course of installing, including ones referenced from dashboards' help.)

**Comment by BigSamu** [comment]
@grinapo,

Please try to gather all those dead links you find and open a separate issue or update this one. I will take a look at them and compare it with issue #5472 mentioned by @hdhalter.

**Comment by hdhalter** [comment]
Please open a new issue if you find other broken links or feel free to submit a PR for a quicker fix. : ) Thanks.

**Comment by grinapo** [comment]
> Please try to gather all those dead links you find and open a separate issue or update this one. 

Responding here, since my linkchecker told me that there are no further dead links in /docs/latest/. Thanks!

`2732 links in 2734 URLs checked, no errors`
