### ISSUE TITLE
[DOC] New OSD Homepage

### ISSUE THREAD

**Issue by seanneumann** [opensearch-project/documentation-website#5530]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 OpenSearch Dashboards is building a new home page that will need accompanying documentation. Please sync up with eng teams to dive into details. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Eng Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5251
Proposed Experience: opensearch-project/OpenSearch-Dashboards/issues/5251

**Comment by wbeckler** [comment]
@joshuarrrr @BSFishy

**Comment by hdhalter** [comment]
Moved to the 2.13 release.

**Comment by hdhalter** [comment]
I'm closing this issue. There is a change to the framework in this release but they are not exposing it in the documentation. @vagimeli  - fyi
