### ISSUE TITLE
Remove Markdown errors from Documentation 

### ISSUE THREAD

**Issue by shubhusion** [opensearch-project/documentation-website#5545]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
 Remove Markdown and linting errors from Documentation.

**Comment by Naarcha-AWS** [comment]
@shubhusion: do you have more details on markdown and linting errors you are encountering?

**Comment by shubhusion** [comment]
> @shubhusion: do you have more details on markdown and linting errors you are encountering?

Punctuation errors, Styling and linting errors, Trailing white spaces etc

**Comment by shubhusion** [comment]
@Naarcha-AWS Ready for PR. Do I need to Update Changelog as well?

**Comment by Naarcha-AWS** [comment]
No need to update the changelog @shubhusion

**Comment by hdhalter** [comment]
The PR was closed, so closing this issue.
