### ISSUE TITLE
[DOC] Mismatch between "normalization-processor" and "normalization_processor"

### ISSUE THREAD

**Issue by upwards-gravity** [opensearch-project/documentation-website#5554]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
I noticed that some pages use the term `normalization_processor` (with an underscore), at least in the text.
The actual name of the processor is `normalization-processor` (with a hyphen) though.
That is also what the examples that I have seen use.

This is confusing and may lead to using the wrong spelling in code, leading to issues downstream.

Affected pages include:
- https://opensearch.org/docs/latest/search-plugins/search-pipelines/normalization-processor
- https://opensearch.org/docs/latest/ml-commons-plugin/semantic-search

I would suggest to replace the term `normalization_processor` with `normalization-processor` on all affected pages.

**What other resources are available?**
The relevant code is: https://github.com/opensearch-project/neural-search/blob/main/src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessor.java#L37

**Comment by hdhalter** [comment]
Hi @upwards-gravity , thanks for the feedback! We'll look into it and update as appropriate. @Naarcha-AWS - can you see if one of the OSCI participants want to take this?
