### ISSUE TITLE
[DOC] Supported model_format in ML Framework

### ISSUE THREAD

**Issue by aruggero** [opensearch-project/documentation-website#5559]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

[Here](https://opensearch.org/docs/latest/ml-commons-plugin/ml-framework/#model-format) both ONNX and TorchScript formats are supported but in the [request fields table](https://opensearch.org/docs/latest/ml-commons-plugin/ml-framework/#upload-model-to-opensearch), the `model_format` parameter only supports `TORCH_SCRIPT`.
Which formats are supported?

**Comment by hdhalter** [comment]
Thanks for your question, @aruggero , we'll look into it! @kolchfa-aws - who would be the best person to ask about this?

**Comment by kolchfa-aws** [comment]
Hi @aruggero, `ONNX` is also supported. I'm updating the documentation. Thanks for bringing it up!
