### ISSUE TITLE
[DOC] Change the sample command for open search-benchmark test-procedure

### ISSUE THREAD

**Issue by beaioun** [opensearch-project/documentation-website#5566]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
For the opensearch-benchmark， there is this **test-procedure** definition at this link:[test-prcedure](https://opensearch.org/docs/latest/benchmark/reference/commands/execute-test/#test-procedures), which includes a sample command that does not work after confirming with the maintainer of this repo. `opensearch-benchmark list test-procedures` here uses list but it is not part of the list feature and will produce an error message like this:
![image](https://github.com/opensearch-project/documentation-website/assets/94433735/89e41ede-4fbc-4650-b9e9-0ae86cdd2f54)
We can replace this sample command with info or just delete it.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks for your feedback, @beaioun! We'll look into it and update as appropriate. 
Assigning to @Naarcha-AWS.
