### ISSUE TITLE
[DOC] Fix wrong example

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/documentation-website#5591]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 https://opensearch.org/docs/latest/ml-commons-plugin/ml-framework/#example-request

MIssed `model_content_hash_value` , refer to https://github.com/opensearch-project/documentation-website/issues/4966

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by kolchfa-aws** [comment]
@ylwu-amzn Should we replace the outdated `upload` call with a `register` call?

**Comment by ylwu-amzn** [comment]
Yes, we should use `register`
