### ISSUE TITLE
Documentation for the support of Date Math Index pattern while creating and indexing data in the indices. 

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/documentation-website#56]
Currently in Open-search we have the index names supporting the date math in the index pattern. We can create indices with the names consisting of the pattern described [here](https://en.wikipedia.org/wiki/Wikipedia:Date_math). % Encoding is required while sending the request. 

In alerting we had a request from the customer where we wanted to give them the support for defining these indices in the desired pattern while creating the monitors. The pattern would be exact similar to the one which is used while creating and indexing data into these indices. 

https://github.com/opensearch-project/alerting/issues/74 
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/17

We have added this functionality and wanted to update our documentation for it. We wanted to link the document describing the index creation in the required pattern in open-search.

Thanks!

**Comment by ashwinkumar12345** [comment]
Please review and add in any comments - https://github.com/opensearch-project/documentation-website/pull/116/files.
