### ISSUE TITLE
[BUG] Typo in ml-commons-plugin/api/

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/documentation-website#560]
### What is the bug?
"Algorithm name: Must be one of a [FunctionaName](https://github.com/opensearch-project/ml-commons/blob/1.3/common/src/main/java/org/opensearch/ml/common/parameter/FunctionName.java)."
Two problems: 
1. the name of the enum is FunctionName, not FunctionaName
2. the syntax is strange

### How can one reproduce the bug?
See page

### What is the expected behavior?
One of these:
- Must be a member of the FunctionName enum.
- Must be a member of FunctionName.
- Must be a FunctionName value.
- Must be an enum of type FunctionName.

### What is your host/environment?
irrelevant

### Do you have any screenshots?
unnecessary

### Do you have any additional context?
no

**Comment by Naarcha-AWS** [comment]
Assign to @hdhalter.
