### ISSUE TITLE
[DOC] Fix doc_values default value in a number of field types

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/documentation-website#5615]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Similar to #5451, we should fix the default doc_values in a bunch of places.

For [number fields](https://opensearch.org/docs/latest/field-types/supported-field-types/numeric/) - doc_values are true by default
Similar with [boolean fields](https://opensearch.org/docs/latest/field-types/supported-field-types/boolean/) - doc_values are true by default
Similar with [date fields](https://opensearch.org/docs/latest/field-types/supported-field-types/date/) -- doc_values are true by 
Similar with [ip field](https://opensearch.org/docs/latest/field-types/supported-field-types/ip/) -- doc_values are true by default
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks for creating this issue, @harshavamsi ! Just confirming that these changes are also relevant starting in  2.12?

**Comment by harshavamsi** [comment]
Hi @hdhalter these have always been the case since the initial fork, just the the documentation reflected differently. I don't think we would need to tie this to a release.

**Comment by hdhalter** [comment]
@harshavamsi - Can you please submit PRs for these changes?

**Comment by harshavamsi** [comment]
Raised #5619
