### ISSUE TITLE
[DOC] Update remove ingest processor documentation for some metadata fields are not allowed to remove

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/documentation-website#5634]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
We'll add some enhancement for the existing remove ingest processor, removing `_index`, `_version`, `_version_type` and `_id` with specific external version parameter will be not allowed because removing these metadata fields will cause issues, we need to modify the existing documentation to make that change clear for users.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

Related issue: https://github.com/opensearch-project/OpenSearch/issues/10732
Related PR: https://github.com/opensearch-project/OpenSearch/pull/10895

**Comment by hdhalter** [comment]
Thanks for creating this issue, @gaobinlong ! Will you be creating the associated PRs for this update? 

@vagimeli for visibility.

**Comment by gaobinlong** [comment]
> Thanks for creating this issue, @gaobinlong ! Will you be creating the associated PR for the updates?
> 
> @vagimeli for visibility.

Yeah, I'll create a PR for this later.

**Comment by hdhalter** [comment]
Thanks, @gaobinlong ! And please let us know which versions this change will apply to.

**Comment by gaobinlong** [comment]
Hi @hdhalter ,this change will apply to version 2.12 and above.

**Comment by gaobinlong** [comment]
Closed by #5870 .
