### ISSUE TITLE
[DOC] The parameter field and target_field in KV ingest processor now supports template snippets

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/documentation-website#5651]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
The parameter field and target_field in KV ingest processor will support template snippets in 2.12, we need to add this enhancement to the documentation. I see that currently we don't have documentation for kv processor, so please include this change when we add the documentation.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/pull/10040

**Comment by reta** [comment]
FYI, the target is  `2.12.0`

**Comment by hdhalter** [comment]
Thanks, @gaobinlong and @reta ! Who will be writing the documentation for this feature? 

In the meantime, I've asked @vagimeli to prioritize on the kv processor, since she is working on the processor documentation currently.

**Comment by reta** [comment]
> Thanks, @gaobinlong and @reta ! Who will be writing the documentation for this feature?

I believe the author of the change (@gaobinlong) should be writing it

**Comment by vagimeli** [comment]
@reta @gaobinlong See PR #https://github.com/opensearch-project/documentation-website/pull/5781. Content in progress. I'll tag you both when it's ready for your review.

**Comment by gaobinlong** [comment]
Close this issue as the related [PR](https://github.com/opensearch-project/documentation-website/pull/5781) has been merged yet.

**Comment by hdhalter** [comment]
@gaobinlong - Does the merged PR contain the information being delivered in 2.12? I believe 5781 was written based on 2.11, but just want to confirm. Thanks!

**Comment by vagimeli** [comment]
This issue has been addressed in the documentation. See PR https://github.com/opensearch-project/documentation-website/pull/5781 and doc site https://opensearch.org/docs/latest/ingest-pipelines/processors/kv/

**Comment by gaobinlong** [comment]
> @gaobinlong - Does the merged PR contain the information being delivered in 2.12? I believe 5781 was written based on 2.11, but just want to confirm. Thanks!

@hdhalter @vagimeli , I see the PR #5781 has been backported to 2.11, but the functionality of `field and target_field in kv processor supports template snippets` which this issue calls out will be released in 2.12.0, and will not be backported to 2.11, so I think we should remove the description of `Supports [template snippets]` in the document of 2.11.
