### ISSUE TITLE
[DOC] Security Analytics Get Mappings API documentation is incorrect. Mandatory param missing

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/documentation-website#5652]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

 Get mappings API in security analytics plugin has a mandatory request parameter called index_name  which is not mentioned in [API documentation](https://opensearch.org/docs/latest/security-analytics/api-tools/mappings-api/#get-mappings)

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://opensearch.org/docs/latest/security-analytics/api-tools/mappings-api/#get-mappings

**Comment by eirsep** [comment]
Plz add the following in the API

Field | Type | Description
-- | -- | --
index_name | String | The name of the index used for log ingestion.

</div>

**Comment by hdhalter** [comment]
@Naarcha-AWS - please update. Thanks!
