### ISSUE TITLE
Documentation for the support of Date Math Index pattern in the search query while defining the monitors. 

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/documentation-website#57]
As a part of these issues: 

opensearch-project/alerting#74
opensearch-project/alerting-dashboards-plugin#17

We have added the support for defining the query indices in the [Data Math Pattern](https://en.wikipedia.org/wiki/Wikipedia:Date_math). 

As a part of this issue, we want to update our documentation to aprise users of this functionality. Once the document for the required pattern is available for [Opensearch](https://github.com/opensearch-project/documentation-website/issues/56), we will link it to our documentation for the plugin.

**Comment by ashwinkumar12345** [comment]
Please review and add in any comments - https://github.com/opensearch-project/documentation-website/pull/116/files.
