### ISSUE TITLE
[FEATURE] [Documentation Request] Parent-child relationships

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/documentation-website#578]
### Is your feature request related to a problem?

Anecdote in the community meetings as well some github issues,

* https://github.com/opensearch-project/documentation-website/issues/410
* https://github.com/opensearch-project/OpenSearch/issues/2474

there are some barriers to adoption regarding the current state of,  and future plan for the use of parent-child document mappings and queries. 

I'd love to see some official documentation on this. 

### What solution would you like?

Whatever current documentation we have regarding index mappings should probably include the related functionality described above.

**Comment by Naarcha-AWS** [comment]
Hi everyone. Parent/child mappings and the `has_child` parameter has been documented here: https://opensearch.org/docs/latest/opensearch/supported-field-types/join/
