### ISSUE TITLE
[DOC] Update and validate instructions for creating read-only roles

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#5783]
Update and validate instructions for configuring customized default roles such as administrator, and creating read-only roles.

**Comment by john-eliatra** [comment]
I can do this one next.

**Comment by hdhalter** [comment]
Here is some additional feedback regarding this item: 

"...I just found that it looks like we are missing some role info from our documentation. For versions after 1.2 it looks like the "opensearch_dashboards_user" and "opensearch_dashboards_read_only" role info is missing from the documentation, but it is still mentioned in the "setting up a read only role" stepset at the bottom of the page.
Version 1.2:[ https://opensearch.org/docs/1.2/security-plugin/access-control/users-roles/](https://opensearch.org/docs/1.2/security-plugin/access-control/users-roles/)
Version 2.7:[ https://opensearch.org/docs/2.7/security/access-control/users-roles/](https://opensearch.org/docs/2.7/security/access-control/users-roles/)
Because this info is missing customers do not know that the two roles must be combined to give a read only user access to Dashboards visualizations.
Could you please take a look at updating and standardizing the roles info on this page or point me to someone that would be able to get this reference documentation fixed for our customers? Thank you!"

**Comment by AntonEliatra** [comment]
Hi @hdhalter,  I can take this one

**Comment by AntonEliatra** [comment]
@hdhalter I created a PR for this https://github.com/opensearch-project/documentation-website/pull/6806
Can you have a look when you get a chance please?

I used UI screenshots to demonstrate role creation, let me know if you want me to add API and yml file configs
