### ISSUE TITLE
[Documentation Update Request] Update `_opendistro/_security/api/ssl/certs` with `_plugins/_security/api/ssl/certs`

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/documentation-website#580]
The `_opendistro/_security/api/ssl/certs` is incompliant with the OpenSearch API naming convention. The new API path `_plugins/_security/api/ssl/certs` has been introduced in [2.0.0](https://github.com/opensearch-project/security/pull/1841). The [documentation](https://opensearch.org/docs/latest/security-plugin/access-control/api/#request-39) needs to be updated accordingly.

**Comment by hdhalter** [comment]
Also appears in anomaly detection (monitoring plugin section) - will fix this too, but Nate will confirm with dev
