### ISSUE TITLE
[DOC] Documentation updates for cluster.index.restrict.replication.type and cluster.indices.replication.strategy setting

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/documentation-website#5806]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
1.  Add new setting `cluster.index.restrict.replication.type` that prevents overriding replication type setting at index level.
2.  `cluster.indices.replication.strategy` setting today allows user to enable replication type setting at cluster level. Setting this at cluster level imposes replication type settings on certain actions which create new indices such as split, clone, index templates etc, need to call out in existing documentation.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Related core issue: https://github.com/opensearch-project/OpenSearch/issues/11457

**Comment by hdhalter** [comment]
Hi @dreamer-89 , thanks for creating the issue. Are we targeting a specific release, for example, 2.12, for this new setting?

**Comment by dreamer-89** [comment]
> Hi @dreamer-89 , thanks for creating the issue. Are we targeting a specific release, for example, 2.12, for this new setting?

Thanks @hdhalter for the clarification and apologies for delay. Yes, I am targeting this change for 2.12 release. Can you please add `2.12` label on this issue. Let know if you have any questions.

**Comment by hdhalter** [comment]
Thanks, @dreamer-89! Can you please open the PR with this setting?
