### ISSUE TITLE
[DOC] Benchmark user guide improvements

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#5815]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

The User Guide doesn't tell a complete story quite yet. Lets add additional content and restructure the section so it can go through everything:

- [x] Concepts
- [x] Installing Benchmark
- [x] Configuring OpenSearch Benchmark
- [x] Understanding workloads
   - [x] Anatomy of a workload
   - [x] Choosing a workload
      - [x] Description of available workloads and what do they.
      - [x] The most popular workloads:
         - [x] NYC Taxis: A basic, well-rounded search workload. 
         - [x] HTTP_logs: A well-rounded time-series workload. If your cluster uses HTTP log data, this might be a good fit for you.
   - [x] Creating a custom workload.
- [x] Running a workload
   - [x] Connecting your current OpenSearch cluster
      - [x] Docker
   - [x] Provisioning an OpenSearch cluster with OSB
   - [x] Running the test
      - [ ] Enabling telemetry devices
- [ ] Understanding Benchmark results (https://github.com/opensearch-project/documentation-website/pull/6984)
   - [ ] Understanding the summary report
   -  [ ] Going deeper with data stores
      - [ ] Telemetry device results are published to the data store.
- [ ] Running distributed loads
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@Naarcha-AWS - What is left to do on this issue? Can you please summarize what is left to do? Thanks!

**Comment by hdhalter** [comment]
Hi @Naarcha-AWS, We received feedback on this page: https://opensearch.org/docs/latest/benchmark/user-guide/telemetry/: 
20231123 | It would be nice to have steps on how to do it.

Since the title of the topic is "Enabling telemetry devices", I would expect a process. Are we going to add something to this topic? If not, maybe we can add this text to the topic on 'Summary reports"?

**Comment by Naarcha-AWS** [comment]
Link to the current User Guide: https://opensearch.org/docs/latest/benchmark/user-guide/index/

The only remaining items are the following: 

- Going deeper with data stores
- Enabling telemetry devices

**Comment by Naarcha-AWS** [comment]
Closing this as complete for now.
