### ISSUE TITLE
Document how to integrate Kafka with Logstash

### ISSUE THREAD

**Issue by Gayu1134** [opensearch-project/documentation-website#587]
Logstash for opensearch

i have installed opensearch and opensearch dashboards , its working fine 
i need to add kafka in logstash, referred (https://opensearch.org/docs/latest/clients/logstash/index/#install-logstash) that link was not helpful for installing in aks  ,kindly share step by step process or helm step to install

**Comment by dlvenable** [comment]
@Gayu1134 , The OpenSearch project has two Logstash projects - [opensearch-project/logstash-output-opensearch](https://github.com/opensearch-project/logstash-output-opensearch) and [opensearch-project/logstash-input-opensearch](https://github.com/opensearch-project/logstash-input-opensearch).

In general, I believe our documentation should focus on those plugins. Using Kafka in Logstash is more related to Logstash core and the logstash-input-kafka plugin. Please see that documentation: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html

**Comment by hdhalter** [comment]
Thanks, David! Closing this issue.
