### ISSUE TITLE
Add support matrix

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#59]
**Is your feature request related to a problem? Please describe.**

Users don't have a place to find what's supported with what. For example, [a user asks what the minimum JVM runtime environment is](https://discuss.opendistrocommunity.dev/t/minimum-runtime-environment-for-os-ga/6307).

**Describe the solution you'd like**

Publish a set of support matrices in the product documentation, showing OS, JVM, browser configurations we've tested with, and inter-compatibilities between product versions. 

via @julesg, Probably should cover "validated" or "tested" configurations rather than "supported" ones... since the project itself doesn't offer 'support' in the same way a commercial service might.

**Comment by aetter** [comment]
https://github.com/opensearch-project/documentation-website/pull/62
