### ISSUE TITLE
[DOC] Enhance Searchable Snapshots Documentation

### ISSUE THREAD

**Issue by anasalkouz** [opensearch-project/documentation-website#5941]
**What do you want to do?**
 
- [ x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Coming from [this](https://github.com/opensearch-project/OpenSearch/issues/11552) issue, I think we should enhance searchable snapshots documentation by adding an example of the restore api for searchable snapshot [here](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot/#create-a-searchable-snapshot-index)

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/issues/11552

**Comment by hdhalter** [comment]
Thanks, @anasalkouz ! Who can help with submitting a PR for the doc change?
