### ISSUE TITLE
[BUG] CAT API child pages not expandable

### ISSUE THREAD

**Issue by lukas-vlcek** [opensearch-project/documentation-website#595]
### What is the bug?

Page `title` of the CAT API has been changed recently (see [#af4afc2](https://github.com/opensearch-project/documentation-website/commit/af4afc2c1cc09675b9fbdf396beb394ba1554ee5) and [#e669674](https://github.com/opensearch-project/documentation-website/commit/e669674d6419517c772b9dd12d57d1ebe386acd7)).

This means that without relevant changes all child pages become non visible when the CAT API section is expanded.

### How can one reproduce the bug?

Click the CAT API section (as of writing apply to 2.x doc only).
Visit https://opensearch.org/docs/2.0/opensearch/rest-api/cat/index/

### What is the expected behavior?

The value of `parent` field in all child pages should match the value of `title` field in the parent (i.e. in the index.md) file.

For example, the following is excerpt from one of the children:
```
---
layout: default
title: cat field data
parent: CAT
grand_parent: REST API reference
nav_order: 15
has_children: false
---
```

And this is the excerpt from the parent (index.md) file:
```
---
layout: default
title: CAT API
parent: REST API reference
nav_order: 100
has_children: true
redirect_from:
  - /opensearch/catapis/
---
```

`parent` in the child does not match `title` in the parent: `"CAT" != "CAT API"`

### What is your host/environment?

Documentation for 2.x

### Do you have any screenshots?

<img width="273" alt="Screenshot 2022-05-21 at 9 38 57" src="https://user-images.githubusercontent.com/205174/169641350-7a936762-9b34-4fbd-92de-07b7c134e1c8.png">

**Comment by lukas-vlcek** [comment]
@alicejw-aws Maybe you want to check this out? 🙏 
I do not know if it is possible to distinguish between page ID and its title. Sounds like page ID would be very useful to have because that would allow to change page title without breaking the relationship to all children.

**Comment by hdhalter** [comment]
Thanks, Lukas! @kolchfa-aws - can you please take a look at this?
