### ISSUE TITLE
[DOC] Document job-scheduler

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#60]
**Is your feature request related to a problem? Please describe.**

Job scheduler has configuration, API, etc., but is not documented. I don't think having a supporting role is a good enough argument not to publish its documentation. Maybe it belongs in a different section.

**Describe the solution you'd like**

At least job scheduler settings documented.

**Additional context**

Coming from https://github.com/opensearch-project/opensearch-plugins/pull/15#discussion_r628371981 and https://github.com/opensearch-project/opensearch-plugins/pull/18#pullrequestreview-656744966.

**Comment by ariamarble** [comment]
The documentation status of this issue is currently in a "needs research" status. Working on this on my end.

**Comment by ariamarble** [comment]
Will be working with the team next week for clarification on documentation requirements.

**Comment by ariamarble** [comment]
Reached out to SMEs for further information to get documentation started. Currently in "need research" status.

**Comment by ariamarble** [comment]
First draft created along with PR.
