### ISSUE TITLE
[DOC] Add documentation for filter support for neural query

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/documentation-website#6012]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The neural search query allows users to use a ML model to turn their text into vector embeddings, and then perform k-NN search over an index with the embedding. 

Neural queries are just wrappers around k-NN queries. For k-NN, we support filter. For neural, we support filter as well. We mention this in the Semantic Search section here: https://opensearch.org/docs/latest/search-plugins/semantic-search/#step-4-search-the-index-using-neural-search:

> To perform vector search on your index, use the neural query clause either in the [k-NN plugin API](https://opensearch.org/docs/latest/search-plugins/knn/api/#search-model) or [Query DSL](https://opensearch.org/docs/latest/opensearch/query-dsl/index/) queries. You can refine the results by using a [k-NN search filter](https://opensearch.org/docs/latest/search-plugins/knn/filter-search-knn/).

We should add this to the documentation about the neural search query in the query DSL docs as well: https://opensearch.org/docs/latest/query-dsl/specialized/neural/

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/neural-search/issues/523

**Comment by hdhalter** [comment]
Thanks, @jmazanec15 ! Can you please open a doc PR with this info?

**Comment by jmazanec15** [comment]
@hdhalter created #6254
