### ISSUE TITLE
Proposal for improving the documentation contribution experience

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#603]
Hi all, 
We'd like to improve the experience for contributing to the documentation backlog, and we'd like your input! 

### Current experience
Currently contributors enter a documentation issue in Github in the following ways:

- With a direct link: https://github.com/opensearch-project/documentation-website/issues
- From the Contribution page: https://github.com/opensearch-project/documentation-website/blob/main/CONTRIBUTING.md
- From the documentation site: https://opensearch.org/docs/latest  - on the bottom: *Submit issues* or *Edit this page*

After the contributor selects an option above, they are presented with several options: Bug report, Feature request, and Proposal: 

<img width="725" alt="Screen Shot 2022-05-24 at 2 55 41 PM" src="https://user-images.githubusercontent.com/104463754/170138790-a698c3e5-4aea-47a5-9e87-c2cf42a780fc.png">

They are then presented with a default template. For example, here is the template for a feature request:

<img width="616" alt="Screen Shot 2022-05-24 at 2 58 56 PM" src="https://user-images.githubusercontent.com/104463754/170139153-e845e7c6-05c5-4f78-bec8-c76693c02b40.png">

### Problems with this experience

We feel that this sequence of steps is not adequate for a documentation request, nor are the templates. For example:

- Contributors unnecessarily have to make a choice about what kind of issue they want to create
- The template is primarily written for developing features or reporting bugs
- Writers that need to consume the information are presented with information that is not organized well, nor does it contain the information they need

### Solution

We propose the following solution. Instead of being presented with choices, the contributor will open an issue form directly. It will contain the following info: 

-----------------------------------------------------
[Title - Brief description of the request]

Thanks for your interest in improving the OpenSource documentation! We value and appreciate all feedback and contributions from our community.

What do you want to do? 
    * [ ] Request a change to existing documentation
    * [ ] Add new documentation
    * [ ] Report a technical problem with the documentation
    * [ ] Other 

Tell us about your request. For example, what feature or area does it affect? What versions? If it affects existing content, which pages (URLs)? 

Are there any related resources to help us get started (for example, link to a related fixed issue, design doc, or feature brief)? Any particular SME who has more information?

Is there anything else you'd like to add?

Thank you! We will follow up if we have additional questions. 

---------------------------------------------------------

The documentation team will then triage the request and apply the appropriate labels. 

Thanks for reading. We appreciate your feedback!

**Comment by hdhalter** [comment]
Hi @lukas-vlcek , as a frequent contributor to the documentation repo, I'd be interested to hear your thoughts on this. Do you have any feedback on this proposal? Thanks so much!

**Comment by lukas-vlcek** [comment]
Hi @hdhalter,

I like your proposal.

I think that currently the process of creating a new ticket is highly formalized and perhaps borrows quite a lot from projects like [opensearch-project/opensearch](https://github.com/opensearch-project/opensearch) – i.e. from programming language repo. I am not strictly a documentation guy so I do not know if that is usual for documentation repos but I welcome making the process more light and less formal. This can improve UX when opening a new tickets (on the other hand there will be more work for those who will do triaging, but that is expected).

From my experience what I see as the most important is if users provide URL link(s) and specify version(s) of product, and you already mention that in your proposal.

I would also welcome if more info about versioning and branching of the documentation is available (for example, what are [releases](https://github.com/opensearch-project/documentation-website/releases) used for?). I expect that most users will send PRs against the `main` branch, but in many cases these can (and should be) back-ported to earlier versions as well. And currently, I am not sure if users have clear instructions about how they can help with that (again, if not done by users then it will be up to those doing reviews and PR merging).

Last, but not least, I miss information about what users can expect from their PR review process. Sometimes I was not sure if I was expected to provide changes or someone from reviewers will do it for me.

HTH,
Lukáš

**Comment by hdhalter** [comment]
@natebower , @alicejw-aws - please review. Thanks!

**Comment by hdhalter** [comment]
Thanks, Nate and @lukas-vlcek! How about this....

What do you want to do?
* [ ] Make a change to existing documentation
* [ ] Add new documentation
* [ ] Report a technical problem with the documentation
* [ ] Other

Please provide the following information:

* Give a brief description of your request.

* Which versions are affected? 

* Which pages or URLs are affected?

* What resources are available (for example, links to a related issue, PR, design doc, or feature brief)? 

* Who should we contact with technical questions?  

* Is there anything else you’d like us to know about your requested change?

**Comment by hdhalter** [comment]
@lukas-vlcek , thanks so much for your feedback! I will look into that Releases page, as I'm not sure if it has been kept up. Regarding the PR review process, we are also defining the process now. We should have something available shortly. Thanks for your patience as we build up the doc team. We truly appreciate your input!

**Comment by Naarcha-AWS** [comment]
Sounds good @hdhalter
