### ISSUE TITLE
[DOC] document `dfm_empty_overrides_all` setting in the security plugin

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#6049]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
the `dfm_empty_overrides_all` config option introduced in https://github.com/opensearch-project/security/pull/1735 for https://github.com/opensearch-project/security/issues/1572 doesn't seem to be documented (searching for it on opensearch.org does not yield a result). this should be documented.
 

**What other resources are available?**
see the original issue for a link to the same feature in Search Guard (the feature was ported 1:1 by floragunn, thus it behaves the same and you might be allowed to copy the documentation as well).
the opensearch-security team should be able to provide further input if needed.

**Comment by hdhalter** [comment]
Thanks for entering this issue, @rursprung ! Would you be willing to submit a PR for the update in the documentation repo?

**Comment by rursprung** [comment]
i currently don't have time for this, sorry :(

**Comment by hdhalter** [comment]
> i currently don't have time for this, sorry :(

No worries, we are appreciative of your contributions in any form!

**Comment by hdhalter** [comment]
@john-eliatra - Can we add this to your list?

**Comment by john-eliatra** [comment]
Hi @hdhalter , will do.
