### ISSUE TITLE
[DOC] Update Security Analytics documentation for alerts and findings API

### ISSUE THREAD

**Issue by jowg-amazon** [opensearch-project/documentation-website#6064]
**What do you want to do?**

- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

There are a few small bugs in the alerts API [page](https://opensearch.org/docs/latest/security-analytics/api-tools/alert-finding-api/#parameters) for security analytics. The `detectorID` field under the parameters should be changed to `detector_id`. Additionally in the `sortOrder` parameter description field, it should be `asc` and `desc` instead of `ascending` and `descending` to avoid confusion. 

Additionally, there should be an extra section in the [get findings API](https://opensearch.org/docs/latest/security-analytics/api-tools/alert-finding-api/#get-findings) to include the supported query params, similar to the [get alerts API](https://opensearch.org/docs/latest/security-analytics/api-tools/alert-finding-api/#get-alerts).

Parameters and descriptions in this section include:
`detector_id` - The ID of the detector used to fetch alerts. Optional when the detectorType is specified. Otherwise required.
`detectorType` - The type of detector used to fetch alerts. Optional when the detectorId is specified. Otherwise required.
`sortOrder` - The order used to sort the list of findings, either `asc` or `desc`. Optional.
`size` - An optional limit for the maximum number of results returned in the response. Optional.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Security analytics alerts and findings page: https://opensearch.org/docs/latest/security-analytics/api-tools/alert-finding-api/#get-findings

**Comment by hdhalter** [comment]
Thanks for creating this issue, @jowg-amazon ! Do you want to take a stab at editing the content and submitting a PR? https://github.com/opensearch-project/documentation-website/edit/main/_security-analytics/api-tools/alert-finding-api.md. We can help with the review and getting it merged.
