### ISSUE TITLE
[BUG] The index name should be `.kibana` instead of `.opensearch_dashboards`

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/documentation-website#607]
All the places under [Configuration](https://opensearch.org/docs/latest/security-plugin/access-control/multi-tenancy/#configuration) and [Manage OpenSearch Dashboards indices](https://opensearch.org/docs/latest/security-plugin/access-control/multi-tenancy/#manage-opensearch-dashboards-indices) referencing to the index `.opensearch-dashboards` should be changed to `.kibana`

**Comment by Naarcha-AWS** [comment]
@cliu123: Are there plans to update this convention at some point, considering we no longer refer to Dashboards as Kibana in OpenSearch?

**Comment by cliu123** [comment]
> @cliu123: Are there plans to update this convention at some point, considering we no longer refer to Dashboards as Kibana in OpenSearch?

It was [decided](https://github.com/opensearch-project/opensearch-plugins/issues/17#issuecomment-847204447) not to rename index when creating OpenSearch.
