### ISSUE TITLE
[DOC] The command for returning the list of plugins in Tarball installation of OpenSearch instructions has some characters that should be removed.

### ISSUE THREAD

**Issue by john-eliatra** [opensearch-project/documentation-website#6127]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

[Test your OpenSearch settings with security enabled](https://opensearch.org/docs/latest/install-and-configure/install-opensearch/tar/#option-1-test-your-opensearch-settings-with-security-enabled)

When doing the step for querying the plugins endpoint, ie. `curl -X GET https://localhost:9200/_cat/plugins?v -u 'admin:admin' --insecure`, it came back with `zsh: no matches found: https://localhost:9200/_cat/plugins?v,`

I then removed the question mark and the v just after plugins, so my request was `curl -X GET https://localhost:9200/_cat/plugins -u 'admin:admin' --insecure` ...........It then gave the expected response, with all the plugins listed.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks, @john-eliatra !
@peterzhuamazon - Can you please look at this and let me know if this is valid?

**Comment by peterzhuamazon** [comment]
Hi @john-eliatra zsh at times have problem escape special chars.
If you switch to bash it wont error out.
Please try wrapping the request url with double quotes, this should work:
```
curl -X GET "https://localhost:9200/_cat/plugins?v" -u 'admin:admin' --insecure
```

And @hdhalter I think we can update this part in the document if needed. 
Thanks.

**Comment by john-eliatra** [comment]
Hi @peterzhuamazon , thanks for the info, that's interesting to know - let me try that and see how it goes. 
Thanks a mill, 
John

**Comment by kolchfa-aws** [comment]
@peterzhuamazon I think it's OK to leave the documentation as is because all our requests are based on bash.
