### ISSUE TITLE
[DOC] Add docs about configuring Content Security Policy (CSP) rules in OpenSearch Dashboards

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/documentation-website#6139]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We have proposed a new way to configure CSP rules for OpenSearch Dashboards. We plan to launch it in 2.12.0 release.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
RFC https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5639
PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5641

**Comment by tianleh** [comment]
cc @seraphjiang for visibility

**Comment by hdhalter** [comment]
Thanks for entering the issue, @tianleh ! Will you be submitting the doc PR or someone else?

**Comment by tianleh** [comment]
> Thanks for entering the issue, @tianleh ! Will you be submitting the doc PR or someone else?

I will write the doc PR

**Comment by hdhalter** [comment]
Hi @tianleh - Are you on track to complete the doc PR? Thank you.

**Comment by tianleh** [comment]
> Hi @tianleh - Are you on track to complete the doc PR? Thank you.

We may not be able to catch this release. I will still create a draft PR by end of today.

@hdhalter

**Comment by tianleh** [comment]
Draft PR created https://github.com/opensearch-project/documentation-website/pull/6291

**Comment by tianleh** [comment]
@hdhalter We are still developing the feature and cannot catch the 2.12.0 release. Please remove the 2.12.0 label from the issue and PR. https://github.com/opensearch-project/documentation-website/pull/6291

cc @seraphjiang

**Comment by tianleh** [comment]
Both changes are merged into 2.x and target at 2.13.0

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5855

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5641

I am working on the doc PR
