### ISSUE TITLE
[DOC] Add copy ingest processor

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/documentation-website#6147]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
In the incoming release 2.12.0, we'll add a new ingest processor called `copy processor`, we should document the usage.

Please assign this issue to me, I'll open a PR for that.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://github.com/opensearch-project/OpenSearch/pull/11870

**Comment by vagimeli** [comment]
@gaobinlong @hdhalter I can support you on this. Please assign me to the PR once it's created.
