### ISSUE TITLE
[FEATURE] Please update the top navigation

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/documentation-website#616]
### Is your feature request related to a problem?
Menu update needed. 

### What solution would you like?
I have updated the top navigation menu on opensearch.org, and removed 'Partners' from the footer since it's now in the top nav - please update the doc site to match. It should now be:
    Download
    Documentation
    Blog
    Forum
    Events
    Partners 
(see https://github.com/opensearch-project/project-website/pull/844 for details)

### What alternatives have you considered?
N/A

### Do you have any additional context?
tagging: 
@AMoo-Miki @alicejw-aws @Naarcha-AWS for visibility

**Comment by hdhalter** [comment]
Hi @AMoo-Miki, is this something you need to do or can you point me to the right file? Thanks.

**Comment by krisfreedain** [comment]
@AMoo-Miki @hdhalter -

Miki - do you have time to check into this?

**Comment by hdhalter** [comment]
@krisfreedain - Hi Kris, the nav pane works, but before we mreget the code, can you please check the code snippet? We had to hard code the forum string, so wondering if that is ok as is, or if there is a better way to represent that? Thanks!

**Comment by hdhalter** [comment]
Header is fixed and working as expected: https://opensearch.org/docs/latest
I need to update the footer file before closing.
