### ISSUE TITLE
[DOC] Query Insights with Top N Queries

### ISSUE THREAD

**Issue by ansjcy** [opensearch-project/documentation-website#6180]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We need to add documents for the initial Query Insight feature (top N Queries).

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/pull/11506
https://github.com/opensearch-project/OpenSearch/issues/11186
https://github.com/opensearch-project/OpenSearch/issues/11429

**Comment by hdhalter** [comment]
Thanks for entering the doc issue for this feature, @ansjcy! Do you know in which release this feature is targeting? And, will you also be providing the documentation PR?

**Comment by hdhalter** [comment]
Thanks for confirming this is going in 2.12, @ansjcy.
