### ISSUE TITLE
[DOC] Add remove_by_pattern ingest processor

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/documentation-website#6207]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
In release 2.12.0, we'll introduce a new ingest processor called `remove_by_pattern processor`, we need to document the usage.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://github.com/opensearch-project/OpenSearch/pull/11920

**Comment by vagimeli** [comment]
@gaobinlong @hdhalter I can support you on this. Please assign me to the PR when it's created.
