### ISSUE TITLE
[DOC] Enhance documentation to provide clarity for some index level permissions used as cluster level permissions

### ISSUE THREAD

**Issue by donjude** [opensearch-project/documentation-website#621]
### Is your feature request related to a problem?
Can the documentation https://opensearch.org/docs/latest/security-plugin/access-control/permissions be enhanced to provide clarity for some index level permissions that are supposed to be applied as cluster level permissions to grant users the right access.

Example of such permissions are seen below however, they have been classified only as index level permissions:

```
Cluster Permissions:
indices:data/write/bulk*
indices:data/read/scroll
``` 

### What solution would you like?
_This would avoid confusion and provide a clear documentation as to what index level permissions are supposed to be used at the cluster level to grant users the permission they require. 

### Do you have any additional context?
_Mostly we are faced with the example error message for such permission, only to add them as a cluster level permission in order for it to work.

```
"root_cause":{"type":"security_exception","reason":"no permissions for [indices:data/write/delete, indices:data/write/bulk[s]] and User [name=housekeeping, backend_roles=[], requestedTenant=null]"}]
```

**Comment by hdhalter** [comment]
Hi @cwillum , I know you've made some updates to this section. Can you please review to see if we've resolved this issue? Thanks!

**Comment by hdhalter** [comment]
See also: https://github.com/opensearch-project/documentation-website/issues/2359

**Comment by hdhalter** [comment]
Missing cluster-level permissions: https://github.com/opensearch-project/documentation-website/issues/1656

**Comment by AntonEliatra** [comment]
@hdhalter I can take this one

**Comment by hdhalter** [comment]
Closed by https://github.com/opensearch-project/documentation-website/pull/7161
