### ISSUE TITLE
[DOC] Torch config link for all-MiniLM-L12-v2 model incorrectly points to ONNX config

### ISSUE THREAD

**Issue by ArranDengate-Netapp** [opensearch-project/documentation-website#6226]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 

In the [pretrained model page ](https://opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/#supported-pretrained-models), each model has a link to Torch config and a link to ONNX config (in the `TorchScript artifact` and `ONNX artifact` columns of the table, respectively). The link to Torch config for the all-MiniLM-L12-v2 model is incorrect; it points to ONNX config (so for this model, rather than one config_url link to Torch and one to ONNX, both links point to ONNX). This appears to be the only model in the page with this issue, all other Torch config links point to Torch config.

If this ONNX config is used with the Torch model, the following error occurs in OpenSearch logs when deploying the model:

```
[ERROR][o.o.m.e.a.DLModel`        ] [ip-172-31-62-254.ec2.internal] Failed to deploy model smYvF40BgFhXOXZgGEgm
java.lang.NoClassDefFoundError: Could not initialize class ai.djl.onnxruntime.engine.OrtNDManager 
```

The incorrect link is:

https://artifacts.opensearch.org/models/ml-models/huggingface/sentence-transformers/all-MiniLM-L12-v2/1.0.1/onnx/config.json

The correct link can be determined from context. The link to Torch config for this model should instead be:

https://artifacts.opensearch.org/models/ml-models/huggingface/sentence-transformers/all-MiniLM-L12-v2/1.0.1/torch_script/config.json

This file exists, and appears to be correct - I was able to deploy the model using it.

I will submit a PR with the change shortly.

**Comment by hdhalter** [comment]
Thanks, @ArranDengate-Netapp !
