### ISSUE TITLE
[DOC] Google search finds old doc page rather than latest

### ISSUE THREAD

**Issue by smacrakis** [opensearch-project/documentation-website#6234]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Google search for [opensearch term level query] finds the 2.1 version doc; [opensearch vector performance] finds the 1.2 version doc. I assume that there are similar problems with other pages.

How can we convince Google to prefer the current page?

There seem to be several problems with the current setup:
* https://opensearch.org/sitemap.xml doesn't mention /docs/ at all. Putting new pages there makes it more likely that they will be crawled soon, and it also provides a place to communicate the last-modified date to Google.
* on the page https://opensearch.org/docs/1.2/search-plugins/knn/performance-tuning/, the metadata says `<meta property="article:published_time" content="2024-01-10T00:19:39+00:00" />` and the ld+json block shows the same for dateModified and datePublished. At the same time, https://opensearch.org/docs/2.11/search-plugins/knn/performance-tuning/ shows dates of 2024-01-19, only 9 days later. Surely 1.2 was published long before 2024.
* There's the pink warning box that it's an old version at the top of these pages, with a link to "the current documentation". But for https://opensearch.org/docs/2.1/opensearch/query-dsl/term/, that's a link to the _top level_ of the current documentation -- shouldn't it go to the _latest_ version of the current page, as it does for example on https://opensearch.org/docs/1.2/search-plugins/knn/performance-tuning/?

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks, Stavros! We are currently working on a solution to address issues just like this. If you find anything else odd, please add it to this issue.

**Comment by kolchfa-aws** [comment]
Closed by #7436, #7438, #7439, #7440, #7442, #7443, #7444,  #7445, #7446, #7448, #7449, #7450, #7451, #7453, #7454, #7455, #7456
