### ISSUE TITLE
Failure in `gem install bundler jekyll`

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/documentation-website#6242]
Following this document to generate website in local. https://github.com/opensearch-project/documentation-website/blob/main/CONTRIBUTING.md

However, `gem install bundler jekyll` command is failing with following error. 

ERROR:  Error installing jekyll:
	The last version of sass-embedded (~> 1.54) to support your Ruby & RubyGems was 1.63.6. Try installing it with `gem install sass-embedded -v 1.63.6` and then running the current command again
	sass-embedded requires Ruby version >= 3.1.0. The current ruby version is 2.7.2.137.

Happening both in mac and linux.

**Comment by kolchfa-aws** [comment]
@heemin32 Can you try installing Ruby 3.0 and see if that solves the problem?

**Comment by heemin32** [comment]
> @heemin32 Can you try installing Ruby 3.0 and see if that solves the problem?

I am using mac M1 processor. 

Getting this error when using Ruby 3.13

```
An error occurred while installing posix-spawn (0.3.15), and Bundler
cannot continue.

In Gemfile:
  jekyll-last-modified-at was resolved to 1.3.0, which depends on
    posix-spawn
```

Having trouble to launch server locally.

**Comment by kolchfa-aws** [comment]
You don't really need the last modified plugin locally so if it gives you trouble, you can remove it or comment it out from line 25 in the Gemfile. Then delete Gemfile.lock and try running `bundle install` again. In the meantime, we'll figure out what the problem is and will update the instructions.

**Comment by heemin32** [comment]
Thanks. Simply removing jekyll-last-modified-at from Gemfile does not work either as it is being used inside code. I just used docker to run the site locally.

**Comment by AMoo-Miki** [comment]
@heemin32, can you please try `rvm install ruby-3.2.0` and then continue with the rest of the steps. I verified 3.2.0 and 3.3.0 on a clean-ish machine but would appreciate it if you could let us know if it worked for you or not.

**Comment by heemin32** [comment]
I could not install ruby-3.2.0 so I deleted homebrew and reinstalled it following https://github.com/rvm/rvm/issues/5043#issuecomment-967000943

After that, 
```
brew install openssl
gem install eventmachine -- --with-cppflags=-I/usr/local/opt/openssl/include
bundle install
```

It works now. Thanks.

**Comment by AMoo-Miki** [comment]
Thanks for letting us know. I am glad it is resolved now.
