### ISSUE TITLE
[DOC] Update bundled JDK version (January 2024 Patch releases)

### ISSUE THREAD

**Issue by reta** [opensearch-project/documentation-website#6246]
**What do you want to do?**

Update bundled JDK versions following https://github.com/opensearch-project/OpenSearch/issues/11906 

- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
There would be new JDK versions, for `2.12.0` and `1.3.15`

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

@hdhalter I will pick it up once the OpenSearch core issue is resolved, thank you

**Comment by vagimeli** [comment]
@reta I'll be the supporting tech writer. You're welcome to ping me when the PR is ready.

**Comment by hdhalter** [comment]
> @reta I'll be the supporting tech writer. You're welcome to ping me when the PR is ready.

@Naarcha-AWS already jumped on this one.
