### ISSUE TITLE
Remove the Releases page in the doc repo

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#625]
What do you want to do?

* [ ] Make a change to existing documentation
* [ ] Add new documentation
* [ ] Report a technical problem with the documentation
* [x] Other

Please provide the following information:

Give a brief description of your request.
I'd like to have the Releases page removed from the Repo, as it provides no value.

Which versions are affected?
The last update was 1.0, so probably 2.0 and 1.x

Which pages or URLs are affected?
https://github.com/opensearch-project/documentation-website/releases

What resources are available (for example, links to a related issue, PR, design doc, or feature brief)?
None
 
Who should we contact with technical questions?
Miki
 
Is there anything else you’d like us to know about your requested change?
A customer requested more information about versioning and branching of the documentation, including the Releases page. See https://github.com/opensearch-project/documentation-website/issues/603

**Comment by kolchfa-aws** [comment]
Removed releases page and tags.
