### ISSUE TITLE
[DOC] Update mutate event processors docs for Data Prepper

### ISSUE THREAD

**Issue by oeyh** [opensearch-project/documentation-website#6266]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The existing docs are missing a few new options. This readme has the latest info: https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/mutate-event-processors/README.md

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Existing doc: https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/mutate-event/

**Comment by Naarcha-AWS** [comment]
@oeyh: Is this for Data Prepper 2.7?

**Comment by Naarcha-AWS** [comment]
@oeyh: Going to close this since this has been addressed. Feel free to reopen the issue if needed.
