### ISSUE TITLE
[DOC] Update docs for date processor in Data Prepper

### ISSUE THREAD

**Issue by oeyh** [opensearch-project/documentation-website#6267]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The existing docs are missing a few new options. This readme has the latest info: https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/date-processor/README.md

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Existing doc: https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/date/

**Comment by Naarcha-AWS** [comment]
@oeyh: Is this and the mutate event processor specifically for Data Prepper 2.7?

**Comment by oeyh** [comment]
This is not for 2.7. The relevant code is released, but the docs have a gap. 

Specifically, it's missing:
- Details about the `patterns` option under `match` block
- `to_origination_metadata` option

It's also better to have some examples.
