### ISSUE TITLE
[DOC] Incorrect description of default value for indices.breaker.total.use_real_memory

### ISSUE THREAD

**Issue by hogesako** [opensearch-project/documentation-website#6269]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The documentation states that the default value of `indices.breaker.total.use_real_memory` is false, but in the source code it is set to true.
https://github.com/opensearch-project/documentation-website/blob/main/_install-and-configure/configuring-opensearch/circuit-breaker.md?plain=1#L18

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerService.java#L91

**Comment by hdhalter** [comment]
Thanks, @hogesako - do you want to take a stab at creating a PR for the fix?

**Comment by hdhalter** [comment]
@hogesako Nicely done! I'll send this through doc review. Thanks!
