### ISSUE TITLE
[FEATURE] document anonymous authentication feature

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#627]
### Is your feature request related to a problem?
this is a long-standing feature (from the opendistro times) but is undocumented.

### What solution would you like?
if `config.dynamic.http.anonymous_auth_enabled: true` is set in the general security config then unauthenticated calls are not rejected but are instead let through.
there's also the `opendistro_security_anonymous_backendrole` backend role which can be used in role mappings to identify unauthenticated users, which allows granting specific rights to unauthenticated users.

currently, this feature is not documented in the OpenSearch docs.

### What alternatives have you considered?
read the [Search Guard docs](https://docs.search-guard.com/latest/anonymous%20authentication) instead as the feature is (roughly) equivalent 🙃

### Do you have any additional context?
* the security config flag is mentioned in passing in this place: https://opensearch.org/docs/latest/security-plugin/configuration/configuration/#http
* for detailed input please check with the https://github.com/opensearch-project/security team who own this feature

**Comment by hdhalter** [comment]
Hi Chris, can you please look into this? We got a 'dislike' on the /docs/latest/security/configuration/index page, and they pointed to this issue.

**Comment by cwillum** [comment]
From what I can tell, this setting for anonymous authentication is made in the HTTP section of the `config.yml` file now. Even Search Guard (referenced in "What alternatives have you considered?") calls their approximate setting a "legacy configuration" now made in their own `sg_auth.yml` file. It appears we make the same setting in the OpenSearch Security `config.yml` file. Still, @rursprung makes a legitimate request to round out the documentation for Anonymous Authentication. We say very little about it in [HTTP](https://opensearch.org/docs/latest/security/configuration/configuration/#http) configuration.

**Comment by hdhalter** [comment]
@scrawfor99 - Do you know if this information was updated adequately in the most recent updates of the documentation? Thanks.

**Comment by scrawfor99** [comment]
Hi @hdhalter, I don't think we have any new changes covering this so we should still look into adding documentation explaining how this works if it is not already clear.

**Comment by hdhalter** [comment]
> Hi @hdhalter, I don't think we have any new changes covering this so we should still look into adding documentation explaining how this works if it is not already clear.

Is this something you can take, @scrawfor99 ?

**Comment by scrawfor99** [comment]
Sure @hdhalter

**Comment by scrawfor99** [comment]
Anonymous documentation is explained (briefly) here: https://opensearch.org/docs/latest/security/configuration/configuration/

@hdhalter is there more that needs to be added for this feature? The description gives the general idea of what the setting does:

```
anonymous_auth_enabled 	Either enables or disables anonymous authentication. When true, [HTTP authenticators](https://opensearch.org/docs/latest/security/configuration/configuration/#authentication) try to find user credentials in the HTTP request. If credentials are found, the user is authenticated. If none are found, the user is authenticated as an “anonymous” user. This user then has the username “anonymous” and one role named “anonymous_backendrole”. When you enable anonymous authentication, all defined HTTP authenticators are non-challenging. Also see [The challenge setting](https://opensearch.org/docs/latest/security/authentication-backends/basic-authc/#the-challenge-setting).
```
It does not explicitly call all the definition of roles in the anonymous backend role however it does mention that the backenend role is used for all anonuymous users.
