### ISSUE TITLE
[DOC] Deprecated metrics

### ISSUE THREAD

**Issue by chibacchie** [opensearch-project/documentation-website#6271]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**

As NodeStatsFixedShardsMetricsCollector has been deprecated by [opensearch-project/performance-analyze#551](https://github.com/opensearch-project/performance-analyzer/pull/551), it should be mentioned in [the Metrics reference](https://github.com/opensearch-project/documentation-website/blob/main/_monitoring-your-cluster/pa/reference.md). 

AFAIK, the following metrics collected by NodeStatsFixedShardsMetricsCollector are no longer available.

- Refresh_Event
- Refresh_Time
- Flush_Event
- Flush_Time
- Merge_Event
- Merge_Time
- Merge_CurrentEvent
- Indexing_Buffer
- Segments_Total
- IndexWriter_Memory
- Bitset_Memory
- VersionMap_Memory	
- Shard_Size_In_Bytes

**What other resources are available?**

- [opensearch-project/performance-analyze#551](https://github.com/opensearch-project/performance-analyzer/pull/551)

**Comment by hdhalter** [comment]
Hi @khushbr - Can you please confirm whether these should be removed from the documentation?

**Comment by khushbr** [comment]
@hdhalter Yes, we are good to remove these metrics. @chibacchie Thank you for highlighting this!
