### ISSUE TITLE
[DOC] add include_named_queries_score for returning scores for named queries

### ISSUE THREAD

**Issue by Dharin-shah** [opensearch-project/documentation-website#6278]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
https://github.com/opensearch-project/OpenSearch/pull/11626
Pushing a change here that allows clients to get the matched queries with its respective scores when the `include_named_queries_score` flag is passed
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks, @Dharin-shah ! Do you want to take a stab at creating the documentation PR?

**Comment by Dharin-shah** [comment]
> Thanks, @Dharin-shah ! Do you want to take a stab at creating the documentation PR?

sure, mind directing me, so i can do this quickly :)

**Comment by hdhalter** [comment]
> > Thanks, @Dharin-shah ! Do you want to take a stab at creating the documentation PR?
> 
> sure, mind directing me, so i can do this quickly :)

I believe this is the file you want to update: https://github.com/opensearch-project/documentation-website/edit/main/_api-reference/search.md. Thanks!

**Comment by Dharin-shah** [comment]
here is the PR
https://github.com/Dharin-shah/documentation-website/pull/1
