### ISSUE TITLE
[DOC]: Migrate Just the Docs to 0.4

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#6283]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

To fix the SaaS build errors we've been encountering, we need to migrate our Just The Docs version from 0.33 to 0.4. Just The Docs includes a handy migration guide to help us get started. https://just-the-docs.com/migration/#v033--v04x

@AMoo-Miki and @kolchfa-aws will provide the tech review.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
This has been completed.
