### ISSUE TITLE
[DOC] OpenSearch Assistant Toolkit Documentation

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/documentation-website#6292]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 In OpenSearch 2.12, we are releasing an experimental OpenSearch Assistant Toolkit that will be working with other new experimental features like the [Agent Framework](https://github.com/opensearch-project/ml-commons/issues/1161) and the [Flow Framework](https://github.com/opensearch-project/OpenSearch/issues/9213).
The OpenSearch Assistant Toolkit allows for gen-ai type features in users' OpenSearch clusters such as chat, natural language to ppl query generation, and summarization. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
- Toolkit blog post: https://opensearch.org/blog/opensearch-adds-new-generative-ai-assistant-toolkit/
- OpenSearch Assistant Toolkit RFC: https://github.com/opensearch-project/dashboards-assistant/issues/18
- Flow Framework: https://github.com/opensearch-project/OpenSearch/issues/9213
- Agent Framework: https://github.com/opensearch-project/ml-commons/issues/1161

**Comment by hdhalter** [comment]
@kolchfa-aws  is including this content with the agent framework PR.
