### ISSUE TITLE
[DOC] Tiered caching in OpenSearch

### ISSUE THREAD

**Issue by sgup432** [opensearch-project/documentation-website#6300]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We are adding a tiered caching feature where we will extend the existing RequestCache within OpenSearch to include disk cache as well. This is the first milestone.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/issues/10024
Milestone1 - https://github.com/opensearch-project/OpenSearch/issues/10870

**Comment by hdhalter** [comment]
@sgup432 - Please let me know if this isn't going to make it in 2.12. Thanks!

**Comment by bbarani** [comment]
@sgup432 @kkhatua Can you please confirm if this feature will make it to 2.12.0 release?

**Comment by kkhatua** [comment]
Unfortunately no. I've updated the labels. @sgup432  will do for the others as well so as to reflect the revised feature release correctly.

**Comment by kkhatua** [comment]
Reopened since there is documentation around the Stats API that is missing.

**Comment by hdhalter** [comment]
Thanks, @kkhatua. @sgup432 - what is the ETA for producing the doc PR? To meet entrance criteria, the PR must be open and in review by 4/30. Thanks!

**Comment by sgup432** [comment]
@hdhalter I will open it by tomorrow. There are few more changes which needs to be merged in 2.14, so waiting on that before I open up a doc PR.

**Comment by kiranprakash154** [comment]
@sgup432 can you also add docs to these settings ?
```java
IndicesRequestCache.INDICES_REQUEST_CACHE_CLEANUP_INTERVAL_SETTING,
IndicesRequestCache.INDICES_REQUEST_CACHE_STALENESS_THRESHOLD_SETTING,
``` introduced in https://github.com/opensearch-project/OpenSearch/pull/12625/files and registered in https://github.com/opensearch-project/OpenSearch/pull/12941 ?

**Comment by sgup432** [comment]
Add this for reminder.
Need to add doc for below setting. If this is disabled, we expect the user to clear the disk cache manually. See https://github.com/opensearch-project/OpenSearch/pull/13373#discussion_r1580255032
```
TIERED_SPILLOVER_DISK_CACHE_SETTING
```

**Comment by hdhalter** [comment]
Doc PR in progress.
