### ISSUE TITLE
[DOC] New Datetime format rfc3339_lenient

### ISSUE THREAD

**Issue by CaptainDredge** [opensearch-project/documentation-website#6308]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We need to add new format rfc3339_lenient format introduced in [#11465](https://github.com/opensearch-project/OpenSearch/pull/11465) in the datetime formats doc [here](https://github.com/opensearch-project/documentation-website/blob/main/_field-types/supported-field-types/date.md#full-date-formats)

Format name: `rfc3339_lenient`
Description: An RFC3339 compatible datetime formatter which is much faster than other full date lenient formats like `strict_date_optional_time`
Pattern and examples:
```
Year:
        YYYY (eg 1997)
Year and month:
        YYYY-MM (eg 1997-07)
 Complete date:
        YYYY-MM-DD (eg 1997-07-16)
 Complete date plus hours and minutes:
        YYYY-MM-DDThh:mmTZD (eg 1997-07-16T19:20+01:00)
 Complete date plus hours, minutes and seconds:
        YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)
 Complete date plus hours, minutes, seconds and a decimal fraction of a second
        YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00)
        YYYY-MM-DDThh:mm:ss,sTZD (eg 1997-07-16T19:20:30,45+01:00)
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Backport 2.x: https://github.com/opensearch-project/OpenSearch/pull/12107

**Comment by CaptainDredge** [comment]
cc: @hdhalter

**Comment by hdhalter** [comment]
Thanks, @CaptainDredge ! Can you please create the documentation PR with this information?

**Comment by bbarani** [comment]
@CaptainDredge Can you please confirm if this feature will make it to 2.12.0 release? If so, can you create the documentation PR with this information?

**Comment by CaptainDredge** [comment]
@bbarani yes this has already been merged in `2.x` so it should make it to `2.12.0`. I've raised documentation PR here
https://github.com/opensearch-project/documentation-website/pull/6337
