### ISSUE TITLE
Audit existing content and list missing topics

### ISSUE THREAD

**Issue by alicejw-aws** [opensearch-project/documentation-website#632]
Actions: Conduct an audit of the current doc set content and identify which topics are missing and need documentation coverage, or need to be clarified where content is confusing or not optimally organized for discoverability.

PHASE I: 
In a separate spreadsheet, provide a content coverage status for all items listed (this includes current content and missing content):

a. 0 = missing completely from doc set content
b. 1 = light coverage, or what's documented is confusing and needs to be reorganized for clarity.
c. 2 = adequate coverage, does not need to be rewritten

PHASE II: Make a list of doc content topics that are **missing from the doc set**, and separate them into categories:
1. Feature or capability is exclusive to OpenSearch (i.e. Elastic doesn't provide this feature).
2. Feature is not exclusive to OpenSearch.

Mechanisms to gather data for phase II:
1. survey the OpenSearch team - (done).
2. survey the community members via forum post in General Feedback category:
https://forum.opensearch.org/c/feedback/ (in-progress)

Final docs:
1. Comprehensive list of categories and individual topics that we need to document. 
2. Provide the percentage of coverage per category. This represents percentage of topics within that category are covered 0 - 100% (e.g. Installation 29%)

**Comment by alicejw-aws** [comment]
Update: 
PHASE I is complete. Updated spreadsheet is available in WorkDocs: [Documentation priorities.xlsx](https://amazon.awsapps.com/workdocs/index.html#/document/98496dc50ceaa7d1aa7f5f1df011ececda68d6449c3439e2acc4ff576a227bf5)
See Worksheet: Content Coverage Status - each item contains content coverage status and URL if content is available.

PHASE II: Survey is in-progress. Final responses due Tues 6-7 by EOD. 
Quip with response analysis will be added to OS Docs Team quip folder after responses are received.

**Comment by alicejw-aws** [comment]
Survey community members with a Forum post:  https://forum.opensearch.org/c/feedback/ 

Draft in-progress, will finalize post survey question, and get editor's review before we post it. 

"Hello OpenSearch developer community members! 
Could you help us identify which features you use now that are missing usage guides in our documentation set  [OpenSearch.org/docs/latest](https://opensearch.org/docs/latest) (https://opensearch.org/docs/latest)? 

We are eager to write new content to make using OpenSearch more efficient for you, so we need your help to identify which features and topics you need the most!"

**Comment by hdhalter** [comment]
@alicejw-aws  - is this final or do you need sign-off by anyone else?

**Comment by alicejw-aws** [comment]
@hdhalter - yes this is final - ready to post today.

**Comment by alicejw-aws** [comment]
Posted to community forum: https://forum.opensearch.org/t/help-us-improve-our-docs/9958

General data capture plan: 
1. check it daily for responses, and add to worksheet with list of new sections needed.
2. Add to spreadsheet - worksheet: Community requests. 
3. Share with team in OS Docs Team folder.

**Comment by alicejw-aws** [comment]
PHASE II point 2 is complete: Survey results are organized into a spreadsheet:Missing topics list for OpenSearch docs,  Survey list of topics - sheet
Shared in OS Docs Team folder.
Note: we did not get the team to identify which features are exclusive to OpenSearch (i.e. Elastic does not provide).

**Comment by alicejw-aws** [comment]
List of features exclusive to OpenSearch is now complete. 
1. See quip with description - [OpenSearch exclusive features](https://quip-amazon.com/rO8DAmkugkhe/OpenSearch-exclusive-features-Elastic-does-not-provide)
2. See worksheet with list of topics and doc URLs - [Topics exclusive to OpenSearch](https://quip-amazon.com/lxATAzVrISbB/Missing-topics-list-for-OpenSearch-docs#temp:C:KfMfea11f0cc0a98cd8cad0134ce)

**Comment by hdhalter** [comment]
Great job, Alice! Thanks!
