### ISSUE TITLE
[DOC] Metrics Framework

### ISSUE THREAD

**Issue by Gaganjuneja** [opensearch-project/documentation-website#6338]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

- Describe this [feature](https://github.com/opensearch-project/OpenSearch/issues/10141).
- Configuration changes.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
RFC - https://github.com/opensearch-project/OpenSearch/issues/10141
PR1 - https://github.com/opensearch-project/OpenSearch/pull/10241
PR2 - https://github.com/opensearch-project/OpenSearch/pull/12062

**Comment by hdhalter** [comment]
Thanks, @Gaganjuneja . Do you know which release we are targeting?

**Comment by Gaganjuneja** [comment]
@hdhalter, We are releasing this as an experimental feature in 2.12 release. I will provide you the write up by tomorrow.
