### ISSUE TITLE
[DOC] Availability and recovery Snapshots Take and restore snapshots 

### ISSUE THREAD

**Issue by etgraylog** [opensearch-project/documentation-website#6339]
**What do you want to do?**
 
- [x] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
When an AWS EC2 Instance uses an AWS IAM Instance Profile with a Policy granting required access to the S3 Bucket and Trust Relationship established with ec2.amazonaws.com, adding `s3.client.default.access_key` & `s3.client.default.secret_key` to OpenSearch's keystore is not necessary & will cause problems if done while following the instructions.

Steps 2 thru 7 of these instructions can be skipped with this configuration:
https://opensearch.org/docs/2.11/tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore/#amazon-s3

Affected versions: 2.11.0 (& above)

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks, @etgraylog ! Can you please submit a PR with the proposed changes?
