### ISSUE TITLE
[DOC] install/docker page: versions

### ISSUE THREAD

**Issue by smacrakis** [opensearch-project/documentation-website#6342]
**What do you want to do?**
 
- [X ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
On https://opensearch.org/docs/2.11/install-and-configure/install-opensearch/docker/ , it says
```
docker pull opensearchproject/opensearch:2
docker pull opensearchproject/opensearch-dashboards:2
```
Why `2` and not `latest`? What does "2" mean? Maybe the latest 2.X version? If I already have a 2.X version, does it update to the latest, or does it keep the one I have?

Also, this command is given for checking that the search server is active, and gets the version:
```curl https://localhost:9200 -ku 'admin:admin'```
but I don't see the equivalent for the dashboard. It would be good to know how to check the Dashboard version either via API/curl or in the Dashboard UI.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks, @smacrakis ! Latest, 2, and 2.11.1 are the same image so you will get the latest version of the second major release.

**Comment by smacrakis** [comment]
Thanks,

To me at least (ignorant as I am of Docker conventions), latest seems clearer than 2, which is pretty obscure.

Maybe that dashboard version command should also be mentioned on the page (especially since it isn't the same as the command for the server)? (I guess it's not a documentation issue that it comes out as unformatted JSON...)

I think that the Dashboard version is what you see by clicking on the question mark in a circle in the upper right of the Dashboards page to the right of the word HELP, but it's not 100% clear that that's the Dashboards version and not the back end server version (shouldn't both be listed somewhere?).

**Comment by smacrakis** [comment]
By the way, there is a typo in your curl command.
You wrote: ``curl http://localhost:5601/api/status -ku ‘admin:admin’.``
But it should be: ``curl http://localhost:5601/api/status -ku 'admin:admin'``.
They look almost the same, but the first version uses curly quotes, which give an error!

**Comment by hdhalter** [comment]
> By the way, there is a typo in your curl command. You wrote: `curl http://localhost:5601/api/status -ku ‘admin:admin’.` But it should be: `curl http://localhost:5601/api/status -ku 'admin:admin'`. They look almost the same, but the first version uses curly quotes, which give an error!

Sorry, copy/paste error! I should have written it in code format.

**Comment by hdhalter** [comment]
@Naarcha-AWS - can you please work with Stavros to make the updates? Thanks!

**Comment by leanneeliatra** [comment]
I can do this @hdhalter if you like? Assign me and I can do the update if that's helpful. Thanks.

**Comment by hdhalter** [comment]
I believe this is not a documentation concern, so I am closing this issue. @smacrakis - if there is anything we can do, let me know.
