### ISSUE TITLE
[DOC] Add documentation about how to use import saved objects with enabled multiple data source feature

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/documentation-website#6345]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
With https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5712, when multiple data source feature is turned on, user can upload file which stores saved objects from a remote datasource and the dashboard can recognize and use the saved objects. We are releasing this feature in Open Search dashboards 2.12 and ongoing versions. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5777
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5781

**Comment by vagimeli** [comment]
Hi @BionIT, Please tag me once the PR is available. I'll move the content through the doc and editorial reviews and then merge the PR. Thank you :)

**Comment by hdhalter** [comment]
Emma will have the PR ready by 12 pm 2/6

**Comment by BionIT** [comment]
Hi @vagimeli, the PR is ready for review and please let me know if any question
cc @hdhalter
