### ISSUE TITLE
[DOC] describe index.query.max_nested_depth setting

### ISSUE THREAD

**Issue by mkhludnev** [opensearch-project/documentation-website#6346]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Completion of https://github.com/opensearch-project/OpenSearch/pull/11670 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by mkhludnev** [comment]
Thanks @mkhludnev 
how I can put #6347 to 3.0 as well?

**Comment by hdhalter** [comment]
> Thanks @mkhludnev how I can put #6347 to 3.0 as well?

This will get pushed to 3.0, but if you want additional changes, you can create a new PR.

**Comment by mkhludnev** [comment]
@hdhalter 
> This will get pushed to 3.0, but if you want additional changes, you can create a new PR.
3.0 doc change #6715

**Comment by hdhalter** [comment]
I'm looking for a way to clone this issue, but I don't think it's possible in GitHub. In any event, after 2.13, I'll reopen this issue so we can use it for tracking for the 3.0 PR.
