### ISSUE TITLE
[DOC] Request to Add Missing Datasource Permissions to Access Control Documentation

### ISSUE THREAD

**Issue by ghost** [opensearch-project/documentation-website#6360]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

### Tell us about your request. Provide a summary of the request and all versions that are affected.

I've identified missing permissions in the Opensearch documentation that are crucial for administrators and developers working with Opensearch's datasources. The permissions

> cluster:admin/opensearch/ql/datasources/create

>   cluster:admin/opensearch/ql/datasources/read

>   cluster:admin/opensearch/ql/datasources/update

>   cluster:admin/opensearch/ql/datasources/delete

>   cluster:admin/opensearch/ql/datasources/patch

>   cluster:admin/opensearch/ql/async_query/create

>   cluster:admin/opensearch/ql/async_query/result

>   cluster:admin/opensearch/ql/async_query/delete

are not currently listed in the [permissions documentation](https://github.com/opensearch-project/documentation-website/blob/main/_security/access-control/permissions.md?plain=1). The permissions are essential for working with data sources across the cluster, and its absence from the documentation could lead to confusion and misconfiguration of security roles within Opensearch deployments.

Adding the permissions to the documentation would provide a more comprehensive overview of the permissions available in Opensearch, helping users to correctly set up and manage their instances. This request pertains to all current and future versions of the Opensearch documentation that include access control and permission configurations.

### What other resources are available? Provide links to related issues, POCs, steps for testing, etc.

Currently, there are no direct links to issues or POCs related to this specific permission since it's an observation from using Opensearch and consulting the official documentation.

For reference and testing, the current documentation on access control and permissions can be found here: [Access Control Permissions](https://github.com/opensearch-project/documentation-website/blob/main/_security/access-control/permissions.md?plain=1).

This update would ensure that the documentation reflects all capabilities and configurations available to Opensearch users, improving security and operational efficiency.

**Comment by hdhalter** [comment]
Thanks, @yoicomment ! Do you want to make this change to https://github.com/opensearch-project/documentation-website/blob/main/_security/access-control/permissions.md?plain=1?

**Comment by yoicomment** [comment]
Yes, I can do it

**Comment by yoicomment** [comment]
@hdhalter Do you know what "ql" means?

**Comment by hdhalter** [comment]
@scrawfor99 - Stephen, do you know what ql means in this context: cluster:admin/opensearch/**ql**/datasources/patch

**Comment by scrawfor99** [comment]
Hi @hdhalter and @yoicomment, I think that is just meant to represent "query language." It was added as part of these and similar changes: https://github.com/opensearch-project/security-dashboards-plugin/pull/1395

For example DQL is Dashboards Query Language, SQL is Structured Query Language etc.

**Comment by yoicomment** [comment]
One thing I'm really upset about is that some permissions are meaningless and that I don't understand them. Maybe that's a problem on my part but for example the following permission:

``
cluster:admin/opensearch/ql/datasources/create
``
I don't really understand what this permission really does. I know that this permission gives rights to create something, but I don't know what. And why and when do I need to assign this permission to a role/user.

**Comment by scrawfor99** [comment]
HI @yoicomment, I hear empathize with your frustration. We (OpenSearch as a whole) are always seeking to improve the experience of getting started and using the suite. I am not particularly knowledgeable about the query language plugin so I don't know how much insight I can provide there; I do know a fair bit about the Security plugin however.

For reference:

Each permission in OpenSearch is specified by a path like the one you shared (`cluster:admin/opensearch/ql/datasources/create`). 

Each of these paths represents a group of permissions for an "action"(s) which is how OpenSearch internally models requests and operations. For example, you might have an action that maps to searching an index. 

The first part of the permission string specifies the type of permission it is. This will generally be either a "cluster" or "index" permission. Cluster permissions provide cluster-wide functionality while index map to a specific index.

The next parts of the permission string generally specify a grouping for the permission which works like a hierarchy or tree with the other permissions in OpenSearch. In this case, `cluster:admin/opensearch/ql/` means that the permission is part of the "ql" group so will be associated with other permissions that are from that plugin. 

The other parts of the permissions will correspond to greater specificity with the permission and  how things are grouped. So again this permission corresponds to the "create" action for "datasources." 

To your question of why you need to specify this and assign a role: OpenSearch is designed for industrial applications primarily. This type of permission model is common in cases where you have lots of users with similar positions. For example "accountant" could be one role shared by 100 people while "engineer" may be a different role shared by 50 people. You don't want to have to assign permissions individually to each person so roles let you specify a class of privileges you want a group of users to have.

This is a bit of a simplified explanation but covers the basics for the framework.

**Comment by yoicomment** [comment]
Thanks for the reply! It makes thing clearer. Another thing that confused me at the beginning was that the permission contains the term "admin". Therefore at the beginning, I immediately thought it is a permission I just should give admin users this permission and not regular users. But now knowing more, it is also a permission regular users can have.

**Comment by AntonEliatra** [comment]
PR raised https://github.com/opensearch-project/documentation-website/pull/6964
