### ISSUE TITLE
[DOC] Views

### ISSUE THREAD

**Issue by peternied** [opensearch-project/documentation-website#6363]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 I'm adding a new set of administration and usage APIs for a new feature views.  This feature abstracts where data is from those that want to search it, like an alias with more flexibility.  The feature is experimental and will be building up a critical mass of functionality before becoming part of the public API.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
- https://github.com/opensearch-project/OpenSearch/issues/6181

Note; I'll start writing documentation in draft for developers to review.

**Comment by hdhalter** [comment]
Thanks, Peter. Do you have a release you are targeting?

**Comment by peternied** [comment]
@hdhalter Not at this time, I'll update as soon as we've got it slated.

**Comment by peternied** [comment]
I'm going to close out this issue until we've got investment in views - just like the PR that was closed
