### ISSUE TITLE
[DOC]  Document how to configure XContent codepoint limit (YAML)

### ISSUE THREAD

**Issue by reta** [opensearch-project/documentation-website#6397]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Please check this change for reference https://github.com/opensearch-project/OpenSearch/pull/12301/files

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Target is 2.13.0, @hdhalter please feel free to assign it to me, thank you

**Comment by hdhalter** [comment]
Hi @reta! Do you have an ETA for the doc PR? Our internal deadline for having everything up and in review is Tuesday, 3/19, for the first release candidate of 2.13. Thanks!

**Comment by reta** [comment]
> Hi @reta! Do you have an ETA for the doc PR? Our internal deadline for having everything up and in review is Tuesday, 3/19, for the first release candidate of 2.13. Thanks!

Ah sorry about that @hdhalter , will do first thing tomorrow morning, thank you!
