### ISSUE TITLE
[BUG] link to version 1.3 is showing 2.0.0 documentation.

### ISSUE THREAD

**Issue by neuralsearch-opensearch** [opensearch-project/documentation-website#640]
### What is the bug?
The 1.3.x docs  page https://opensearch.org/docs/1.3/security-plugin/configuration/security-admin/ is showing the below config which is 2.0.0 specific configuration and does not work on 1.3.x.

./securityadmin.sh -f ../../../config/opensearch-security/internal_users.yml \
  -t internalusers \
  -icl \
  -nhnv \
  -cacert ../../../config/root-ca.pem \
  -cert ../../../config/kirk.pem \
  -key ../../../config/kirk-key.pem
### How can one reproduce the bug?
_Steps to reproduce the behavior._

**Comment by hdhalter** [comment]
Hi @peterzhuamazon - Can you please tell me if this is still an issue and how we can fix it? Here is the page: https://opensearch.org/docs/1.3/security/configuration/security-admin/.

**Comment by hdhalter** [comment]
@scrawfor99 - what is the correct script to add here?

**Comment by scrawfor99** [comment]
Hi @hdhalter, 

The security admin script is supported for all version of OpenSearch so this should be fine. @neuralsearch-opensearch could you provide the error you are encountering so that I can try to take a look at reproducing your issue or debugging the problem?

Thank you!

**Comment by hdhalter** [comment]
Closing this issue since we cannot reproduce it.
