### ISSUE TITLE
Drag and Drop in Dashboards

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#642]
What do you want to do?

- Make a change to existing documentation
**- Add new documentation**
- Report a technical problem with the documentation
- Other

Please provide the following information:

**Give a brief description of your request.** 
Document new functionality coming in 2.1: Drag and Drop enhancements to Dashboards.

**Which versions are affected?**
New to 2.1

**Which pages or URLs are affected?**
We have limited information on our Dashboards in the doc, but the info on dashboards starts here: https://opensearch.org/docs/latest/dashboards/index/ 

**What resources are available** (for example, links to a related issue, PR, design doc, or feature brief)?
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1157
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/379

**Who should we contact with technical questions?**
Andrew Hopp is the PM for Dashboards; Sean Neumann is Engineering manager of Dashboards

**Is there anything else you’d like us to know about your requested change?**

**Comment by kavilla** [comment]
Hello @hdhalter,

I believe this is targeted as 2.2 experimental feature.

cc: @ahopp, @ashwin-pc, @joshuarrrr, @cptnb

**Comment by ashwin-pc** [comment]
Additional references:

Proposal: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/883
Design: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/896

**Comment by hdhalter** [comment]
Hi Melissa, the Feature Review meeting for this is 7/26 11 a.m. PDT.

**Comment by vagimeli** [comment]
Info gathering session scheduled

**Comment by vagimeli** [comment]
release confirmed for 2.2, interviewed developer (8/4), demo provided, content writing started

**Comment by ashwin-pc** [comment]
@VachaShah Why was the Tag moved to 2.3? This has already been released in 2.2

**Comment by kavilla** [comment]
> @Naarcha-AWS  Why was the Tag moved to 2.3? This has already been released in 2.2

+1

**Comment by kolchfa-aws** [comment]
@kavilla @ashwin-pc It's because there was no documentation required for this feature for 2.2. It was decided to put it only in the release notes. Documenting this on the docs website is planned for 2.3.

**Comment by vagimeli** [comment]
This feature is experimental. Projected to continue being experimental for 2.3. Content development in progress.

**Comment by hdhalter** [comment]
This has been documented for 2.3: https://opensearch.org/docs/latest/dashboards/drag-drop-wizard/
