### ISSUE TITLE
[DOC] SAML example in docker-compose is broken

### ISSUE THREAD

**Issue by lllamnyp** [opensearch-project/documentation-website#6420]
**What do you want to do?**
 
- Request a change to existing documentation
- Report a technical problem with the documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

The [docker compose SAML configuration example](https://opensearch.org/docs/latest/security/authentication-backends/saml/#docker-example) does not launch as described. Some of this is due to minor typos in `customize-docker-compose.yml`:

```diff
@@ -22,1 +22,1 @@
-      - ./config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
+      - ./customize-config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
```

```diff
@@ -47,1 +47,1 @@
-      - ./config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
+      - ./customize-config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
```

```diff
@@ -61,1 +61,1 @@
-      - ./custom-opensearch-dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
+      - ./customize-opensearch-dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
```

Having got that out of the way and renamed `customize-docker-compose.yml => docker-compose.yml` for convenience, I try to run with `docker compose up` and hit the next couple of issues:

```
opensearch-saml-dashboards  | 
opensearch-saml-dashboards  |  FATAL  ValidationError: [config validation of [vis_type_timeline].ui]: definition for this key is missing
opensearch-saml-dashboards  | 
opensearch-saml-dashboards exited with code 1
```

and

```
opensearch-saml-dashboards  |  FATAL  Error: Invalid server options  {
...
opensearch-saml-dashboards  |   "host" [1]: "0"
...
opensearch-saml-dashboards  | [1] "host" must be a valid hostname
```

Some trial and error leads me to adjust `customize-opensearch-dashboards.yml` as follows:

```diff
@@ -15,3 +15,3 @@
-timelion.ui.enabled: true
+# timelion.ui.enabled: true
 server.name: opensearch-dashboards
-server.host: "0"
+server.host: "0.0.0.0"
```

After this all components finally launch. However, when I browse to http://localhost:5601, I go through a couple of redirects to arrive at http://localhost:5601/auth/saml/login?nextUrl=%2F&redirectHash=false where I get the response

```
{"statusCode":500,"error":"Internal Server Error","message":"Internal Error"}
```

I have spelunked a bit and injected proxies to intercept requests and responses between Opensearch Dashboards and the Opensearch nodes, as well as the dockerized SAML IdP. I have observed that

- Prior to returning the error 500, Dashboards calls the node with `GET /_plugins/_security/authinfo` without any credentials, receiving a 401.
- When Dashboards sends keepalives to the nodes, it **does** pass its credentials in a basic-auth header.
- At no point in time is a request made to the SAML-IdP.

I have tried this with image tags `2.4.0`, `2.6.0`, `2.8.0`, `2.11.0`, and `latest` with similar results. I also tried following the general documentation on the [SAML page](https://opensearch.org/docs/latest/security/authentication-backends/saml) to set up a production cluster with the Opensearch Kubernetes Operator, where I also hit the same error.

I'm not particularly well-versed in the Java ecosystem, so I'm a bit lost as to how to dig deeper.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

Just go through the docker-compose example to reproduce.

**Comment by hdhalter** [comment]
@DarshitChanpura - Can you please comment on this? Thanks.

**Comment by DarshitChanpura** [comment]
I will be raising a PR soon with an updated example.

**Comment by DarshitChanpura** [comment]
@hdhalter I've created a PR to update the steps for SAML example: https://github.com/opensearch-project/documentation-website/pull/6532

@lllamnyp The example should be updated once https://github.com/opensearch-project/demos/pull/126 and https://github.com/opensearch-project/documentation-website/pull/6532 are merged.

**Comment by lllamnyp** [comment]
@DarshitChanpura much appreciated! I'll give it a shot and see how it works.
