### ISSUE TITLE
[DOC] Get snapshot status docs have incorrect information

### ISSUE THREAD

**Issue by lmako-aws** [opensearch-project/documentation-website#6428]
**What do you want to do?**
 
- [ X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Hi Team, 

Can we please review this bit of the documentation. 
```
Three request variants provide flexibility:

    GET _snapshot/_status returns the status of all currently running snapshots in all repositories.

    GET _snapshot/<repository>/_status returns the status of only currently running snapshots in the specified repository. This is the preferred variant.

    GET _snapshot/<repository>/<snapshot>/_status returns the status of all snapshots in the specified repository whether they are running or not.
```
The last bit says `returns the status of all snapshots in the specified repository whether they are running or not.`. I'm pretty sure this is incorrect as the request path already has a specific snapshot id in it, so the response will have to be snapshot specific. This is in alignment with the example request underneath...
```
GET _snapshot/my-opensearch-repo/my-first-snapshot/_status
{
   "ignore_unavailable": true 
}
```
...that returns status information of a single snapshot called `my-first-snapshot` from the `my-opensearch-repo` repository.

And the Elasticsearch docs seem to agree with me as well :) 
https://www.elastic.co/guide/en/elasticsearch/reference/current/get-snapshot-status-api.html#get-snapshot-status-api-example

I recommend that we change the second and the third examples in our docs as follows:
```
Three request variants provide flexibility:

    GET _snapshot/_status returns the status of all currently running snapshots in all repositories.

    GET _snapshot/<repository>/_status returns all currently running snapshots in the specified repository. This is the preferred variant.

    GET _snapshot/<repository>/<snapshot>/_status returns detailed status information of a specific snapshot in a specific repository, regardless of whether it is currently running or not.
```

Cheers,
Laz

**Comment by hdhalter** [comment]
Thanks for discovering the problem and entering this issue, @lmako-aws ! Would you be willing to push up a PR with this change to expedite the process?

**Comment by lmako-aws** [comment]
I'd love to help @hdhalter but unfortunately I have no idea how to do a PR, sorry.

**Comment by hdhalter** [comment]
OK : ) But if you'd like to learn how, it's pretty straight-forward. The easiest thing to do is go to the [file](https://opensearch.org/docs/latest/api-reference/snapshots/get-snapshot-status/) and click "Edit this page", make the changes, commit the changes, then push up the PR. We then review it and merge it in production. Full instructions are here: We https://github.com/opensearch-project/documentation-website/blob/main/CONTRIBUTING.md.

**Comment by hdhalter** [comment]
Thanks, @lmako-aws! But can you please fork the doc repo and make your changes there? Alternatively, we can create a new PR with your changes. Whichever you prefer! Thanks. Here is the file: https://github.com/opensearch-project/documentation-website/edit/main/_api-reference/snapshots/get-snapshot-status.md.

**Comment by lmako-aws** [comment]
Hi @hdhalter - My apologies, I thought I've already replied to your previous comment. If you could do this please, that would be very much appreciated. Thanks for your help!

**Comment by hdhalter** [comment]
> Hi @hdhalter - My apologies, I thought I've already replied to your previous comment. If you could do this please, that would be very much appreciated. Thanks for your help!

No problem, thanks!
