### ISSUE TITLE
Multi-terms aggregation feature

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#643]
What do you want to do?

Make a change to existing documentation
**Add new documentation**
Report a technical problem with the documentation
Other

Please provide the following information:

**Give a brief description of your request.**
New feature added in v2.1: Have an aggregation feature that lets me sort by a number of a document or a metric aggregation on a composite key and get top N results.

**Which versions are affected?**
Being added to 2.1

**Which pages or URLs are affected?**
?

**What resources are available** (for example, links to a related issue, PR, design doc, or feature brief)?
https://www.elastic.co/guide/en/elasticsearch//reference/master/search-aggregations-bucket-multi-terms-aggregation.html
https://github.com/opensearch-project/OpenSearch/issues/1629

**Who should we contact with technical questions?**
?

**Is there anything else you’d like us to know about your requested change?**

**Comment by alicejw-aws** [comment]
Duplicate issue - see [issue 582](https://github.com/orgs/opensearch-project/projects/22/views/1?filterQuery=assignee%3A%40me)
