### ISSUE TITLE
Contribution analysis function

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#645]
What do you want to do?

Make a change to existing documentation
**Add new documentation**
Report a technical problem with the documentation
Other

Please provide the following information:**

**Give a brief description of your request.**
New feature in 2.1: Contribution analysis is to find the top contributors to some abnormal period like which server contributes most for the error spike. We can integrate anomaly localization with ml-commons to provide general anomaly localization function.

**Which versions are affected?**
Being added in 2.1

**Which pages or URLs are affected?**
https://opensearch.org/docs/latest/ml-commons-plugin/index/

**What resources are available** (for example, links to a related issue, PR, design doc, or feature brief)?
https://github.com/opensearch-project/ml-commons/issues/98

**Who should we contact with technical questions?**

**Is there anything else you’d like us to know about your requested change?**

**Comment by Naarcha-AWS** [comment]
Turns out that Contribution Analysis and localization have already been added to ML-Commons per the linked PR. Closing this issue.
