### ISSUE TITLE
[DOC] Update Snapshot Repository documentation

### ISSUE THREAD

**Issue by astute-decipher** [opensearch-project/documentation-website#6485]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 
Our current documentation for "**Registering or updating a snapshot repository**" only talks about configuring Amazon S3 and local filesystem as repositories. We should also include other commonly used cloud based storage services like Azure Container and Google Cloud Storage

**What other resources are available?**
Current documentation : https://opensearch.org/docs/latest/api-reference/snapshots/create-repository/

**Comment by hdhalter** [comment]
Tagging [nilushancosta](https://github.com/nilushancosta), as he also recently reported this content gap.

**Comment by nilushancosta** [comment]
@hdhalter, I sent a PR with instructions for Azure
