### ISSUE TITLE
Support for more zoom levels in dashboard

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#649]
What do you want to do?

**Make a change to existing documentation**
Add new documentation
Report a technical problem with the documentation
Other

Please provide the following information:

**Give a brief description of your request.**
This is a new feature slated for 2.1: Currently we have zoom level of 10 but we would need to further increase to 20.

**Which versions are affected?**
2.1

**Which pages or URLs are affected?**
This feature may not be mentioned in the documentation at all.

**What resources are available** (for example, links to a related issue, PR, design doc, or feature brief)?
https://github.com/opensearch-project/maps/issues/4

**Who should we contact with technical questions?**
See issue.

**Is there anything else you’d like us to know about your requested change?**

**Comment by dtaivpp** [comment]
@hdhalter I was actually just looking for documentation on this. From what I can see the maps documentation is missing from the whole website. I missed the doc that floated around for missing docs but I think this is a good candidate to make it to that backlog.

**Comment by Naarcha-AWS** [comment]
Let's indicate support for additional levels in the release notes, since we don't have maps documentation as of right now.

**Comment by hdhalter** [comment]
Sounds like they are bumping this up to x14 for version 2.2.

**Comment by vagimeli** [comment]
This is a change to the map service and relevant to release 2.0, 2.1, and 2.2. Documenting in release blog.

**Comment by vagimeli** [comment]
Zoom level increase to 20x.

**Comment by vagimeli** [comment]
Documentation on zoom levels to be included in Maps foundational content

**Comment by vagimeli** [comment]
Zoom levels overview is in release notes for 2.1; comprehensive documentation to be added to Maps foundational content in subsequent release
