### ISSUE TITLE
[DOC] Lucene Inbuilt Byte Quantization 

### ISSUE THREAD

**Issue by naveentatikonda** [opensearch-project/documentation-website#6496]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Since OpenSearch version 2.9, users can ingest byte vectors using the [Lucene Byte Vector](https://opensearch.org/docs/latest/field-types/supported-field-types/knn-vector#lucene-byte-vector) feature. But, Cx still need to do the quantization on their end to convert floats into bytes as it only accepts the byte range [-128 to 127]. But, now lucene added support for inbuilt scalar quantization where it takes float vectors as input and quantizes them into byte vectors which removes the overhead for the Cx besides improving the performance and memory optimization.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/k-NN/issues/1277

**Comment by naveentatikonda** [comment]
Can someone pls add v2.13 label to this issue

**Comment by naveentatikonda** [comment]
@hdhalter Please change the label to v2.14.0. Thanks!

**Comment by hdhalter** [comment]
Hi @naveentatikonda , what is your ETA for producing the doc PR? To meet entrance criteria, the PR must be open and in review by 4/30. Thanks!

**Comment by hdhalter** [comment]
Will do, thanks, @naveentatikonda !

**Comment by naveentatikonda** [comment]
@hdhalter Pls change the label to 2.16

**Comment by hdhalter** [comment]
@naveentatikonda - Is this on track for 2.16? Thanks!

**Comment by naveentatikonda** [comment]
Yes @hdhalter, will create a draft PR today by EOD
