### ISSUE TITLE
[DOC] Add instructions on registering Azure storage as a snapshot repository

### ISSUE THREAD

**Issue by nilushancosta** [opensearch-project/documentation-website#6515]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore/#register-repository states that Azure storage can be used as a snapshot repository. However detailed instructions on registering a snapshot repository are only available for Shared file system and Amazon S3. Would it be possible to add instructions for Azure storage as well?
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Hi @nilushancosta, thanks for entering this issue! We have other similar requests. Let me see if I can get some help with this one. 
https://github.com/opensearch-project/documentation-website/issues/6485
https://github.com/opensearch-project/documentation-website/issues/4334
https://github.com/opensearch-project/documentation-website/issues/417

**Comment by nilushancosta** [comment]
Hey @hdhalter,
Thanks for looking into this. Sorry I did not see that there were issues for this request already. Since this is a duplicate issue, please let me know if you would like me to close it.

**Comment by hdhalter** [comment]
Sure, @nilushancosta. I'll close it. Do you want to test it when we get something up? I can tag you in the other issue.
