### ISSUE TITLE
[DOC] Support radius search in k-NN

### ISSUE THREAD

**Issue by junqiu-lei** [opensearch-project/documentation-website#6528]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
We are introducing a radius search feature in the k-NN plugin, necessitating updates to the documentation. This update impacts versions starting from 2.13.

The radius search feature enables users to find all points within a specified distance from a query point in a vector space, enhancing search flexibility and utility. This significant enhancement requires documentation updates to accurately reflect the new capabilities available from version 2.13 onwards.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

RFC: https://github.com/opensearch-project/k-NN/issues/1483
Issue: https://github.com/opensearch-project/k-NN/issues/814

**Comment by hdhalter** [comment]
Thanks for entering this issue, @junqiu-lei! Will you be writing the PR for this doc update?

**Comment by junqiu-lei** [comment]
Hi @hdhalter, yes and this feature moved to 2.14 release.

**Comment by hdhalter** [comment]
Hi @junqiu-lei , what is your ETA for producing the doc PR? To meet entrance criteria, the PR must be open and in review by 4/30. Thanks!

**Comment by junqiu-lei** [comment]
Hi @hdhalter I'm working on this doc, will have PR in review before 4/30. Thanks!
