### ISSUE TITLE
[FEATURE] Add documentation for missing clients

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/documentation-website#653]
### Is your feature request related to a problem?
We have few clients which are not included in the documentation on the website. These clients are: [Rust](https://github.com/opensearch-project/opensearch-rs), [High Level Python](https://github.com/opensearch-project/opensearch-dsl-py) and [Ruby](https://github.com/opensearch-project/opensearch-ruby).

### What solution would you like?
Add documentation for these clients.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by Naarcha-AWS** [comment]
Issue for the Ruby client: #318

**Comment by kolchfa-aws** [comment]
Issue for the Rust client #1089

**Comment by kolchfa-aws** [comment]
Issue for the high-level Python client #1090

**Comment by kolchfa-aws** [comment]
All of the above issues are implemented so closing meta issue.
