### ISSUE TITLE
[DOC] Review Dashboards documentation wording

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#6531]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Take a look at our word choices across the Dashboards documentation. We seem to do a lot of "exploring," "discovering," and "unlocking," when it would be better to use a word that reflects what the user will actually do.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@vagimeli - Can this issue be closed?
