### ISSUE TITLE
[DOC] Pipeline ingest processor supports ignore_missing_pipeline parameter

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/documentation-website#6534]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

In 2.13.0, we'll introduce a new parameter `ignore_missing_pipeline` for the pipeline ingest processor, we need to document that.

```
PUT _ingest/pipeline/outer
{
  "description": "outer pipeline",
  "processors": [
    {
      "pipeline": {
        "name": "inner",
        "ignore_missing_pipeline": true
      }
    }
  ]
}
```

But now we don't have documentation for the pipeline ingest processor, we need to add that document firstly.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://github.com/opensearch-project/OpenSearch/pull/12476

**Comment by gaobinlong** [comment]
The related code [PR](https://github.com/opensearch-project/OpenSearch/pull/12476) hasn't be merged because the idea in that PR isn't accepted by the maintainers,  so this change doesn't target for 2.13.0, now I'll close this issue and if the code PR is merged, I'll open a new doc issue for it.

**Comment by hdhalter** [comment]
Thanks, @gaobinlong !
