### ISSUE TITLE
[DOC] Add documentation for `kuromoji_completion` analyzer and filter

### ISSUE THREAD

**Issue by msfroh** [opensearch-project/documentation-website#6552]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
@hogesako added support for the `kuromoji_completion` analyzer and token filter. [The original Lucene issue](https://issues.apache.org/jira/browse/LUCENE-10102) explains what it does nicely.

For now, the analyzer needs to be configured from scratch (i.e. it's not available as an out-of-the-box language analyzer), so it probably makes sense to add it to https://opensearch.org/docs/latest/analyzers/token-filters/index/, I think.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

Change to add the filter: https://github.com/opensearch-project/OpenSearch/pull/12287

**Comment by hdhalter** [comment]
Thanks, @msfroh. Do you know if this will be merged in 2.13?

**Comment by msfroh** [comment]
> Do you know if this will be merged in 2.13?

Very likely. We're just fighting with build checks, then we should be able to merge it in.

**Comment by hdhalter** [comment]
Hi @hogesako , can you please create a PR for this documentation? msfroh recommended to update this page: https://github.com/opensearch-project/documentation-website/edit/main/_analyzers/token-filters/index.md. Thanks!

**Comment by hdhalter** [comment]
> Hi @hogesako , can you please create a PR for this documentation? msfroh recommended to update this page: https://github.com/opensearch-project/documentation-website/edit/main/_analyzers/token-filters/index.md. Thanks!

Never mind. Thanks, @msfroh !

**Comment by hogesako** [comment]
Thank you, @msfroh !
