### ISSUE TITLE
[BUG] OpenSearch Dashboards Vega Help - need to remove Help menu item

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/documentation-website#658]
**Describe the bug**

- <img width="1485" alt="image" src="https://user-images.githubusercontent.com/32652829/172729444-98aee7f1-c191-4dfb-87c8-01bd067d7dc8.png">

- Clicking that link leads to https://opensearch.org/docs/latest/dashboards/index/

- I know we may not have full documentation for any visualizations in OSD. Is there a meta issue for creating those documentation? 

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by alicejw-aws** [comment]
Update: Vega is a 3rd party product. . .they don't appear to have any Help docs available on their site: https://vega.github.io/vega/about/. 
We probably just need to reassign the ticket to UX team to remove that menu option from the Dashboards.

**Comment by alicejw-aws** [comment]
Hi @kgcreative , I'm not sure what is the process to update the Dashboards UI. Could you help me route this to someone on your team to remove the drop-down menu item for OS Dashboards Vega help docs? (This doc isn't available yet) thanks

**Comment by kgcreative** [comment]
@kavilla - for now, let's remove the link to `OpenSearch Dasboards Vega help`

**Comment by alicejw-aws** [comment]
quick status: i created an issue for opensearch-dashboards repo to remove the menu item. keeping this doc ticket open to maintain the research it contains for us.

**Comment by alicejw-aws** [comment]
Here is the UI bug ticket for the opensearch-dashboards repo.

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2504

**Comment by AMoo-Miki** [comment]
OSD has a specific implementation of Vega that extends its capabilities and these extended capabilities need to be exposed via our documentations.

**Comment by vagimeli** [comment]
> OSD has a specific implementation of Vega that extends its capabilities and these extended capabilities need to be exposed via our documentations. Without this information, users have no way to discover these awesome capabilities that are made available to them.

@AMoo-Miki Do we need to add on to this documentation? https://opensearch.org/docs/latest/dashboards/visualize/vega/
