### ISSUE TITLE
[DOC] Default Audit Log logger name is "sgaudit" instead of "audit"

### ISSUE THREAD

**Issue by johtani** [opensearch-project/documentation-website#6602]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 

[Audit log storage types](https://github.com/opensearch-project/documentation-website/blob/main/_security/audit-logs/storage-types.md#log4j) document says "By default, the Security plugin uses the logger name `audit`".
However, it looks like `sgaudit` instead of `audit` in [the implementation](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/auditlog/sink/Log4JSink.java#L30) 

What do you think?

**Comment by Naarcha-AWS** [comment]
@johtani, tagging the person I usually ask technical details for security, @scrawfor99. @scrawfor99, could you provide additional insight on which logger name is correct?

**Comment by scrawfor99** [comment]
The default name in the security plugin just needs to be swapped. The example configuration provided is correct but the actual code will populate with the 'sgaudit' name if no name is provided. I assume the documentation was referring to the fact that the demo opensearch.yml comes with the name set to 'audit'.

**Comment by hdhalter** [comment]
@scrawfor99 - Should we leave the documentation as is, and assume it will be updated on the security plugin soon?

**Comment by scrawfor99** [comment]
Hi @hdhalter, yes. That is what I would recommend. It should be a quick fix in the security repo and the docs are consistent with the intended state as well as what most people would see when using the demo opensearch.yml file.

**Comment by hdhalter** [comment]
Thanks, @scrawfor99, I will close this issue.
