### ISSUE TITLE
[DOC] Add Hadoop client to the clients list

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/documentation-website#6638]
**What do you want to do?**
 
-  Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 This page is missing a reference to the hadoop client:
https://opensearch.org/docs/latest/clients/

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/opensearch-hadoop

**Comment by hdhalter** [comment]
Sure, @wbeckler , we can add it! Do you think it is sufficient to list it and link to the github repo, or is there more we can say about Hadoop in the user docs?

**Comment by wbeckler** [comment]
I think we could list it like the others
