### ISSUE TITLE
[DOC] Default Model Id for Neural Sparse Search Query clause

### ISSUE THREAD

**Issue by zhichao-aws** [opensearch-project/documentation-website#6652]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

In 2.11 release, we introduce `neural_query_enricher` to support default model id in neural search ([ref](https://github.com/opensearch-project/documentation-website/issues/5060)). In 2.13 release, we enhance the neural_query_enricher to enable it to support neural sparse query, too. ([PR link](https://github.com/opensearch-project/neural-search/pull/614)). The API invokation works same as the neural query.
 
Now we want to change existing documentation to inform users about this feature. We can modify the description of neural_query_enricher in `search-processors.md` and `neural-query-enricher.md` to add neural sparse search. We can also add a section "## Setting a default model on an index or field" in `neural-sparse-search.md` like the doc for semantic search ([ref](https://opensearch.org/docs/latest/search-plugins/semantic-search/#setting-a-default-model-on-an-index-or-field)).

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
related issues&PR: 
https://github.com/opensearch-project/documentation-website/issues/5060
https://github.com/opensearch-project/neural-search/pull/614
https://github.com/opensearch-project/documentation-website/pull/5121

**Comment by hdhalter** [comment]
Thanks, @zhichao-aws ! Will you be writing the doc PR for this?

**Comment by zhichao-aws** [comment]
> Thanks, @zhichao-aws ! Will you be writing the doc PR for this?

Sure, I'll create a PR for this.

**Comment by hdhalter** [comment]
HI @zhichao-aws - do you have a doc PR for this?

**Comment by zhichao-aws** [comment]
> HI @zhichao-aws - do you have a doc PR for this?

Will create one today

**Comment by zhichao-aws** [comment]
PR created: #6725
