### ISSUE TITLE
[DOC] Update multiple data sources exiting documents to include the recently changes

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/documentation-website#6667]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

-  We introduced couple new feature flags and enhancement for multiple data sources
    -  data_source.authTypes
    -  data_source.hideLocalCluster

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

- https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5916
- https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5827

**Comment by hdhalter** [comment]
Thanks, @Flyingliuhub! Looks like this update will be for 2.13?

**Comment by hdhalter** [comment]
Got it. @Flyingliuhub - Can you create the doc PR for the back-end setting changes? It also looks like there are some UI changes as well. Do you have an endpoint where we can view the changes to the UI?

**Comment by Flyingliuhub** [comment]
> Got it. @Flyingliuhub - Can you create the doc PR for the back-end setting changes? It also looks like there are some UI changes as well. Do you have an endpoint where we can view the changes to the UI?

Yes. We will create the documentation PR for the setting changes and provide an endpoint for you to see the changes.
Adding @xinruiba @bandinib-amzn here
cc: @seraphjiang

**Comment by Flyingliuhub** [comment]
@hdhalter we deployed version OSD 2.x to our [dev environment](https://playground.opensearch.oss.aws.dev/). Please take a look at the two feature flags we introduced [here](https://github.com/opensearch-project/dashboards-anywhere/blob/5af0fdc702ccb4272a0e5254a03dc7105578e045/config/playground/helm/dev/helm-opensearch-dashboards.yaml#L120C1-L130C39), which have been configured in the dev environment. Please let us know if you have any questions. Thanks.
cc: @bandinib-amzn @xinruiba @BionIT @seraphjiang

**Comment by bandinib-amzn** [comment]
@hdhalter We are releasing some changes which can be used by developers. For example, we did some architectural change in multi data source which enables developer to build their own authentication method in external plugin. Clearly it would be used by developers of OSD and not user. 

Do you think we can document that [here](https://opensearch.org/docs/latest/dashboards/management/multi-data-sources/)? What would be the best place to document technical details?

**Comment by hdhalter** [comment]
> @hdhalter We are releasing some changes which can be used by developers. For example, we did some architectural change in multi data source which enables developer to build their own authentication method in external plugin. Clearly it would be used by developers of OSD and not user.
> 
> Do you think we can document that [here](https://opensearch.org/docs/latest/dashboards/management/multi-data-sources/)? What would be the best place to document technical details?

HI @bandinib-amzn , those details are typically maintained in the supported repo.
