### ISSUE TITLE
[DOC] Getting started with OpenSearch security

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#6668]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
We are currently drafting a new section in the docs called "Getting started in OpenSearch", and one of the areas we want to point to is security. We need to draft a new section called "Getting started with OpenSearch security", advising the community on how to quickly get started or navigate the various options for security in OpenSearch.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Related to https://github.com/opensearch-project/documentation-website/issues/6533.

**Comment by hdhalter** [comment]
@AntonEliatra - Can you please comment so I can assign you to this? Thanks!

**Comment by AntonEliatra** [comment]
@hdhalter Yes, please assign to myself

**Comment by AntonEliatra** [comment]
@hdhalter I've cerated a draft PR for this https://github.com/opensearch-project/documentation-website/pull/7128

Can you have a look and let me know if you this is what you had in mind?
If so I will add more links to existing docs etc, otherwise I'll change the approach as you seem appropriate

**Comment by hdhalter** [comment]
@kolchfa-aws - Do you think this getting started topic fits into the getting started section, maybe after the quickstart? Alternatively, we can add to the Security section. Thanks.

**Comment by kolchfa-aws** [comment]
I think it's best to put this topic in the Getting started section but link to it from the main security page.
