### ISSUE TITLE
[DOC] Add documentation for retry settings for Remote reindex

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/documentation-website#6674]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We've introduced 2 new setting (for all newer versions starting with `2.13`) which allows users to configure the retry mechanism for remote reindex.
- `reindex.remote.retry.initial_backoff`: Backoff time for retries with default as `500ms`. Subsequent retries will do exponential backoff based on initial backoff time. 
- `reindex.remote.retry.max_count`: Max retry count with default  value of 15 retries

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/pull/12561/files

**Comment by hdhalter** [comment]
@ankitkala - Can you please submit a doc PR for this update? Thanks!
