### ISSUE TITLE
[DOC] Create documentation for OpenSearch Github PR 12607 

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/documentation-website#6675]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
I will add more details once the https://github.com/opensearch-project/OpenSearch/pull/12607 is reviewed and I see consensus on the change.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
HI @ashking94 , what is your ETA for producing the doc PR? To meet entrance criteria, the PR must be open and in review by 4/30. Thanks!

**Comment by ashking94** [comment]
Thanks @hdhalter, let me try to get a PR online by 29th.

**Comment by ashking94** [comment]
@hdhalter  I have raised the PR https://github.com/opensearch-project/documentation-website/pull/7057, need your help on getting it the required reviews.
