### ISSUE TITLE
[DOC] Add docs for split event processor

### ISSUE THREAD

**Issue by srikanthjg** [opensearch-project/documentation-website#6679]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 New processor: [opensearch-project/data-prepper/pull/4166](https://github.com/opensearch-project/data-prepper/pull/4166)
This will be in Data Prepper 2.7

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
PR #5991

**Comment by Naarcha-AWS** [comment]
#6682
