### ISSUE TITLE
[DOC] Update Metrics Framework documentation

### ISSUE THREAD

**Issue by Gaganjuneja** [opensearch-project/documentation-website#6694]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Update the existing doucementation with details about the Gauge metric type.
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

RFC - https://github.com/opensearch-project/OpenSearch/issues/10141#issuecomment-1987093415
Issue - https://github.com/opensearch-project/OpenSearch/issues/12641
PR - https://github.com/opensearch-project/OpenSearch/pull/12642

**Comment by reta** [comment]
@hdhalter fyi, this is scheduled for 2.13.0, thank you

**Comment by hdhalter** [comment]
@Gaganjuneja - Are you submitting a doc PR for this change? If this is going in 2.13, we need it ASAP.
