### ISSUE TITLE
Add documentation for the .NET  client[FEATURE]

### ISSUE THREAD

**Issue by anirudha** [opensearch-project/documentation-website#671]
### Is your feature request related to a problem?
Add documentation for the .NET  client

https://www.nuget.org/profiles/opensearchproject

**Comment by Naarcha-AWS** [comment]
@anirudha: Will the .NET client be compatible with all versions of OpenSearch upon release?

**Comment by Naarcha-AWS** [comment]
Break this up into these issues:

- [ ] High-level OSC installation/getting started  (addressed by this issue)
- [ ] Low-level .NET installation/getting started 
- [ ] OSC Best practices
- [ ] Low-level Best practices
