### ISSUE TITLE
Support redirects for old website links 

### ISSUE THREAD

**Issue by ps48** [opensearch-project/documentation-website#6716]
**Is your feature request related to a problem? Please describe.**
When we add the documentation website link to OpenSearch Dashboards Plugin code, it stays there forever. Later, when website re-structures we have to manually change these links. But, the older versions still point to older link which are redirected to the home page. 

**Describe the solution you'd like**
In OpenSearch 1.2 we added a link to PPL documentation on the website inside the OpenSearch Observability Dashboards plugin. When the website got updated, from https://opensearch.org/docs/latest/observability-plugin/ppl/commands/ to https://opensearch.org/docs/latest/search-plugins/sql/ppl/index/ our old code still pointed towards the older link. 

This is not a good user experience for the users who are using older versions of OpenSearch Dashboards. The older link now just redirects to the home page. Also, the plugin teams should be informed about the link changes if any, so that they can be fixed in the future releases. 

**Describe alternatives you've considered**
If possible not change the website links for older URLs, which are already linked in plugin code. 

**Additional context**

**Comment by hdhalter** [comment]
Thanks, fixing now.
