### ISSUE TITLE
[Documentation] Support ML node role 

### ISSUE THREAD

**Issue by brijos** [opensearch-project/documentation-website#672]
Is your feature request related to a problem?
ML model generally consuming more resources, especially for training process. The community wants to support bigger ML models which might require more resources and special hardware like GPU.

As OpenSearch doesn’t support ML node, we dispatch ML task to data node only. That means if user wants to train a large model, they need to scale up all data nodes which can be costly.

What solution would you like?
Support a dedicated ML node, users don’t need to scale up their data node at all. Instead just configure a new ML node (with different settings, more powerful instance type) and add it to cluster via the YAML file (requires a cluster restart). By doing so, users can separate resource usage better by running ML task on dedicated node which can reduce impact to other critical tasks like search/ingestion.

What alternatives have you considered?
https://github.com/opensearch-project/OpenSearch/issues/2877

Do you have any additional context?
https://github.com/opensearch-project/OpenSearch/issues/2877

Meta Reference - [Meta - Support ML node role](https://github.com/opensearch-project/anomaly-detection/issues/571)

**Comment by Naarcha-AWS** [comment]
Need to figure out if this is still relevant to 2.1.

**Comment by ylwu-amzn** [comment]
> @brijos: Is this issue implying that we might have ML node support by 2.1.0?

Yes, we are going to release this in 2.1.0.
