### ISSUE TITLE
Setting number of shards and replicas in 2.0 needs to be documented

### ISSUE THREAD

**Issue by KnowledgeGarden** [opensearch-project/documentation-website#673]
**Is your feature request related to a problem? Please describe.**
The online documentation for the 1+ version is explicit on ways to configure number of shards and replicas.
The online documentation for the 2.0 version has no such example. Perhaps it is the case that setting those values was moved to some other API, but 

- It's not at all easy to find by using search around the repo
- It's not documented at all online that I can find

**Describe the solution you'd like**
I want to see an example for configuring the client which includes shards and replicas.

**Comment by Naarcha-AWS** [comment]
https://opensearch.org/docs/latest/opensearch/shard-indexing-backpressure/ <---- These should be documented here, feel free to reopen if you feel like more is missing.
