### ISSUE TITLE
[DOC] Auto deploy model when predict request comes

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/documentation-website#6734]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
We will support auto deploy model when predict request comes for remote model in 2.13.
https://github.com/opensearch-project/ml-commons/issues/1148

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Hi @ylwu-amzn , please create a doc PR ASAP if this is going to be merged in 2.13. Thanks.
