### ISSUE TITLE
Backend - Point in Time Search

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#674]
What do you want to do?
Request a change to existing documentation
**Add new documentation**
Report a technical problem with the documentation
Other

**Give a brief description of your request.**
This is a new feature: Point in Time allows users to run different queries against the same fixed data set in time. Point in time only takes data into account up until the moment it is created. Hence, none of the resources that are required to return the data from the initial request are modified or deleted. Segments are retained, even though the segment might already have been merged away and is not needed for the live data set. In short, Point in Time Search allows user to maintain a state which can be re-used by different queries in order to achieve consistent results.

**Which versions are affected?**
2.2 or later

**Which pages or URLs are affected?**
Dashboards

**What resources are available** (for example, links to a related issue, PR, design doc, or feature brief)?
https://github.com/opensearch-project/OpenSearch/issues/1147
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1612

**Who should we contact with technical questions?**
ramaran

**Is there anything else you’d like us to know about your requested change?**

**Comment by kolchfa-aws** [comment]
This issue is to track the backend changes for Point in Time

**Comment by kolchfa-aws** [comment]
Waiting for a testing environment from the developer.

**Comment by bharath-techie** [comment]
As discussed offline, github issue and postman collection will be used for the documentation.

**Comment by dhruv16dhr** [comment]
@kolchfa-aws Please close this issue after closing the PR

**Comment by kolchfa-aws** [comment]
@dhruv16dhr It should be closed automatically when the PR is merged, but I'll make sure. Thanks.
