### ISSUE TITLE
[DOC] Data Prepper geoip processor documentation

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/documentation-website#6765]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Data Prepper is adding a new `geoip` processor. We will need this documented in the documentation site.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

I plan to create a PR on this.

**Comment by vagimeli** [comment]
@dlvenable Can we lean on any of this documentation? https://opensearch.org/docs/2.12/ingest-pipelines/processors/ip2geo/

**Comment by dlvenable** [comment]
> @dlvenable Can we lean on any of this documentation? https://opensearch.org/docs/2.12/ingest-pipelines/processors/ip2geo/

@vagimeli , If we want to take any wording on either the concept of IP-based geolocation, or anything about the MaxMind databases, we could use that.

The configurations, setup, and how it works are completely different however.

I have submitted a PR for this - #6772.
