### ISSUE TITLE
[DOC] Convert ingest processor supports ip type

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/documentation-website#6784]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

In release 2.14.0, the convert ingest processor will support ip type, we need to document that. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/pull/12818

**Comment by hdhalter** [comment]
Hi @gaobinlong , what is your ETA for producing the doc PR? To meet entrance criteria, the PR must be open and in review by 4/30. Thanks!
