### ISSUE TITLE
Documentation for logstash-output-opensearch

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/documentation-website#68]
Repo -> https://github.com/opensearch-project/logstash-output-opensearch. 
We can start with basic configuration as file/beats/http as input, grok as filter and opensearch as output with and without template

**Comment by aetter** [comment]
Hey @VijayanB, is there a built artifact, or do we need to follow the steps here? https://github.com/opensearch-project/logstash-output-opensearch/blob/main/DEVELOPER_GUIDE.md#22-run-in-an-installed-logstash

Install on top of 7.12.1, 7.13.2, or some other version?

@ashwinkumar12345 for visibility.

**Comment by VijayanB** [comment]
@aetter I will upload the artifact and share with you and @ashwinkumar12345 . Will that work?

**Comment by aetter** [comment]
@VijayanB Yep, sounds great. @ashwinkumar12345 has already written a lot of content on getting started with Logstash, so the OpenSearch output should help close the loop on it. https://github.com/opensearch-project/documentation-website/pull/53
