### ISSUE TITLE
[PROPOSAL] Implement automated validations in GitHub Actions

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/documentation-website#681]
### What are you proposing?
Automated content validation for:
* broken links
* missing pictures
* etc

On each Commit and/or Pull Request.

### How did you come up with this proposal?

1. Modify `build.sh` script just to build the website
2. Introduce new script which builds and launches the local web server (as `build.sh` acts now)
3. Create a GitHub Actions (GHA) workflow which will run `build.sh` and validate the output. In case if something goes wrong (e.g. broken links) it fails the build (the GHA). PR with failed GHA couldn't be merged.

Also good to have one more script which installs pre-requisites, like `ruby`, `bundler`, all required gems and so on.

### What is the user experience going to be?
Having docs automatically checked there is a less probability for user to get 404 or broken link.

### Why should it be built? Any reason not to?
It is a kind of autotest.

### What will it take to execute?
Once implemented, validation would be performed automatically on GitHub environment. These checks could be added to git hooks or executed manually as well.

**Comment by hdhalter** [comment]
@kolchfa-aws - Fanit, do you have an open issue for this task?

**Comment by kolchfa-aws** [comment]
@hdhalter I don't have an issue for that but if you create one, you can assign it to me.

**Comment by hdhalter** [comment]
Is it ok if I assign this issue to you? I know that you are implementing additional github actions, but this includes where you wanted to start.

**Comment by kolchfa-aws** [comment]
Sure

**Comment by Yury-Fridlyand** [comment]
I can share my draft I used to validate broken links.

**Comment by kolchfa-aws** [comment]
@Yury-Fridlyand We have the link_checker.rb script in the _plugins directory that we can use to check for broken links. I'll put it in a workflow on a PR/commit. Thank you!

**Comment by kolchfa-aws** [comment]
Link checker is implemented in #3584

**Comment by hdhalter** [comment]
We've added a number of checks to the build script, so I'm closing this issue. If you find any additional issues that you'd us to address, please open another issue. Thanks for your support!
