### ISSUE TITLE
[DOC] Async search missing docs on "index" query parameter

### ISSUE THREAD

**Issue by andrross** [opensearch-project/documentation-website#6812]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The asynchronous search documentation does not detail how to invoke a search against a single index by using the `index` query parameter. See this slack thread: https://opensearch.slack.com/archives/C051D137M7G/p1711633954357529

This relates to all OpenSearch versions.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
 https://opensearch.org/docs/latest/search-plugins/async/index/

**Comment by IanMenendez** [comment]
@andrross will add this
