### ISSUE TITLE
[BUG] Fix docker image name in Pipelines documentation

### ISSUE THREAD

**Issue by jzonthemtn** [opensearch-project/documentation-website#682]
### What is the bug?
The example command to run Data Prepper using docker at the bottom of https://opensearch.org/docs/latest/clients/data-prepper/pipelines/ has the wrong image name.

### How can one reproduce the bug?
Shown: `opensearchproject/opensearch-data-prepper:latest`

### What is the expected behavior?
Should be: `opensearchproject/data-prepper:latest`

**Comment by Naarcha-AWS** [comment]
Thanks @jzonthemtn! Your PR is merged in.
