### ISSUE TITLE
[DOC] On mobile, mention the version in the "This documentation..."

### ISSUE THREAD

**Issue by smacrakis** [opensearch-project/documentation-website#6827]
**What do you want to do?**
 
- [X ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
On mobile, out-of-date pages (e.g., [Trace analytics](https://opensearch.org/docs/1.2/observability-plugin/trace/index/)) display the "This version of the OS doc is no longer maintained" message, but the actual version number is not shown by default (although you can display it by clicking on the Documentation panel at the top).

I'd recommend that that message include the version number (and maybe even the release date), something like this:

- This documentation is for version 2.10 (9/2023). For current information, see the [2.12 documentation](https://opensearch.org/docs/latest/observing-your-data/trace/index/)....

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Hi Stavros, since there is a way to get the version number (clicking the Documentation link at the top), I don't see this as an issue. But let me check to see if there is an easy way to pull in the version, for example, by adding a variable.

**Comment by hdhalter** [comment]
@AMoo-Miki - Do you have any thoughts on this? Would it be straight forward to add a variable here? 

https://github.com/opensearch-project/documentation-website/blob/9a6bb8a426bb0b1f9f4596e3235e4682ed11bc5f/_layouts/default.html#L170. 

Thanks!

**Comment by AMoo-Miki** [comment]
Showing the `latest` version will not be easy at all but we could at least show the current version that the user is viewing:
```
This version of the OpenSearch documentation, {{site.opensearch_major_minor_version}}, is no longer maintained ...
```

This will show:
```
This version of the OpenSearch documentation, 2.13, is no longer maintained ...
```

**Comment by smacrakis** [comment]
Nice improvement!

**Comment by hdhalter** [comment]
Awesome, thanks for implementing, @kolchfa-aws !
