### ISSUE TITLE
[DOC] Documentation for Azure Managed Identity Support in repository-azure plugin

### ISSUE THREAD

**Issue by chengwushi-netapp** [opensearch-project/documentation-website#6874]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Add documentation for https://github.com/opensearch-project/OpenSearch/pull/12559

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
- PR: https://github.com/opensearch-project/OpenSearch/pull/12559
- Issue: https://github.com/opensearch-project/OpenSearch/issues/12423

**Comment by hdhalter** [comment]
Thanks for submitting an issue for this feature, @chengwushi-netapp ! Can you please submit a [documentation PR](https://github.com/opensearch-project/documentation-website/blob/main/CONTRIBUTING.md)? 

@andrross - Do you know if we will deliver this in an upcoming release?

**Comment by andrross** [comment]
@hdhalter Yes, the PR isn't merged yet but I expect it to be there in 2.14

**Comment by hdhalter** [comment]
Hi @chengwushi-netapp, @andrross , what is your ETA for producing the doc PR? To meet entrance criteria, the PR must be open and in review by 4/30. Thanks!

**Comment by chengwushi-netapp** [comment]
@hdhalter, I just fork this repo to my local, and i did not manage to find dedicated section related to `repository-azure` plugin, I just need to add a small section to document how to configure Managed Identity. Probably need some direction from your regarding where can I include this small section
