### ISSUE TITLE
[DOC] node.search.cache.size is not documented

### ISSUE THREAD

**Issue by drewmiranda-gl** [opensearch-project/documentation-website#6912]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
While searching for documentation related to `node.search.cache.size`, i was unable to find any references to this. I understand this is speicific to searchable snapshots but i'm curious to know how this should be configured, how the value is used, what happens if its too big or too small, etc. Also what types of resrouces does this cache consume/use? RAM? Hard Disk?

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Hi @kotwanikunal, do you have information about this setting and how it is configured and used?

**Comment by kotwanikunal** [comment]
Thanks for flagging this @drewmiranda-gl! I thought we did cover it as a part of [the searchable snapshot documentation.](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot/)

@hdhalter I have raised a PR around this: https://github.com/opensearch-project/documentation-website/pull/6930

Can you please help with the review and backports? Thanks!
