### ISSUE TITLE
[DOC] Concurrent segment search support for composite aggs without scripting

### ISSUE THREAD

**Issue by jed326** [opensearch-project/documentation-website#6929]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 For 2.14 we should update https://opensearch.org/docs/latest/search-plugins/concurrent-segment-search/#limitations to indicate that composite aggs now do support concurrent segment search but only when scripting is not used.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
- https://github.com/opensearch-project/OpenSearch/issues/12331
- https://github.com/opensearch-project/OpenSearch/issues/12947

**Comment by hdhalter** [comment]
Hi @jed326 , what is your ETA for producing the doc PR? To meet entrance criteria, the PR must be open and in review by 4/30. Thanks!
