### ISSUE TITLE
[DOC] Query Insights Exporters

### ISSUE THREAD

**Issue by ansjcy** [opensearch-project/documentation-website#6945]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

We need to add related documentation for the query insights exporters.
 
Related documentations: 
https://opensearch.org/docs/latest/observing-your-data/query-insights/top-n-queries/

Related PRs: 
https://github.com/opensearch-project/OpenSearch/pull/12982

**Comment by hdhalter** [comment]
Thanks, @ansjcy. Is this targeting 2.14?

**Comment by ansjcy** [comment]
Hi @hdhalter ! Sorry I missed your previous comment, this is targeting 2.15.

**Comment by ansjcy** [comment]
Combined document for exporter and CPU/Memory metrics enhancements: https://github.com/opensearch-project/documentation-website/pull/7326
