### ISSUE TITLE
[DOC] Add documentation for separate Segment Replication rate limiting

### ISSUE THREAD

**Issue by mch2** [opensearch-project/documentation-website#6948]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 With [this](https://github.com/opensearch-project/OpenSearch/pull/12959) PR we will be adding an additional index setting `indices.replication.max_bytes_per_sec` to control the max bytes per second for node-node segment replication.

[This](https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/index-settings/) page should be updated to reflect this new setting.

I am thinking:

> indices.replication.max_bytes_per_sec (String): Limits the total inbound and outbound replication traffic for each node. This applies to segment replication between nodes. Default is tied to the set value of `indices.recovery.max_bytes_per_sec`, which is by default 40mb. If you set the replication traffic value to less than or equal to 0mb, rate limiting will be disabled, which causes replication data to be transferred at the highest possible rate.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks, @mch2 ! I assume we are targeting 2.14?

**Comment by mch2** [comment]
@hdhalter Yup this will be introduced starting 2.14.  Thanks

**Comment by hdhalter** [comment]
Hi @mch2 , what is your ETA for producing the doc PR? To meet entrance criteria, the PR must be open and in review by 4/30. Thanks!

**Comment by mch2** [comment]
> Hi @mch2 , what is your ETA for producing the doc PR? To meet entrance criteria, the PR must be open and in review by 4/30. Thanks!

Will get this up today thanks for the heads up!
