### ISSUE TITLE
[DOC]Rename ingest processor supports overriding target field if exists

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/documentation-website#6949]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
In 2.14.0, we'll add a new parameter `override_target` for the existing rename ingest processor, we need to document the change.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/pull/12990

**Comment by hdhalter** [comment]
@gaobinlong , @vagimeli - I don't see the override_target parameter in the https://github.com/opensearch-project/documentation-website/pull/6951 PR. Can you please attach the PR that fixes this issue? Thanks!

**Comment by gaobinlong** [comment]
> @gaobinlong , @vagimeli - I don't see the override_target parameter in the #6951 PR. Can you please attach the PR that fixes this issue? Thanks!

I'll open another PR to add the `override_target` parameter after the PR #6951 is merged, because I think the PR #6951 needs to backport to other old versions, but the parameter `override_target` is only available in 2.14.0.

**Comment by hdhalter** [comment]
Thanks, @gaobinlong. Let's go ahead and merge 6951, then.

**Comment by vagimeli** [comment]
@hdhalter @gaobinlong #6951 has been merged for about a week. We'll have to open another PR for the parameter.
