### ISSUE TITLE
[DOC] Add rename ingest processor

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/documentation-website#6950]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Now we don't have documentation for the existing rename ingest processor, we need to add it for all versions of OpenSearch.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Since this is complete for 2.14 and ready to merge, I'm closing this issue.

**Comment by hdhalter** [comment]
I tagged this as 2.14, since the PR was tagged as 2.14.
