### ISSUE TITLE
[DOC] New cluster setting related to aggregation query

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/documentation-website#6957]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
I am adding a new cluster setting `search.max_aggregation_rewrite_filters` to be able to dynamically change the threshold of the rewritten filters number. This is a non-negative integer and 0 means disable this optimization, currently defaults to 24.

We probably should add the document for this new setting here https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/search-settings/

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://github.com/opensearch-project/OpenSearch/pull/13179

**Comment by hdhalter** [comment]
Hi @bowenlan-amzn , what is your ETA for producing the doc PR? To meet entrance criteria, the PR must be open and in review by 4/30. Thanks!

**Comment by bowenlan-amzn** [comment]
@hdhalter I created the PR to add the change #7033
