### ISSUE TITLE
[DOC] Update bundled JDK version (April 2024 Patch releases)

### ISSUE THREAD

**Issue by reta** [opensearch-project/documentation-website#6967]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

@hdhalter it is on me, scheduled for `2.14.0`, thank you!

**Comment by hdhalter** [comment]
Hi @reta , what is your ETA for producing the doc PR? To meet entrance criteria, the PR must be open and in review by 4/30. Thanks!

**Comment by reta** [comment]
> Hi @reta , what is your ETA for producing the doc PR?

I will try to make it within next 2 days, thanks @hdhalter
