### ISSUE TITLE
[DOC][BUG] Default Index Merge Policy is Not Customizable for Cluster Level Settings  

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/documentation-website#6969]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The current [documentation](https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/index-settings/#cluster-level-index-settings) informs users that they can switch OpenSearch merge policies by overriding the cluster-level settings. However, after confirming with @jainankitk, @rishabhmaurya, and @ansjcy  merge policies can only be changed on an index-level basis. 

The following section of the documentation is misleading and should be removed. When users follow the documentation and attempt to update the `default_index_merge_policy`, they encounter a validation error:
```
indices.time_series_index.default_index_merge_policy (String): This setting allows you to specify the default merge policy for time-series indexes, particularly for those with an @timestamp field, such as data streams. The two available options are tiered (default) and log_byte_size. Using log_byte_size for time-series indexes is recommended for enhancing the performance of range queries with the @timestamp field. To override the merge policy on a per-index basis, you can use the index.merge.policy index setting.
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
How to recreate error:
1. Setup an opensource OpenSearch cluster. Ensure that you can curl against it.
2. Run this command against your cluster endpoint. A validation error is encountered.
```
curl -XPUT '<cluster_endpoint>/_cluster/settings' -H 'Content-Type: application/json' -d '{
  "indices" : {
    "time_series_index.default_index_merge_policy": "log_byte_size"
  }
}'
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: no settings to update;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: no settings to update;"},"status":400}
```

**Comment by jainankitk** [comment]
Thanks @IanHoang for filing this issue. We should move the cluster setting to static section from dynamic.

**Comment by hdhalter** [comment]
Thanks for filing the issue. Do you want to remove the cluster setting or move it? We don't have a section for static cluster-level settings, but can create one. If easier to do than explain, please update here: https://github.com/opensearch-project/documentation-website/edit/main/_install-and-configure/configuring-opensearch/index-settings.md. Thanks!

**Comment by IanHoang** [comment]
Synced up with Heather and we can just remove it since it's already in the static section
