### ISSUE TITLE
[DOC] add query_by_tokens option in Neural Sparse Search

### ISSUE THREAD

**Issue by zhichao-aws** [opensearch-project/documentation-website#7027]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 In 2.14 we'll add query by tokens option to Neural Sparse Search. We want to modify docs of Neural Sparse part to inform this change. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/neural-search/issues/608
https://github.com/opensearch-project/neural-search/pull/693

**Comment by hdhalter** [comment]
Thanks for creating the issue, @zhichao-aws ! What is the ETA for the doc PR? We need to have it open and in review by 4/30 to meet entrance criteria for 2.14. Thanks.

**Comment by zhichao-aws** [comment]
> Thanks for creating the issue, @zhichao-aws ! What is the ETA for the doc PR? We need to have it open and in review by 4/30 to meet entrance criteria for 2.14. Thanks.

Hi @hdhalter, I'll cut the doc PR and finish its content by 4/29

**Comment by zhichao-aws** [comment]
PR created. https://github.com/opensearch-project/documentation-website/pull/7040
