### ISSUE TITLE
[DOC] Add documentation for model interface

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/documentation-website#7060]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

To make it easier for user to learn what's the ml-commons model interface and other components to check model interface easily, we will support specifying model interface (input/output parameter list and type) when create model. Read this Github issue for more details https://github.com/opensearch-project/ml-commons/issues/2354

PR : https://github.com/opensearch-project/ml-commons/pull/2357

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks, @ylwu-amzn! I can't assign @b4sjoo directly, so added you as the assignee.
