### ISSUE TITLE
[DOC] Add documentation for index.use_compound_file setting

### ISSUE THREAD

**Issue by andrross** [opensearch-project/documentation-website#7088]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Add documentation for new [`index.use_compound_file`](https://github.com/opensearch-project/OpenSearch/blob/14cd0e33ebfe6c84fcb09687c060e5a0f047c0a7/server/src/main/java/org/opensearch/index/engine/EngineConfig.java#L239-L243) setting.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/pull/13478

**Comment by andrross** [comment]
@samuel-oci Do you might putting together a quick PR for documentation for this new setting?

**Comment by samuel-oci** [comment]
> @samuel-oci Do you might putting together a quick PR for documentation for this new setting?

@andrross sure thing, any chance there is an example you can send my way?

**Comment by andrross** [comment]
@samuel-oci I think it would go here: https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/index-settings/#static-index-level-index-settings ([source](https://github.com/opensearch-project/documentation-website/blob/main/_install-and-configure/configuring-opensearch/index-settings.md))

**Comment by samuel-oci** [comment]
@andrross created a PR https://github.com/opensearch-project/documentation-website/pull/7092

**Comment by hdhalter** [comment]
Thanks, @samuel-oci and @andrross . Is this a 2.14 feature?

**Comment by andrross** [comment]
@hdhalter This will go in the 2.15 release.
