### ISSUE TITLE
[DOC] Port Documentation wrong (9250 for CCS)

### ISSUE THREAD

**Issue by HenryTheSir** [opensearch-project/documentation-website#7100]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 https://opensearch.org/docs/latest/install-and-configure/install-opensearch/index/#network-requirements
 
 Lists 9250 as required Port for Cross Cluster Search. IMHO CCS uses 9300. 

I think the error comes from this doc: https://opensearch.org/docs/1.1/security-plugin/access-control/cross-cluster-search/ 

There 9250 got listed but gets mapped internally to 9300. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
I believe you are right, @HenryTheSir. Do you want to create a PR that updates the doc?

**Comment by HenryTheSir** [comment]
Hi, 

I linked a PR which removes 9250 and adds CCS to 9300. 

best regards

**Comment by ankitkala** [comment]
9250 port in network requirement is defintinely wrong. Thanks for fixing this. 

Just wanted to clarify, In the cross cluster search documentation, the 9250 port is mapped to 9200 port of 2nd node(i.e. `opensearch-ccs-node2`). Not really related to cross cluster search as such.

**Comment by hdhalter** [comment]
> 9250 port in network requirement is defintinely wrong. Thanks for fixing this.
> 
> Just wanted to clarify, In the cross cluster search documentation, the 9250 port is mapped to 9200 port of 2nd node(i.e. `opensearch-ccs-node2`). Not really related to cross cluster search as such.

@ankitkala - Are the port numbers [here](https://opensearch.org/docs/latest/search-plugins/cross-cluster-search/) correct?

**Comment by ankitkala** [comment]
> > 9250 port in network requirement is defintinely wrong. Thanks for fixing this.
> > Just wanted to clarify, In the cross cluster search documentation, the 9250 port is mapped to 9200 port of 2nd node(i.e. `opensearch-ccs-node2`). Not really related to cross cluster search as such.
> 
> @ankitkala - Are the port numbers [here](https://opensearch.org/docs/latest/search-plugins/cross-cluster-search/) correct?

The port numbers are correct as per the include sample docker configuration.
