### ISSUE TITLE
[DOC] add index.search.default_pipeline setting

### ISSUE THREAD

**Issue by IanMenendez** [opensearch-project/documentation-website#7102]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 
Information about `index.search.default_pipeline` is missing under [index settings docs](https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/index-settings/#dynamic-index-level-index-settings)

**Comment by hdhalter** [comment]
Thanks, @IanMenendez !
