### ISSUE TITLE
[DOC] Add a step to set the initial password in the installation quickstart

### ISSUE THREAD

**Issue by vladislav-sharapov** [opensearch-project/documentation-website#7118]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

The [installation quickstart](https://opensearch.org/docs/latest/getting-started/quickstart/) page doesn't mention that you have to set a password in the `OPENSEARCH_INITIAL_ADMIN_PASSWORD` variable. For example, there may be an additional step to add this variable to the shell environment using `export` (not sure if it's worth specifying password requirements). This would also help running `curl` later.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks, @vladislav-sharapov ! Do you want to create the PR for this update?

**Comment by vladislav-sharapov** [comment]
@hdhalter, yes, but I have a question.

The installation using docker page already [contains](https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/#setting-a-custom-admin-password) this information. These pages have some overlap in content so I'm not sure if just copying would be appropriate. What do you think is the best way to update the installation quickstart page?

**Comment by hdhalter** [comment]
> @hdhalter, yes, but I have a question.
> 
> The installation using docker page already [contains](https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/#setting-a-custom-admin-password) this information. These pages have some overlap in content so I'm not sure if just copying would be appropriate. What do you think is the best way to update the installation quickstart page?

Yes, the less redundant information, the better! I think we should point to the other section from the Quickstart.

**Comment by hdhalter** [comment]
Thanks so much, @vladislav-sharapov !
