### ISSUE TITLE
[DOC] Add documentation for remote store migration support

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/documentation-website#7120]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation : [Meta Issue](https://github.com/opensearch-project/OpenSearch/issues/12718) [RFC](https://github.com/opensearch-project/OpenSearch/issues/12246)
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@gbbafna , Is this a 2.14 feature?

**Comment by hdhalter** [comment]
@gbbafna - is there a development Pr or issue to associate with this?

**Comment by gbbafna** [comment]
> @gbbafna - is there a development Pr or issue to associate with this?

Added links in the description. 

>@gbbafna , Is this a 2.14 feature?

Yes, this is an experimental feature in 2.14
