### ISSUE TITLE
[DOC] Configure masking algorithm default 

### ISSUE THREAD

**Issue by terryquigleysas** [opensearch-project/documentation-website#7133]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

I would like to add supporting documentation for https://github.com/opensearch-project/security/issues/4213 . It is for a new configuration option for masked fields. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://github.com/opensearch-project/security/issues/4213
https://github.com/opensearch-project/security/pull/4336
https://github.com/opensearch-project/security/issues/3420

**Comment by hdhalter** [comment]
Thanks, @terryquigleysas !
