### ISSUE TITLE
[Blog] OpenSearch Project Update: A Look at Performance Progress through Version 2.13

### ISSUE THREAD

**Issue by getsaurabh02** [opensearch-project/documentation-website#7143]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [x] Other 

**Tell us about your request.** 
Review and publish new blog, which will be second blog to the Performance blog series which we started in Jan 2024. 
Project website link: https://github.com/opensearch-project/project-website/issues/2859

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Proposed posting date - May 2024

**Comment by kolchfa-aws** [comment]
Closing because the blog has been published https://github.com/opensearch-project/project-website/pull/2951/

**Comment by kolchfa-aws** [comment]
Closing because the blog has been published https://github.com/opensearch-project/project-website/pull/2951
