### ISSUE TITLE
[DOC] add constant keyword field

### ISSUE THREAD

**Issue by IanMenendez** [opensearch-project/documentation-website#7164]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

Add new constant keyword index field type to docs
This field type was added in OS 2.14.0: opensearch-project/OpenSearch#12285

**Comment by hdhalter** [comment]
Thanks, @IanMenendez! Do you want to create the PR?

**Comment by IanMenendez** [comment]
> Thanks, @IanMenendez! Do you want to create the PR?

Hi! Sorry, but I am quite busy these next weeks :(

**Comment by hdhalter** [comment]
@msfroh - Can you please create the doc Pr for this?
