### ISSUE TITLE
[DOC] Ingest processor link to OpenSearch doc home page

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/documentation-website#7185]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Go to this page https://opensearch.org/docs/latest/ingest-pipelines/processors/index-processors/
Click "Convert" from left menu, then it redirect to https://opensearch.org/docs/latest/

![Screenshot 2024-05-16 at 1 32 09 PM](https://github.com/opensearch-project/documentation-website/assets/49084640/a3fe4982-f77a-4ddc-81ec-326fbdb2c9c1)

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@ylwu-amzn - this is a known issue. There is a slight delay in link resolution when a build is running. See https://github.com/opensearch-project/documentation-website/issues/5846
