### ISSUE TITLE
[DOC] Add fingerprint ingest processor

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/documentation-website#7191]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
We'll add a new ingest processor named `fingerprint`, it targets for 2.15.0, we should document the usage.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/pull/13724

**Comment by gaobinlong** [comment]
Please assign this issue to me, I'll add a new documentation for it.

**Comment by vagimeli** [comment]
@gaobinlong Please tag me in the PR and I'll provide writing support.

**Comment by gaobinlong** [comment]
Hi @vagimeli , the code PR is not ready for now, we may not have enough time to complete it before the code freeze date, so could you help to remove the `v2.15.0` label? Thank you!
