### ISSUE TITLE
Document override_main_response_version

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#72]
A cluster setting was introduced in https://github.com/opensearch-project/OpenSearch/pull/847. We removed the distribution in backwards-compatible mode in https://github.com/opensearch-project/OpenSearch/pull/898. Set `compatibility.override_main_response_version` to put the cluster into a configuration that returns 7.10.2 as with ES OSS.

Currently https://docs-beta.opensearch.org/clients/agents-and-ingestion-tools/index/ point to "yes via a cluster setting" which links to https://github.com/opensearch-project/OpenSearch/issues/693, but should be linking to the documentation that explains how to set this setting.

**Comment by aetter** [comment]
@dblock Is `version.number` in `opensearch.yml` still present/required, or is `override_main_response_version` all a user needs to set? Ordinarily I'd test this sort of thing, but https://hub.docker.com/r/opensearchstaging/opensearch/tags.

**Comment by dblock** [comment]
> @dblock Is `version.number` in `opensearch.yml` still present/required, or is `override_main_response_version` all a user needs to set? Ordinarily I'd test this sort of thing, but https://hub.docker.com/r/opensearchstaging/opensearch/tags.

@mch2 can provide all the details as needed

**Comment by mch2** [comment]
@aetter compatibility.override_main_response_version is all a user needs to set.  This can be enabled via opensearch.yml or toggled as a cluster setting:

```
PUT /_cluster/settings
{
  "compatibility" : {
    "override_main_response_version" : true
  }
}
```

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/documentation-website/pull/77
