### ISSUE TITLE
[SAML] SAML document page outdated 

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/documentation-website#721]
### What is the bug?
I followed the sample [steps](https://opensearch.org/docs/latest/security-plugin/configuration/saml/) to run SAML, I cannot login SAML login page with `Log in as admin with a password of admin`

### How can one reproduce the bug?

1. Download and unzip [the example ZIP file](https://opensearch.org/docs/latest/assets/examples/saml-example.zip).
2. At the command line, run docker-compose up.
3. Review the files:
   - docker-compose.yml defines two OpenSearch nodes, an OpenSearch Dashboards server, and a SAML server.
   - custom-opensearch_dashboards.yml add a few SAML settings to the default opensearch_dashboards.yml file.
   - config.yml configures SAML for authentication.
4. Access OpenSearch Dashboards at http://localhost:5601/. Note that OpenSearch Dashboards immediately redirects you to the SAML login page.
5. Log in as admin with a password of admin.  // I cannot login by username admin and password admin

### What is the expected behavior?
I should successfully logging in.

### What is your host/environment?
MacOS

### Do you have any screenshots?
<img width="937" alt="image" src="https://user-images.githubusercontent.com/33105471/175749453-7806a5ec-ff5f-47de-8f76-6f232afb8d50.png">

### Do you have any additional context?
NO

**Comment by cwillum** [comment]
@opensearch-project/security The custom-opensearch-dashboards.yml file contained in the downloaded zip file includes opensearch.username and opensearch.password properties that specify "kibanaserver" values. Is there a connection with the "admin" credentials users are told to use in documentation?

**Comment by peternied** [comment]
@Flyingliuhub Could you post the modifications to your configuration?

I tested the example with no modifications and it worked with `admin:admin` to get access, confirm by logging in and seeing the user information populated through the saml server

![image](https://user-images.githubusercontent.com/2754967/178597337-9ca1181d-a1b7-4d34-acfd-00146d6d2ce9.png)

**Comment by peternied** [comment]
@cwillum The docker images created by OpenSearch contain a [demo scripts](https://github.com/opensearch-project/security/blob/main/tools/install_demo_configuration.sh) installer that copies many default such as [kibanaserver](https://github.com/opensearch-project/security/blob/main/config/internal_users.yml#L27) into the image.  The only connection to the admin credentials as mentioned is that are 'bootstrapped' with the same process by operationally they are unrelated.

**Comment by cwillum** [comment]
@peternied Explanation appreciated. Thank you.

**Comment by Flyingliuhub** [comment]
> @Flyingliuhub Could you post the modifications to your configuration?
> 
> I tested the example with no modifications and it worked with `admin:admin` to get access, confirm by logging in and seeing the user information populated through the saml server
> 

I deployed without modifications. did you successfully login with admin:admin in the following saml redirect from local saml server ?

<img width="801" alt="image" src="https://user-images.githubusercontent.com/33105471/178600914-a2ba0999-0bcc-4c96-8236-9d9085be6df6.png">

**Comment by peternied** [comment]
Yes I did, could you check the log output from any of the docker image to see if there are any errors establishing the connections between the containers?

**Comment by hdhalter** [comment]
@peternied - Is there anything we can do from a documentation standpoint to clarify this, or should I close? Thanks!
