### ISSUE TITLE
[DOC] No documentation present for dynamic templates in Opensearch which is already supported by Opensearch since its inception

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/documentation-website#7212]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [X] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Opensearch has a feature since its Elastic days called as dynamic templates which can be used for updating the behavior in which Opensearch interprets the fields if no mapping is present for that field. But in the documentation, it is no where to be found. My request here is to add the documentation for that.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
This feature is already present, I am attaching some request about the feature I am taking about.

```
PUT movies1
{
  "mappings": {
    "dynamic_templates": [
      {
        "strings": {
          "match_mapping_type": "string",
          "mapping": {
            "type": "text",
            "fields": {
              "keyword": {
                "type":  "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    ]
  }
}
```

**Comment by vagimeli** [comment]
See PR https://github.com/opensearch-project/documentation-website/pull/6933 

SME input needed to move this topic forward
