### ISSUE TITLE
[DOC] [Remote Store] Add documentation for segment upload timeout settings

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/documentation-website#7227]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
- As part of https://github.com/opensearch-project/OpenSearch/pull/13679 we introduced a new setting to configure segments upload timeout for Remote Store. 
- Before this change there was no such setting and segments upload could be stuck forever if there was a bug.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks, will this fix go out with the 2.15 release?

**Comment by linuxpi** [comment]
> Thanks, will this fix go out with the 2.15 release?

Yes, i'll raise the PR by next week

**Comment by hdhalter** [comment]
@linuxpi will raise a PR by end of day 6/6. Thanks!
