### ISSUE TITLE
[DOC] Add documentation for new feature ReIndex Workflow Step in Flow Framework

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/documentation-website#7243]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
We will be enabling easy migration of BM25 index to neual index through a new workflow step called as ReIndex workflow step in Flow Framework. Once https://github.com/opensearch-project/flow-framework/pull/718 is merged, will create a doc PR for the same to add the documentation. 
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/flow-framework/issues/617

**Comment by minalsha** [comment]
@owaiskazi19  lets ensure that documentation clearly outlines guardrails that need to be highlighted for customer. Please work with @navneet1v on the guardrails. Thanks

**Comment by minalsha** [comment]
@hdhalter  what are the next steps here? PR has already been raised by @owaiskazi19  last week. Thanks

**Comment by hdhalter** [comment]
Great! Looks like it has been approved from a technical standpoint, so I pushed it forward to doc review.
