### ISSUE TITLE
[DOC] Missing documentation executing stored scripts in update/bulk operations

### ISSUE THREAD

**Issue by camerondurham** [opensearch-project/documentation-website#7248]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

As an OpenSearch user, I would like to have documentation around how to perform operations using a stored script. The docs cover how to use inline scripts but not how to reference a stored script.

Please let me know if I maybe missed it in documentation, or if this is too much of an "edge-case" to be useful. 

Here's a specific, potentially useful example it would nice to have documentation around:

Example below executes the `conditional` script in a cluster with incoming doc in `params` to conditionally update the doc with `_id=test-1`. I came across this while answering [this amazon-opensearch question](https://stackoverflow.com/questions/77955204/open-search-bulk-update-with-script-and-upsert) and didn't find docs to link to.

```
curl -XPOST "http://localhost:9200/_bulk?_source=true" -H 'Content-Type: application/json' -d'
    {"update":{"_index":"overflow-index","_type":"_doc","_id":"test-1","retry_on_conflict":1}}
    {"script":{"id":"conditional","params":{ "uuid": "test", "status": false, "timestamp": "3994-01-31T23:05:09.909525Z"}}}
'
```

Also, I'm happy PR as long I know where and how documentation owners think this should be updated.

Thanks!

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

- Current bulk documentation for scripts: https://opensearch.org/docs/latest/api-reference/document-apis/bulk/
- Update by query includes how to add a script to your query but now how to reference a stored script: https://opensearch.org/docs/latest/api-reference/document-apis/update-by-query/

**Comment by hdhalter** [comment]
Thanks, @camerondurham, did you look in this section? https://opensearch.org/docs/latest/api-reference/script-apis/create-stored-script/

**Comment by camerondurham** [comment]
Hi @hdhalter ,
Thanks for pointing out that documentation, (https://opensearch.org/docs/latest/api-reference/script-apis/exec-stored-script/#running-a-painless-stored-script-with-parameters). I had missed it earlier.

Would it be helpful to clarify if/when stored scripts can be used in other contexts (bulk, update by query, index, etc.)? Or should developers infer that stored scripts can be referenced wherever scripts are allowed?

Ref: 
- https://github.com/opensearch-project/documentation-website/blob/fe979d5ff87b2246a63ca9817315f52424482e5d/_api-reference/script-apis/exec-stored-script.md?plain=1#L14
- https://github.com/opensearch-project/documentation-website/blob/fe979d5ff87b2246a63ca9817315f52424482e5d/_api-reference/document-apis/bulk.md?plain=1#L131
- https://github.com/opensearch-project/documentation-website/blob/fe979d5ff87b2246a63ca9817315f52424482e5d/_api-reference/document-apis/update-by-query.md?plain=1#L14

I'm okay to close the issue if the current documentation is sufficient.

**Comment by hdhalter** [comment]
@dhwanilpatel - Do you have any thoughts on this?

**Comment by dhwanilpatel** [comment]
While passing script we need to pass either "source" or "id", so it seems we can pass the id for the stored script instead of source.

https://github.com/opensearch-project/OpenSearch/blob/f2ed7d6071145d1e4e98f6e988be9392fdf9939a/server/src/main/java/org/opensearch/script/Script.java#L363-L366

We can include this one liner in our documentation so users wont have to go through the code to understand this.

**Comment by leanneeliatra** [comment]
I'll update this @hdhalter, please assign me.
