### ISSUE TITLE
[DOC] Update documentation for `obfuscate` processor

### ISSUE THREAD

**Issue by Utkarsh-Aga** [opensearch-project/documentation-website#7250]
**What do you want to do?**
Starting Data Prepper 2.8, `single_word_only` option was added to the `obfuscate` processor, but the documentation does not talks about it, thus adding the same to the documentation.
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
[Pull request](https://github.com/opensearch-project/data-prepper/pull/4476) for `single_word_only` option.

**Comment by hdhalter** [comment]
This is closed by https://github.com/opensearch-project/documentation-website/pull/7251.
