### ISSUE TITLE
[DOC] Add documentation on how to use the feature to disable the recovery_source

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/documentation-website#7282]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
I am working on adding a new feature in Opensearch which can be used to disable the `_recovery_source`. As this is a new feature documentation needs to be added. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Github issue: https://github.com/opensearch-project/OpenSearch/issues/13490

**Comment by Naarcha-AWS** [comment]
@navneet1v: Is this for 2.15?

**Comment by navneet1v** [comment]
yes

**Comment by hdhalter** [comment]
@navneet1v will raise a PR by end of day 6/6. Thanks!

**Comment by hdhalter** [comment]
Hi @navneet1v , what is the ETA for the doc PR? Thanks!

**Comment by navneet1v** [comment]
@hdhalter I am trying to figure out where to put the documentation. There is no documentation page for metadata fields just like this:https://www.elastic.co/guide/en/elasticsearch/reference/7.17/mapping-fields.html Please suggest where to put information related to metadata fields.

**Comment by hdhalter** [comment]
Hi @navneet1v, you're right, it doesn't exist yet, but it is in progress: https://github.com/opensearch-project/documentation-website/pull/6933. We may be able to finalize this content before the release so we can add it here, but I'll need to check with the author. @vagimeli - thoughts?
