### ISSUE TITLE
[DOC] Add information regarding Kerberos integration

### ISSUE THREAD

**Issue by spapadop** [opensearch-project/documentation-website#7295]
**What do you want to do?**
 
- [x] Add new documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Currently OpenSearch security plugin supports Kerberos as Authentication backend. However, it is not listed on the relevant section: https://opensearch.org/docs/latest/security/authentication-backends/authc-index/

So, let's add it. Here's an example working config:
```
...
      "authc": {
        "basic_internal_auth_domain": {
          "http_enabled": true,
          "transport_enabled": true,
          "order": 1,
          "http_authenticator": {
            "challenge": false,
            "type": "basic",
            "config": {}
          },
          "authentication_backend": {
            "type": "intern",
            "config": {}
          },
          "description": "Authenticate via HTTP Basic against internal users database"
        },
        "kerberos_auth_domain": {
          "http_enabled": true,
          "transport_enabled": true,
          "order": 2,
          "http_authenticator": {
            "challenge": true,
            "type": "kerberos",
            "config": {
              "krb_debug": false,
              "strip_realm_from_principal": true
            }
          },
          "authentication_backend": {
            "type": "noop",
            "config": {}
          },
          "description": "Authenticate via Kerberos"
        }
...

**Comment by hdhalter** [comment]
Thanks, @spapadop ! Would you like to create the PR? 

Tagging @AntonEliatra , as he wrote a great blog on security concepts, including Kerberos: https://opensearch.org/blog/opensearch-security-concepts/

**Comment by spapadop** [comment]
Gladly yeah, I'll come back asap.

**Comment by hdhalter** [comment]
Hi @spapadop - Just checking in to see if you still want to submit the documentation PR? Thanks.

**Comment by spapadop** [comment]
Hi @hdhalter, apologies for the delay and thanks for the reminder! Yeah, let me work on it and I'll raise a PR soon.

**Comment by spapadop** [comment]
there you go https://github.com/opensearch-project/documentation-website/pull/7844

**Comment by hdhalter** [comment]
Awesome! Please tag me when it is ready for review. Thanks.
