### ISSUE TITLE
[DOC] Update documentation for multiple datasource

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/documentation-website#7301]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 As part of 2.15 release, alerting, security analytics dashboards plugins and feature anywhere now support multi data source, and we want to update the documentation to reflect the new feature.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@BionIT will raise a doc PR end of day tomorrow, 6/7. Thanks, @BionIT!
