### ISSUE TITLE
[FEATURE] add missing documentation for batch mode documentation of opensearch-plugin install

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#731]
### Is your feature request related to a problem?
`opensearch-plugin install` has a `--batch` / `-b` parameter which is currently undocumented.

### What solution would you like?
the parameter must be documented.

### What alternatives have you considered?
as it already existed in ES 7.10.2 their documentation can be used as a reference for now...

### Do you have any additional context?
see the ES documentation on this: https://www.elastic.co/guide/en/elasticsearch/plugins/7.10/_other_command_line_parameters.html#_batch_mode

for further details please check with whoever owns the implementation (fun-fact: with a brief search on GitHub i couldn't find the actual code for this...)

**Comment by lukas-vlcek** [comment]
@rursprung One note, even if this feature has been documented in Elasticsearch prior to license change the documentation for OpenSearch needs to be a brand new writing.
