### ISSUE TITLE
[DOC] Feedback on security docs

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#7367]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Community feedback on these access control topics:
- [x] 20240131 | /docs/latest/security/access-control/index/ | The description of Backend role is not helpful. "Arbitrary strings" is not helpful. Saying that it comes from an an external authentication system doesn't say what it is, just where it comes from. omes from an an external authentication system doesn't say what it is, just where it comes from. Fixed by https://github.com/opensearch-project/documentation-website/pull/7378/.
- [x] 20240215 | /docs/2.9/security/access-control/default-action-groups/ | This page should explicitly say which actions are included in which action group. This is unhelpful for users trying to build custom roles because the actions are not listed. Already addressed in [6405](https://github.com/opensearch-project/documentation-website/pull/6405). See https://opensearch.org/docs/latest/security/access-control/default-action-groups/. 
- [x] 20240522 | /docs/latest/security/authentication-backends/jwt/ | it is unclear, this page should describe jwt_auth_domain, but in JWKS section the example says openid_auth_domain. Here is the link and section: https://opensearch.org/docs/latest/security/authentication-backends/jwt/#using-a-jwks-endpoint-to-validate-a-jwt. Addressed by https://github.com/opensearch-project/documentation-website/pull/7398.

 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by leanneeliatra** [comment]
@hdhalter can you assign me please.

**Comment by leanneeliatra** [comment]
I have submitted the PR for 20240131 https://github.com/opensearch-project/documentation-website/pull/7378/files cc @hdhalter and @scrawfor99

**Comment by leanneeliatra** [comment]
@hdhalter @natebower In our conversation yesterday in relation to 
`20240215 | /docs/2.9/security/access-control/default-action-groups/ | This page should explicitly say which actions are included in which action group. This is unhelpful for users trying to build custom roles because the actions are not listed.`
[This has been updated in the recent versions of the documentation](https://opensearch.org/docs/latest/security/access-control/default-action-groups/) and therefore, I think point 2 above (20240215) can be closed.

**Comment by leanneeliatra** [comment]
I did indeed thanks @hdhalter

**Comment by leanneeliatra** [comment]
Hi @AntonEliatra, could you guide/give input on 20240522 please?

**Comment by hdhalter** [comment]
All issues have been addressed. Thanks, @leanneeliatra  and @AntonEliatra !
