### ISSUE TITLE
[DOC] Add links to Best Practices for Security and Getting Started in Security

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#7376]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
A 'best practices for security in OpenSearch' was recently added, but it seems a bit hidden. Should we move this up, and/or link to it from other topics, for instance, https://opensearch.org/docs/latest/security/? 

We also have a new 'Getting Started in security' topic that should also be linked to other topics, for instance, https://opensearch.org/docs/latest/security/. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://opensearch.org/docs/latest/security/configuration/best-practices/
https://opensearch.org/docs/latest/getting-started/security/

**Comment by leanneeliatra** [comment]
[PR created.](https://github.com/opensearch-project/documentation-website/pull/7389)
