### ISSUE TITLE
[DOC][Workspace] Add documentation for workspace UX and API

### ISSUE THREAD

**Issue by ruanyl** [opensearch-project/documentation-website#7407]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Hi @ruanyl , is this a feature being implemented in an upcoming release?

**Comment by xluo-aws** [comment]
Please reassign to @SuZhou-Joe

**Comment by vagimeli** [comment]
@SuZhou-Joe Please tag me when the initial draft content is ready for tech writer support and review. Thank you.
