### ISSUE TITLE
[DOC] DataPrepper write_json processor 

### ISSUE THREAD

**Issue by ferngus** [opensearch-project/documentation-website#7457]
**What do you want to do?**
Check documentation for DataPrepper write_json processor
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** There's an issue with the write_json processor page, seems a formatting issue

***Version:** all
 
**What other resources are available?** N/A

**Comment by hdhalter** [comment]
Looks like we are missing the example. @kkondaka - can you please provide an example for the 'target' option?
