### ISSUE TITLE
[FEATURE] Request to add documentation to enable audit logs and compliance configuration using APIs

### ISSUE THREAD

**Issue by jimishs** [opensearch-project/documentation-website#746]
### Is your feature request related to a problem?
Audit logs and compliance configuration requires the user to enable it in Dashboards

### What solution would you like?
Users should be able to use the API to enable the same

### What alternatives have you considered?
There is no alternative 

### Do you have any additional context?
See attached screenshot
<img width="1535" alt="Screen Shot 2022-06-30 at 2 19 12 PM" src="https://user-images.githubusercontent.com/2586454/176798636-de37485c-9495-429d-8fdd-d00ed71be9bf.png">

**Comment by Naarcha-AWS** [comment]
Thanks for the issue @jimishs! I'm assuming the security plugin must be enabled in order to test this properly?

**Comment by cwillum** [comment]
See [#927 ](https://github.com/opensearch-project/documentation-website/pull/927)for in-process PR.

**Comment by cwillum** [comment]
Closing this after merging #927
