### ISSUE TITLE
[Blog] Boosting Hybrid Query Performance in OpenSearch 2.15

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/documentation-website#7479]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [X] Other 

**Tell us about your request.** Provide a summary of the request.
Review and publish new blog for improvements in performance of Hybrid Query that we have done in 2.15.
Project website link: https://github.com/opensearch-project/project-website/issues/3001

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Proposed posting date - End of June - begging of July 2024

**Comment by hdhalter** [comment]
Thanks for the heads-up, @martin-gaievski! We'll give it a review as soon as we get the go-ahead from @pajuric.

**Comment by hdhalter** [comment]
Here is the PR for review: https://github.com/opensearch-project/project-website/pull/3020
