### ISSUE TITLE
Document JDK version

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#75]
OpenSearch requires JDK 11 to build at a minimum per [dev guide](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#jdk-11). It has been building with JDK14 (and will be building with 11 post 1.0 with [this change](https://github.com/opensearch-project/OpenSearch/pull/940)). The combined artifact is packaging JDK 15.0.1. 

- document the above
- potentially document what JDK(s) we testing with, core and plugins

**Comment by aetter** [comment]
Hey @dblock, are you sure about that? My understanding was that we require 11 to *build* at a minimum, but that you can run OpenSearch it with 8 or 11. In general, the build instructions for a particular repo go in the README, and the documentation is more concerned with using and extending the off-the-shelf artifacts. See this PR: https://github.com/opensearch-project/documentation-website/pull/62

**Comment by dblock** [comment]
> Hey @dblock, are you sure about that? My understanding is that we require 11 to _build_ at a minimum, but that you can run OpenSearch it with 8 or 11. In general, the build instructions for a particular repo go in the README, and the documentation is more concerned with using and extending the off-the-shelf artifacts. See this PR: #62

You are correct. I think #62 actually addresses this issue!

**Comment by aetter** [comment]
https://github.com/opensearch-project/documentation-website/pull/62
