### ISSUE TITLE
[DOC-META] Dashboard Documentation

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#751]
What do you want to do?

Make a change to existing documentation
**Add new documentation**
Report a technical problem with the documentation
Other

**Give a brief description of your request.**
We need to build the documentation for OpenSearch Dashboards.

**Which versions are affected?**
We'll start with version 2.0. We should keep an eye on any differences between 2.0 and 1.3. If there are no differences, we can backport to 1.3.

**Which pages or URLs are affected?**
Here is where the dashboard content exists today:
https://opensearch.org/docs/latest/dashboards/index/

**What resources are available (for example, links to a related issue, PR, design doc, or feature brief)?**
The UX team should be able to provide the best insight into how dashboards are used by customers.  
Andrew Hopp - PM

Other:

Here's a suggested TOC for the Dashboards section of the doc:

- [x] #941
- [x] #991
- [x] #992
- [x] #993
- [x] #994
- [x] #995
- [x] #996
- [x] #997

We don't want to go into details about each plugin here. We can refer to the plugins and give a summary of the functionality, but we want to describe specific dashboard functionality with the plugin itself.

**Comment by hdhalter** [comment]
Assign to Melissa once she gets access to Github.

**Comment by vagimeli** [comment]
Content sections being written and published in order of priority and as completed. Priority 1 content status = writing

**Comment by vagimeli** [comment]
Closing meta issue. Topic-specific issues will be opened as needed.
