### ISSUE TITLE
[BUG] Update documentation doesn't mention upserts

### ISSUE THREAD

**Issue by tmccombs** [opensearch-project/documentation-website#755]
### What is the bug?
The documentation at https://opensearch.org/docs/2.0/opensearch/rest-api/document-apis/update-document/ doesn't mention the upsert functionality, or using `doc_as_upsert`.

the `upsert` option is mentioned on https://opensearch.org/docs/1.1/opensearch/index-data/, but I can't find any reference to `doc_as_upsert`. Although, if it is compatible with elasticsearch 7.10 it should support that (and I do see references to it in the opensearch source code). 

### How can one reproduce the bug?
Visit the page mentioned above

### What is the expected behavior?
The documentation should discuss upserts.

### What is your host/environment?
N/A

### Do you have any screenshots?
No

### Do you have any additional context?
No

**Comment by cwillum** [comment]
PR to fix this is [#934](https://github.com/opensearch-project/documentation-website/pull/934).
