### ISSUE TITLE
[FEATURE] Document custom folders

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#756]
### Is your feature request related to a problem?

Document changes in https://github.com/opensearch-project/OpenSearch/pull/848

**Comment by JeffH-AWS** [comment]
Taking a look at this.

**Comment by JeffH-AWS** [comment]
Seeking feedback on where this would live and how it should be covered. Based on my understanding of the related PR (from the core product) this sounds like guidance for plugin developers rather than OpenSearch users. Bearing that in mind I'm not quite sure where this would go.

**Comment by JeffH-AWS** [comment]
@dblock

**Comment by dblock** [comment]
@VachaShah see @JeffH-AWS's questions above

**Comment by VachaShah** [comment]
I think the documentation was added in this commit https://github.com/opensearch-project/opensearch-plugins/commit/d0c019c9f65c3bc0740e0c77179c349947a810ef, the file has changed over time. 

I think this would go in a place where we have user documentation for plugins in general - https://opensearch.org/docs/latest/opensearch/install/plugins/. This looks to be a nice place to add documentation for building custom plugins or modify the plugin-descriptor file to add custom folder name and then install/remove using the custom folder name.

**Comment by JeffH-AWS** [comment]
@VachaShah can you please link me to the design doc for this? How does an OpenSearch user interact with this setting?

**Comment by JeffH-AWS** [comment]
Putting this ticket on the backlog again pending follow-up from someone familiar with the functionality.

**Comment by JeffH-AWS** [comment]
Reached out to Vacha again.

**Comment by JeffH-AWS** [comment]
I still have not gotten any engagement from Vacha.

Based on re-reviewing the content in the [linked commit](https://github.com/opensearch-project/opensearch-plugins/commit/d0c019c9f65c3bc0740e0c77179c349947a810ef),  this does not seem to belong in the OpenSearch user documentation.  These steps seem to be pretty clearly aimed at developers who are customizing or altogether building plugins.  The references to changes include Java classes which are not relevant to the operation or use of OpenSearch.

If I'm misunderstanding something please feel free to raise a new issue.  At a bare minimum, the issue should include:

- A description of the feature - what does it do?
- Relevancy - why would someone use it?
- Who is the target audience?
- Usage details - how would someone use it?
- Notes including detailed steps on how to enable the feature and verify that it is working as expected
