### ISSUE TITLE
[DOC] Profile API page seems to be no longer present

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/documentation-website#7602]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
Profile API appears in the API reference dropdown, but when clicked on, it returns to root docs page. https://opensearch.org/docs/latest/api-reference/profile/

![image](https://github.com/opensearch-project/documentation-website/assets/19438237/0af0766a-58b6-4ef0-a567-8852ce698ab4)

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 
Not sure. Seems to be working for 1.3: https://opensearch.org/docs/1.3/api-reference/profile/

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks, @jmazanec15. Can you please try again? This is a known issue with our system where links are not resolving properly when publishing content, which happens frequently throughout the day. We are looking into a fix.

**Comment by Naarcha-AWS** [comment]
@jmazanec15: If you want more information on what we're considering to fix this issue, see https://github.com/opensearch-project/documentation-website/issues/5846

**Comment by jmazanec15** [comment]
Oh interesting. It works now. Must be same issue. Thanks
