### ISSUE TITLE
[DOC] What is a "multi-data query"?

### ISSUE THREAD

**Issue by smacrakis** [opensearch-project/documentation-website#7608]
**What do you want to do?**
 
- [ x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.

https://opensearch.org/docs/latest/search-plugins/sql/ppl/index/
What is a "multi-data query"? This is not standard industry terminology, and it is only mentioned on this page in our docs.

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.

The term first showed up in the 2.7 version of the doc and is still there in 2.15.
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks, @smacrakis. I'm not sure what was meant here. In any event, I defer to you as an expert on PPL. Please review this PR and comment, as appropriate. Thanks! https://github.com/opensearch-project/documentation-website/pull/7637
