### ISSUE TITLE
[DOC] _cat/nodes local parameter is deprecated

### ISSUE THREAD

**Issue by landon-lengyel** [opensearch-project/documentation-website#7625]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
When using the API endpoint `_cat/nodes?local=true` the node returns: `Deprecated parameter [local] used. This parameter does not cause this API to act locally, and should not be used. It will be unsupported in version 8.0.`

This command should be removed from the documentation. I will be submitting a PR for this.

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
7.10.2 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Make a GET request to this API endpoint:  `_cat/nodes?local=true`

> Note: It seems to only respond this way the first time. Subsequent requests do not have that alert, however sending the request to a new node will produce the alert again.

**Comment by shreedaddy** [comment]
> **What do you want to do?**
> 
> * [ ]  Request a change to existing documentation
> * [ ]  Add new documentation
> * [x]  Report a technical problem with the documentation
> * [ ]  Other
> 
> **Tell us about your request.** Provide a summary of the request. When using the API endpoint `_cat/nodes?local=true` the node returns: `Deprecated parameter [local] used. This parameter does not cause this API to act locally, and should not be used. It will be unsupported in version 8.0.`
> 
> This command should be removed from the documentation. I will be submitting a PR for this.
> 
> ***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all. 7.10.2
> 
> **What other resources are available?** Provide links to related issues, POCs, steps for testing, etc. Make a GET request to this API endpoint: `_cat/nodes?local=true`
> 
> > Note: It seems to only respond this way the first time. Subsequent requests do not have that alert, however sending the request to a new node will produce the alert again.

Please let me know if this issue has been resolved. If not can I pick this up. Just got started on OpenSearch couple of days ago. Was able to complete setup on my Windows 11. Thought of checking out the documentation to get started as contributor as this might be better place and then move on to OpenSearch product.
