### ISSUE TITLE
[DOC] Document create or update alias API

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/documentation-website#7640]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.

We need to document the usage of the create or update alias API.

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.

All version
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
Also relates to #3790
