### ISSUE TITLE
[DOC] knn.advanced.filtered_exact_search_threshold is mentioned as a cluster settings but it's not

### ISSUE THREAD

**Issue by Rmaan** [opensearch-project/documentation-website#7642]
[This page](https://opensearch.org/docs/2.15/search-plugins/knn/settings/) lists `knn.advanced.filtered_exact_search_threshold` as a cluster setting. But if you try to apply it, you will get an error:
```
persistent setting [knn.advanced.filtered_exact_search_threshold], not recognized
```
After a some trial and error I dug [into code](https://github.com/opensearch-project/k-NN/blob/5139b163bc4a36aef7c99ce53d5e8b14c43eb768/src/main/java/org/opensearch/knn/index/KNNSettings.java#L81) and found it's actually an index level settings. The table need to be updated into 2 separated parts, or at least prefix index ones with `index.`.

**Comment by hdhalter** [comment]
Thanks, @Rmaan ! @kolchfa-aws , can you please look into this? Thanks.
