### ISSUE TITLE
Update Feature Anywhere documentation to explicitly call out what types of anomaly results are supported

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/documentation-website#7647]
Currently, only real-time, single-entity results are supported and visible on OSD Visualizations for linked detectors. [This documentation](https://opensearch.org/docs/latest/observing-your-data/ad/dashboards-anomaly-detection/) should be updated to explicitly call that out.

Depending on when [this proposed enhancement in AD to support historical results](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/803) is completed, this will need to be updated once more.

**Comment by hdhalter** [comment]
Thanks, @ohltyler. Can you help updating with the appropriate documentation?  https://github.com/opensearch-project/documentation-website/edit/main/_observing-your-data/ad/dashboards-anomaly-detection.md

**Comment by ohltyler** [comment]
> Thanks, @ohltyler. Can you help updating with the appropriate documentation? https://github.com/opensearch-project/documentation-website/edit/main/_observing-your-data/ad/dashboards-anomaly-detection.md

updated in #7663 :)
