### ISSUE TITLE
[DOC] Flow Framework Deprovision API allow_delete parameter

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/documentation-website#7648]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 

 - https://github.com/opensearch-project/flow-framework/pull/763

During development, also noted the lack of documentation for Delete Search Pipeline API.

***Version:***

 2.16.0
 
**What other resources are available?** 

 - https://github.com/opensearch-project/flow-framework/issues/579
 - https://github.com/opensearch-project/flow-framework/issues/748

Have already opened documentation PR
 - https://github.com/opensearch-project/documentation-website/pull/7639

**Comment by hdhalter** [comment]
Thanks, @dbwiddis !
