### ISSUE TITLE
[DOC] Faiss Byte Vector

### ISSUE THREAD

**Issue by naveentatikonda** [opensearch-project/documentation-website#7661]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
For lucene engine we have [Lucene byte vector feature](https://opensearch.org/docs/latest/field-types/supported-field-types/knn-vector#lucene-byte-vector), which accepts byte vectors in the range [-128 to 127] providing memory savings upto 75% when compared with fp32 vectors. But, for large scale workloads we usually prefer to use faiss engine and as of today Faiss only supports fp32 and fp16 vectors(using SQfp16). So, adding byte vector support to faiss engine helps to reduce memory requirements especially for those users who are using LLM like [Cohere Embed](https://cohere.com/blog/int8-binary-embeddings) that generates signed int8 embeddings ranging from [-128 to 127].

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 2.16

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/k-NN/issues/1659

**Comment by naveentatikonda** [comment]
Please add 2.16 label. Thanks!

**Comment by naveentatikonda** [comment]
Please change the label to 2.17. Thanks!

**Comment by hdhalter** [comment]
> Please change the label to 2.17. Thanks!

Done. Thanks!
