### ISSUE TITLE
Document which OpenSearch versions are a drop-in replacement for which ElasticSearch versions

### ISSUE THREAD

**Issue by tuxayo** [opensearch-project/documentation-website#767]
### Is your feature request related to a problem? Please describe

To illustrate, I contribute to an application where some of our choices break compatibility with ES 6 (EOL) to get compatibility with ES 8.
And we need to know if OpenSearch 2 is a drop-in replacement for ES 8 or ES 7 because that *might* mean (maybe OpenSearch is more flexible on some things) that the same choice must be made to support OpenSearch 2 than ES 8.

### Describe the solution you'd like

For the above example and to generally ease migration and support for both search engines, it would be good to have documented a correspondence between ES and OpenSearch versions. That is if I have an application that runs on ES 7 only, is it expected to work on OpenSearch 1.x ? What about OpenSearch 2.x ? Same question with an application that runs on ES 8 only.

I haven't found such info for now, maybe I missed it?

**Comment by lizsnyder** [comment]
This is not something that we should be doing. When we forked Elasticsearch and created OpenSearch, we effectively disassociated from that product and became our own product with our own feature development timelines and milestones. We do not want to give the impression that we're trying to imitate any of the features or functionality that Elastic is building on ES, even if some of our own solutions/plugins happen to resemble theirs.

These folders have all of the relevant release notes that might not be on the version history page of the documentation (https://opensearch.org/docs/latest/version-history/), so users can check compatibility here:

https://github.com/opensearch-project/opensearch-build/tree/main/release-notes
https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/main/release-notes

**Comment by tuxayo** [comment]
Thanks for the answer. So if I understand correctly, OpenSearch isn't mean to stay a drop-in replacement. (1.x was for ES 7.x I suppose) Now it's living it's own life.

**Comment by lizsnyder** [comment]
@tuxayo that's correct. OpenSearch 1.0 is a fork of 7.10, but we did add some new features/functionality: https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-1.0.0.md

From there the projects diverged.
