### ISSUE TITLE
[DOC] Sorting and Search After in Hybrid Search

### ISSUE THREAD

**Issue by vibrantvarun** [opensearch-project/documentation-website#7670]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 
For Hybrid Query we have enabled the support for two features i.e sorting the hybrid query results and a customer can paginate the sort results by using `search_after` clause. 

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
2.15
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
[https://github.com/opensearch-project/neural-search/issues/507](https://github.com/opensearch-project/neural-search/issues/507)

**Comment by hdhalter** [comment]
@vibrantvarun , do you have an ETA for this PR? Thanks!

**Comment by vibrantvarun** [comment]
Yes I am working on the PR. It will be out soon.

**Comment by hdhalter** [comment]
Thanks, @vibrantvarun !
