### ISSUE TITLE
Dead links in https://opensearch.org/docs/latest/query-dsl/ [DOC]

### ISSUE THREAD

**Issue by smacrakis** [opensearch-project/documentation-website#7683]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [X ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.

On page https://opensearch.org/docs/latest/query-dsl/, several links are dead and end up redirected to the top level doc node:
* Geographic and xy queries (https://opensearch.org/docs/latest/opensearch/query-dsl/geo-and-xy/index/)
* Span queries (https://opensearch.org/docs/latest/opensearch/query-dsl/span-query/)

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 
2.15

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
This is a known issue with link resolution that we are working on resolving. Please try again.
