### ISSUE TITLE
[DOC] The split ingest processor documentation has format issue

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/documentation-website#7694]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
<img width="988" alt="image" src="https://github.com/user-attachments/assets/643440cc-aa88-4b2c-b82e-20a643ab8de8">

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
All versions
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks for fixing this, @gaobinlong!
