### ISSUE TITLE
[DOC] Security Analytics - Need documentation for Threat Intel Analytics platform in the Security Analytics plugin

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/documentation-website#7714]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
We are adding threat intel analytics platform as part of the security anayltics plugin. We require documentaiton of the features and APIs
***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 2.16 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://github.com/opensearch-project/security-analytics/issues/1117

**Comment by hdhalter** [comment]
@eirsep - Can you please give me an ETA for this PR? Thanks!

**Comment by hdhalter** [comment]
@eirsep will work on this starting Wednesday.
