### ISSUE TITLE
[DOC]There are two fields named "source" in reindex request body

### ISSUE THREAD

**Issue by ddoudle** [opensearch-project/documentation-website#7746]
**What do you want to do?**
 
- [✅ ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
There are two fields named "source" in reindex request body: https://opensearch.org/docs/latest/api-reference/document-apis/reindex/#request-body
![image](https://github.com/user-attachments/assets/b0a2118d-e374-44ff-81f4-bf77618b02c0)

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 N/A
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
N/A

**Comment by hdhalter** [comment]
Thanks, @ddoudle !
