### ISSUE TITLE
[DOC] Update documentation for create / update repository api 

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/documentation-website#7749]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
This is for updating the existing documentation corresponding to https://github.com/opensearch-project/OpenSearch/pull/14790. 

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
This will apply to 2.16 if the PR gets merged and backported before 2.16 code freeze.
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@ashking94 - Do you know who is creating this PR?

**Comment by ashking94** [comment]
> @ashking94 - Do you know who is creating this PR?

Let me attempt making this change.

**Comment by hdhalter** [comment]
Hi @ashking94 - What is the ETA for this PR? Thanks!

**Comment by ashking94** [comment]
> Hi @ashking94 - What is the ETA for this PR? Thanks!

Raised the PR -> https://github.com/opensearch-project/documentation-website/pull/7851
