### ISSUE TITLE
[DOC] Automated model interface generation on aws llms

### ISSUE THREAD

**Issue by b4sjoo** [opensearch-project/documentation-website#7793]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
We will enable automated model interface generation on AWS managed llms (Bedrock models, Comprehend APIs, Textract APIs)

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
2.16
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Connector we support: 
All blueprints with Amazon or Bedrock prefix in docs folder will have this feature:
https://github.com/opensearch-project/ml-commons/tree/main/docs/remote_inference_blueprints

**Comment by hdhalter** [comment]
@b4sjoo - Will you be producing the doc PR?

**Comment by b4sjoo** [comment]
@hdhalter Added!

**Comment by hdhalter** [comment]
> @hdhalter Added!

Let me know if it needs a tech review or if it's ready for a doc review. Thanks!

**Comment by b4sjoo** [comment]
@hdhalter I think it's ok to go for a doc review now
