### ISSUE TITLE
[DOC] Query categorization for query insights plugin

### ISSUE THREAD

**Issue by deshsidd** [opensearch-project/documentation-website#7798]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
Recently moved a feature called query categorization from core to query-insights plugin. This feature is not documented yet and we need to add some documentation. This feature essentially adds instrumentation on the search path to keep track of the count of requests per query type, aggregation type and the latency and resource usage per query type, aggregation type.

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by deshsidd** [comment]
This will be required for 2..16

**Comment by hdhalter** [comment]
@deshsidd - Are you providing the documentation for this?

**Comment by deshsidd** [comment]
Yes, will provide the documentation for this unless you can take this up? Can provide any details required

**Comment by hdhalter** [comment]
No, we need you to create the draft since you have all the details. Once it's technically correct, my team will take over to review it and get it merged. What is the ETA?
