### ISSUE TITLE
[DOC] Integrate new Action Type of Batch Transform in Connectors and support CRUD transform jobs in Ml-Commons Tasks

### ISSUE THREAD

**Issue by b4sjoo** [opensearch-project/documentation-website#7848]
**What do you want to do?**
See https://github.com/opensearch-project/ml-commons/issues/2488 

- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 2.16

**Comment by ylwu-amzn** [comment]
@Zhangxunmt can you prepare draft doc for this ? This is for OS 2.16 release.

**Comment by Zhangxunmt** [comment]
Working out the doc. Will send out the PR soon.

**Comment by Zhangxunmt** [comment]
https://github.com/opensearch-project/documentation-website/pull/7853

**Comment by hdhalter** [comment]
See https://github.com/opensearch-project/documentation-website/pull/7899
