### ISSUE TITLE
[DOC] Documentation for ingest-attachment Plugin

### ISSUE THREAD

**Issue by ldrick** [opensearch-project/documentation-website#7858]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
The "ingest-attachment" Plugin has no documentation, how to use it.

**Version:**
2.15
 
**What other resources are available?**
Unfortunately none, it is just in the List of available Plugins.

**Comment by ldrick** [comment]
Thanks @hdhalter, I could do, once I have worked with it. Right now, I just saw it exists and wanted to discover as soon as my colleagues take the story. So if September is ok (holiday comes first 😄), I can provide a PR than.

**Comment by hdhalter** [comment]
Sounds good! Maybe you could collaborate with @cwperks, as I know he wants to get some of the other plugins documented.

**Comment by ldrick** [comment]
@cwperks I would go on adding it here: https://github.com/opensearch-project/documentation-website/tree/main/_install-and-configure/additional-plugins as I saw you just started at this place to document additional plugins, if that is fine for you

**Comment by cwperks** [comment]
@ldrick Yes that would be the right place. Eventually, I think it would make sense to categorize the plugins by type. i.e. Dropdown for Mapper Plugins, Dropdown for Analysis Plugins, etc, but there isn't enough on the documentation website of these built in plugins to separate them just yet.

**Comment by ldrick** [comment]
Could you please have a short look over this: https://github.com/ldrick/documentation-website/blob/add-documentation-ingest-attachment-plugin/_install-and-configure/additional-plugins/ingest-attachment-plugin.md

I personally didn't play around with all config options for now, but if you want them to be described, I can try to fiddle in some time to try them out. Until now it is the most easy and straight forward path described.
