### ISSUE TITLE
[Security Plugin] The `root_ca` property for Open ID configurations isn't documented 

### ISSUE THREAD

**Issue by zehonghuang** [opensearch-project/documentation-website#786]
https://github.com/opensearch-project/security-dashboards-plugin/blob/5e4004fbb7195f5a5f9f7ded14ea7ea49dadecaa/server/auth/types/openid/openid_auth.ts#L115

I have expended efforts to solve just because `this.config.openid.root_ca` display no in documentnation. 
Using https keycloak-openid maybe occur `OpenId authentication failed: Error: Client request error: unable to get issuer certificate`.

So, Please Update doc !

**Comment by peternied** [comment]
Based on the name and usage, its a path to a root certification authority file, in a `pem` format.  AFAIK it should follow the same usage patterns we have in security around other root CA certificates.  See additional background from https://opensearch.org/docs/latest/dashboards/install/tls/ that looks like it should align with this usage.

**Comment by cwillum** [comment]
If this property is used for certificate validation using OpenID, it's not clear to me how ```root_ca``` would differ from ```pemtrustedcas_filepath``` (described as "Absolute path to the PEM file containing the root CAs of your IdP."). Should ```root_ca``` specify a different path?

**Comment by zehonghuang** [comment]
> If this property is used for certificate validation using OpenID, it's not clear to me how `root_ca` would differ from `pemtrustedcas_filepath` (described as "Absolute path to the PEM file containing the root CAs of your IdP."). Should `root_ca` specify a different path?

Actually, they are the same file, but used in different places. Kibana verify OpenID TLS with `root_ca`.

**Comment by zehonghuang** [comment]
> If this property is used for certificate validation using OpenID, it's not clear to me how `root_ca` would differ from `pemtrustedcas_filepath` (described as "Absolute path to the PEM file containing the root CAs of your IdP."). Should `root_ca` specify a different path?

Actually, they are the same file, but used in different places. Kibana verify OpenID TLS with `root_ca`.

**Comment by zehonghuang** [comment]
I think names should at least be consistent, and documented.  :p

**Comment by peternied** [comment]
@cwillum I've started a discussion to try to get help looking into this issue, follow up at https://github.com/orgs/opensearch-project/teams/security/discussions/3

**Comment by hdhalter** [comment]
Hi @peternied - did you find any resolution to this issue? I can't access the above link, so not sure if there was any discussion about this. Thanks!

**Comment by peternied** [comment]
I can't find it either, looks like that was deleated.  Can we document the setting for `root_ca` like we've documented the other dashboards settings.  Looks like we can existing description for `pemtrustedcas_filepath` as a good starting point.

**Comment by hdhalter** [comment]
Sounds good! Can you please update the file with the description? And would it go here: https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/security-settings/?

**Comment by peternied** [comment]
@derek-ho Would you mind taking a look at making this change?
