### ISSUE TITLE
Add API template 

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#788]
Transfer the [API format](https://quip-amazon.com/l2FdAJWSVLap/OpenSearch-Style-Guide-API-sections-and-formats) into markdown, inside a `Templates` directory.

**Comment by alicejw-aws** [comment]
Hi @cwillum, I have a basic API page template in markdown if you want to use or modify it in this PR: [808](https://github.com/opensearch-project/documentation-website/pull/808)

The guidelines you are also converting to markdown could be a good complement, or if you want to merge them together. 
Thanks,
Alice

**Comment by cwillum** [comment]
Reopening to make further changes to the API guide.

**Comment by cwillum** [comment]
Merged to main in #895. But still open to contributions if someone sees room for improvement.
