### ISSUE TITLE
[DOC] Fix lucene HNSW vector dimensionality.

### ISSUE THREAD

**Issue by Devanshu24** [opensearch-project/documentation-website#7886]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [x] Report a technical problem with the documentation

**Tell us about your request.** Provide a summary of the request.
From the docs, https://github.com/opensearch-project/documentation-website/blob/d4bbdd919cab989bc0744e2fa155a85ef4d0d8d6/_search-plugins/vector-search.md?plain=1#L98-L100 it states the max dimension for vectors in `1,024`. However, that seems outdated after this addition (https://github.com/opensearch-project/k-NN/pull/1346), which is also released(https://github.com/opensearch-project/k-NN/releases/tag/2.12.0.0) in `2.12`.

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 2.12+
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
There was also an effort to update the documentation but I believe this page was missed 
- https://github.com/opensearch-project/documentation-website/issues/5874

**Comment by hdhalter** [comment]
Thanks for reporting this, @Devanshu24! Do you want to create the PR for this fix? 

Tagging @kolchfa-aws, since that page on vector search is a recent update, and @junqiu-lei, since you implemented the fix. Thanks!

**Comment by Naarcha-AWS** [comment]
Thanks for bring this to our attention @Devanshu24! I submitted PR #8051 which should resolve the issue.
