### ISSUE TITLE
[DOC] Remove aggregation and concurrent segment search from limitations of derived fields

### ISSUE THREAD

**Issue by rishabhmaurya** [opensearch-project/documentation-website#7902]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
Aggregations and Concurrent segment search, which are currently set as limitation, will be supported from 2.17 and onwards. 
Aggregation support is fixed by https://github.com/opensearch-project/OpenSearch/pull/14618 thanks @mch2 
Derived fields support is fixed by https://github.com/opensearch-project/OpenSearch/pull/15072 thanks @jed326 

There is an open issue https://github.com/opensearch-project/documentation-website/issues/7850 to add derived field aggregation examples in the documentation as well. 

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 2.17

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by mch2** [comment]
@rishabhmaurya We don't have compatibility with concurrent search yet.  In https://github.com/opensearch-project/OpenSearch/pull/15072 @jed326 added some ITs that are currently skipped with concurrent search.

**Comment by Naarcha-AWS** [comment]
@rishabhmaurya or @mch2: Is there a PR in progress for this?

**Comment by mch2** [comment]
@Naarcha-AWS will get that up today thanks for the reminder

**Comment by mch2** [comment]
@Naarcha-AWS Just raised https://github.com/opensearch-project/documentation-website/pull/8222
