### ISSUE TITLE
[DOC]Generating self-signed certificates: Using IP address in SAN syntax

### ISSUE THREAD

**Issue by ProCycleDev** [opensearch-project/documentation-website#7939]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
In the section detailing creating node and client certificates it mentions specifying a SAN. If a user is creating a certificate for a server that only has an IP address then the syntax `DNS:127.0.0.1` will result in a validation error.

We should change this:

```
Before generating a signed certificate, create a SAN extension file which describes the DNS A record for the host:
```

To something like this:

```
Before generating a signed certificate, create a SAN extension file which describes the DNS A record for the host. Use `IP:` for IP addresses:
```

***Version:**
All versions?

**Comment by Naarcha-AWS** [comment]
@ProCycleDev: Thanks for bringing this to our attention! I opened a PR that hopefully address the issue: #7972 

Can you take a look at that PR and make sure the change is accurate?
