### ISSUE TITLE
[DOC] Updating Zero-ETL data source 

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/documentation-website#7948]
## Description
In `2.16` we have migrated the original S3 and Prometheus data source in dashboards observability into Dashboards management section of OSD core. This created an unified experience with opensearch connection data source. In addition, it also start supporting MDS features and allow users to view + edit an datasource from a remote cluster when the MDS feature flag is enabled (`data_source.enabled: true`).

### Before 2.16.0 - Current experience in dashboards observability
At the left side menu, user can see the option for access into the Zero-ETL data source:
<img width="306" alt="Screenshot 2024-08-08 at 12 41 37 PM" src="https://github.com/user-attachments/assets/e8e4050c-2f8b-4667-9957-d18e6a8d7a2f">

For the data connection page it only supports the management of connections that is from local cluster
<img width="1510" alt="Screenshot 2024-08-08 at 12 42 50 PM" src="https://github.com/user-attachments/assets/10712c3f-a24c-42bc-90ac-59dfde34f4a6">

For the creation flow, we have a tab for creating S3/Prometheus data sources
<img width="1508" alt="Screenshot 2024-08-08 at 12 47 32 PM" src="https://github.com/user-attachments/assets/cf6db193-ef07-4058-a682-d88bc1f9c835">

## After 2.16.0 - Unified experience with Multiple data sources in Dashboards Management
After the migration in version 2.16.0, we have unregistered the old data source option from the left side menu, and right now user should be able to access their data source management page from `Dashboards managment` --> `Data sources`
<img width="260" alt="Screenshot 2024-08-08 at 12 52 02 PM" src="https://github.com/user-attachments/assets/9e2f6752-fff9-4f5b-89d6-0f7a8926799c">

### MDS disabled - `data_source.enabled: false`
when user has their MDS flag disabled, from the data sources management page, it will only show the Zero-ETL data sources from the local cluster
<img width="1510" alt="Screenshot 2024-08-08 at 12 55 36 PM" src="https://github.com/user-attachments/assets/06ceebed-43fc-41aa-8f04-8802adfd3c1d">

For the creation flow, by clicking the button `Create data source connection` at the top right, it will pop up the card view as creation options 
<img width="1510" alt="Screenshot 2024-08-08 at 1 00 10 PM" src="https://github.com/user-attachments/assets/06619e41-0335-4426-8b80-d02f04095592">

### MDS enabled - `data_source.enabled: true`
After the enabling of the MDS, at the data source management page, user should be able to see both "OpenSearch connections" tab for letting user to manage their remote cluster connections and the "Direct query connections" tab for manage their Zero-ETL data sources.
<img width="1507" alt="Screenshot 2024-08-08 at 1 02 21 PM" src="https://github.com/user-attachments/assets/89fa648b-fd58-4efd-8c0e-651cd1c538bb">

For the "Direct query connections" tab, it adds a cluster picker for the remote cluster selection, so that user should be able to view and manage their Zero ETL data connections for their remote cluster

https://github.com/user-attachments/assets/e32e9087-1644-4b04-9ff7-ffe7a31998e0

For the creation flow's card view, user should be able to see the creating option for OpenSearch connections
<img width="1507" alt="Screenshot 2024-08-08 at 1 13 37 PM" src="https://github.com/user-attachments/assets/3c56f541-9c17-469d-a1e0-cdc54ffcc01c">
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

## References
- https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7143
- https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7323
- https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7461

**Comment by Naarcha-AWS** [comment]
@RyanL1997: would it make sense to add these new flow additions to PR #7800?

**Comment by AntonEliatra** [comment]
@RyanL1997 Am I correct in assuming all MDS connections are listed under "OpenSearch connections" and all Zero-ETL are under "Direct Query connections"? If not can you elaborate on the difference please

**Comment by Naarcha-AWS** [comment]
@RyanL1997: Also, is the Zero-ETL view behind a feature flag or just MDS?

**Comment by vagimeli** [comment]
@RyanL1997 Have you created a doc PR for this feature? Do you want to update the existing documentation (https://opensearch.org/docs/latest/dashboards/management/data-sources/)?
