### ISSUE TITLE
[Doc] AD Anywhere

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#796]
See https://github.com/opensearch-project/anomaly-detection/issues/521

To help address this disconnect between Visualizations and AD, we propose an integrated solution that allows users to quickly create, run and view anomaly results from a Visualization. For certain Visualizations, users can utilize the effort they've already provided to visualize the data they’re interested in (source data, metrics to analyze), and create an anomaly detector on that same data with just a few extra clicks.

**Comment by Naarcha-AWS** [comment]
@vagimeli: Since this is related to Alerting and Observability as well, I'm to go ahead and assign this to Alice.

**Comment by Naarcha-AWS** [comment]
This feature has been delayed to 2.4 or later. Updating labels and milestones now.

**Comment by alicejw-aws** [comment]
Created outline of tasks to document in the Dashboards docs to share with @vagimeli as writer for OpenSearch Dashboards.
Assigning back to Melissa for the Dashboards docs.

**Comment by Naarcha-AWS** [comment]
This issue is moving to 2.5. Updating milestone now.

**Comment by vagimeli** [comment]
Thanks Nate

**Comment by alicejw-aws** [comment]
This is a brief list of the tasks that need to be documented, based on the detailed list within the [META eng ticket #521](http:// https://github.com/opensearch-project/anomaly-detection/issues/521).

What you can do in the Dashboards to detect anomalies in your data visualizations: 

1. Create the anomaly detector in the Dashboards.
2. View the anomaly and get a detailed list.
3. Set up notifications when detections are triggered in the Dashboards.
4. Administer the detector (turn on/off).
5. Set up predefined roles for access.

**Comment by alicejw-aws** [comment]
this appears to be a duplicate ticket to  [META 2075](https://github.com/opensearch-project/documentation-website/issues/2075).

Feature description - same as 2075 
Resource ticket - same: [META 521](https://github.com/opensearch-project/anomaly-detection/issues/521)
is it ok to close and reference other ticket?

**Comment by Naarcha-AWS** [comment]
@alicejw-aws is working specifically on the alerts, @vagimeli is working on the detectors and dashboard. However, due to the prioritization of #2294, this will be delayed to 2.6

**Comment by Naarcha-AWS** [comment]
Closing this in favor of #937

**Comment by Naarcha-AWS** [comment]
Closing this in favor of #2075
