### ISSUE TITLE
[Bug]: Documentation on dockerhub doesn't mention WHERE to place configuration YAML file

### ISSUE THREAD

**Issue by nobletrout** [opensearch-project/documentation-website#797]
### Describe the bug

The documentation [ on docker hub](https://hub.docker.com/r/opensearchproject/opensearch-dashboards) states the following:

```
Just like opensearch.yml, you can pass a custom opensearch_dashboards.yml to the container in the Docker Compose file.
```

But doesn't say where this file should be mounted or what it's contents can be.

### To reproduce

visit docker hub site

**Comment by hdhalter** [comment]
Hi @JeffH-AWS , is this something you can address when you work on the Docker installation?

**Comment by JeffH-AWS** [comment]
I'm working to figure out who is able to address this. Docker Hub isn't part of the documentation-website repo.

**Comment by JeffH-AWS** [comment]
Path forward here is to engage the team that works on deployment pipelines as they have access to edit the Dockerhub page. Once I begin work on the Docker installation process I will pass along a recommended change for the Dockerhub page as well and that team will implement the change so there's no need to worry about providing me access.

**Comment by JeffH-AWS** [comment]
I've engaged a member of the team about this change. The solution is to add a link to https://opensearch.org/docs/latest/opensearch/install/docker/#configure-opensearch for the user to follow if they are not familiar with how to use `Docker`.  Bear in mind that these steps are native to Docker - they aren't exclusive to OpenSearch.

**Comment by JeffH-AWS** [comment]
Due to OpenSearch Con it might take a few days to get pushed since a lot of the team are traveling.

**Comment by JeffH-AWS** [comment]
All fixed!  Validated on the Docker Hub page.
