### ISSUE TITLE
[DOC] SecurityAdmin uses port 9200 (http)

### ISSUE THREAD

**Issue by landon-lengyel** [opensearch-project/documentation-website#7985]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
The `securityadmin.sh` documentation contradicts itself in a few places on whether it uses 9200 or 9300 by default. Currently, it does use 9200 which is the HTTP endpoint by default.

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
2.16.0 (likely more, I only tested with the currently released version)
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Reproduce by trying to run `securityadmin.sh` with:
 - `-p 9300` = Fail
 - `-p 9200` = Success
 - (No port specified) = Success

I will submit a PR to change this momentarily.

**Comment by Naarcha-AWS** [comment]
Closed by #7989
