### ISSUE TITLE
[Doc] RFCSummarize clustering

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#806]
## What do you want to do?
 
- Add new documentation about RFCSummarize

## Tell us about your request. 

This future feature adds the RCFSummarize algorithm developed by CURE. When testable, create a section in [Supported Algorithm](https://opensearch.org/docs/latest/ml-commons-plugin/algorithms/), and add examples for the algorithm. 
 
## Do you have any related resources to help us get started? 

- https://github.com/opensearch-project/ml-commons/issues/356

**Comment by hdhalter** [comment]
Hi Nate, I spoke with Charlie and this feature is going out in 2.2. I updated the label. He will be in touch about the details.

**Comment by model-collapse** [comment]
@Naarcha-AWS, we are going to provide release this feature in 2.2 and following will be included in the doc:
1) Brief introduction to the algorithm background, (similar to K-Means)
2) Advantage comparing to K-Means. (Will give you some material on this)
3) API description. (RESTful example)
