### ISSUE TITLE
Token filters - flatten_graph [DOC]

### ISSUE THREAD

**Issue by AntonEliatra** [opensearch-project/documentation-website#8060]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

Create a separate page for Token filter: flatten_graph

Part of META issue: https://github.com/opensearch-project/documentation-website/issues/1483

***Version:** all

**Comment by natebower** [comment]
> @natebower I can take this one

@Naarcha-AWS ?

**Comment by AntonEliatra** [comment]
Parking this token filter as it would need to reference token filters which have not yet been expanded on
