### ISSUE TITLE
Token filters - hunspell [DOC]

### ISSUE THREAD

**Issue by AntonEliatra** [opensearch-project/documentation-website#8061]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

Create a separate page for Token filter: hunspell

Part of META issue: https://github.com/opensearch-project/documentation-website/issues/1483

***Version:** all

**Comment by AntonEliatra** [comment]
@natebower I can take this one

**Comment by AntonEliatra** [comment]
Parking this for now, as it would need to reference token filters not which have not yet been expanded on

**Comment by vagimeli** [comment]
> @Naarcha-AWS I can take this one

@Naarcha-AWS Thank you for the offer, but this topic has been assigned to @kolchfa-aws, who will be handling it. I will be assigning the contractor-created PRs to the doc reviewers. If you have any questions regarding the PR doc review tasks, please coordinate with me directly. I appreciate your understanding.
