### ISSUE TITLE
[DOC] Add Documentation for WorkloadManagement Settings

### ISSUE THREAD

**Issue by ruai0511** [opensearch-project/documentation-website#8066]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
Adding documentation for workload management settings. As per this PR: https://github.com/opensearch-project/OpenSearch/pull/15028

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
2.x

**Comment by Naarcha-AWS** [comment]
@ruai0511: Could you generate a PR detailing the workload management settings?

**Comment by jainankitk** [comment]
@Naarcha-AWS - Version label should be 2.17 I guess, since it will be released in the upcoming release

**Comment by ruai0511** [comment]
PR is opened here https://github.com/opensearch-project/documentation-website/pull/8228

**Comment by Naarcha-AWS** [comment]
Reopening this issue to reflect the delay.
