### ISSUE TITLE
[DOC] Document support for index level max_slice_count setting and search.concurrent_segment_search.mode setting

### ISSUE THREAD

**Issue by Gankris96** [opensearch-project/documentation-website#8068]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.

Adding to the changes mentioned in https://github.com/opensearch-project/OpenSearch/issues/15268, we will also need to document the availability of the setting at index level. 

As part of the related to this issue - https://github.com/opensearch-project/OpenSearch/issues/15259 
In PR: https://github.com/opensearch-project/OpenSearch/pull/15363# 

we will be introducing a new index and cluster setting 

Cluster:
`search.concurrent_segment_search.mode` 

Index:
`index.search.concurrent_segment_search.mode` 

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://github.com/opensearch-project/OpenSearch/pull/15336#issuecomment-2302677741 Something along these lines to show how the setting can be updated and how it would work in tandem with cluster level setting.

**Comment by Naarcha-AWS** [comment]
@Gankris96: To make sure we have everything we need, please submit a PR with the index-level slice settings after the development PR has been merged and successfully backported.
