### ISSUE TITLE
[DOC] k-NN Disk Based Feature documentation

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/documentation-website#8075]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
For 2.17, we are releasing disk-based k-NN vector search. Details on experience are contained in https://github.com/opensearch-project/k-NN/issues/1779.

We need to enhance the existing k-NN documentation to contain information about the new quantizer support, the new mode and compression level parameters and when to use what. 

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
2.17 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
High level RFC has all details: https://github.com/opensearch-project/k-NN/issues/1779

**Comment by Naarcha-AWS** [comment]
Thanks for submitting @jmazanec15!

**Comment by jmazanec15** [comment]
We're working on it. Will have PR out some time next week.

**Comment by Naarcha-AWS** [comment]
@jmazanec15: Sounds good! Please link the PR to the issue when you're done.

**Comment by jmazanec15** [comment]
PR: https://github.com/opensearch-project/documentation-website/pull/8246
