### ISSUE TITLE
[Blog] AD Benchmarking Blog

### ISSUE THREAD

**Issue by brijos** [opensearch-project/documentation-website#815]
### Is your feature request related to a problem?
Over the course of the Anomaly Detection plugin, we have made several improvement to improve the plugins speed, resource consumption and accuracy. In order to better tell this story to our customers and to have numbers to back these claims we will be starting a series of experiments that will establish how AD has improved.

### What solution would you like?
TBD

### What alternatives have you considered?
NA

### Do you have any additional context?
TBD

**Comment by JeffH-AWS** [comment]
Pinged brijos@ on this - this is a work in progress and scope/output hasn't been defined.  Will revisit once it's ready to be worked.

**Comment by JeffH-AWS** [comment]
This is in progress - awaiting draft for review.

**Comment by JeffH-AWS** [comment]
I was asked to review this while on PTO, so I directed Josh to engage with the docs team for assistance. Not sure where that landed as I didn't receive any updates. I've asked Josh to update the issue.

**Comment by brijos** [comment]
Reassigning to @Naarcha-AWS as he is diving in.
