### ISSUE TITLE
[DOC] Workload management at tenant level to improve resiliency

### ISSUE THREAD

**Issue by kaushalmahi12** [opensearch-project/documentation-website#8194]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 
With this feature admin users will be able to create the QueryGroup constructs to ensure fair resource consumption. This will apply to search workload only.

QueryGroup will have resource (CPU, JVM) level thresholds which the feature will try to enforce at all times during the lifecycle of the Opensearch process.

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by kkhatua** [comment]
@Naarcha-AWS  this might be the dev PR (RFC actually) https://github.com/opensearch-project/OpenSearch/issues/11061
