### ISSUE TITLE
[Doc] Visualizations: Experimental Drag & Drop editor for visualizations 

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/documentation-website#820]
## What do you want to do?
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

## Tell us about your request. 

For example, what feature or area does it affect? What versions? If it’s a change to existing documentation, which pages (URLs) are affected?

We are releasing a new feature in the visualize app for OpenSearch Dashboards that simplifies the process of creating visualizations using a drag and drop interface. Refer to proposal on [OpenSearch-Dashboards Issue 883](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/883). This is an experimental feature in the initial release which only supports the Metric visualization.

It is an incremental feature that that does not break any of the existing ways to create visualizations and can be accessed from the visualization picker. It can be enabled/disabled using a flag in the `opensearch_dashboards.yml` config file and also toggled using the `visualize:enableLabs` flag in Advanced Settings. 
 
## Do you have any related resources to help us get started? 

For example, a link to a related fixed issue, a design doc, or any particular POCs (Eng or PM) who have more information?

Proposal: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/883
Design: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/896

## Is there anything else you'd like to add?**

**Comment by Naarcha-AWS** [comment]
@ashwin-pc: Which versions are affected by this new feature?

**Comment by ashwin-pc** [comment]
Dashboards version 2.2 and beyond

**Comment by ashwin-pc** [comment]
Looks like we already have an issue for this #642.

**Comment by Naarcha-AWS** [comment]
I'm going to go ahead and close this in favor of #642
