### ISSUE TITLE
[FEATURE] Documentation for making all copies of shards spread evenly across all Awareness Attributes

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/documentation-website#828]
### Is your feature request related to a problem?

Meta for this [feature](https://github.com/opensearch-project/OpenSearch/issues/3367)

### What solution would you like?

Documentation for above mentioned feature : 

A boolean cluster level setting `routing.allocation.awareness.balance` which is false by default . When true, we would validate that total copies is always a multiple maximum of awareness attribute value count . If not, we will throw a validation exception.  For example : 

1.  if there are 2 Awareness Attributes, zones and rack ids, each having 2 and 3 values,  total copies needs to be multiple of 3.
2. if there is 1  Awareness Attributes, zones having 2 values, total copies needs to be multiple of 2. 

Note that this will take in effect only  upon `cluster.routing.allocation.awareness.attributes` and `cluster.routing.allocation.awareness.force.zone.values`   being set .

Validation paths : 

1. Create Index API
4. Update Index Settings API
5. Index Template Creation 
6. Snapshot Restore
7. ISM Action of Replica Count modification
8. Index creation triggered by Cross Cluster Replication Plugin. 

The PR is still in progress, and we are targeting 2.2 for release.

**Comment by Naarcha-AWS** [comment]
PR related to: https://github.com/opensearch-project/cross-cluster-replication/pull/461

**Comment by kolchfa-aws** [comment]
Ran tests, wrote docs, created a PR #856
