### ISSUE TITLE
[FEATURE] added _doc_count field to summary documents

### ISSUE THREAD

**Issue by petardz** [opensearch-project/documentation-website#829]
### Is your feature request related to a problem?
We need this new field documented for v2.2.0 [PR](https://github.com/opensearch-project/OpenSearch/pull/3985)

### Do you have any additional context?
Description would be something like this:

`Documents that store pre-aggregated data will have `_doc_count` field representing the number of documents
aggregated in a single summary field. When computing `doc_count` field, value of `_doc_count` will be used, if available, instead of `1`.`
This could be added to bucket-agg.md in "doc_count" paragraph.

**Comment by cwillum** [comment]
@petardz To clarify, from your "additional context" description: "documents that store pre-aggregated data" are those calculated and shown in a response. Yes? Could I see an example of this? 
And, this field appears as `_doc_count` and should not to be confused with `doc_count` Right?

**Comment by cwillum** [comment]
@petardz Actually, it might be more helpful to have a realistic example of a request that would naturally include this field for documents that store pre-aggregated data. Can you think of a document that that would include pre-aggregated data?

**Comment by petardz** [comment]
@cwillum 
Here's elasticsearch doc for this field: [link](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-doc-count-field.html). (We merged their PR). There is a good example shown there.

In ISM plugin, rollup jobs store these documents with pre-aggregated data in rollup indices. We need small PR to include this _doc_count field in them and once that's done we will have correct doc_count calculation when querying rollup indices.
