### ISSUE TITLE
[BUG] Fix version supportability matrix in official guide. 

### ISSUE THREAD

**Issue by ervikrant06** [opensearch-project/documentation-website#831]
### What is the bug?

In supportability matrix, it's mentioned corresponding to "OpenSearch 1.x to 2.x" older versions are supported with "Yes via version setting" But version setting is no longer available in opensearch 2.x onwards hence we should only mention "Opensearch 1.x"

https://opensearch.org/docs/latest/clients/agents-and-ingestion-tools/index/

Refer this issue for details https://github.com/opensearch-project/OpenSearch/issues/3023

**Comment by Naarcha-AWS** [comment]
@nknize: Can you confirm that we should go ahead and make this change? I thought we added the version override setting back in for 2.1 (https://github.com/opensearch-project/OpenSearch/pull/3530).

**Comment by nknize** [comment]
> @nknize: Can you confirm that we should go ahead and make this change? I thought we added the version override setting back in for 2.1 ([opensearch-project/OpenSearch#3530](https://github.com/opensearch-project/OpenSearch/pull/3530)).

We did add the override back in for 2.1 so I don't think we should make the change.

**Comment by vagimeli** [comment]
@nknize @ervikrant06 @Naarcha-AWS Is a documentation update still needed on this issue? The issue is closed but was assigned to me. I search documentation and haven't located any files with the verbiage "OpenSearch 1.x to 2.x."

**Comment by ervikrant06** [comment]
@vagimeli I am good with closure. thanks
