### ISSUE TITLE
[BUG] Reference to OpenDistro should be changed. 

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/documentation-website#832]
### What is the bug?
In the security plugin documentation, under access control -> permissions. Our documentation here makes reference to OpenDistro, which is probably no longer appropriate. 

https://opensearch.org/docs/latest/security-plugin/access-control/permissions/

### How can one reproduce the bug?
View the page referenced above. 

### What is the expected behavior?
Our examples should use up to date software versions.

### What is your host/environment?
Firefox, Windows

### Do you have any screenshots?
![image](https://user-images.githubusercontent.com/96254688/181109792-e424eee7-3660-42d0-9c0f-00c92e1d6a24.png)

**Comment by Naarcha-AWS** [comment]
@nateynateynate: Do we know for sure that these OpenDistro endpoints are deprecated?

**Comment by Naarcha-AWS** [comment]
Verified that these permissions are deprecated. Should be a simple change to remove them.

**Comment by hdhalter** [comment]
Are we sure this applies to 1.3?
