### ISSUE TITLE
[DOC] Reporting Anywhere CLI

### ISSUE THREAD

**Issue by brijos** [opensearch-project/documentation-website#836]
### Is your feature request related to a problem?
Documentation support for Reporting Anything CLI which allows someone to download a report without being inside Dashboards. The benefit to the API consumer is that they can create infrastructure to download and handle reports in an automated fashion.

Release target August.

**Comment by brijos** [comment]
https://github.com/opensearch-project/dashboards-reports/issues/345

**Comment by Naarcha-AWS** [comment]
@brijos: Is this tied to an OpenSearch release?

**Comment by Naarcha-AWS** [comment]
According to the PR (https://github.com/opensearch-project/dashboards-reports/issues/345#issuecomment-1203117543), this should be released in two to four weeks. Adding a Q3 milestone. 

We'll loop back around to this after the 2.2 release.

**Comment by Naarcha-AWS** [comment]
@Naarcha-AWS: Follow up with @brijos about the status of this.

**Comment by alicejw-aws** [comment]
Status: started research 10/24. Learning from demo recording and other information.

**Comment by alicejw-aws** [comment]
Update: 11/17. Picked up again after 2.4 release is done. Starting doc outline from previous research completed.

**Comment by alicejw-aws** [comment]
Note: They are also writing a Developer Guide for the Reporting Anything CLI tool in this PR: https://github.com/opensearch-project/dashboards-reporting/pull/565/files

this doc ticket will represent the concepts content within OpenSearch dashboards documentation, and link to the Developer's Guide for install instructions.

**Comment by alicejw-aws** [comment]
hi @brijos and @davidcui1225

Question: when is the Developer Guide going to be merged/published? [PR](https://github.com/opensearch-project/dashboards-reporting/pull/565)
Reason: I have the overview for reporting CLI that will cross-reference the Dev Guide for how-to/install instructions. 
in this [PR](https://github.com/opensearch-project/documentation-website/pull/2170). 
Would like to publish at the same time as the Dev Guide. Thanks

**Comment by alicejw-aws** [comment]
Update: from PM we also need to add a few examples of how to use Reporting CLI independently as well as with other services such as lambda, SNS, and SES.

**Comment by alicejw-aws** [comment]
Hi @brijos , I added you as a reviewer to read the 1st draft. Could not locate Rupal's GitHub ID, so I sent via email (@maharup) for her to review it, as well. Thanks

**Comment by alicejw-aws** [comment]
Update: adding more info learned in demo today. Pausing tech review to add new content. Thanks

**Comment by alicejw-aws** [comment]
Update: (same note in PR) - all reviews are completed, but we are waiting for ok to publish from engineering - they are not yet ready to release the Reporting CLI tool.

**Comment by alicejw-aws** [comment]
Docs are ready to publish. PR has been tech reviewed by SMEs, 2 doc writer reviews and final editorial review. 

Update: New request for content via Slack chat. 

Need to develop this new content: 
1. @brijos  - please provide some use case examples in addition to plain reporting cli help. eg. how to schedule a daily dashboard report, report emailed on an alert.
2.@nitincd - do you have an observability workflows that we can showcase with reporting-cli
3. @kgcreative - Request -  an example of alerts on Prometheus metrics exceeding a threshold.
4. @nitincd - a weekly report of the key metrics for top 3 urls, showing the % increase/decrease from last week (maybe even 5 week trend in a table/chart)
avg. response time
count of 400 and 500 errors
count of visitors
5. Request to create a section with the top 5  use case examples (need more details). 
6. from Joshua: Setup examples..
CDK, Ansible etc...
Execution examples
Schedule report using lambda to email using internal vpn / networked email access via SNS or SES
Grafana / prometheus alert to report
