### ISSUE TITLE
[BUG] Add Maven coordinates to list of available plugins

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/documentation-website#838]
### What is the bug?

Someone at the community meeting brought this up today - the idea is that we can use the plugin install script with an official plugin name to install a plugin. But -- when visiting https://opensearch.org/docs/1.3/opensearch/install/plugins/#install-a-plugin , we state that plugins can be installed via "Maven Coordinates to a plugin zip file" as well as "A URL to a plugin zip file"

As we offer a list of official plugin names, but not a list of Maven Coordinates or URLs. They use Maven, and found themselves without guidance at all on where to get said plugins. 

### How can one reproduce the bug?

Visit https://opensearch.org/docs/1.3/opensearch/install/plugins/#install-a-plugin

### What is the expected behavior?

A reference of Maven Coordinates for the plugins along with the list of official plugin names.

**Comment by JeffH-AWS** [comment]
This will require research. Who provides Maven coordinates?

**Comment by JeffH-AWS** [comment]
https://maven.apache.org/what-is-maven.html

**Comment by JeffH-AWS** [comment]
https://github.com/opensearch-project/OpenSearch/issues/581

**Comment by JeffH-AWS** [comment]
https://github.com/opensearch-project/opensearch-build/issues/716

**Comment by JeffH-AWS** [comment]
https://github.com/opensearch-project/opensearch-build/issues/1823

**Comment by JeffH-AWS** [comment]
Looking for a SME to assist me with this.  I need two pieces of information:

1. How to derive coordinates for any given plugin in the repo https://repo1.maven.org/maven2/org/opensearch/plugin/
2. How to display those coordinates in the documentation

I think a quick 5 minutes crash course is all I really need, but until I understand that I'm blocked.

I will continue looking for a SME to assist with this.

**Comment by JeffH-AWS** [comment]
Got the information I needed.  Good to go on getting this added to the plugins list.

**Comment by rursprung** [comment]
note: when working with maven you usually don't write a URL but instead use the "maven coordinates" (i.e. group + artifact) and need to know on which maven repository it's published (as you publish it to maven this part isn't really relevant.

you could e.g. add one of the following URLs:
* directly to [all `org.opensearch.plugin` artefacts on maven central](https://search.maven.org/search?q=org.opensearch.plugin)
* [the same list on maven repository](https://mvnrepository.com/artifact/org.opensearch.plugin) (i prefer the visualisation on this page, but that's just personal)

either of these pages then also shows a ton of options on how to write the maven coordinates (which depends on the build system being used) as well as giving a direct download link.

note that there are also artefacts published there which are not the ZIP files (namely JAR files are being published which aren't of much use to end-users of OpenSearch), but i presume that anyone who wants to use OpenSearch plugins via maven will know how to find them

**Comment by JeffH-AWS** [comment]
Thanks for that info @rursprung!  I was struggling a bit with trying to figure out how I should present the Maven coordinates in the docs.  So you think a link to the Maven repository (I also share your preference for the second link) would suffice?  Or could I go further to help OpenSearch users by adding in-line links to each individual artifact?

**Comment by JeffH-AWS** [comment]
Just to clarify - I feel like in-line links would be a little overkill.  Just trying to figure out how a developer would most appreciate these being laid out.

**Comment by JeffH-AWS** [comment]
Thanks for the insights!  That makes total sense.  I had always wondered why we appended an extra `.0` to the versions of some of the plugins when they otherwise had parity with the OS release version.  That distinction, although I know it could change, is helpful to identify.

Just for my own clarity - do you think that just a single link to the Maven repo is all OS users/developers would need to get access to what they need?

**Comment by rursprung** [comment]
> Just for my own clarity - do you think that just a single link to the Maven repo is all OS users/developers would need to get access to what they need?

i'd say this link here, combined with the critical information that not all plugins listed there are plugins which you can install using `opensearch-plugin install` (a description of what these are might be helpful, but you'd have to ask somebody who knows more about them; my presumption would be that those are pre-packaged with opensearch, even in the -min distribution, and can't be uninstalled), should be enough: https://mvnrepository.com/artifact/org.opensearch.plugin

**Comment by JeffH-AWS** [comment]
Nice.  I did a little digging into plugins for another docs request so I think I've got a good idea of what can be installed and what comes bundled.
