### ISSUE TITLE
[DOC] new phone number analyzer plugin

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#8389]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
i'm adding a new plugin (optional, not installed by default) to OpenSearch (starting with 2.18.0) for phone numbers. see the description of the PR for more information and examples: https://github.com/opensearch-project/OpenSearch/pull/15915

***Version:** 2.18.0
 
**What other resources are available?**
see the PR: https://github.com/opensearch-project/OpenSearch/pull/15915

**Comment by reta** [comment]
> since you assigned this to me: am i expected to provide the PR for this or will someone else do it based on the commit message in the linked PR (once it's merged)?

@rursprung usually implementors of the feature provide the documentation update, the documentation team will help to shape it properly, thank you.
