### ISSUE TITLE
Remove Open Distro download links 

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#840]
## What do you want to do?
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

## Tell us about your request. For example, what feature or area does it affect? What versions? If it’s a change to existing documentation, which pages (URLs) are affected?
We need to remove all download links from the Open Distro documentation now that we are no longer offering Open Distro as a download. We may also want to update the Readme and Contribution files and https://hub.docker.com/r/amazon/opendistro-for-elasticsearch-kibana.

## Do you have any related resources to help us get started? For example, a link to a related fixed issue, a design doc, or any particular POCs (Eng or PM) who have more information?

Open Distro doc home page: https://opendistro.github.io/for-elasticsearch-docs/
Blog about archiving of Open Distro: https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/

**Comment by hdhalter** [comment]
@cwillum - Before you merge the PR, reach out to Miki so he can unarchive the Open Distro repo.

**Comment by cwillum** [comment]
Removal of links that provide download of Open Distro on the documentation website are in progress. I want to get a little more clarification on which artifacts need to go and which ones should stay. But I expect this will be done by end of day.

**Comment by cwillum** [comment]
Changes have been made. This also includes the addition of information addressing the inability to install ODFE 1.13.3 with Debian or RPM due to missing upstream artifacts. Waiting to get temporary permission to write to the repo and create a PR on this.

**Comment by cwillum** [comment]
See PR [#535](https://github.com/opendistro/for-elasticsearch-docs/pull/535) in the opendistro/for-elasticsearch-docs repo for in-progress reviews.

**Comment by cwillum** [comment]
Changes are reflected on the ODFE website. Closing this issue.
