### ISSUE TITLE
[DOC] Knn clear cache doc issue

### ISSUE THREAD

**Issue by neetikasinghal** [opensearch-project/documentation-website#8459]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** The method type specified for clear cache API (https://opensearch.org/docs/latest/search-plugins/knn/api/#k-nn-clear-cache) should be `POST` instead of a `GET`. 
ref: https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/plugin/rest/RestClearCacheHandler.java#L58

Curent:

```
GET /_plugins/_knn/clear_cache/index1,index2,index3?pretty
{
  "_shards" : {
    "total" : 6,
    "successful" : 6,
    "failed" : 0
  }
}

GET /_plugins/_knn/clear_cache/index*?pretty
{
  "_shards" : {
    "total" : 6,
    "successful" : 6,
    "failed" : 0
  }
}
```
Expected:

```
POST /_plugins/_knn/clear_cache/index1,index2,index3?pretty
{
  "_shards" : {
    "total" : 6,
    "successful" : 6,
    "failed" : 0
  }
}

POST /_plugins/_knn/clear_cache/index*?pretty
{
  "_shards" : {
    "total" : 6,
    "successful" : 6,
    "failed" : 0
  }
}
```

***Version:** all.

**Comment by navneet1v** [comment]
@naveentatikonda can you please fix the docs

**Comment by Naarcha-AWS** [comment]
Thanks @neetikasinghal! Feel free to ping one of the maintainers on the Doc repo once the PR is ready for review.
