### ISSUE TITLE
[DOC]: Add name for action menu on App Analytics page

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/documentation-website#849]
## What do you want to do?
 
- [ X] Request a change to existing documentation

## Tell us about your request. 

OpenSearch 2.1.x
Application Analytics page
https://opensearch.org/docs/2.1/observability-plugin/app-analytics/

"Get started" says "To get started, choose Observability in OpenSearch Dashboards". It was not obvious to this naive new user that Observability was under the hamburger menu in the top left of the page, under OpenSearch Plugins. This could be made more explicit. I don't know what our usual term for the hamburger menu is, but something like:

"To get started, choose Observability in the top left (hamburger) menu under Plugins."

## Is there anything else you'd like to add?

Perhaps review other pages to see if there is a similar issue. This is especially important because (as far as I can tell), there is no overview of Dashboards usage.

The start page https://playground.opensearch.org/app/opensearch_dashboards_overview#/ makes it seem as though the only options are Dashboard and Discover, which leads the user to believe that everything will be found as options under those....

Am I the only new user to not notice that there's lots of good stuff under the hamburger menu?

**Comment by Naarcha-AWS** [comment]
@macrakis: I think the term I see most commonly used is "Action menu".

**Comment by Naarcha-AWS** [comment]
Alternatives to hamburger:

- Menu Icon
- Menu
