### ISSUE TITLE
[DOC] Feature in 2.2 requires two variables documented. 

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/documentation-website#850]
## What do you want to do?
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [X] Report a technical problem with the documentation
- [ ] Other 

## Tell us about your request. 

When 2.2 comes out, the feature regarding shard allocation awareness (#3367) relies on two configuration variables being set. These variables are not very well described, with their only mention being at https://opensearch.org/docs/2.0/opensearch/cluster/#advanced-step-6-configure-shard-allocation-awareness-or-forced-awareness
 
## Do you have any related resources to help us get started? 

For example, a link to a related fixed issue, a design doc, or any particular POCs (Eng or PM) who have more information?

https://github.com/opensearch-project/OpenSearch/issues/3367
https://opensearch.org/docs/2.0/opensearch/cluster/#advanced-step-6-configure-shard-allocation-awareness-or-forced-awareness

`cluster.routing.allocation.awareness.attributes` and `cluster.routing.allocation.awareness.force.zone.values`

## Is there anything else you'd like to add?

They are documented... elsewhere..... just not on our site.

**Comment by Naarcha-AWS** [comment]
@nateynateynate: We already have an issue for Awareness Attributes in progress, see PR https://github.com/opensearch-project/documentation-website/pull/856/files and issue #828.

Going to close this one, feel free to comment on the linked PR if you want any additional information added to the doc.
