### ISSUE TITLE
[DOC] Cannot navigate to object field type documentation

### ISSUE THREAD

**Issue by msfroh** [opensearch-project/documentation-website#8549]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
It seems like some of the link targets are broken on the 2.17 (latest) version of the documentation website.

If I go to https://opensearch.org/docs/latest/field-types/supported-field-types/index/, and click on the links for `object` and `flat_object` field types, I get redirected to the documentation homepage. For example, navigating to https://opensearch.org/docs/latest/field-types/supported-field-types/flat-object/ redirects to the doc homepage right now.

By comparison, https://opensearch.org/docs/2.16/field-types/supported-field-types/flat-object/ still works.

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
2.17 (current "latest")
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by kolchfa-aws** [comment]
@msfroh This was most likely due to an S3 issue, which is fixed now. Could you check again, and if everything is OK, we can close this issue.

**Comment by msfroh** [comment]
Hmm... Checking from my phone right now, even https://opensearch.org/docs/latest/field-types/supported-field-types/index/ is redirecting to the home page.

**Comment by peterzhuamazon** [comment]
> Hmm... Checking from my phone right now, even https://opensearch.org/docs/latest/field-types/supported-field-types/index/ is redirecting to the home page.

Shows for me on my phone on 2 different browser.

**Comment by peterzhuamazon** [comment]
37min ago there is a new change deployed:
https://github.com/opensearch-project/documentation-website/commit/c6c0041ae577128154a11a4bc7c695c2ecf8f4dc

That probably fix it if there is any leftover for yesterday.

**Comment by msfroh** [comment]
> 37min ago there is a new change deployed:
> 
> https://github.com/opensearch-project/documentation-website/commit/c6c0041ae577128154a11a4bc7c695c2ecf8f4dc
> 
> 
> 
> That probably fix it if there is any leftover for yesterday.

All working for me now! Thanks!
