### ISSUE TITLE
[DOC] Update default value for engine in k-NN index

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/documentation-website#8589]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
In 2.18, we will be updating default engine from nmslib to fiass. We would like to update the same in documentation
https://opensearch.org/docs/latest/search-plugins/knn/knn-index/#method-definitions

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
2.18
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/k-NN/issues/2163
PR is raised to make that change in code here https://github.com/opensearch-project/k-NN/pull/2221

**Comment by Naarcha-AWS** [comment]
Closed by #8620
