### ISSUE TITLE
[DOC] : Geo Shape Aggregation Documentation

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/documentation-website#861]
## What do you want to do?
- [X] Add new documentation

## Tell us about your request. 
Area: Aggregations
Field: GeoShape
Version: 2.5 as of now

The feature is adding a new Aggregation on the GeoShape field. 
 
## Do you have any related resources to help us get started? 
https://github.com/opensearch-project/geospatial/issues/97

https://github.com/opensearch-project/geospatial/issues/93

## Is there anything else you'd like to add?
The Aggregation is similar to what we have on Geo Points field, but instead of field type as GeoPoint, it will GeoShape. More details can be found in the RFC: https://github.com/opensearch-project/geospatial/issues/93

**Comment by navneet1v** [comment]
The feature is moved to 2.7. Updated the label.

**Comment by navneet1v** [comment]
@hdhalter the release moved to 2.8 because of other high priority tasks. Updating the label.

**Comment by kolchfa-aws** [comment]
@navneet1v Is this on track to go into 2.9?

**Comment by navneet1v** [comment]
@kolchfa-aws Yes it is
