### ISSUE TITLE
[DOC] Support xy_point and xy_shape field type

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/documentation-website#862]
## What do you want to do?
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

## Tell us about your request. 

OpenSearch will support two new field type xy_point and xy_shape , similar to geo_point and geo_shape, except, these two new field type facilitates the indexing and searching of points represented as unit less x, y pairs that fall in a 2-dimensional planar coordinate system. 
 
## Do you have any related resources to help us get started? 

https://github.com/opensearch-project/geospatial/issues/95
https://github.com/opensearch-project/geospatial/issues/67

## Is there anything else you'd like to add?

**Comment by alicejw-aws** [comment]
Hi @VijayanB , I looked at all the linked tickets, and just want to confirm we will doc this new xy_point field type with the Mapping API (see docs https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/put-mapping/). 
Or do you also have a use case for this? I want to explain how they would use this. thanks
