### ISSUE TITLE
[DOC] Document how to control read/write access

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#863]
## What do you want to do?
 
- [x] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

## Tell us about your request. 

Coming from https://github.com/opensearch-project/opensearch-py/issues/95 and https://github.com/aws/aws-cdk/issues/17761#issuecomment-1186674964, document how to control read/write access to OpenSearch. Specifically call out that that trying to control read/write access by HTTP verb will not work. See https://github.com/opensearch-project/OpenSearch/issues/4177.
 
## Do you have any related resources to help us get started? 

https://github.com/opensearch-project/opensearch-py/issues/95
https://github.com/aws/aws-cdk/issues/17761

**Comment by alicejw-aws** [comment]
Hi @dblock , do you know if this issue is only for the Python client? (mentioned in linked issue: https://github.com/opensearch-project/opensearch-py/issues/95) thanks

**Comment by alicejw-aws** [comment]
note: looks like we also need to update this top-level page for the Search API (per linked ticket https://github.com/aws/aws-cdk/issues/17761#issuecomment-1186674964,)
https://opensearch.org/docs/latest/opensearch/rest-api/search/

**Comment by alicejw-aws** [comment]
@dblock , I'm searching for the information in the linked tickets to write the instructions for 
How to control read/write access in OpenSearch. Do you have this information, or could you help clarify how do they do this? 

I can also put the note in the REST API section that warns them not to use an HTTP verb to control read/write access.
thanks

**Comment by dblock** [comment]
I don't have answers unfortunately @alicejw-aws, this needs some thorough research and experimenting, cc: @elfisher

**Comment by hdhalter** [comment]
Reassigning to @cwillum

**Comment by hdhalter** [comment]
@Naarcha-AWS - Can you please review and see if this is still an issue? Thanks.

**Comment by hdhalter** [comment]
@AntonEliatra - Since you worked on the permissions docs recently, can you please see if this has been addressed?
