### ISSUE TITLE
[DOC] Column 3 of table in OpenSearch -> Shard Indexing Backpressure -> Settings is too small

### ISSUE THREAD

**Issue by JeffH-AWS** [opensearch-project/documentation-website#865]
## What do you want to do?
 
- [x] Request a change to existing documentation

## Tell us about your request. 

Column three in the tables on this page (https://opensearch.org/docs/latest/opensearch/shard-indexing-settings/) are getting crushed down due to the length of the setting names.  It makes it very difficult to read the descriptions.  This seems to be poorly sized regardless of client resolution/browser.
 
## Do you have any related resources to help us get started? 

This might be a limitation of the current website theme and might need to be looked at again after the site gets migrated to a better backend.

## Is there anything else you'd like to add?

No but thank you for asking.

**Comment by hdhalter** [comment]
This will be fixed in a future release. Closing this issue.
