### ISSUE TITLE
[DOC] Static vs Dynamic Settings

### ISSUE THREAD

**Issue by landon-lengyel** [opensearch-project/documentation-website#8710]
The Index API's [Update Settings](https://opensearch.org/docs/latest/api-reference/index-apis/update-settings/) document mentions the concept of **dynamic** and **static** settings. It doesn't describe them in that document however, and instead asks users to go to the [Create Index](https://opensearch.org/docs/latest/api-reference/index-apis/create-index/) document for that information. That document also does not mention the static and dynamic setting distinction.
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
The Create Index document should properly include the distinction between static and dynamic setting. If there's another document that describes this distinction, then the Update Settings document should link to that other document.

**Version:** 
2.18
 
**What other resources are available?**
N/A

**Comment by landon-lengyel** [comment]
It looks like older versions of the [Create Index](https://opensearch.org/docs/1.1/opensearch/rest-api/index-apis/create-index/) document do include mention of the static and dynamic setting, leading me to believe that there may be a new document that describes this that I'm just having trouble finding.

Or that may be an odd omission on the current Create Index documentation.

**Comment by kolchfa-aws** [comment]
Thanks @landon-lengyel. The static/dynamic settings are described here https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/index/
