### ISSUE TITLE
[DOC]typo to send requests in terminal under security plugins

### ISSUE THREAD

**Issue by kamahuan** [opensearch-project/documentation-website#8770]
**What do you want to do?**
 
- [X ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
The official doc under `Communicate with Open Search` section, the command to send request in terminal looks like this : `curl -X GET "http://localhost:9200/_cluster/health" -ku admin:<custom-admin-password>`. It should be changed to `curl -X GET "https://localhost:9200/_cluster/health" -ku admin:<custom-admin-password>` if it is under security plugin.

**Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
all
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://opensearch.org/docs/latest/getting-started/communicate/

**Comment by Naarcha-AWS** [comment]
Thanks for sending this through @kamahuan!
