### ISSUE TITLE
Fix links in query-dsl/full-text [DOC]

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/documentation-website#879]
## What do you want to do?

- X Report a technical problem with the documentation

## Tell us about your request. 

On page https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/, there are 8 instances of the following link:
``see <a href="#options">options</a>``

They don't work; I believe the correct anchor is optional-query-fields.

## Is there anything else you'd like to add?

Shouldn't there be a tool that checks that all page-internal links are valid? Even better if it could check validity of all links in a pageset.

**Comment by Naarcha-AWS** [comment]
@macrakis: We're working on that last part.
