### ISSUE TITLE
[DOC]the sample url is http even though using the security plugin

### ISSUE THREAD

**Issue by uS-aito** [opensearch-project/documentation-website#8801]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 
The URL is http when using the security plugin on this page.
https://opensearch.org/docs/latest/getting-started/communicate/#sending-requests-in-a-terminal
![image](https://github.com/user-attachments/assets/2b5d7c68-aeac-485c-bd72-eaabe8c6f5d4)

On other pages it is https. I am new to opensearch so apologies if I have misunderstood.

**Version:** 2.18
 
**What other resources are available?** 
https://opensearch.org/docs/latest/getting-started/communicate/#sending-requests-in-a-terminal

**Comment by Naarcha-AWS** [comment]
@uS-aito: You are correct. It should be `HTTPs`. I'll send a PR through shortly.
