### ISSUE TITLE
[DOC]Policies at https://opensearch.org/docs/latest/im-plugin/ism/index/

### ISSUE THREAD

**Issue by slaser78** [opensearch-project/documentation-website#8851]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ x] Report a technical problem with the documentation
- [ ] Other 

"Policies" link is broken

**Version:** List the OpenSearch version 2.18

**Comment by Naarcha-AWS** [comment]
@slaser78: Can't recreate this. Its possible its related to other known caching issues our pipeline experiences. On all browsers and devices I have access to, the link works (https://opensearch.org/docs/latest/im-plugin/ism/policies/).

Feel free to upvote or comment on the original issue: https://github.com/opensearch-project/documentation-website/issues/6586

Commenting or upvoting will help us get these caching issues prioritized.
