### ISSUE TITLE
[DOC] Update Go client documentation to latest major version

### ISSUE THREAD

**Issue by colinking** [opensearch-project/documentation-website#8958]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** The Go client documentation is outdated, as it references `v2` instead of the latest version (`v4`).

**Version:** n/a
 
**What other resources are available?**

Go OpenSearch docs: https://opensearch.org/docs/latest/clients/go/
Reference for latest version: https://pkg.go.dev/github.com/opensearch-project/opensearch-go/v4

**Comment by Naarcha-AWS** [comment]
Closed by #8965
