### ISSUE TITLE
[DOC] New OpenSearch Maps 

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/documentation-website#897]
## What do you want to do?
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

## Tell us about your request. 

Corresponding feature request https://github.com/opensearch-project/dashboards-maps/issues/15

PM: Satish Nandi
PE: Navneet Verma

**Comment by Naarcha-AWS** [comment]
This issues accounts for the following changes to the OpenSearch map features, including

- [Adding layers to maps](https://github.com/opensearch-project/dashboards-maps/issues/15)
- Vector tiles reference. 

Consult @nandi-github for details.

**Comment by vagimeli** [comment]
@nandi-github Let's meet to discuss the writing plan and additions needed to existing documentation. Here's the link to the existing documentation https://opensearch.org/docs/latest/dashboards/geojson-regionmaps/. Do you have a demo of the new feature?
