### ISSUE TITLE
[DOC] ldap docker example is outdated

### ISSUE THREAD

**Issue by Martin-Kemp** [opensearch-project/documentation-website#905]
## What do you want to do?
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

## Tell us about your request. 

ldap docker example is outdated. The zip file on the ldap documentation site is still using `opensearchproject/opensearch:1.0.1` in the `docker-compose.yml` file.

Link: https://opensearch.org/docs/2.2/security-plugin/configuration/ldap/
 
## Do you have any related resources to help us get started? 

For example, a link to a related fixed issue, a design doc, or any particular POCs (Eng or PM) who have more information?

## Is there anything else you'd like to add?

**Comment by bbarani** [comment]
@Naarcha-AWS I have removed old labels from this issue. Please feel free to update the labels as needed.

**Comment by Naarcha-AWS** [comment]
Closed by #1719
