### ISSUE TITLE
[DOC] Refactor of plugins page to prevent versioning issues during release process

### ISSUE THREAD

**Issue by JeffH-AWS** [opensearch-project/documentation-website#909]
**What do you want to do?**

Originally this was raised with the following purpose: 
`Add a section to the `Available plugins` table https://opensearch.org/docs/latest/opensearch/install/plugins/ for OS 1.3.4`

However, it looks like this has just exposed an issue in the release process where these manually-entered plugin versions are losing parity due to how we handle back port merges. Based on a discussion with another team member, it sounds like it's particularly annoying when minor versions are released for a previous major version (I believe that's what was said).

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Version 1.3.4 has been released but we don't have a corresponding row in the table for plugin versions.

**Comment by JeffH-AWS** [comment]
Current recommendation: use version variables and only publish a table of plugins that are relevant to the respective version.  This would eliminate the need for HTML within the page - the table would be much smaller, and can be formatted using markdown.

**Comment by Naarcha-AWS** [comment]
@JeffH-AWS: I'm cool with this. It is something we've already done for 1.3.x (see https://opensearch.org/docs/1.3/opensearch/install/plugins/), unless there's something in the issue description I'm missing.

**Comment by JeffH-AWS** [comment]
1. Yes that's what I'm talking about.
2. Yes because the information is very incomplete and these pages will need to be redone anyway with an exhaustive list of available plugins (which isn't currently available).

**Comment by JeffH-AWS** [comment]
At the very least we need to be consistent across all versions.  We can parameterize it and have each version only display the relevant OS-Plugin version relationships, or we can just dump everything on every page and have it as a static reference.  I feel like the second method is inconsistent with the rest of the site, though.
