### ISSUE TITLE
[DOC] Improve the documentation for Anomaly Detection

### ISSUE THREAD

**Issue by Jon-AtAWS** [opensearch-project/documentation-website#910]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ X ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

 https://opensearch.org/docs/latest/monitoring-plugins/ad/index/
 
About halfway down the page, under “Step 2: Configure the model”
 
"2. For Find Anomalies based on, choose the method to find anomalies. For Field Value choose... [omitted] ... add your own JSON aggregation query"
 
We need something here to explain the syntax of what people can put there. It’s not a full query, it looks like it will be placed in the “aggregations” portion of the query. I’m not sure though, and we don’t seem to document it anywhere.
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
@Jon-AtAWS: Do you have an example of a JSON aggregation query we can test?

**Comment by alicejw-aws** [comment]
Hi @Jon-AtAWS , is there a spec or any resource with the syntax that we should add to the docs? (or any other POCs that I can ask for the information) thanks
