### ISSUE TITLE
[DOC] Documentation request for Multiple Data Source project

### ISSUE THREAD

**Issue by kristenTian** [opensearch-project/documentation-website#922]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
With the multi data source feature (find more info about this feature in next section), there are three major pieces in the stack management need documents:

1. Index Pattern creation
![image](https://user-images.githubusercontent.com/105667444/185511112-3422b539-89cf-4644-8cfd-196820099924.png)

- The creation flow for index pattern will be updated.

2. Data source
![image](https://user-images.githubusercontent.com/105667444/185511146-ccc1d266-1a48-470c-8b5b-0e9fc0f66c78.png)

- New component in stack management. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

GitHub issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1388

There are also recorded demos, test instructions for more detailed reference for this project. -- Using this issue as a parent task to track the overall process.

**Comment by vagimeli** [comment]
Content is in progress; going out for technical review 10/14.

**Comment by vagimeli** [comment]
Tutorials: Playground doesn't have experimental feature; will be available in production; confirming we can experiment on a local host.

**Comment by vagimeli** [comment]
PR #1710
