### ISSUE TITLE
[DOC] Security Plugin documentation: incomplete list of config files

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#935]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
The current documentation has a [list of all YAML config files for OpenSearch Security](https://opensearch.org/docs/latest/security-plugin/configuration/yaml/) with some basic description for them. however, it is incomplete:
* `config.yml` isn't mentioned on that page, though it is mentioned on [a dedicated page](https://opensearch.org/docs/latest/security-plugin/configuration/configuration/) (confusing? the title "YAML files" suggests that it should list them all)
* `audit.yml` isn't mentioned at all (there's [some documentation on audit logs](https://opensearch.org/docs/latest/security-plugin/audit-logs/index/), but that doesn't seem to mention the config file)
* `whitelist.yml` is the old name of `allowlist.yml` (at least that's what i presume as the former isn't documented but the latter is) but there's no mention of that name anywhere anymore except for the list of (upcoming) [breaking changes](https://opensearch.org/docs/latest/breaking-changes/) - though that mentions just the word and not explicitly the file. as long as the file can still be parsed there should at least be a note under `allowlist.yml` along the lines of "previously this was called `whitelist.yml` and files with that name are still parsed in 2.x. support for this will be removed in 3.0.".
 

**What other resources are available?**
* a (hopefully?) complete list of config files should be visible in [the config upload code](https://github.com/opensearch-project/security/blob/6b7a5869c84d453bb22be861a88b744512fa0d64/src/main/java/org/opensearch/security/tools/SecurityAdmin.java#L1203-L1232)
* the team from the [OpenSearch Security plugin](https://github.com/opensearch-project/security) should be able to provide more information on these files (i don't know the details of all of them either which is why i was looking for the documentation 🤷).

**Comment by hdhalter** [comment]
Thanks for your feedback, @rursprung . We've documented the security settings here: https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/security-settings/. Please let us know if we are missing any or if there is anything else we can do to improve the content. (And thanks for your patience!)

**Comment by hdhalter** [comment]
This is closed by https://github.com/opensearch-project/documentation-website/pull/4058.

**Comment by rursprung** [comment]
> Thanks for your feedback, @rursprung . We've documented the security settings here: https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/security-settings/. Please let us know if we are missing any or if there is anything else we can do to improve the content. (And thanks for your patience!)

so i only glanced at this for a few seconds, but: none of the config filenames which i mentioned seem to be present on that page. to me it seems that this only includes the configuration which you can provide in the central `opensearch.yml` - but does not talk about the dedicated config files of the security plugin at all => in that case this issue _isn't_ resolved and should be re-opened (unless you documented these files elsewhere?).
