### ISSUE TITLE
[DOC] Querqy Plugin Release

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#938]
**What do you want to do?**
 
- [ ] Add new documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Find a place within our documentation to mention the new Querqy Plugin, a community plugin based on an Elastic querying tool. The tool functions similarly to how it does in Elastic as documented in the [Querqy documentation](https://docs.querqy.org/querqy/index.html), however the installation process is slightly different as described in the [Readme](https://github.com/querqy/querqy-opensearch#readme). 

We'll need to figure how to link to link Querqy documentation while accounting for the installation differences.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

POCs: @ps48 and @JohannesDaniel

**Comment by hdhalter** [comment]
This content has been added to 1.3. It will also be part of 2.3, so assigning label 2.3.

**Comment by ariamarble** [comment]
Regular pre-compiled plugin will be made available on plugins pages after it's release in 2.3
