### ISSUE TITLE
[DOC] Update navigation on Documentation page

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#945]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 The navigation on the documentation page needs to match the navigation on the rest of the site. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Here is the Doc page: https://opensearch.org/docs/latest/ 
<img width="1172" alt="Screen Shot 2022-08-22 at 3 44 41 PM" src="https://user-images.githubusercontent.com/104463754/186031693-af8f9e80-821f-4f22-b987-5de7f439657e.png">

Here is an example from the Downloads page: 
https://opensearch.org/downloads.html#opensearch
<img width="1227" alt="Screen Shot 2022-08-22 at 3 45 00 PM" src="https://user-images.githubusercontent.com/104463754/186031729-26775199-0902-4947-8bdb-7e6031e343e7.png">

You'll find our header file in _includes/header.html

**Comment by hdhalter** [comment]
@AMoo-Miki - Fanit will look at this.

**Comment by hdhalter** [comment]
@kolchfa-aws - Refer to this PR to see the other navigation files. https://github.com/opensearch-project/documentation-website/pull/708

**Comment by kolchfa-aws** [comment]
This issue is fixed by #984
