### ISSUE TITLE
whitelist.yml file is undocumented

### ISSUE THREAD

**Issue by bgagnon** [opensearch-project/documentation-website#95]
The file is missing from the documentation website:
https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/yaml/

The only documentation available is inside the YAML file itself, in the repo:
https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/whitelist.yml

**Comment by keithhc2** [comment]
Hey @bgagnon, thanks for letting us know about the gap. We just merged #120, which adds some context about `whitelist.yml` to the yaml files on our documentation website. Please let us know if you have any other questions!
