### ISSUE TITLE
[DOC] Document maps service hosted by AWS

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#983]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Opensearch Dashboards is built with a plugin that allows users to create geographical visualizations of their data on maps. The map supports zoom and also comes with boundaries. To render the maps, OpenSearch Dashboards client code sends requests to a maps service hosted by AWS at https://*.maps.opensearch.org, (formerly https://*.maps.search-services.aws.a2z.com). This service is undocumented. Its URL changed to opensearch.org in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/777 to support users in regions such as India. The map service is a CDN that serves map tiles (images). The tiles are sourced from OpenStreetMaps, an open source project that collects maps data from all over the world.

- Document that the default installation of OpenSearch Dashboards will make HTTPs requests to these URLs. 
- Document how to run one own's tile server in a private network, https://github.com/opensearch-project/maps/issues/27. 
- Document how to configure OpenSearch Dashboards to point to the tile server in my private network.
 
**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

- See https://forum.opensearch.org/t/status-of-kibana-maps/5106/38 for a discussion about the service.
- https://github.com/opensearch-project/maps/issues/27
- https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1098
- https://github.com/opensearch-project/dashboards-reports/pull/425#discussion_r954039652

**Comment by joshuali925** [comment]
One note, it would be helpful to document since what version `maps.search-services.aws.a2z.com` became `maps.opensearch.org`. This would help reporting plugin to adjust the allowed domains. thanks

**Comment by hdhalter** [comment]
HI Melissa, can you please look into this? Thanks.

**Comment by vagimeli** [comment]
> 

Yes, I'm researching this issue.

**Comment by vagimeli** [comment]
@kolchfa-aws @hdhalter I believe this issue is addressed by this documentation: https://opensearch.org/docs/latest/dashboards/visualize/selfhost-maps-server/. Please let me know if this issue and that doc aren't related. Thanks :)

**Comment by hdhalter** [comment]
Looks like some of it has been addressed. @dblock, can you please take a look to see if your concerns have been met? Thanks.
