### ISSUE TITLE
[DOC] Finding language analyzers

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/documentation-website#990]
**What do you want to do?**
 
- [X ] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

1.1 doc lists the analyzers for Japanese (analysis-kuromoji), Korean (analysis-nori), Chinese (analysis-smartcn), and Polish (analysis-stempel) in [OpenSearch plugin installation](https://opensearch.org/docs/2.0/opensearch/install/plugins/#:~:text=kuromoji) but there is no way to find them by the language name. (I did various web searches and then looked at the source code to figure out that we're using nori and not seunjeon, as mentioned in [a blog](https://aws.amazon.com/blogs/opensource/open-source-korean-analyzer-support-amazon-elasticsearch-service/) for AES/AOSS in 2021; and in the [AWS documentation for OpenSearch](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-plugins.html#:~:text=Seunjeon).

What's more, these languages are not listed in [Convert text with analyzers](https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#:~:text=arabic), leaving the impression that we don't support them.

Also, the procedure for using the analyzers isn't documented. After installing the appropriate plugin, do you say analyzer=korean or analyzer=nori or analyzer=analysis-nori?

Minor point: the language names should be capitalized.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
@macrakis: We've documented this for Query DSL here: https://opensearch.org/docs/latest/opensearch/query-dsl/text-analyzers/#language-analyzer.

Are you hoping to have the same change implemented in 1.1 version of OpenSearch?

**Comment by hdhalter** [comment]
@macrakis , currently, we are only maintaining the documentation for versions of OpenSearch 1.3 and later.
