### ISSUE TITLE
[DOC] Dashboards Visualizing Webpage

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#992]

**Comment by vagimeli** [comment]
Status: content planning and writing ongoing

TOC (working draft)* Visualizations

    * Visualization panels
        * types of visualizations
    * Create your first dashboards
    * Analyze time series data
    * Create panels with editors
    * Make dashboards interactive
    * Improve dashboard loading time

**Comment by ashwin-pc** [comment]
> Query and transform data
Are you referring to Vega or TSVB or something else entirely?

**Comment by ashwin-pc** [comment]
> Panel editor overview
Configure panels

Also what do you mean by this?

**Comment by ashwin-pc** [comment]
Here's how i was thinking of the most important sections for visualizations:
- A list of all the vis types and what they are (And sub pages for each vis type)
- A list of all the aggregations, what they are and how they aggregate data (Common for all visualizations)
- How the query bar, filters and date range work with visualizations.
  - How the query bar works
  - Different options for the time range and filters
  - Auto refresh
- How the inspect and other top nav options work
<img width="249" alt="Screen Shot 2022-11-22 at 1 19 52 PM" src="https://user-images.githubusercontent.com/20453492/203423323-7f73625c-2b9c-4e10-9e05-31c75fd988b5.png">

- How to add it to a dashboard (Can just link to the docs for dashboard)
- How to export/import the visualizations (Can link to general export/import feature in saved object management)

This is the basic information i would need to feel confident using any visualization in OSD
