### ISSUE TITLE
[META-DOC] Dashboards - Detection new site page and content

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#994]

**Comment by vagimeli** [comment]
Status: content planning

TOC (working draft)
* Alerting
    * Alerting fundamentals
    * Set up
    * Create and manage rules
    * Rule types
    * Troubleshooting and limitations

**Comment by vagimeli** [comment]
Status: Finalizing release date; won't be part of 2.6; writer held doc kickoff meeting 2/13; writer continuing to work with UX and eng and attend feature briefs

**Comment by hdhalter** [comment]
@vagimeli - Is there a dev issue associated with this?

**Comment by vagimeli** [comment]
Closing meta issue; see specific issues for alerting and anomaly detection topics
