### ISSUE TITLE
[META-DOC] Create Internationalization documentation

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#997]

**Comment by vagimeli** [comment]
Status: content planning

TOC (working draft)

- Make languages available
- Provide translations on the Internationalization tab for each object you want to internationalize.
- Specify a language for the user

**Comment by hdhalter** [comment]
@vagimeli - you can close this issue until we have it in our backlog. I know they are adding language support in an upcoming release, but that is tracked under a different issue. Thanks.

**Comment by vagimeli** [comment]
Closing meta issue; see specific issues as they are created
